### ISSUE TITLE
SQLiteLog error while updating OneSignal from 3.11.2 to 3.14.0

### ISSUE THREAD

**Issue by kmrinmoy07** [OneSignal/OneSignal-Android-SDK#1033]
**Description:**

I have updated OneSignal from 3.11.2 to 3.14.0 and now I am getting some issue with SQLite error with **no such column: session** and **table cached_unique_outcome already exists**.
I have added the stacktraces below for more details.

I am adding OneSignal using-

    buildscript {
        repositories {
           maven { url 'https://plugins.gradle.org/m2/'}
        }
       dependencies {
          classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:0.12.7'
       }
    }
    apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'
    apply plugin: 'com.android.application'
    apply plugin: 'com.google.gms.google-services'

    android {
       compileSdkVersion 29
       buildToolsVersion '29.0.2'
       ......
        manifestPlaceholders = [onesignal_app_id               : "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                                onesignal_google_project_number: "REMOTE"]
       multiDexEnabled true
     }
   
    dependencies {
       implementation 'com.onesignal:OneSignal:3.14.0'
       }

 Initializing in MyApplication using
        
           OneSignal.startInit(this)
                .inFocusDisplaying(OneSignal.OSInFocusDisplayOption.Notification)
                .unsubscribeWhenNotificationsAreDisabled(true)
                .init();

**Environment**
   Android SDK version 3.5.1

**Steps to Reproduce Issue:**

1. Whenever I open my app with the new version of OneSignal 

**Anything else:**

Here is the complete stacktraces

> E/SQLiteLog: (1) no such column: session
W/System.err: android.database.sqlite.SQLiteException: no such column: session (code 1 SQLITE_ERROR): , while compiling: INSERT INTO outcome_backup SELECT _id,name,session,timestamp,notification_ids FROM outcome;
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:986)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:593)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:61)
        at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:33)
        at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1805)
        at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1733)
        at com.onesignal.OneSignalDbHelper.upgradeOutcomeTableRevision1To2(OneSignalDbHelper.java:277)
        at com.onesignal.OneSignalDbHelper.upgradeToV5(OneSignalDbHelper.java:245)
        at com.onesignal.OneSignalDbHelper.internalOnUpgrade(OneSignalDbHelper.java:198)
        at com.onesignal.OneSignalDbHelper.onUpgrade(OneSignalDbHelper.java:179)
        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:417)
        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:317)
W/System.err:     at com.onesignal.OneSignalDbHelper.getSQLiteDatabaseWithRetries(OneSignalDbHelper.java:155)
        at com.onesignal.OneSignalCacheCleaner.cleanOldCachedData(OneSignalCacheCleaner.java:33)
        at com.onesignal.OneSignal.setAppContext(OneSignal.java:626)
        at com.onesignal.OneSignal.init(OneSignal.java:688)
        at com.onesignal.OneSignal.init(OneSignal.java:672)
        at com.onesignal.OneSignal.access$000(OneSignal.java:87)
        at com.onesignal.OneSignal$Builder.init(OneSignal.java:391)
        at com.myapp.example.MyApplication.onCreate(MyApplication.java:46)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1190)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6540)
        at android.app.ActivityThread.access$1400(ActivityThread.java:220)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1883)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7520)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

> E/SQLiteLog: (1) no such column: session
W/System.err: android.database.sqlite.SQLiteException: no such column: session (code 1 SQLITE_ERROR): , while compiling: INSERT INTO outcome(_id,name,timestamp,notification_ids,weight,notification_influence_type) SELECT _id,name,timestamp,notification_ids,weight,session FROM outcome_aux;
W/System.err:     at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:986)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:593)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:61)
        at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:33)
        at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1805)
        at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1733)
        at com.onesignal.outcomes.OSOutcomeTableProvider.upgradeOutcomeTableRevision2To3(OSOutcomeTableProvider.java:70)
        at com.onesignal.OneSignalDbHelper.upgradeToV8(OneSignalDbHelper.java:260)
        at com.onesignal.OneSignalDbHelper.internalOnUpgrade(OneSignalDbHelper.java:208)
        at com.onesignal.OneSignalDbHelper.onUpgrade(OneSignalDbHelper.java:179)
        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:417)
        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:317)
        at com.onesignal.OneSignalDbHelper.getSQLiteDatabaseWithRetries(OneSignalDbHelper.java:155)
        at com.onesignal.OneSignalCacheCleaner.cleanOldCachedData(OneSignalCacheCleaner.java:33)
        at com.onesignal.OneSignal.setAppContext(OneSignal.java:626)
        at com.onesignal.OneSignal.init(OneSignal.java:688)
        at com.onesignal.OneSignal.init(OneSignal.java:672)
        at com.onesignal.OneSignal.access$000(OneSignal.java:87)
        at com.onesignal.OneSignal$Builder.init(OneSignal.java:391)
        at com.myapp.example.MyApplication.onCreate(MyApplication.java:46)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1190)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6540)
        at android.app.ActivityThread.access$1400(ActivityThread.java:220)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1883)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7520)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by Deepakkast** [comment]
i have   
  compileSdkVersion 28
        minSdkVersion 16
    implementation 'com.onesignal:OneSignal:3.14.0'


and still i am getting many crashes only because of onesignal 
crashes is like :

com.onesignal.outcomes.OSOutcomeEventsCache.getAllEventsToSend (OSOutcomeEventsCache.java:173)

Fatal Exception: android.database.sqlite.SQLiteDatabaseLockedException
database is locked (code 5 SQLITE_BUSY): retrycount exceeded


OneSignalCacheCleaner.java line 147
com.onesignal.OneSignalCacheCleaner.cleanCachedNotifications

**Comment by jkasten2** [comment]
@kmrinmoy07 This issue is now fixed in the 3.14.2 release.

**Comment by jkasten2** [comment]
@Deepakkast This is a different issue however it was also fixed in the 3.14.2 release.
