### ISSUE TITLE
d

### ISSUE THREAD

**Issue by prabhakar612** [OneSignal/OneSignal-Android-SDK#1037]

**Comment by jkasten2** [comment]
@prabhakar612 Could you provide the following details?
1. Does the issue only happen on your Xiaomi mi a7 (android pie) devic?, can you test other devices and / or an Android emulator?
2. Can you provide a full VERBOSE no filter adb logcat log when you click on the notification on that Xiaomi device?
3. Can you try changing your Battery Saver, "memory optimization", etc for your app in the Xiaomi settings noted in the [OneSignal - The App is Force Stopped documentation](https://documentation.onesignal.com/docs/notifications-show-successful-but-are-not-being-shown#the-app-is-force-stopped)?

**Comment by prabhakar612** [comment]
@jkasten2  1. It  is happening in Xiaomi devices only.
2. Getting the logs
2020-06-12 16:25:14.723 24106-25743/com.medtrail.arya D/Varun: message received: com.google.firebase.messaging.RemoteMessage@e72662f
2020-06-12 16:25:14.723 24106-25743/com.medtrail.arya D/Varun: remoteMessage.getMessageId() : 0:1591959315540228%19eecb00f9fd7ecd
2020-06-12 16:25:14.729 24106-24192/com.medtrail.arya D/PrescriptionAckJob: onAdded
2020-06-12 16:25:14.730 24106-25743/com.medtrail.arya D/Varun: key: custom value: {"a":{"prevNotificationId":"","data":{"callId":"1277","firebaseDocumentRef":"\/consultations\/102334\/consultations\/2020-05-30\/consultations\/8671","doctorId":"102821","appointmentId":"8671"},"notificationId":"1661_1","type":"call_trigger"},"i":"7a21ffe0-1bc9-46cf-a0b1-ffcd0ee0785d"}
2020-06-12 16:25:14.730 24106-25743/com.medtrail.arya D/Varun: key: alert value: Incoming Patient Call
2020-06-12 16:25:14.730 24106-25743/com.medtrail.arya D/Varun: key: sicon value: medtrail_notif
2020-06-12 16:25:14.730 24106-25743/com.medtrail.arya D/Varun: key: title value: Medtrail-Teleconsultations
2020-06-12 16:25:14.730 24106-25743/com.medtrail.arya D/FCMMessageManager: saveJSONMessage: {}
2020-06-12 16:25:14.731 24106-25743/com.medtrail.arya W/System.err: org.json.JSONException: No value for t
2020-06-12 16:25:14.743 24106-25743/com.medtrail.arya W/System.err:     at org.json.JSONObject.get(JSONObject.java:392)
2020-06-12 16:25:14.743 24106-25743/com.medtrail.arya W/System.err:     at org.json.JSONObject.getString(JSONObject.java:553)
2020-06-12 16:25:14.743 24106-25743/com.medtrail.arya W/System.err:     at in.medtrail.fcm.FCMMessageManager.saveJSONMessage(FCMMessageManager.java:87)

3. I have tried batter saver but no luck.

**Comment by prabhakar612** [comment]
@jkasten2  I have observe when i given permission of "display pop-up window while running in background". It is working fine but problem is not a way to know tis permission is given or not.
![xiaomi_permission](https://user-images.githubusercontent.com/66254408/84502884-cb2e2800-acd6-11ea-9f56-fd9f45bbee48.jpeg)

**Comment by jkasten2** [comment]
@prabhakar612 From this part of your log it looks like you are not correctly handling a missing JSON key of "t".
```java
2020-06-12 16:25:14.730 24106-25743/com.medtrail.arya D/FCMMessageManager: saveJSONMessage: {}
2020-06-12 16:25:14.731 24106-25743/com.medtrail.arya W/System.err: org.json.JSONException: No value for t
2020-06-12 16:25:14.743 24106-25743/com.medtrail.arya W/System.err: at org.json.JSONObject.get(JSONObject.java:392)
2020-06-12 16:25:14.743 24106-25743/com.medtrail.arya W/System.err: at org.json.JSONObject.getString(JSONObject.java:553)
2020-06-12 16:25:14.743 24106-25743/com.medtrail.arya W/System.err: at in.medtrail.fcm.FCMMessageManager.saveJSONMessage(FCMMessageManager.java:87)
```

I am not sure what your code is here but it seems you may not be handling something correctly when your app is cold started through this flow.
