### ISSUE TITLE
Always getting "Fatal Exception: java.lang.IllegalStateException: Apps may not schedule more than 100 distinct jobs"

### ISSUE THREAD

**Issue by MittapalliHareesh** [OneSignal/OneSignal-Android-SDK#1069]
Fatal Exception: java.lang.IllegalStateException: Apps may not schedule more than 100 distinct jobs
       at android.os.Parcel.readException(Parcel.java:1692)
       at android.os.Parcel.readException(Parcel.java:1637)
       at android.app.job.IJobScheduler$Stub$Proxy.schedule(IJobScheduler.java:158)
       at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:42)
       at com.onesignal.OneSignalSyncServiceUtils.scheduleSyncServiceAsJob(OneSignalSyncServiceUtils.java:155)
       at com.onesignal.OneSignalSyncServiceUtils.scheduleSyncTask(OneSignalSyncServiceUtils.java:124)
       at com.onesignal.OneSignalSyncServiceUtils.scheduleLocationUpdateTask(OneSignalSyncServiceUtils.java:69)
       at com.onesignal.LocationGMS.scheduleUpdate(LocationGMS.java:108)
       at com.onesignal.LocationGMS$2.run(LocationGMS.java:284)
       at java.lang.Thread.run(Thread.java:761)

Can you please help to resolve this issue?  I am using the below version of your  SDK
 classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.6, 0.99.99]'

Thanks!!  cc @RyanAmos @vsayer

**Comment by MittapalliHareesh** [comment]
Hi OneSignal Team, Can you please update on this,  We are seeing several firebase alerts.

  
Thanks !!

**Comment by Jeasmine** [comment]
HI @MittapalliHareesh did you tried specifying 
implementation 'com.onesignal:OneSignal:3.15.0' ?
This is the last release and includes the fix

**Comment by MittapalliHareesh** [comment]
Sure, Thanks for the update Jeasmine.

We will try to add 3.15.0 and will update on this.,

**Comment by rgomezp** [comment]
Closing due to no follow up. If it didn't work please comment below and tag myself or Jeasmine
