### ISSUE TITLE
OneSignalSyncServiceUtils.java line 152 com.onesignal.OneSignalSyncServiceUtils.scheduleSyncServiceAsJob.  Fatal Exception: java.lang.IllegalStateException Apps may not schedule more than 100 distinct jobs

### ISSUE THREAD

**Issue by ningappamoodi-rakuten** [OneSignal/OneSignal-Android-SDK#1082]
**Description:**

Hi,
We are still seeing this issue in One signal version 3.12.2.
We have 773 crashes affecting 11 users.
Please help to resolve this issue.
This issue happening 99% in Android 7 devices and 1% in Android 8 device.
Sony 76%
HUAWEI 13%
FUJITSU 11%

Device States 77% background.

Fatal Exception: java.lang.IllegalStateException
Apps may not schedule more than 100 distinct jobs
android.os.Parcel.readException (Parcel.java:1700)
android.os.Parcel.readException (Parcel.java:1640)
android.app.job.IJobScheduler$Stub$Proxy.schedule (IJobScheduler.java:158)
android.app.JobSchedulerImpl.schedule (JobSchedulerImpl.java:42)
com.onesignal.OneSignalSyncServiceUtils.scheduleSyncServiceAsJob (OneSignalSyncServiceUtils.java:152)
com.onesignal.OneSignalSyncServiceUtils.scheduleSyncTask (OneSignalSyncServiceUtils.java:121)
com.onesignal.OneSignalSyncServiceUtils.scheduleSyncTask (OneSignalSyncServiceUtils.java:71)
com.onesignal.FocusTimeController$FocusTimeProcessorBase.syncUnsentTimeOnBackgroundEvent (FocusTimeController.java:195)
com.onesignal.FocusTimeController$FocusTimeProcessorUnattributed.sendTime (FocusTimeController.java:113)
com.onesignal.FocusTimeController$FocusTimeProcessorBase.sendUnsentTimeNow (FocusTimeController.java:184)
com.onesignal.FocusTimeController$FocusTimeProcessorBase.addTime (FocusTimeController.java:177)
com.onesignal.FocusTimeController$FocusTimeProcessorBase.access$000 (FocusTimeController.java:139)
com.onesignal.FocusTimeController.giveProcessorsValidFocusTime (FocusTimeController.java:79)
com.onesignal.FocusTimeController.appBackgrounded (FocusTimeController.java:50)
com.onesignal.OneSignal.onAppLostFocus (OneSignal.java:1204)
com.onesignal.ActivityLifecycleHandler$AppFocusRunnable.run (ActivityLifecycleHandler.java:256)
android.os.Handler.handleCallback (Handler.java:751)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:241)
android.os.HandlerThread.run (HandlerThread.java:61)

**Environment**

Android 7.0
Android 7.1.1

**Steps to Reproduce Issue:**

1. Occurs when app is in background.

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by rgomezp** [comment]
Howdy,
You are on an old version of the SDK. Please upgrade to the latest before opening an issue.

Cheers

**Comment by alexfu** [comment]
Hello,

We are experiencing the same issue. 99% of the devices are on Android 7 and we are using **4.4.0** of the SDK and **0.13.4** of the Gradle plugin.

<details><summary>Stacktrace from Firebase</summary>

```
Fatal Exception: java.lang.IllegalStateException: Apps may not schedule more than 100 distinct jobs
       at android.os.Parcel.readException(Parcel.java:1692)
       at android.os.Parcel.readException(Parcel.java:1637)
       at android.app.job.IJobScheduler$Stub$Proxy.schedule(IJobScheduler.java:158)
       at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:42)
       at com.onesignal.OSBackgroundSync.scheduleSyncServiceAsJob(OSBackgroundSync.java:140)
       at com.onesignal.OSBackgroundSync.scheduleBackgroundSyncTask(OSBackgroundSync.java:90)
       at com.onesignal.OSSyncService.scheduleSyncTask(OSSyncService.java:108)
       at com.onesignal.OSSyncService.scheduleLocationUpdateTask(OSSyncService.java:116)
       at com.onesignal.LocationController.scheduleUpdate(LocationController.java:127)
       at com.onesignal.LocationController.fireCompleteForLocation(LocationController.java:404)
       at com.onesignal.GMSLocationController$GoogleApiClientListener.onConnected(GMSLocationController.java:138)
       at com.google.android.gms.common.internal.zah.zaa(zah.java:30)
       at com.google.android.gms.common.api.internal.zaar.zaa(zaar.java:295)
       at com.google.android.gms.common.api.internal.zaaf.zaf(zaaf.java:130)
       at com.google.android.gms.common.api.internal.zaaf.zaa(zaaf.java:108)
       at com.google.android.gms.common.api.internal.zaaz.onConnected(zaaz.java:105)
       at com.google.android.gms.common.api.internal.zaq.onConnected(zaq.java:5)
       at com.google.android.gms.common.internal.zag.onConnected(zag.java:2)
       at com.google.android.gms.common.internal.zzf.zza(zzf.java:10)
       at com.google.android.gms.common.internal.zza.zzd(zza.java)
       at com.google.android.gms.common.internal.zzc.zze(zzc.java:3)
       at com.google.android.gms.common.internal.zzb.handleMessage(zzb.java:31)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:179)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```
</details>
