### ISSUE TITLE
Class com.google.firebase.remoteconfig.ktx.FirebaseConfigKtxRegistrar is not an found.

### ISSUE THREAD

**Issue by bkanchan82** [OneSignal/OneSignal-Android-SDK#1106]
Class com.google.firebase.remoteconfig.ktx.FirebaseConfigKtxRegistrar is not an found.
    java.lang.ClassNotFoundException: com.google.firebase.remoteconfig.ktx.FirebaseConfigKtxRegistrar
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:453)
        at java.lang.Class.forName(Class.java:378)
        at com.google.firebase.components.ComponentDiscovery.instantiate(com.google.firebase:firebase-components@@16.0.0:80)
        at com.google.firebase.components.ComponentDiscovery.discover(com.google.firebase:firebase-components@@16.0.0:73)
        at com.google.firebase.FirebaseApp.<init>(com.google.firebase:firebase-common@@19.3.0:404)
        at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@19.3.0:300)
        at com.onesignal.PushRegistratorFCM.initFirebaseApp(PushRegistratorFCM.java:109)
        at com.onesignal.PushRegistratorFCM.getToken(PushRegistratorFCM.java:93)
        at com.onesignal.PushRegistratorAbstractGoogle.attemptRegistration(PushRegistratorAbstractGoogle.java:97)
        at com.onesignal.PushRegistratorAbstractGoogle.access$100(PushRegistratorAbstractGoogle.java:37)
        at com.onesignal.PushRegistratorAbstractGoogle$1.run(PushRegistratorAbstractGoogle.java:84)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.remoteconfig.ktx.FirebaseConfigKtxRegistrar" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.meetdonut.android-_gJCxSTz1U5Vlk76VR68gw==/base.apk"],nativeLibraryDirectories=[/data/app/com.meetdonut.android-_gJCxSTz1U5Vlk76VR68gw==/lib/arm64, /data/app/com.meetdonut.android-_gJCxSTz1U5Vlk76VR68gw==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:171)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:453) 
        at java.lang.Class.forName(Class.java:378) 
        at com.google.firebase.components.ComponentDiscovery.instantiate(com.google.firebase:firebase-components@@16.0.0:80) 
        at com.google.firebase.components.ComponentDiscovery.discover(com.google.firebase:firebase-components@@16.0.0:73) 
        at com.google.firebase.FirebaseApp.<init>(com.google.firebase:firebase-common@@19.3.0:404) 
        at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@19.3.0:300) 
        at com.onesignal.PushRegistratorFCM.initFirebaseApp(PushRegistratorFCM.java:109) 
        at com.onesignal.PushRegistratorFCM.getToken(PushRegistratorFCM.java:93) 
        at com.onesignal.PushRegistratorAbstractGoogle.attemptRegistration(PushRegistratorAbstractGoogle.java:97) 
        at com.onesignal.PushRegistratorAbstractGoogle.access$100(PushRegistratorAbstractGoogle.java:37) 
        at com.onesignal.PushRegistratorAbstractGoogle$1.run(PushRegistratorAbstractGoogle.java:84) 
        at java.lang.Thread.run(Thread.java:764) 

I am getting above warning on logcat,
I am using [3.15.0, 3.99.99] version

**Comment by rgomezp** [comment]
Howdy,
Please follow our issue template so that we can better assist you.

**Comment by bkanchan82** [comment]
@rgomezp  where I can get issue template. I cant find it, can you please link that, and If possible then can you please check log,I am getting this warning  in logcat and my device is not getting subscribed user on one signal console, So I am not able to send any notification.
Please let me know If you need any other information

**Comment by jkasten2** [comment]
@bkanchan82 It looks like this is a bug with `implementation 'com.google.firebase:firebase-config-ktx:19.1.4` and was fixed if you upgrade to 19.2.0
https://github.com/firebase/firebase-android-sdk/issues/1697#issuecomment-653552027

Let us know if you are still seeing an issue after upgrading.
