### ISSUE TITLE
ANR: OSH_LocationHandlerThread

### ISSUE THREAD

**Issue by janbolat** [OneSignal/OneSignal-Android-SDK#1112]
Hi OneSignal team, seeing an ANR.  
- OneSignal:3.15.2  
- firebase-messaging:20.2.4  
- play-services-location:17.0.0  

**Android 10, Redmi 9**
```
Thread "main" prio=5 tid=1 Waiting
...
Thread "OSH_LocationHandlerThread" prio=5 tid=33 Blocked
 at com.onesignal.GMSLocationController.fireFailedComplete (GMSLocationController.java:1)
  at com.onesignal.GMSLocationController$GoogleApiClientListener.onConnectionSuspended (GMSLocationController.java:1)
  at com.google.android.gms.common.internal.j.a (unavailable:29)
  at com.google.android.gms.common.api.internal.m0.a (unavailable:44)
  at com.google.android.gms.common.api.internal.x.onConnectionSuspended (unavailable:2)
  at com.google.android.gms.common.api.internal.y.a (unavailable:1)
  at com.google.android.gms.common.api.internal.t0.a (unavailable:4)
  at com.google.android.gms.common.api.internal.u0.handleMessage (unavailable:5)
  at android.os.Handler.dispatchMessage (Handler.java:107)
  at h.a.a.b.c.b.h.dispatchMessage (unavailable:1)
  at android.os.Looper.loop (Looper.java:224)
  at android.os.HandlerThread.run (HandlerThread.java:67)
Thread "OS_GMS_LOCATION_FALLBACK" prio=5 tid=34 Sleeping  
  at java.lang.Thread.sleep (Native method)
  at java.lang.Thread.sleep (Thread.java:440)
  at java.lang.Thread.sleep (Thread.java:356)
  at com.onesignal.GMSLocationController$1.run (GMSLocationController.java:1)
  at java.lang.Thread.run (Thread.java:919)
```

**Android 10, Motorola Moto G Turbo Edition:** (Should be running Android 5 or 6 but it is 10 🤯)
```
Thread "main" prio=5 tid=1 Waiting
...
Thread "OSH_LocationHandlerThread" prio=5 tid=33 Blocked
  at com.onesignal.GMSLocationController.fireFailedComplete (GMSLocationController.java:1)
  at com.onesignal.GMSLocationController$GoogleApiClientListener.onConnectionSuspended (GMSLocationController.java:1)
Thread "OS_GMS_LOCATION_FALLBACK" prio=5 tid=34 Blocked. 
 at com.onesignal.LocationController.fireFailedComplete (LocationController.java:2)
  at com.onesignal.GMSLocationController$1.run (GMSLocationController.java:3)
  at java.lang.Thread.run (Thread.java:919)
```

We haven't seen such ANRs when we removed OneSignal for 4-5 months. Any thoughts?

Thank you.

**Comment by janbolat** [comment]
btw, why not use FusedLocationProviderClient in GMSLocationController as in HMSLocationController. 
Then there won't be any difference in the code, just different package name.

**Comment by janbolat** [comment]
More details from Crashlytics (maybe not related I don't know):

**Android 8.1, Xiaomi Redmi Go**
```
Fatal Exception: java.lang.NullPointerException: Attempt to get length of null array
       at java.util.Formatter$FormatSpecifier.addZeros(Formatter.java:3505)
       at java.util.Formatter$FormatSpecifier.print(Formatter.java:3401)
       at java.util.Formatter$FormatSpecifier.print(Formatter.java:3332)
       at java.util.Formatter$FormatSpecifier.printFloat(Formatter.java:2893)
       at java.util.Formatter$FormatSpecifier.print(Formatter.java:2844)
       at java.util.Formatter.format(Formatter.java:2523)
       at java.util.Formatter.format(Formatter.java:2458)
       at java.lang.String.format(String.java:2770)
       at android.location.Location.toString(Location.java:1032)
       at java.lang.String.valueOf(String.java:2827)
       at java.lang.StringBuilder.append(StringBuilder.java:132)
       at com.onesignal.GMSLocationController$GoogleApiClientListener.onConnected(GMSLocationController.java:132)
       at com.google.android.gms.common.internal.GmsClientEventManager.onConnectionSuccess(GmsClientEventManager.java:33)
       at com.google.android.gms.common.api.internal.zaaw.zab(zaaw.java:292)
       at com.google.android.gms.common.api.internal.zaak.zaaq(zaak.java:125)
       at com.google.android.gms.common.api.internal.zaak.onConnected(zaak.java:105)
       at com.google.android.gms.common.api.internal.zabe.onConnected(zabe.java:101)
       at com.google.android.gms.common.api.internal.zaq.onConnected(zaq.java:6)
       at com.google.android.gms.common.internal.zaf.onConnected(zaf.java:2)
       at com.google.android.gms.common.internal.BaseGmsClient$zzf.zzm(BaseGmsClient.java:24)
       at com.google.android.gms.common.internal.BaseGmsClient$zza.zza(BaseGmsClient.java:12)
       at com.google.android.gms.common.internal.BaseGmsClient$zzc.zzo(BaseGmsClient.java:11)
       at com.google.android.gms.common.internal.BaseGmsClient$zzb.handleMessage(BaseGmsClient.java:49)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at com.google.android.gms.internal.common.zze.dispatchMessage(zze.java:8)
       at android.os.Looper.loop(Looper.java:164)
       at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by janbolat** [comment]
Another one:
Android 8, Huawei Y6 Prime 2018
```
Fatal Exception: java.lang.IllegalStateException: Not connected. Call connect() and wait for onConnected() to be called.
       at com.google.android.gms.common.internal.BaseGmsClient.checkConnected(BaseGmsClient.java:198)
       at com.google.android.gms.internal.location.zzk.createServiceInterface(zzk.java)
       at com.google.android.gms.internal.location.zzl.checkConnected(zzl.java:2)
       at com.google.android.gms.internal.location.zzas.a(zzas.java:2)
       at com.google.android.gms.internal.location.zzaz.a(zzaz.java:2)
       at com.google.android.gms.internal.location.zzz.doExecute(zzz.java:19)
       at com.google.android.gms.common.api.internal.BaseImplementation$ApiMethodImpl.run(BaseImplementation.java:19)
       at com.google.android.gms.common.api.internal.zaah.execute(zaah.java:20)
       at com.google.android.gms.common.api.internal.zabe.execute(zabe.java:23)
       at com.google.android.gms.common.api.internal.zaaw.execute(zaaw.java:74)
       at com.google.android.gms.internal.location.zzq.a(zzq.java:5)
       at com.onesignal.GMSLocationController.onFocusChange(GMSLocationController.java:114)
       at com.onesignal.LocationController.onFocusChange(LocationController.java:275)
       at com.onesignal.OneSignal.onAppLostFocus(OneSignal.java:1252)
       at com.onesignal.ActivityLifecycleHandler$AppFocusRunnable.run(ActivityLifecycleHandler.java:263)
       at android.os.Handler.handleCallback(Handler.java:808)
       at android.os.Handler.dispatchMessage(Handler.java:101)
       at android.os.Looper.loop(Looper.java:166)
       at android.os.HandlerThread.run(HandlerThread.java:65)
```
similar to https://github.com/OneSignal/OneSignal-Android-SDK/issues/719#issuecomment-568260747

@jkasten2

**Comment by jkasten2** [comment]
@janbolat 
## ANRs
Could you include the full ANR stack for all threads for these? An ANR happens due to the main thread stalling so we need this a least, however there might be more threads in between so the full ANR is preferred.

## Other errors
Could you create 2 new github issues for the other 2 errors? Since they are are unrelated to the ANR and each other.

**Comment by rgomezp** [comment]
Closing due to no response
