### ISSUE TITLE
Not connected. Call connect() and wait for onConnected() to be called.

### ISSUE THREAD

**Issue by janbolat** [OneSignal/OneSignal-Android-SDK#1120]
* OneSignal:3.15.2
* firebase-messaging:20.2.4
* play-services-location:17.0.0

**Android 8, Huawei Y6 Prime 2018**

```
Fatal Exception: java.lang.IllegalStateException: Not connected. Call connect() and wait for onConnected() to be called.
       at com.google.android.gms.common.internal.BaseGmsClient.checkConnected(BaseGmsClient.java:198)
       at com.google.android.gms.internal.location.zzk.createServiceInterface(zzk.java)
       at com.google.android.gms.internal.location.zzl.checkConnected(zzl.java:2)
       at com.google.android.gms.internal.location.zzas.a(zzas.java:2)
       at com.google.android.gms.internal.location.zzaz.a(zzaz.java:2)
       at com.google.android.gms.internal.location.zzz.doExecute(zzz.java:19)
       at com.google.android.gms.common.api.internal.BaseImplementation$ApiMethodImpl.run(BaseImplementation.java:19)
       at com.google.android.gms.common.api.internal.zaah.execute(zaah.java:20)
       at com.google.android.gms.common.api.internal.zabe.execute(zabe.java:23)
       at com.google.android.gms.common.api.internal.zaaw.execute(zaaw.java:74)
       at com.google.android.gms.internal.location.zzq.a(zzq.java:5)
       at com.onesignal.GMSLocationController.onFocusChange(GMSLocationController.java:114)
       at com.onesignal.LocationController.onFocusChange(LocationController.java:275)
       at com.onesignal.OneSignal.onAppLostFocus(OneSignal.java:1252)
       at com.onesignal.ActivityLifecycleHandler$AppFocusRunnable.run(ActivityLifecycleHandler.java:263)
       at android.os.Handler.handleCallback(Handler.java:808)
       at android.os.Handler.dispatchMessage(Handler.java:101)
       at android.os.Looper.loop(Looper.java:166)
       at android.os.HandlerThread.run(HandlerThread.java:65)
```

similar to https://github.com/OneSignal/OneSignal-Android-SDK/issues/719#issuecomment-568260747

**Comment by janbolat** [comment]
Something similar:
```
Fatal Exception: java.lang.IllegalStateException: Not connected. Call connect() and wait for onConnected() to be called.
       at com.google.android.gms.common.internal.BaseGmsClient.checkConnected(BaseGmsClient.java:198)
       at com.google.android.gms.internal.location.zzk.createServiceInterface(zzk.java)
       at com.google.android.gms.internal.location.zzl.checkConnected(zzl.java:2)
       at com.google.android.gms.internal.location.zzas.a(zzas.java:2)
       at com.google.android.gms.internal.location.zzaz.a(zzaz.java:2)
       at com.google.android.gms.internal.location.zzz.doExecute(zzz.java:19)
       at com.google.android.gms.common.api.internal.BaseImplementation$ApiMethodImpl.run(BaseImplementation.java:19)
       at com.google.android.gms.common.api.internal.zaah.execute(zaah.java:20)
       at com.google.android.gms.common.api.internal.zabe.execute(zabe.java:23)
       at com.google.android.gms.common.api.internal.zaaw.execute(zaaw.java:74)
       at com.google.android.gms.internal.location.zzq.a(zzq.java:5)
       at com.onesignal.GMSLocationController.onFocusChange(GMSLocationController.java:114)
       at com.onesignal.LocationController.onFocusChange(LocationController.java:275)
       at com.onesignal.OneSignal.onAppLostFocus(OneSignal.java:1252)
       at com.onesignal.ActivityLifecycleHandler$AppFocusRunnable.run(ActivityLifecycleHandler.java:263)
       at android.os.Handler.handleCallback(Handler.java:808)
       at android.os.Handler.dispatchMessage(Handler.java:101)
       at android.os.Looper.loop(Looper.java:166)
       at android.os.HandlerThread.run(HandlerThread.java:65)
```
![image](https://user-images.githubusercontent.com/6511056/91892264-23f8d580-ecb4-11ea-90a3-f54d4e8a9354.png)

**Comment by Jeasmine** [comment]
Hey @janbolat, are you able to reproduce? any steps to follow? Thanks!

**Comment by janbolat** [comment]
No, I have not tried.
![image](https://user-images.githubusercontent.com/6511056/95812060-60e5cc80-0d36-11eb-800c-dab5d7317196.png)
94% Android 8
5% Android 9
1% Android 7
Thanks

**Comment by nan-li** [comment]
Hi @janbolat, it has been a while, is this still happening for you? Have you updated OneSignal-Android-SDK to 4.x.x?

**Comment by emawby** [comment]
Closing due to inactivity
