### ISSUE TITLE
[4.0.0-beta2]  java.lang.NullPointerException: Attempt to read from field 'android.content.Context

### ISSUE THREAD

**Issue by cmargonis** [OneSignal/OneSignal-Android-SDK#1195]
**Description:**

Hello folks, I'd like to report a crash that we had on our app after updating to `4.0.0-beta2` version.
I'm attaching some relevant information from crashlytics.

**Environment**

1. OneSignal SDK version: `4.0.0-beta2`.
2. Compile SDK `29`
3. Target SDK `29`
4. Installed via Gradle.
5. Crash report observed on Android 10 device while the app was in the background.
6. User Device:  Galaxy S20+ 5G.

**Steps to Reproduce Issue:**

Unknown at the moment. It's a crash report via Firebase Crashlytics.

**Anything else:**

Stacktrace

```
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'android.content.Context com.onesignal.DelayedConsentInitializationParameters.context' on a null object reference
       at com.onesignal.OneSignal.reassignDelayedInitParams(OneSignal.java:972)
       at com.onesignal.OneSignal.onRemoteParamSet(OneSignal.java:726)
       at com.onesignal.OneSignal$5.complete(OneSignal.java:934)
       at com.onesignal.OneSignalRemoteParams.processJson(OneSignalRemoteParams.java:203)
       at com.onesignal.OneSignalRemoteParams.access$100(OneSignalRemoteParams.java:12)
       at com.onesignal.OneSignalRemoteParams$1.onSuccess(OneSignalRemoteParams.java:149)
       at com.onesignal.OneSignalRestClient$5.run(OneSignalRestClient.java:269)
       at java.lang.Thread.run(Thread.java:919)
```

**Comment by techupdate54** [comment]
Having the same problem

`Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'android.content.Context com.onesignal.DelayedConsentInitializationParameters.a' on a null object reference
       at com.onesignal.OneSignal.reassignDelayedInitParams(OneSignal.java:2)
       at com.onesignal.OneSignal.onRemoteParamSet(OneSignal.java:4)
       at com.onesignal.OneSignal$5.complete(OneSignal.java:25)
       at com.onesignal.OneSignalRemoteParams.processJson(OneSignalRemoteParams.java:10)
       at com.onesignal.OneSignalRemoteParams.access$100(OneSignalRemoteParams.java)
       at com.onesignal.OneSignalRemoteParams$1.onSuccess(OneSignalRemoteParams.java:2)
       at com.onesignal.OneSignalRestClient$5.run(OneSignalRestClient.java:4)
       at java.lang.Thread.run(Thread.java:919)`

**Comment by starchey** [comment]
We're seeing this as well on 4.0.0-beta2. We've had five devices crash so far, LGs and Samsungs running Android 8 and Android 10, all while in the background.

**Comment by Jeasmine** [comment]
Hey @cmargonis, thanks in advance for using the beta version and your feedback, we will take a look.

**Comment by starchey** [comment]
Just an update on my earlier comment, we rolled out an app update with beta2 to more users and this crash has impacted ~1.5% of them. Same stack trace as above, always in background. Haven't reproduced locally but we have ~9k distinct crashes in Firebase Crashlytics.

Also, wasn't sure if I should open a new issue for this, but we've had ~300 crashes with a very similar stack trace:

```
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.onesignal.DelayedConsentInitializationParameters.appId' on a null object reference
       at com.onesignal.OneSignal.reassignDelayedInitParams(OneSignal.java:973)
       at com.onesignal.OneSignal.onRemoteParamSet(OneSignal.java:726)
       at com.onesignal.OneSignal$5.complete(OneSignal.java:934)
       at com.onesignal.OneSignalRemoteParams.processJson(OneSignalRemoteParams.java:203)
       at com.onesignal.OneSignalRemoteParams.access$100(OneSignalRemoteParams.java:12)
       at com.onesignal.OneSignalRemoteParams$1.onSuccess(OneSignalRemoteParams.java:149)
       at com.onesignal.OneSignalRestClient$5.run(OneSignalRestClient.java:269)
       at java.lang.Thread.run(Thread.java:919)
```

**Comment by Jeasmine** [comment]
@cmargonis Do you have shared location active?

**Comment by cmargonis** [comment]
Hello @Jeasmine ,thanks for taking a look 😊 No, our app doesn't use location at all.

**Comment by Jeasmine** [comment]
Hey @cmargonis sorry for the delayed answer! but we will release a fix for this on the next beta cut release

**Comment by cmargonis** [comment]
Thanks @Jeasmine that's great 😄

**Comment by jkasten2** [comment]
[4.0.0-beta3](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/4.0.0-beta3) is now released with fix noted above.
