### ISSUE TITLE
App fails with java.lang.IllegalArgumentException: unknown worker class name: com.onesignal.OSNotificationRestoreWorkManager after migrating to 4.0.0

### ISSUE THREAD

**Issue by KChernenko** [OneSignal/OneSignal-Android-SDK#1241]
**Description:**

I'm getting a runtime exception after migrating to the 4.0.0 using the provided guide: https://documentation.onesignal.com/docs/step-by-step-android-native-3x-to-400-upgrade-guide
I've double-checked the guide as well as the sample code: 
https://github.com/OneSignal/OneSignal-Android-SDK/blob/master/Examples/OneSignalDemo/app/src/main/java/com/onesignal/sdktest/application/MainApplication.java

**Environment**

Version of the SDK: 4.0.0
Gradle plugin version: 0.12.9
Emulator Pixel 4 API 30 with Google Play

**Steps to Reproduce Issue:**

1. Manual setup described in the migration guide.
1. Or setup code: https://github.com/OneSignal/OneSignal-Android-SDK/blob/master/Examples/OneSignalDemo/app/src/main/java/com/onesignal/sdktest/application/MainApplication.java

**Anything else:**

(crash stacktraces, as well as any other information here)
The stack trace:

```
    java.lang.IllegalArgumentException: unknown worker class name: com.onesignal.OSNotificationRestoreWorkManager$NotificationRestoreWorker
        at com.mycompany.base.injection.factories.SimpleWorkerFactory.createWorker(SimpleWorkerFactory.kt:20)
        at androidx.work.WorkerFactory.createWorkerWithDefaultFallback(WorkerFactory.java:83)
        at androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.java:242)
        at androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:136)
        at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
```

**Comment by KChernenko** [comment]
My bad. The issue was related to my Android Work library setup.
