### ISSUE TITLE
can not download OneSignal dependencies

### ISSUE THREAD

**Issue by AlfredjinAndroid** [OneSignal/OneSignal-Android-SDK#1243]
When I added OneSignal dependencies in version  3.15.4 or 4.0.0 , it kept loading all the time.
The log shows as "Gradle: Download maven-metadata.xml".
When I removed OneSignal, build success...

**Comment by AlfredjinAndroid** [comment]
`        at com.onesignal.androidsdk.GradleProjectPlugin.processIncomingResolutionResults(GradleProjectPlugin.groovy:775)
        at com.onesignal.androidsdk.GradleProjectPlugin$processIncomingResolutionResults$6.callStatic(Unknown Source)
        at com.onesignal.androidsdk.GradleProjectPlugin.triggerResolutionStrategy(GradleProjectPlugin.groovy:766)
        at com.onesignal.androidsdk.GradleProjectPlugin$triggerResolutionStrategy$5.callStatic(Unknown Source)
        at com.onesignal.androidsdk.GradleProjectPlugin.generateHighestVersionsForGroups(GradleProjectPlugin.groovy:742)
        at com.onesignal.androidsdk.GradleProjectPlugin$generateHighestVersionsForGroups$3.callStatic(Unknown Source)
        at com.onesignal.androidsdk.GradleProjectPlugin$_doResolutionStrategyAndroidPluginV3_closure9.doCall(GradleProjectPlugin.groovy:423)

`

**Comment by AlfredjinAndroid** [comment]
My gradle problems
