### ISSUE TITLE
ANR after update OneSignal to 4.1.0

### ISSUE THREAD

**Issue by mwaked** [OneSignal/OneSignal-Android-SDK#1254]
**Description:**

After updating OneSignal to 4.1.0 app gives me ANR and the app can't opened!

**Environment**
Android 10, Android 11

**Steps to Reproduce Issue:**

**Project Gradle**

```
repositories {
        google()
        jcenter()
        maven { url 'https://maven.google.com' }
        maven { url 'https://plugins.gradle.org/m2/' }
        maven { url 'https://jitpack.io' }
        maven { url  "http://dl.bintray.com/lukaville/maven"}
        maven { url "https://sdk.smartlook.com/android/release" }
        maven {url "http://kochava.bintray.com/maven"}
        maven { url "https://github.com/ConnectyCube/connectycube-android-sdk-releases/raw/master/" }
        maven {url 'https://mvn.jwplayer.com/content/repositories/releases/'}
        maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }//////Added by Shimaa
        gradlePluginPortal()
    }

  dependencies {
        classpath(
                "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version",
                "com.android.tools.build:gradle:${build_gradle_version}",
                "gradle.plugin.com.onesignal:onesignal-gradle-plugin:0.12.10",
                "com.google.gms:google-services:$build_google_play_services",
                "com.github.triplet.gradle:play-publisher:$play_builder_version",
                "android.arch.navigation:navigation-safe-args-gradle-plugin:$nav_version",
        )
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.4.1'
    }
```

**App Gradle**

```
apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'
dependencies {
 implementation "com.onesignal:OneSignal:4.1.0"

}
```

**BaseApplication**

```
      OneSignal.setLogLevel(OneSignal.LOG_LEVEL.DEBUG, OneSignal.LOG_LEVEL.NONE)
       OneSignal.initWithContext(this)
       OneSignal.setAppId(ONESIGNAL_APP_ID)
```

**Comment by jkasten2** [comment]
@mwaked Thanks for reporting and the details so far. Could you also attach a full ANR report? If possible please include the stacktrace for all thread as the main thread could be waiting on other thread(s) we would need the details on to help debug.

**Comment by mwaked** [comment]
@jkasten2  Please check, if i comment these 3 lines:
```
        OneSignal.setLogLevel(OneSignal.LOG_LEVEL.DEBUG, OneSignal.LOG_LEVEL.NONE)
        OneSignal.initWithContext(this)
        OneSignal.setAppId(ONESIGNAL_APP_ID)
```
the app open and work fine.

```
2021-01-17 09:10:05.916 31883-31883/com.timeviewer.tv D/OneSignal: OneSignal InAppMessageTracker initInfluencedTypeFromCache: OSChannelTracker{tag=iam_id, influenceType=UNATTRIBUTED, indirectIds=null, directId=null}
2021-01-17 09:10:05.916 31883-31883/com.timeviewer.tv D/OneSignal: OneSignal NotificationTracker initInfluencedTypeFromCache: OSChannelTracker{tag=notification_id, influenceType=UNATTRIBUTED, indirectIds=null, directId=null}
2021-01-17 09:10:05.918 31883-31883/com.timeviewer.tv D/OneSignal: OneSignal getUnattributedUniqueOutcomeEventsSentByChannel: []
2021-01-17 09:10:05.927 31883-31883/com.timeviewer.tv D/OneSignal: Starting request to get Android parameters.
2021-01-17 09:10:05.931 31883-31984/com.timeviewer.tv D/OneSignal: OneSignalRestClient: Making request to: https://api.onesignal.com/apps/27d2dd89-f54c-452c-8189-7367e830ecd3/android_params.js
2021-01-17 09:10:05.931 31883-31982/com.timeviewer.tv D/OneSignal: redisplayedInAppMessages: []
2021-01-17 09:10:05.932 31883-31982/com.timeviewer.tv D/OneSignal: Attempted to clean 6 month old IAM data, but none exists!
2021-01-17 09:10:05.933 31883-31984/com.timeviewer.tv D/OneSignal: OneSignalRestClient: Adding header if-none-match: W/"365c7a9379ce41c037acf7a7eeaa5cfd"
2021-01-17 09:10:06.152 31883-31984/com.timeviewer.tv D/OneSignal: OneSignalRestClient: GET - Using Cached response due to 304: {"awl_list":{},"android_sender_id":"510675284779","chnl_lst":[],"fba":true,"outcomes":{"direct":{"enabled":false},"indirect":{"notification_attribution":{"minutes_since_displayed":60,"limit":10},"enabled":false},"unattributed":{"enabled":false}},"receive_receipts_enable":false}
2021-01-17 09:10:06.161 31883-31994/com.timeviewer.tv D/OneSignal: OneSignal saveInfluenceParams: InfluenceParams{indirectNotificationAttributionWindow=60, notificationLimit=10, indirectIAMAttributionWindow=1440, iamLimit=10, directEnabled=false, indirectEnabled=false, unattributedEnabled=false}
2021-01-17 09:10:06.163 31883-31994/com.timeviewer.tv D/OneSignal: reassignDelayedInitParams with appContext: timeviewer.tv.application.BaseApplication@b51da40
2021-01-17 09:10:06.168 31883-31994/com.timeviewer.tv D/OneSignal: OneSignal handleActivityLifecycleHandler inForeground: false
2021-01-17 09:10:06.182 31883-31994/com.timeviewer.tv D/OneSignal: initWithCachedInAppMessages: null
2021-01-17 09:10:06.186 31883-31994/com.timeviewer.tv I/OneSignal: Location permissions not added on AndroidManifest file
2021-01-17 09:10:06.186 31883-31994/com.timeviewer.tv D/OneSignal: LocationController sendAndClearPromptHandlers from non prompt flow
2021-01-17 09:10:06.191 31883-31994/com.timeviewer.tv D/OneSignal: registerUser:registerForPushFired:false, locationFired: true, remoteParams: com.onesignal.OneSignalRemoteParams$2@5b5f049, appId: 27d2dd89-f54c-452c-8189-7367e830ecd3
2021-01-17 09:10:06.191 31883-31994/com.timeviewer.tv D/OneSignal: registerUser not possible
2021-01-17 09:10:06.209 31883-31994/com.timeviewer.tv D/OneSignal: startPendingTasks with task queue quantity: 0
2021-01-17 09:10:06.222 31883-31996/com.timeviewer.tv I/FirebaseApp: Device unlocked: initializing all Firebase APIs for app ONESIGNAL_SDK_FCM_APP_NAME
2021-01-17 09:10:06.315 31883-32005/com.timeviewer.tv W/OneSignal: getTags called under a null user!
2021-01-17 09:10:06.525 31883-32008/com.timeviewer.tv I/okhttp.OkHttpClient: --> POST https://dev.timeviewer.tv/api/onesignal
2021-01-17 09:10:06.566 31883-31883/com.timeviewer.tv D/OneSignal: onActivityResumed: timeviewer.tv.ui.activities.splash.SplashActivity@43089c1
2021-01-17 09:10:06.566 31883-31883/com.timeviewer.tv D/OneSignal: curActivity is NOW: timeviewer.tv.ui.activities.splash.SplashActivity:timeviewer.tv.ui.activities.splash.SplashActivity@43089c1
2021-01-17 09:10:06.566 31883-31883/com.timeviewer.tv D/OneSignal: ActivityLifecycleHandler handleFocus, with runnable: null nextResumeIsFirstActivity: true
2021-01-17 09:10:06.566 31883-31883/com.timeviewer.tv D/OneSignal: ActivityLifecycleHandler reset background state, call app focus
2021-01-17 09:10:06.566 31883-31883/com.timeviewer.tv D/OneSignal: Application on focus
2021-01-17 09:10:06.576 31883-31883/com.timeviewer.tv D/OneSignal: Application foregrounded focus time: 35089324
2021-01-17 09:10:06.576 31883-31883/com.timeviewer.tv D/OneSignal: isPastOnSessionTime currentTimeMillis: 1610863806576 lastSessionTime: 1610863712362 difference: 94214
2021-01-17 09:10:06.576 31883-31883/com.timeviewer.tv D/OneSignal: Starting new session with appEntryState: APP_OPEN
2021-01-17 09:10:06.580 31883-31883/com.timeviewer.tv D/OneSignal: OneSignal cleanOutcomes for session
2021-01-17 09:10:06.580 31883-31883/com.timeviewer.tv D/OneSignal: OneSignal save unattributedUniqueOutcomeEvents: []
2021-01-17 09:10:06.581 31883-31883/com.timeviewer.tv D/OneSignal: OneSignal SessionManager restartSessionIfNeeded with entryAction: APP_OPEN
     channelTrackers: [OSChannelTracker{tag=notification_id, influenceType=UNATTRIBUTED, indirectIds=null, directId=null}, OSChannelTracker{tag=iam_id, influenceType=UNATTRIBUTED, indirectIds=null, directId=null}]
2021-01-17 09:10:06.581 31883-31883/com.timeviewer.tv D/OneSignal: OneSignal ChannelTracker getLastReceivedIds lastChannelObjectReceived: []
2021-01-17 09:10:06.587 31883-31883/com.timeviewer.tv D/OneSignal: OneSignal SessionManager restartSessionIfNeeded lastIds: []
2021-01-17 09:10:06.588 31883-31883/com.timeviewer.tv D/OneSignal: OneSignal ChannelTracker getLastReceivedIds lastChannelObjectReceived: []
2021-01-17 09:10:06.588 31883-31883/com.timeviewer.tv D/OneSignal: OneSignal SessionManager restartSessionIfNeeded lastIds: []
2021-01-17 09:10:06.588 31883-31883/com.timeviewer.tv D/OneSignal: OneSignal SessionManager sendSessionEndingWithInfluences with influences: []
2021-01-17 09:10:06.588 31883-31883/com.timeviewer.tv D/OneSignal: Last session time set to: 1610863806588
2021-01-17 09:10:06.588 31883-31883/com.timeviewer.tv D/OneSignal: initWithCachedInAppMessages: null
```

```
2021-01-17 09:24:05.230 1440-1440/com.timeviewer.tv E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.timeviewer.tv, PID: 1440
    java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/work/impl/utils/futures/AbstractFuture;
        at androidx.work.impl.WorkManagerImpl.initialize(WorkManagerImpl.java:181)
        at androidx.work.WorkManager.initialize(WorkManager.java:210)
        at androidx.work.impl.WorkManagerInitializer.onCreate(WorkManagerInitializer.java:40)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2092)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2066)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6983)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6528)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6445)
        at android.app.ActivityThread.access$1300(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.ClassNotFoundException: androidx.work.impl.utils.futures.AbstractFuture
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at androidx.work.impl.WorkManagerImpl.initialize(WorkManagerImpl.java:181) 
        at androidx.work.WorkManager.initialize(WorkManager.java:210) 
        at androidx.work.impl.WorkManagerInitializer.onCreate(WorkManagerInitializer.java:40) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2092) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2066) 
        at android.app.ActivityThread.installProvider(ActivityThread.java:6983) 
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6528) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6445) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:219) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/common/util/concurrent/ListenableFuture;
        at androidx.work.impl.WorkManagerImpl.initialize(WorkManagerImpl.java:181) 
        at androidx.work.WorkManager.initialize(WorkManager.java:210) 
        at androidx.work.impl.WorkManagerInitializer.onCreate(WorkManagerInitializer.java:40) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2092) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2066) 
        at android.app.ActivityThread.installProvider(ActivityThread.java:6983) 
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6528) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6445) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:219) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.common.util.concurrent.ListenableFuture" on path: DexPathList[[zip file "/data/app/com.timeviewer.tv-U5BGYzLpe93ZqT8Aox5UKw==/base.apk"],nativeLibraryDirectories=[/data/app/com.timeviewer.tv-U5BGYzLpe93ZqT8Aox5UKw==/lib/x86, /data/app/com.timeviewer.tv-U5BGYzLpe93ZqT8Aox5UKw==/base.apk!/lib/x86, /system/lib, /system/product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at androidx.work.impl.WorkManagerImpl.initialize(WorkManagerImpl.java:181) 
        at androidx.work.WorkManager.initialize(WorkManager.java:210) 
        at androidx.work.impl.WorkManagerInitializer.onCreate(WorkManagerInitializer.java:40) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2092) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2066) 
        at android.app.ActivityThread.installProvider(ActivityThread.java:6983) 
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6528) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6445) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:219) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
```

**Comment by mwaked** [comment]
Any update?

**Comment by MIF50** [comment]
I have the same issue Any update to fix it?

**Comment by mwaked** [comment]
It's fixed after adding 

```
configurations {
    all*.exclude group: 'com.google.guava', module: 'listenablefuture'
}

```
in gradle file.

**Comment by yiann0s** [comment]
> Any update?

Hello there,
found that by implementing the suggestion found at the issue [here](https://github.com/fluttercommunity/flutter_downloader/issues/223) , resolved this problem ! 

Long story short, removing the line
`configurations.all {
 all*.exclude group: 'com.google.guava', module: 'listenablefuture'
}` will fix this issue

**Comment by yiann0s** [comment]
> I have the same issue Any update to fix it?

Check the above comment ^ ^
