### ISSUE TITLE
Caused by android.os.DeadSystemException

### ISSUE THREAD

**Issue by arunabimanyu7** [OneSignal/OneSignal-Android-SDK#1257]
**Description:**

After getting a Push notification from one signal we are getting this crash

**Environment**

Build configuration 
One signal SDK version: 3.15.6
Android SDK version: 30 
Android Build version: 29.0.3

 
 **Device Model**

Brand: Samsung
Model: Galaxy Note10+
Orientation: Portrait
Version: 9
Rooted: No
Ram free: 3.47 GB

**Steps to Reproduce Issue:**

Issue is intermittent 

**Stack trace**

```
Caused by android.os.DeadSystemException
       at android.app.ActivityThread.handleSleeping(ActivityThread.java:4608)
       at android.app.ActivityThread.access$2500(ActivityThread.java:248)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1930)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7263)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
```

**Comment by Jeasmine** [comment]
Hey @arunabimanyu7, did you check the last major release update? Please update for us to address this issue. Versions below 4.0.0 are not being maintained.

**Comment by jkasten2** [comment]
Closing due to no response
