### ISSUE TITLE
 Unable to instantiate service com.onesignal.HmsMessageServiceOneSignal

### ISSUE THREAD

**Issue by arunabimanyu7** [OneSignal/OneSignal-Android-SDK#1262]
`Fatal Exception: java.lang.RuntimeException: Unable to instantiate service com.onesignal.HmsMessageServiceOneSignal: java.lang.ClassNotFoundException: Didn't find class "com.onesignal.HmsMessageServiceOneSignal" on path: DexPathList[[zip file "/data/app/com.rizek.android.users-1/base.apk"],nativeLibraryDirectories=[/data/app/com.rizek.android.users-1/lib/x86, /vendor/lib, /system/lib]]
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:2865)
       at android.app.ActivityThread.-wrap4(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1430)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5421)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
`

**Phone details** 

Phone and Model - LGE  Nexus 4
Orientation: Portrait
RAM free: 967.64 MB
Disk free: 181.94 MB
Operating System
Version: 6.0.1

**SDK version**

3.15.6

**Steps to Reproduce**

When the user launches the app.It's Happening every time

**Comment by franznkemaka** [comment]
Hello to all,

I'm also having this issue. Here is more information from my end:

**Describe the bug**
My app crashed in production. 

`
Fatal Exception: java.lang.RuntimeException
Unable to instantiate service com.onesignal.HmsMessageServiceOneSignal: java.lang.ClassNotFoundException: Didn't find class "com.onesignal.HmsMessageServiceOneSignal" on path: DexPathList[[zip file "/data/app/com.example.app-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.app-1/lib/x86, /vendor/lib, /system/lib]]
`

`
Caused by java.lang.ClassNotFoundException
Didn't find class "com.onesignal.HmsMessageServiceOneSignal" on path: DexPathList[[zip file "/data/app/com.example.app-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.app-1/lib/x86, /vendor/lib, /system/lib]]
`

**Device Information**

```
Brand: LGE
Model: Nexus 4
Orientation: Portrait
RAM free: 1.1 GB
Disk free: 271.52 MB 
Version: 6.0.1
Orientation: Portrait
Rooted: No 
```

The app is built using **React Native 0.63.3**

**To Reproduce**

Apparently, it happens in production only. When the app launches, it crashes.

**Comment by Jeasmine** [comment]
Hey! @franznkemaka thanks for reporting this, can you provide your build.gradle? And check if you have any proguard rule for OneSignal? Thanks!

**Comment by franznkemaka** [comment]
Hi @Jeasmine for sure

build.gradle:

```gradle


```



Thanks!

**Comment by fi8er1** [comment]
Fatal Exception: java.lang.RuntimeException
Unable to instantiate service com.onesignal.HmsMessageServiceOneSignal: java.lang.ClassNotFoundException: Didn't find class "com.onesignal.HmsMessageServiceOneSignal" on path: DexPathList[[zip file "/data/app/com.smartsco.recaru-J1nEFZZm0VlePHn7aJlLhg==/base.apk"],nativeLibraryDirectories=[/data/app/com.smartsco.recaru-J1nEFZZm0VlePHn7aJlLhg==/lib/arm64, /data/app/com.smartsco.recaru-J1nEFZZm0VlePHn7aJlLhg==/base.apk!/lib/arm64-v8a, /system/lib64, /hw_product/lib64, /system/product/lib64]]

Device
Brand:HUAWEI
Model:LIO-AL00
Orientation: Portrait
RAM free: 5.95 GB
Disk free: 43.2 GB

Operating System
Version:10
Orientation: Portrait
Rooted:No

**Comment by joaoeudes7** [comment]
Because try load this service in devices without Huawei Services?

Brand: Samsung
Model:Galaxy Tab A
Version:Android 7.1.2
Rooted:Yes

**Comment by nan-li** [comment]
Note, related to https://github.com/OneSignal/OneSignal-Android-SDK/issues/1407 and https://github.com/OneSignal/OneSignal-Android-SDK/issues/1507

**Comment by jkasten2** [comment]
It looks like Android is trying to load all classes on startup most likely due to multidex. You can remove the `HmsMessageServiceOneSignal` service from your build with the following ` tools:node="remove"`.

###### AndroidManifest.xml
```xml
<application ...>
        <service
            android:name="com.onesignal.HmsMessageServiceOneSignal"
            tools:node="remove" />
</application>
```

In the future we will look into making this it's own module so it is omitted by default.

**Comment by CharlieZheng** [comment]
> It looks like Android is trying to load all classes on startup most likely due to multidex. You can remove the `HmsMessageServiceOneSignal` service (if you are not using HMS push in your app) from your build with the following ` tools:node="remove"`.

Hi jkasten2, I'm confuse about the code above, will it remove HmsMessageServiceOneSignal from the app. Will it cause that huawei device unable to receive the push

**Comment by hebamekawi** [comment]
Hello, Any updates about this issue ?

    Is this only happening in production? Can you reproduce it? Is it happening for your own device?
Yes on production, No cant reproduce it on my device

     Do you have proguard rules for OneSignal?
No, any proguard rules should be added ?

     What percent of your users are affected by this? And some details about the model and versions?
Not sure about the exact percentage number for Huawei users only
Example device: 
* Model: JLN-LX1
* OS: Android 11

**Comment by hagen00** [comment]
I have the same problem for a Huawei phone. Using Flutter. 
![crash2](https://github.com/OneSignal/OneSignal-Android-SDK/assets/16573005/26956621-2eff-4d43-9ce7-0d2d6c6f7987)

**Comment by harun119** [comment]
Is there any solutions for this problem. I am facing this problem also in some Huawei devices. Not all Huawei devices facing with this crash. Just some of them is crashing on opening.
![Screen Shot 2023-12-13 at 14 46 28](https://github.com/OneSignal/OneSignal-Android-SDK/assets/34312463/6d346f91-7af7-45f6-badf-c1cfe7dc5207)
![Screen Shot 2023-12-13 at 14 46 19](https://github.com/OneSignal/OneSignal-Android-SDK/assets/34312463/44ac62de-781d-4eb7-ac3a-e28cb8750083)
