### ISSUE TITLE
SSLHandshakeException: Handshake failed

### ISSUE THREAD

**Issue by SuleymanovTat** [OneSignal/OneSignal-Android-SDK#1266]
OneSignal -4.0.0
https://github.com/OneSignal/OneSignal-Android-SDK/issues/859

OneSignalRestClient: null Error thrown from network stack. 
    javax.net.ssl.SSLHandshakeException: Handshake failed
        at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:396)
        at com.android.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:123)
        at com.android.okhttp.Connection.connect(Connection.java:151)
        at com.android.okhttp.Connection.connect(Connection.java:187)
        at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:238)
        at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:134)
        at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:382)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:369)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:287)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:130)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java)
        at com.android.tools.profiler.support.network.httpurl.TrackedHttpURLConnection.connect(TrackedHttpURLConnection.java:154)
        at com.android.tools.profiler.support.network.httpurl.TrackedHttpURLConnection.tryConnect(TrackedHttpURLConnection.java:81)
        at com.android.tools.profiler.support.network.httpurl.TrackedHttpURLConnection.trackResponse(TrackedHttpURLConnection.java:102)
        at com.android.tools.profiler.support.network.httpurl.TrackedHttpURLConnection.tryTrackResponse(TrackedHttpURLConnection.java:127)
        at com.android.tools.profiler.support.network.httpurl.TrackedHtt

**Comment by jkasten2** [comment]
@SuleymanovTat The `javax.net.ssl.SSLHandshakeException: Handshake failed` points to something on your network blocking the initial connection to onesignal.com. I recommend debugging from you network and devices to ensure it can get to onesignal.com.
