### ISSUE TITLE
Crash on the show notification - GenerateNotification.java line 397

### ISSUE THREAD

**Issue by batikansosun** [OneSignal/OneSignal-Android-SDK#1278]
**Description:**
This crash affects my users. I can not reproduce the case because I haven't the environments(Android 5.1 and others)

**Gradle & SDK info**
compileSdkVersion 30
buildToolsVersion "30.0.1"
minSdkVersion 21
targetSdkVersion 30

'com.onesignal:OneSignal:[3.15.0, 3.99.99]'

**Environment**

* Device
Brand: General Mobile
Model: Etab5
Orientation: Portrait
RAM free: 1.04 GB
Disk free: 1.96 GB
* Operating System
Version: 5.1
Orientation: Portrait
Rooted: Yes

- - -
* Device
Brand: samsung
Model: Galaxy Tab4 10.1
Orientation: Portrait
RAM free: 383.18 MB
Disk free: 3.16 GB
* Operating System
Version: 5.0.2
Orientation: Portrait
Rooted: No

- - -
* Device
Brand: samsung
Model: Galaxy Note3
Orientation: Portrait
RAM free: 400.52 MB
Disk free: 6.02 GB
* Operating System
Version: 5.0
Orientation: Portrait
Rooted: No

- - -
* Device
Brand: samsung
Model: Galaxy Tab4 10.1
Orientation: Portrait
RAM free: 412.25 MB
Disk free: 3.16 GB
* Operating System
Version: 5.0.2
Orientation: Portrait
Rooted: No

- - -
* Device
Brand: samsung
Model: Galaxy S4
Orientation: Portrait
RAM free: 445.04 MB
Disk free: 2.36 GB
* Operating System
Version: 5.0.1
Orientation: Portrait
Rooted: No

- - -
* Device
Brand: samsung
Model: Galaxy J2
Orientation: Portrait
RAM free: 248.37 MB
Disk free: 509.49 MB
* Operating System
Version: 5.1.1
Orientation: Portrait
Rooted: No

**Crash Stacktraces**
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 92939232 byte allocation with 2097152 free bytes and 31MB until OOM
       at dalvik.system.VMRuntime.newNonMovableArray(VMRuntime.java)
       at android.graphics.Bitmap.nativeCreateFromParcel(Bitmap.java)
       at android.graphics.Bitmap.access$100(Bitmap.java:32)
       at android.graphics.Bitmap$1.createFromParcel(Bitmap.java:1472)
       at android.graphics.Bitmap$1.createFromParcel(Bitmap.java:1464)
       at android.widget.RemoteViews$BitmapCache.<init>(RemoteViews.java:952)
       at android.widget.RemoteViews.<init>(RemoteViews.java:1733)
       at android.widget.RemoteViews.<init>(RemoteViews.java:1725)
       at android.app.Notification$BuilderRemoteViews.<init>(Notification.java:5097)
       at android.app.Notification$BuilderRemoteViews.clone(Notification.java:5109)
       at android.app.Notification$BuilderRemoteViews.clone(Notification.java:5095)
       at android.app.Notification.cloneInto(Notification.java:1519)
       at android.app.Notification.clone(Notification.java:1440)
       at android.app.NotificationManager.notify(NotificationManager.java:149)
       at androidx.core.app.NotificationManagerCompat.notify(NotificationManagerCompat.java:215)
       at androidx.core.app.NotificationManagerCompat.notify(NotificationManagerCompat.java:199)
       at com.onesignal.GenerateNotification.showNotification(GenerateNotification.java:397)
       at com.onesignal.GenerateNotification.fromJsonPayload(GenerateNotification.java:115)
       at com.onesignal.NotificationBundleProcessor.ProcessJobForDisplay(NotificationBundleProcessor.java:115)
       at com.onesignal.NotificationBundleProcessor.ProcessFromGCMIntentService(NotificationBundleProcessor.java:98)
       at com.onesignal.GcmIntentService.onHandleIntent(GcmIntentService.java:60)
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:194)
       at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by jkasten2** [comment]
@batikansosun Thanks for reporting, it looks like you are using a very large image in your notification as it ends up being 88.6MiB when decreased / converted to bitmap to be displayed.

As a work around you can use a smaller image for now.

`OutOfMemoryError` is something however OneSignal should be handling a move on without the image in this case.
