### ISSUE TITLE
Unity crash: android.database.sqlite.SQLiteCantOpenDatabaseException

### ISSUE THREAD

**Issue by shefich** [OneSignal/OneSignal-Android-SDK#1280]
**Description:**

I don't know how to reproduce the issue, but I have too many crashes in Google Play Vitals.
Happens on many various devices. Happens on every Android SDK, except probably Android 11.

**Environment**
1. Unity 2019.4.19
2. OneSignal 2.13.3 . Added like every custom .unitypackage
3. Targeting Android 11.

**Steps to Reproduce Issue:**

1. Add the OneSignal SDK to your project
2. Place your App ID in the application's gradle file
3. Attempt to receive a push notification

**Stacktrace:**
Type:
android.database.sqlite.SQLiteCantOpenDatabaseException

android.database.sqlite.SQLiteCantOpenDatabaseException: 
  at android.database.sqlite.SQLiteConnection.nativeOpen (Native Method)
  at android.database.sqlite.SQLiteConnection.open (SQLiteConnection.java:211)
  at android.database.sqlite.SQLiteConnection.open (SQLiteConnection.java:195)
  at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked (SQLiteConnectionPool.java:503)
  at android.database.sqlite.SQLiteConnectionPool.open (SQLiteConnectionPool.java:204)
  at android.database.sqlite.SQLiteConnectionPool.open (SQLiteConnectionPool.java:196)
  at android.database.sqlite.SQLiteDatabase.openInner (SQLiteDatabase.java:880)
  at android.database.sqlite.SQLiteDatabase.open (SQLiteDatabase.java:865)
  at android.database.sqlite.SQLiteDatabase.openDatabase (SQLiteDatabase.java:739)
  at android.database.sqlite.SQLiteDatabase.openDatabase (SQLiteDatabase.java:729)
  at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked (SQLiteOpenHelper.java:355)
  at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase (SQLiteOpenHelper.java:298)
  at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase (FrameworkSQLiteOpenHelper.java:92)
  at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase (FrameworkSQLiteOpenHelper.java:53)
  at androidx.room.RoomDatabase.beginTransaction (RoomDatabase.java:328)
  at androidx.work.impl.utils.ForceStopRunnable.cleanUp (ForceStopRunnable.java:135)
  at androidx.work.impl.utils.ForceStopRunnable.run (ForceStopRunnable.java:79)
  at androidx.work.impl.utils.SerialExecutor$Task.run (SerialExecutor.java:75)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
  at java.lang.Thread.run (Thread.java:764)

**Comment by jkasten2** [comment]
@shefich Thanks for reporting but I don't see OneSignal in the stacktrace. OneSignal also does not use the `Room` library.

Looking at the fullstack trace I only see Android AOSP and the AndroidX (Jetpack) library. This seems to indicate there is some kind of bug with the version of the WorkManager as I see ` androidx.work`  in the stack.

Can you try updating to a newer version of the AndroidX work library?
https://developer.android.com/jetpack/androidx/releases/work

**Comment by jkasten2** [comment]
Closing due to missing details and no recent activity

**Comment by jkasten2** [comment]
OneSignal does use WorkManager, this may or may not be the only one using it in your app. I recommend ensuring you have the latest `work-runtime` dependency in your app. You can do this by running `./gradlew app:dependencies` and searching for `work-runtime` in there. The latest is 2.7.1 (at the time of writing) so if this is older add the following line:
```gradle
implementation "androidx.work:work-runtime:2.7.1"
```

**Comment by thefaisalurrehman** [comment]
1. After implementing OneSignal push notification the crashes occur from the google console.


```
java.lang.IllegalStateException: 
at androidx.work.impl.utils.ForceStopRunnable.run (ForceStopRunnable.java:128)
at androidx.work.impl.utils.SerialExecutor$Task.run (SerialExecutor.java:91)
at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
at java.lang.Thread.run (Thread.java:923)
Caused by: android.database.sqlite.SQLiteCantOpenDatabaseException: 
at android.database.sqlite.SQLiteConnection.open (SQLiteConnection.java:365)
at android.database.sqlite.SQLiteConnection.open (SQLiteConnection.java:226)
at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked (SQLiteConnectionPool.java:737)
at android.database.sqlite.SQLiteConnectionPool.open (SQLiteConnectionPool.java:284)
at android.database.sqlite.SQLiteConnectionPool.open (SQLiteConnectionPool.java:251)
at android.database.sqlite.SQLiteDatabase.openInner (SQLiteDatabase.java:1392)
at android.database.sqlite.SQLiteDatabase.open (SQLiteDatabase.java:1337)
at android.database.sqlite.SQLiteDatabase.openDatabase (SQLiteDatabase.java:980)
at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked (SQLiteOpenHelper.java:444)
at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase (SQLiteOpenHelper.java:387)
at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase (FrameworkSQLiteOpenHelper.java:145)
at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase (FrameworkSQLiteOpenHelper.java:106)
at androidx.room.RoomDatabase.inTransaction (RoomDatabase.java:476)
at androidx.room.RoomDatabase.assertNotSuspendingTransaction (RoomDatabase.java:281)
at androidx.work.impl.model.SystemIdInfoDao_Impl.getWorkSpecIds (SystemIdInfoDao_Impl.java:120)
at androidx.work.impl.background.systemjob.SystemJobScheduler.reconcileJobs (SystemJobScheduler.java:298)
at androidx.work.impl.utils.ForceStopRunnable.cleanUp (ForceStopRunnable.java:249)
at androidx.work.impl.utils.ForceStopRunnable.forceStopRunnable (ForceStopRunnable.java:215)
at androidx.work.impl.utils.ForceStopRunnable.run (ForceStopRunnable.java:110)
Caused by: android.database.sqlite.SQLiteCantOpenDatabaseException: 
at android.database.sqlite.SQLiteConnection.nativeOpen (Native Method)
at android.database.sqlite.SQLiteConnection.open (SQLiteConnection.java:337)
```

Note I'm just initialization OneSignal in the Application class  onCreate method

```
OneSignal.initWithContext(MyApplication.this)
OneSignal.setAppId(ONESIGNAL_APP_ID);
```

**Comment by jkasten2** [comment]
@thefaisalurrehman Thanks for reporting, see https://github.com/OneSignal/OneSignal-Android-SDK/issues/1280#issuecomment-1063724214 above to find what version of `work-runtime` is being used in your project and if upgrading helps if you don't have the latest.

**Comment by thefaisalurrehman** [comment]
> @thefaisalurrehman Thanks for reporting, see [#1280 (comment)](https://github.com/OneSignal/OneSignal-Android-SDK/issues/1280#issuecomment-1063724214) above to find what version of `work-runtime` is being used in your project and if upgrading helps if you don't have the latest.

Thanks for response, I wasn't using it before, now lets check

**Comment by ubuntudroid** [comment]
Right after adding OneSignal to our native Android (no Unity) app and since publishing to our users we are starting to see this as well, but with OneSignal in the stack trace:

```
Fatal Exception: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14 SQLITE_CANTOPEN): Could not open database
       at android.database.sqlite.SQLiteConnection.nativeOpen(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:215)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:197)
       at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:505)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:206)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:198)
       at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:915)
       at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:895)
       at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:759)
       at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:748)
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:374)
       at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:317)
       at com.onesignal.OneSignalDbHelper.getSQLiteDatabase(OneSignalDbHelper.java:150)
       at com.onesignal.OneSignalDbHelper.getSQLiteDatabaseWithRetries(OneSignalDbHelper.java:174)
       at com.onesignal.OneSignalDbHelper.delete(OneSignalDbHelper.java:289)
       at com.onesignal.outcomes.data.OSOutcomeEventsCache.cleanCachedUniqueOutcomeEventNotifications(OSOutcomeEventsCache.java:327)
       at com.onesignal.outcomes.data.OSOutcomeEventsRepository.cleanCachedUniqueOutcomeEventNotifications(OSOutcomeEventsRepository.kt:46)
       at com.onesignal.OSOutcomeEventsController$1.run(OSOutcomeEventsController.java:71)
       at java.lang.Thread.run(Thread.java:919)
```

According to Crashlytics user has enough storage space, so that's not what's causing it. Happens in foreground and in background.

It happened only to one user so far, but for them 39(!) times within just a few minutes.

We also have our own database in the app and that one is working just fine, no crashes there - so it seems to be an issue specific to OneSignal and how the SDK accesses the DB.

We are using version 4.7.0 of the SDK.

**Comment by jkasten2** [comment]
@ubuntudroid Thanks for reporting. There are two different SQL crash reports:
* Issue #1280 (this issue) - Focuses on the crash that comes from `androidx.work` (which is not directly from OneSignal)
* Issue #1432 focuses on the crash from `OneSignalDbHelper` (OneSignal code).

@ubuntudroid could you post this crash on #1432?, this is the one you will want to follow to get updated on when your issue is fixed.

**Comment by ubuntudroid** [comment]
@jkasten2 sure, will do!
