### ISSUE TITLE
Fatal Exception: 'boolean android.app.NotificationChannel.isDeleted()

### ISSUE THREAD

**Issue by DaxeshV** [OneSignal/OneSignal-Android-SDK#1291]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.app.NotificationChannel.isDeleted()' on a null object reference
       at android.os.Parcel.readException(Parcel.java:2035)
       at android.os.Parcel.readException(Parcel.java:1975)
       at android.app.INotificationManager$Stub$Proxy.getNotificationChannels(INotificationManager.java:1824)
       at android.app.NotificationManager.getNotificationChannels(NotificationManager.java:483)
       at com.onesignal.NotificationChannelManager.processChannelList(NotificationChannelManager.java:49)
       at com.onesignal.OneSignal$5.complete(OneSignal.java:36)
       at com.onesignal.OneSignalRemoteParams.processJson(OneSignalRemoteParams.java:10)
       at com.onesignal.OneSignalRemoteParams.access$100(OneSignalRemoteParams.java)
       at com.onesignal.OneSignalRemoteParams$1.onSuccess(OneSignalRemoteParams.java:2)
       at com.onesignal.OneSignalRestClient$5.run(OneSignalRestClient.java:4)
       at java.lang.Thread.run(Thread.java:764)

**Comment by jkasten2** [comment]
@DaxeshV Thanks for reporting, could you provide the following details as well?
1. Device models with Android version.
2. Number of crashes and users affected.
3. Steps to reproduce the crash.

**Comment by codingbeautifully** [comment]
I also encountered this problem.

**This is Stack Trace**.

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.app.NotificationChannel.isDeleted()' on a null object reference
       at android.os.Parcel.createException(Parcel.java:1972)
       at android.os.Parcel.readException(Parcel.java:1934)
       at android.os.Parcel.readException(Parcel.java:1884)
       at android.app.INotificationManager$Stub$Proxy.getNotificationChannels(INotificationManager.java:2158)
       at android.app.NotificationManager.getNotificationChannels(NotificationManager.java:568)
       at com.onesignal.NotificationChannelManager.processChannelList(NotificationChannelManager.java:236)
       at com.onesignal.OneSignal$5.complete(OneSignal.java:1072)
       at com.onesignal.OneSignalRemoteParams.processJson(OneSignalRemoteParams.java:188)
       at com.onesignal.OneSignalRemoteParams.access$100(OneSignalRemoteParams.java:12)
       at com.onesignal.OneSignalRemoteParams$1.onSuccess(OneSignalRemoteParams.java:140)
       at com.onesignal.OneSignalRestClient$5.run(OneSignalRestClient.java:270)
       at java.lang.Thread.run(Thread.java:764)

**Details**
1. Device models with Android version.

100% are oppo phones

79% oppo's phone versions are Android 9.
21% oppo's phone versions are Android 8.

2. Number of crashes and users affected.

This issue has 396 crash events affecting 14 users.

3. Steps to reproduce the crash.

We don't have oppo phones so we can't reproduce the crash.

**Comment by es0329** [comment]
- On March 25th 2021, this issue began appearing in 68 crash events impacting 3 users
- 100% of occurrences are observed on Oppo devices running API 28 (Android 9)
- The effected release of our app depends on OneSignal-Android-SDK version 3.15.3
- Steps to reproduce are unknown

```txt
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.app.NotificationChannel.isDeleted()' on a null object reference
       at android.os.Parcel.createException(Parcel.java:1972)
       at android.os.Parcel.readException(Parcel.java:1934)
       at android.os.Parcel.readException(Parcel.java:1884)
       at android.app.INotificationManager$Stub$Proxy.getNotificationChannels(INotificationManager.java:2158)
       at android.app.NotificationManager.getNotificationChannels(NotificationManager.java:568)
       at com.onesignal.NotificationChannelManager.processChannelList(NotificationChannelManager.java:236)
       at com.onesignal.OneSignal$5.complete(OneSignal.java:1071)
       at com.onesignal.OneSignalRemoteParams.processJson(OneSignalRemoteParams.java:188)
       at com.onesignal.OneSignalRemoteParams.access$100(OneSignalRemoteParams.java:12)
       at com.onesignal.OneSignalRemoteParams$1.onSuccess(OneSignalRemoteParams.java:140)
       at com.onesignal.OneSignalRestClient$5.run(OneSignalRestClient.java:270)
       at java.lang.Thread.run(Thread.java:764)
```

**Comment by jennantilla** [comment]
Hi @DaxeshV 

Looking at your stack trace, are you doing anything with notification channels?

According to other reports, this is crash appears to be specific to Android 8+ Oppo devices. Is that the case with you as well? If so have you attempted to address this issue with the device manufacturer?

A potential workaround you could try is not initializing OneSignal on Oppo devices.
```
String deviceName = android.os.Build.MODEL;
String deviceMan = android.os.Build.MANUFACTURER;
```

If you have any additional info that hasn't been provided previously, please share here.

**Comment by DaxeshV** [comment]
> Hi @DaxeshV
> 
> Looking at your stack trace, are you doing anything with notification channels?
> 
> According to other reports, this is crash appears to be specific to Android 8+ Oppo devices. Is that the case with you as well? If so have you attempted to address this issue with the device manufacturer?
> 
> A potential workaround you could try is not initializing OneSignal on Oppo devices.
> 
> ```
> String deviceName = android.os.Build.MODEL;
> String deviceMan = android.os.Build.MANUFACTURER;
> ```
> 
> If you have any additional info that hasn't been provided previously, please share here.

- In my side crash report showing 180 crash happen within 48 hrs and 50 % Xiaomi devices , 42 % OPPO and 8 % Samsung devices.  In android 8  98% crash and android 9 have 2% Crash happen. All are non rooted devices.  Before it working fine crash happening after a 4.2.0 version.

Please check below link of firebase crash report.
https://prnt.sc/10z222p
https://prnt.sc/10z232f

**Comment by rgomezp** [comment]
@Jeasmine, @jkasten2  coming from here.

From a surface-level it seems that the OneSignal Notification Manager is tracking references to channels that at some point get deleted and are thus null.

**Comment by ramanbindal** [comment]
hi @rgomezp , do we have any fix to this issue yet?

**Comment by rgomezp** [comment]
Howdy,
Nothing yet. Thanks for your patience.

**Comment by janbolat** [comment]
We have the same problem (NotificationChannelManager.java:236). 
Try/catch maybe? :)
![image](https://user-images.githubusercontent.com/6511056/114259749-ffa36b00-99f1-11eb-91f4-41fd7e9d021b.png)

**Comment by ZakariaEsbaiy** [comment]
**This issue has 85 crash events affecting 2 users** for the last 2 hours

**Stack trace:**
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.app.NotificationChannel.isDeleted()' on a null object reference
       at android.os.Parcel.createException(Parcel.java:1972)
       at android.os.Parcel.readException(Parcel.java:1934)
       at android.os.Parcel.readException(Parcel.java:1884)
       at android.app.INotificationManager$Stub$Proxy.getNotificationChannels(INotificationManager.java:2158)
       at android.app.NotificationManager.getNotificationChannels(NotificationManager.java:568)
       at com.onesignal.NotificationChannelManager.processChannelList(NotificationChannelManager.java:53)
       at com.onesignal.OneSignal$5.complete(OneSignal.java:53)
       at com.onesignal.OneSignalRemoteParams.processJson(OneSignalRemoteParams.java:53)
       at com.onesignal.OneSignalRemoteParams.access$100(OneSignalRemoteParams.java:53)
       at com.onesignal.OneSignalRemoteParams$1.onSuccess(OneSignalRemoteParams.java:53)
       at com.onesignal.OneSignalRestClient$5.run(OneSignalRestClient.java:4)
       at java.lang.Thread.run(Thread.java:764)

**Caused by android.os.RemoteException**
Caused by android.os.RemoteException: Remote stack trace:
	at com.android.server.notification.RankingHelper.getNotificationChannels(RankingHelper.java:1135)
	at com.android.server.notification.NotificationManagerService$10.getNotificationChannels(NotificationManagerService.java:2613)
	at android.app.INotificationManager$Stub.onTransact(INotificationManager.java:432)
	at com.android.server.notification.NotificationManagerService$10.onTransact(NotificationManagerService.java:2094)
	at android.os.Binder.execTransact(Binder.java:731)



**Device status: 93% In background**

**Device:**
Brand:OPPO
Model:A1k
Orientation: Portrait
RAM free: 704.46 MB
Disk free: 2.8 GB

**Operating System:**
Version:9
Orientation: Portrait
Rooted:No
Crash Date:11 Apr 2021, 18:17:08

**Comment by novanto** [comment]
I'm getting same errors with others. Looks like it's specific on Oppo Devices - specifically on A1K. Error stack trace same as above so I'm not attaching the stack traces.

![image](https://user-images.githubusercontent.com/3339477/114533684-5a4df880-9c78-11eb-9b45-b60972ff0ea1.png)

**Comment by DaxeshV** [comment]
@Jeasmine don't forgot we subscribe paid plan of one signal. and this typo of issue not accepted. Humble request please fix this issue asap.

**Comment by Jeasmine** [comment]
We had the fix released under https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/4.3.1

**Comment by janbolat** [comment]
@Jeasmine Do you have any plans to port it to 3.x?

**Comment by jkasten2** [comment]
@janbolat Are there any blockers for you to update to the latest 4.x.x branch of the OneSignal-Android-SDK? If so feel free to create an issue and at me and I can follow up.
For most projects it only takes a few steps to upgrade to the latest by following this guide:
https://documentation.onesignal.com/docs/step-by-step-android-native-3x-to-400-upgrade-guide

We are minimizing the number of fixes for the 3.x.x branch to critical issues that are widespread and security fixes. Since this is affecting a limited number of specific Oppo devices on a specific ROM version we are not planning to backport the fix from 4.x.x to 3.x.x.

**Comment by janbolat** [comment]
@jkasten2 Thank you.
Will update to 4.x

**Comment by Jeasmine** [comment]
Fix released under https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/4.3.1
