### ISSUE TITLE
Crash on com.onesignal.FocusTimeController.getTimeFocusedElapsed

### ISSUE THREAD

**Issue by hendrawd** [OneSignal/OneSignal-Android-SDK#1292]
**Description:**
A crash from Crashlytics:

```
FocusTimeController.java line 93
com.onesignal.FocusTimeController.getTimeFocusedElapsed
```

**Environment**

1. What version of the Android SDK are you using?
`com.onesignal:OneSignal:3.15.4`
1. How did you add the SDK to your project
via gradle

**Steps to Reproduce Issue:**
It's from Crashlytics, and we still can't reproduce it, but based on the log, we know that the crash happens as soon as our app starts.

**Anything else:**
Stacktrace

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
       at com.onesignal.FocusTimeController.getTimeFocusedElapsed(FocusTimeController.java:93)
       at com.onesignal.FocusTimeController.giveProcessorsValidFocusTime(FocusTimeController.java:77)
       at com.onesignal.FocusTimeController.onSessionEnded(FocusTimeController.java:59)
       at com.onesignal.OneSignal$1.onSessionEnding(OneSignal.java:442)
       at com.onesignal.OSSessionManager$1.run(OSSessionManager.java:248)
       at java.lang.Thread.run(Thread.java:818)
```

![](https://user-images.githubusercontent.com/9481791/111266923-ccbdbf80-865d-11eb-82bc-3450b88fdce9.png)

**Comment by jkasten2** [comment]
@hendrawd Thanks for reporting, could you let us know how many users and how many crashes you are seeing?

From looking at the stack trace we haven't seen any other reports of this crash.

Could you try updating to the latest 4.x.x version of OneSignal to see if this is no longer an issue?:
https://documentation.onesignal.com/docs/step-by-step-android-native-3x-to-400-upgrade-guide

**Comment by nan-li** [comment]
Closing due to no response

**Comment by hendrawd** [comment]
@jkasten2 @jennantilla @nan-li Sorry for the late response, I missed this. In fact, we haven't seen this problem in the last 90 days. I'm not sure why, but I'll keep you posted if the crash happens again.

**Comment by nan-li** [comment]
I appreciate the followup information @hendrawd, and good to hear you haven't been seeing this issue lately.

**Comment by CharlieZheng** [comment]
We using the version 4.7.2, and it crash 2 times in the last 90 days. 
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
       at com.onesignal.FocusTimeController.getTimeFocusedElapsed(FocusTimeController.java:98)
       at com.onesignal.FocusTimeController.appStopped(FocusTimeController.java:50)
       at com.onesignal.ActivityLifecycleHandler.handleLostFocus(ActivityLifecycleHandler.java:182)
       at com.onesignal.ActivityLifecycleHandler.onActivityPaused(ActivityLifecycleHandler.java:102)
       at com.onesignal.ActivityLifecycleListener.onActivityPaused(ActivityLifecycleListener.java:97)
       at android.app.Application.dispatchActivityPaused(Application.java:248)
       at android.app.Activity.onPause(Activity.java:1739)
       at androidx.fragment.app.FragmentActivity.onPause(FragmentActivity.java:388)
       at pullrefresh.lizhiyun.com.baselibrary.base.RxFragmentActivity.onPause(RxFragmentActivity.java:84)
       at pullrefresh.lizhiyun.com.baselibrary.base.BaseAct.onPause(BaseAct.java:412)
       at android.app.Activity.performPause(Activity.java:7341)
       at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1487)
       at android.app.ActivityThread.performNewIntents(ActivityThread.java:3338)
       at android.app.ActivityThread.handleNewIntent(ActivityThread.java:3358)
       at android.app.servertransaction.NewIntentItem.execute(NewIntentItem.java:49)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1977)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6923)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
```
