### ISSUE TITLE
Attempt to invoke virtual method 'boolean android.app.NotificationChannel.isDeleted()' on a null object reference

### ISSUE THREAD

**Issue by ZakariaEsbaiy** [OneSignal/OneSignal-Android-SDK#1308]
**Stack trace:**
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.app.NotificationChannel.isDeleted()' on a null object reference
       at android.os.Parcel.createException(Parcel.java:1972)
       at android.os.Parcel.readException(Parcel.java:1934)
       at android.os.Parcel.readException(Parcel.java:1884)
       at android.app.INotificationManager$Stub$Proxy.getNotificationChannels(INotificationManager.java:2158)
       at android.app.NotificationManager.getNotificationChannels(NotificationManager.java:568)
       at com.onesignal.NotificationChannelManager.processChannelList(NotificationChannelManager.java:53)
       at com.onesignal.OneSignal$5.complete(OneSignal.java:53)
       at com.onesignal.OneSignalRemoteParams.processJson(OneSignalRemoteParams.java:53)
       at com.onesignal.OneSignalRemoteParams.access$100(OneSignalRemoteParams.java:53)
       at com.onesignal.OneSignalRemoteParams$1.onSuccess(OneSignalRemoteParams.java:53)
       at com.onesignal.OneSignalRestClient$5.run(OneSignalRestClient.java:4)
       at java.lang.Thread.run(Thread.java:764)

**Caused by android.os.RemoteException**
Caused by android.os.RemoteException: Remote stack trace:
	at com.android.server.notification.RankingHelper.getNotificationChannels(RankingHelper.java:1135)
	at com.android.server.notification.NotificationManagerService$10.getNotificationChannels(NotificationManagerService.java:2613)
	at android.app.INotificationManager$Stub.onTransact(INotificationManager.java:432)
	at com.android.server.notification.NotificationManagerService$10.onTransact(NotificationManagerService.java:2094)
	at android.os.Binder.execTransact(Binder.java:731)

**Device:**
Brand:OPPO
Model:A1k
Orientation: Portrait
RAM free: 704.46 MB
Disk free: 2.8 GB

**Operating System:**
Version:9
Orientation: Portrait
Rooted:No
Crash Date:11 Apr 2021, 18:17:08

**Comment by ZakariaEsbaiy** [comment]
Sorry, I just noticed there is already an issue open with the same thing!
I am going to post this at the other opened issue
