### ISSUE TITLE
NullPointerException com.onesignal.UserState.getSyncValuesCopy 

### ISSUE THREAD

**Issue by rosebm** [OneSignal/OneSignal-Android-SDK#1317]
**Description:**

We received this crash report from Crashlytics:
 
 Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'java.lang.String org.json.JSONObject.toString()' on a null object reference
com.onesignal.UserState.getSyncValuesCopy (UserState.java:85) 

**Environment**
Min SDK: 21
Target SDK: 30

Gradle: com.onesignal:OneSignal:4.3.0

**Steps to Reproduce Issue:**
Are unknown since the issue is coming as a report from Crashlytics.
The occurrences are observed on:
Device: LG Max
OS Version: 5.0

**Anything else:**

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.json.JSONObject.toString()' on a null object reference
       at com.onesignal.UserState.getSyncValuesCopy(UserState.java:85)
       at com.onesignal.UserState.getSyncValues(UserState.java:76)
       at com.onesignal.UserStateSynchronizer.getRegistrationId(UserStateSynchronizer.java:56)
       at com.onesignal.OneSignalStateSynchronizer.getRegistrationId(OneSignalStateSynchronizer.java:141)
       at com.onesignal.OneSignal$4.complete(OneSignal.java:936)
       at com.onesignal.PushRegistratorAbstractGoogle.attemptRegistration(PushRegistratorAbstractGoogle.java:123)
       at com.onesignal.PushRegistratorAbstractGoogle.access$100(PushRegistratorAbstractGoogle.java:37)
       at com.onesignal.PushRegistratorAbstractGoogle$1.run(PushRegistratorAbstractGoogle.java:84)
       at java.lang.Thread.run(Thread.java:818)

```

** Similar issue closed:**
https://github.com/OneSignal/OneSignal-Android-SDK/issues/612

**Comment by rosebm** [comment]
Thank you guys!, looks has been fixed on v.4.3.3
