### ISSUE TITLE
NPE at UserStateSynchronizer.java:224

### ISSUE THREAD

**Issue by matteinn** [OneSignal/OneSignal-Android-SDK#1319]
**Description:**

Hi!
Below you can find one of the outstanding crashes on the 4.3.0 Android SDK.

**Environment**

SDK 4.3.0 added via maven

**Steps to Reproduce Issue:**

Unknown

**Anything else:**

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'org.json.JSONObject com.onesignal.UserState.generateJsonDiff(com.onesignal.UserState, boolean)' on a null object reference
       at com.onesignal.UserStateSynchronizer.persist(UserStateSynchronizer.java:224)
       at com.onesignal.OneSignalStateSynchronizer.persist(OneSignalStateSynchronizer.java:112)
       at com.onesignal.OneSignal.scheduleSyncService(OneSignal.java:1308)
       at com.onesignal.OneSignal.backgroundSyncLogic(OneSignal.java:1303)
       at com.onesignal.OneSignal.onAppLostFocus(OneSignal.java:1291)
       at com.onesignal.ActivityLifecycleHandler$AppFocusRunnable.run(ActivityLifecycleHandler.java:282)
       at java.lang.Thread.run(Thread.java:919)
```

**Comment by Jeasmine** [comment]
I Will continue reporting under https://github.com/OneSignal/OneSignal-Android-SDK/issues/1279
