### ISSUE TITLE
OneSignal.java line 3063 com.onesignal.OneSignal.notValidOrDuplicated

### ISSUE THREAD

**Issue by JingleBit** [OneSignal/OneSignal-Android-SDK#1357]
**Description:**

OneSignal notification click crashes my app.

**Environment**

Issue is on Android 9, Android 10 & Android 11

**Steps to Reproduce Issue:**

1. Send OneSignal notification.
2. Click on notification on Android 9 Android 10 or Android 11
3. App is crashed

**Stack trace:**

Fatal Exception: java.lang.RuntimeException: Unable to start receiver com.onesignal.FCMBroadcastReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.onesignal.OSNotificationDataController.notValidOrDuplicated(org.json.JSONObject, com.onesignal.OSNotificationDataController$InvalidOrDuplicateNotificationCallback)' on a null object reference
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4139)
       at android.app.ActivityThread.access$1600(ActivityThread.java:257)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1993)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:236)
       at android.app.ActivityThread.main(ActivityThread.java:8060)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

**Comment by Jeasmine** [comment]
This has been released under https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/4.4.1
