### ISSUE TITLE
java.lang.SecurityException: Not allowed to bind to service Intent

### ISSUE THREAD

**Issue by iamAliRaza** [OneSignal/OneSignal-Android-SDK#1358]
**OneSignalChromeTab.java line 56
com.onesignal.OneSignalChromeTab.open**

Fatal Exception: java.lang.SecurityException: Not allowed to bind to service Intent { act=android.support.customtabs.action.CustomTabsService pkg=com.android.chrome }
       at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1741)
       at android.app.ContextImpl.bindService(ContextImpl.java:1651)
       at android.content.ContextWrapper.bindService(ContextWrapper.java:705)
       at androidx.browser.customtabs.CustomTabsClient.bindCustomTabsService(CustomTabsClient.java:80)
       **at com.onesignal.OneSignalChromeTab.open(OneSignalChromeTab.java:56)
       at com.onesignal.OneSignalChromeTabAndroidFrame.setup(OneSignalChromeTabAndroidFrame.java:23)
       at com.onesignal.OneSignal$8.run(OneSignal.java:1338)**
       at java.lang.Thread.run(Thread.java:919)

**Getting this exception on specfic devices Android 10. I am using chrome custom tabs inside my project using this dependency
implementation 'androidx.browser:browser:1.3.0'**

**i am also using OneSignal for push notifications.
I am not sure what's causing this issue.**

**Comment by jkasten2** [comment]
@iamAliRaza Thanks for reporting. I see `OneSignalChromeTabAndroidFrame` in the stacktrace which was removed in PR #1326 and is part of the [OneSignal-Android-SDK 4.3.4 release](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/4.3.4). Updating this version or new will solve this crash.

There is another entry point into OneSignalChromeTab which is used for URLs on the OneSignal In-App Message feature. If you see a similar crash with that please open a new issue with the updated stacktrace and we can address it separately. Thanks.
