### ISSUE TITLE
SQLiteCantOpenDatabaseException on NotificationRestorer.java

### ISSUE THREAD

**Issue by iForests** [OneSignal/OneSignal-Android-SDK#136]
I saw some OneSignal's crashes on Crashlytics.
![Crashlytics' Screenshot](http://i.imgur.com/jILI29r.png)

There are two types of crash log:

<pre>
Fatal Exception: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
       at android.database.sqlite.SQLiteConnection.nativeOpen(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:338)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:232)
       at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:512)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:206)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:178)
       at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:902)
       at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:872)
       at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:709)
       at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1333)
       at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:268)
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:224)
       at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:164)
       <b>at com.onesignal.NotificationRestorer.restore(SourceFile:57)
       at com.onesignal.NotificationRestoreService.onHandleIntent(SourceFile:43)</b>
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:146)
       at android.os.HandlerThread.run(HandlerThread.java:61)
</pre>

And

<pre>
Fatal Exception: android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file (code 14): , while compiling: PRAGMA journal_mode
       at android.database.sqlite.SQLiteConnection.nativePrepareStatement(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:896)
       at android.database.sqlite.SQLiteConnection.executeForString(SQLiteConnection.java:641)
       at android.database.sqlite.SQLiteConnection.setJournalMode(SQLiteConnection.java:323)
       at android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:297)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:218)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:196)
       at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
       at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:836)
       at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:821)
       at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:714)
       at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:576)
       at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:269)
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
       at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
       <b>at com.onesignal.NotificationRestorer.restore(NotificationRestorer.java:57)
       at com.onesignal.NotificationRestoreService.onHandleIntent(NotificationRestoreService.java:43)</b>
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:207)
       at android.os.HandlerThread.run(HandlerThread.java:61)
</pre>

Please let me know if I can provide any additional information. Thanks.

**Comment by jkasten2** [comment]
@iForests Thanks for the report. This on the 3.4.0 version of the SDK?

**Comment by iForests** [comment]
It's on v3.3.0.
Since there is no difference between v3.3.0 and v3.4.0 in NotificationRestorer, I think it will crash on v3.4.0 too. But I can update to v3.4.0 if necessary.

**Comment by jkasten2** [comment]
@iForests Thanks, there are no changes around this since 3.3.0 so updating would fix this issue.

**Comment by anukools** [comment]
Hey @iForests @jkasten2 I am also facing same crashed. Any solution to this found...?

**Comment by jkasten2** [comment]
A few more reported stack traces.

```Java
Fatal Exception: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database 
at android.database.sqlite.SQLiteConnection.nativeOpen(SQLiteConnection.java) 
at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:209) 
at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193) 
at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463) 
at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185) 
at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177) 
at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:831) 
at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:816) 
at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:709) 
at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1230) 
at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:267) 
at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223) 
at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163) 
at com.onesignal.NotificationRestorer.restore(SourceFile:57) 
at com.onesignal.NotificationRestoreService.onHandleIntent(SourceFile:43) 
at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65) 
at android.os.Handler.dispatchMessage(Handler.java:106) 
at android.os.Looper.loop(Looper.java:189) 
at android.os.HandlerThread.run(HandlerThread.java:61)
```

```Java
Fatal Exception: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database 
at android.database.sqlite.SQLiteConnection.nativeOpen(SQLiteConnection.java) 
at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:209) 
at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193) 
at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463) 
at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185) 
at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177) 
at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:831) 
at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:816) 
at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:709) 
at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:234) 
at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187) 
at com.onesignal.OneSignal.isDuplicateNotification(SourceFile:1377) 
at com.onesignal.OneSignal.notValidOrDuplicated(SourceFile:1407) 
at com.onesignal.NotificationBundleProcessor.ProcessFromGCMIntentService(SourceFile:62) 
at com.onesignal.GcmIntentService.onHandleIntent(SourceFile:58) 
at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65) 
at android.os.Handler.dispatchMessage(Handler.java:106) 
at android.os.Looper.loop(Looper.java:189) 
at android.os.HandlerThread.run(HandlerThread.java:61)
```
```Java
Crashed Thread: Thread[OS_RESTORE_NOTIFS,5,main]
android.database.sqlite.SQLiteException: not an error (code 0): Could not open the database in read/write mode.
at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:212)
at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:196)
at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:836)
at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:821)
at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:714)
at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:578)
at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:269)
at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
at com.onesignal.NotificationRestorer.restore(SourceFile:57)
at com.onesignal.NotificationRestorer$1.run(SourceFile:46)
at java.lang.Thread.run(Thread.java:818)
```

**Comment by jkasten2** [comment]
I tried to spawn a number of threads calling `getWritableDatabase` and `getReadableDatabase` to attempt to reproduce the issue on Android 7.0, 5.0.1, 4.2.2, and 6.0.1. It wasn't reproducible so the issue can't be any sort of race condition in the SDK. This must be a rare device issue that seems I/O related or in one case while compiling: PRAGMA journal_mode which is also seems to indicating the database is catching up on I/O.

Added a limited number of retries with back off and a catch to prevent these crashes in commit 1b280a7cb1bdd67ddcece07fdaaa5e1ae32df648.

**Comment by Rickyen** [comment]
hay me to, i have a same crash

android.database.sqlite.SQLiteException: 
 
  at android.database.sqlite.SQLiteOpenHelper.onDowngrade (SQLiteOpenHelper.java:360)
 
  at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked (SQLiteOpenHelper.java:254)
 
  at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase (SQLiteOpenHelper.java:163)
 
  at com.onesignal.NotificationRestorer.restore (NotificationRestorer.java:57)
 
  at com.onesignal.NotificationRestorer$1.run (NotificationRestorer.java:46)
 
  at java.lang.Thread.run (Thread.java:818)

**Comment by jkasten2** [comment]
@Rickyen This the onDowngrade issue which has more details on issue #222.
