### ISSUE TITLE
Background crashes in com.onesignal.OSOutcomeEventsController.sendSavedOutcomes(OSOutcomeEventsController.java:36)

### ISSUE THREAD

**Issue by chokokatana** [OneSignal/OneSignal-Android-SDK#1374]
**Description:**

App has started crashing in the background with the following stacktrace:
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
       at com.onesignal.OSOutcomeEventsController.sendSavedOutcomes(OSOutcomeEventsController.java:36)
       at com.onesignal.OneSignal.init(OneSignal.java:812)
       at com.onesignal.OneSignal.setAppId(OneSignal.java:685)
       at com.onesignal.OneSignal.reassignDelayedInitParams(OneSignal.java:1096)
       at com.onesignal.OneSignal.onRemoteParamSet(OneSignal.java:819)
       at com.onesignal.OneSignal$5.complete(OneSignal.java:1037)
       at com.onesignal.OneSignalRemoteParams.processJson(OneSignalRemoteParams.java:206)
       at com.onesignal.OneSignalRemoteParams.access$100(OneSignalRemoteParams.java:12)
       at com.onesignal.OneSignalRemoteParams$1.onSuccess(OneSignalRemoteParams.java:151)
       at com.onesignal.OneSignalRestClient$5.run(OneSignalRestClient.java:269)
       at java.lang.Thread.run(Thread.java:818)
```
According to crashlytics 50% motorola, 38% Android 6, 100% crashes in the background.

**Environment**
One signal gradle plugin [0.12.10, 0.99.99], library at [4.4.0, 4.99.99].
Target and compile SDK 30, minsdk 17. 
Not using jcenter.

**Steps to Reproduce Issue:**

Don't know what is triggering the problem, no idea how to reproduce. It does not happen on my development devices and only today have I started getting crash reports from the field. Given that 100% crashes are in the background I suspect some push is happening, but nothing from our part as far as I know.

**Comment by uniquevik** [comment]
When can we get an updates on this? I am using latest version and found a crash report for this bug. @Jeasmine

**Comment by mahmoudElfeel67** [comment]
@Jeasmine i also have crashes coming from this is there an update ???

**Comment by nan-li** [comment]
Hi @chokokatana, @android-guru-vikas, @mahmoudElfeel67, thanks for reporting and I apologize for not getting a reply in earlier. 

There is another report of this with details, so I will close this issue. Please track the problem at #1514.
