### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean getUserSubscribePreference()' on a null object reference

### ISSUE THREAD

**Issue by JurajKuliska** [OneSignal/OneSignal-Android-SDK#1394]
**Description:**
Our crash reporting system is reporting a crash that I can't reproduce myself on my device. 
It's a **NullPointerException** that happens right on the start of the app but after `OneSignal.initWithContext()` and `OneSignal.setAppId()` have already been called.
The crash happens in the first second after app start according to the crash report.

**Environment**
Using the **4.4.1** version of OneSignal SDK added using maven

**Steps to Reproduce Issue:**
I can't really reproduce the issue, I'm only getting occassional crash reports from different devices
The Android OS version of the devies is 11, 10 and 9 so I think it's not Android OS version related

The crash happens when we read `getUserId()` right on the app start and we are making sure it's after OneSignal is initialized

**Anything else:**

The stacktrace I'm getting is:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean getUserSubscribePreference()' on a null object reference
         at com.onesignal.OneSignalStateSynchronizer.getUserSubscribePreference()
         at com.onesignal.OSSubscriptionState.<init>(OSSubscriptionState.java)
         at com.onesignal.OneSignal.getCurrentSubscriptionState()
         at com.onesignal.OneSignal.getDeviceState()
         at com.my.app.OneSignalManager.getUserId()
```
It seems like getUserSubscribePreference() is returning null even tho I'm not quite seeing how that can happen, maybe a race condition when two async codes are trying to read from this function at the same time. Maybe wrapping it in a synchronized block would solve the issue but I'm not sure.

**Comment by Jeasmine** [comment]
Hey @JurajKuliska, we already have this fix https://github.com/OneSignal/OneSignal-Android-SDK/pull/1389. That is coming on the next release. Thanks for pointing this up!
