### ISSUE TITLE
NoClassDefFoundError: LocationServices

### ISSUE THREAD

**Issue by PedroOkawa** [OneSignal/OneSignal-Android-SDK#140]
Hi,

I'm facing an issue related to LocationServices using OneSignal.
It happened just once while I was trying to open a fragment that shows a mapview with the current location, it gave me a NoClassDefFoundError.

Here's the full stack:

```
00:00 W/OneSignal: Location permission exists but there was an error initializing: 
00:00 W/OneSignal: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/location/LocationServices;
00:00 W/OneSignal: 	at com.onesignal.LocationGMS.startGetLocation(LocationGMS.java:116)
00:00 W/OneSignal: 	at com.onesignal.LocationGMS.getLocation(LocationGMS.java:103)
00:00 W/OneSignal: 	at com.onesignal.OneSignal.startLocationUpdate(OneSignal.java:327)
00:00 W/OneSignal: 	at com.onesignal.OneSignal.startRegistrationOrOnSession(OneSignal.java:319)
00:00 W/OneSignal: 	at com.onesignal.OneSignal.onAppFocus(OneSignal.java:587)
00:00 W/OneSignal: 	at com.onesignal.ActivityLifecycleHandler.handleFocus(ActivityLifecycleHandler.java:120)
00:00 W/OneSignal: 	at com.onesignal.ActivityLifecycleHandler.onActivityResumed(ActivityLifecycleHandler.java:74)
00:00 W/OneSignal: 	at com.onesignal.ActivityLifecycleListener.onActivityResumed(ActivityLifecycleListener.java:50)
00:00 W/OneSignal: 	at android.app.Application.dispatchActivityResumed(Application.java:214)
00:00 W/OneSignal: 	at android.app.Activity.onResume(Activity.java:1211)
00:00 W/OneSignal: 	at android.support.v4.app.BaseFragmentActivityGingerbread.onResume(BaseFragmentActivityGingerbread.java)
00:00 W/OneSignal: 	at android.support.v4.app.FragmentActivity.onResume(FragmentActivity.java:485)
00:00 W/OneSignal: 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1281)
00:00 W/OneSignal: 	at android.app.Activity.performResume(Activity.java:6320)
00:00 W/OneSignal: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3110)
00:00 W/OneSignal: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3152)
00:00 W/OneSignal: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2495)
00:00 W/OneSignal: 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
00:00 W/OneSignal: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
00:00 W/OneSignal: 	at android.os.Handler.dispatchMessage(Handler.java:102)
00:00 W/OneSignal: 	at android.os.Looper.loop(Looper.java:148)
00:00 W/OneSignal: 	at android.app.ActivityThread.main(ActivityThread.java:5443)
00:00 W/OneSignal: 	at java.lang.reflect.Method.invoke(Native Method)
00:00 W/OneSignal: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
00:00 W/OneSignal: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
00:00 W/OneSignal: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.location.LocationServices" on path: DexPathList[[zip file "/data/app/pt.ageas.mundo-1/base.apk"],nativeLibraryDirectories=[/data/app/pt.ageas.mundo-1/lib/arm, /data/app/pt.ageas.mundo-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
00:00 W/OneSignal: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
00:00 W/OneSignal: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
00:00 W/OneSignal: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
00:00 W/OneSignal: 	... 25 more
00:00 W/OneSignal: 	Suppressed: java.lang.ClassNotFoundException: com.google.android.gms.location.LocationServices
00:00 W/OneSignal: 		at java.lang.Class.classForName(Native Method)
00:00 W/OneSignal: 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
00:00 W/OneSignal: 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
00:00 W/OneSignal: 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
00:00 W/OneSignal: 		... 26 more
00:00 W/OneSignal: 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```

If any other info is necessary to help you find a solution or even a reason, please let me know and I can provide it.

Thanks.

**Comment by jkasten2** [comment]
@PedroOkawa Can you make sure you have the following in your `app/build.gradle` file?
```gradle
compile "com.google.android.gms:play-services-location:+"
```

Thanks.

**Comment by PedroOkawa** [comment]
@jkasten2 I just checked and it's missing, I just had `compile "com.google.android.gms:play-services-maps:9.4.0"` added.

Really thanks, mate.
