### ISSUE TITLE
Error Caused by java.lang.ClassNotFoundException: com.huawei.hms.api.HuaweiApiAvailability

### ISSUE THREAD

**Issue by fillipeoliveira-hotmart** [OneSignal/OneSignal-Android-SDK#1423]
**Description:**

After add Dexguard on our project, I start to receive some errors of `NoClassDefFoundError` on `HuaweiApiAvailability`. I search on other issues, like https://github.com/OneSignal/OneSignal-Android-SDK/issues/1194 and https://github.com/OneSignal/OneSignal-Android-SDK/issues/1085 but the only solution is keep everything from OneSignal on dexguard rules.

**Environment**

OneSignal 4.4.2 via Gradle + Dexguard
`implementation ('com.onesignal:OneSignal:4.4.2')`

**Steps to Reproduce Issue:**

None

**Anything else:**
```
Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/huawei/hms/api/HuaweiApiAvailability;
       at com.onesignal.OSUtils.isHMSCoreInstalledAndEnabled(OSUtils.java:289)
       at com.onesignal.OSUtils.supportsHMS(OSUtils.java:317)
       at com.onesignal.OSUtils.getDeviceType(OSUtils.java:349)
       at com.onesignal.OSUtils.initializationChecker(OSUtils.java:112)
       at com.onesignal.OneSignal.init(OneSignal.java:711)
       at com.onesignal.OneSignal.setAppId(OneSignal.java:625)
       at com.onesignal.OneSignal.reassignDelayedInitParams(OneSignal.java:1028)
       at com.onesignal.OneSignal.onRemoteParamSet(OneSignal.java:759)
       at com.onesignal.OneSignal$5.complete(OneSignal.java:969)
       at com.onesignal.OneSignalRemoteParams.processJson(OneSignalRemoteParams.java:205)
       at com.onesignal.OneSignalRemoteParams.access$100(OneSignalRemoteParams.java:12)
       at com.onesignal.OneSignalRemoteParams$1.onSuccess(OneSignalRemoteParams.java:150)
       at com.onesignal.OneSignalRestClient$5.run(OneSignalRestClient.java:269)
       at java.lang.Thread.run(Thread.java:929)
```
```
Caused by java.lang.ClassNotFoundException: com.huawei.hms.api.HuaweiApiAvailability
       at com.onesignal.OSUtils.isHMSCoreInstalledAndEnabled(OSUtils.java:289)
       at com.onesignal.OSUtils.supportsHMS(OSUtils.java:317)
       at com.onesignal.OSUtils.getDeviceType(OSUtils.java:349)
       at com.onesignal.OSUtils.initializationChecker(OSUtils.java:112)
       at com.onesignal.OneSignal.init(OneSignal.java:711)
       at com.onesignal.OneSignal.setAppId(OneSignal.java:625)
       at com.onesignal.OneSignal.reassignDelayedInitParams(OneSignal.java:1028)
       at com.onesignal.OneSignal.onRemoteParamSet(OneSignal.java:759)
       at com.onesignal.OneSignal$5.complete(OneSignal.java:969)
       at com.onesignal.OneSignalRemoteParams.processJson(OneSignalRemoteParams.java:205)
       at com.onesignal.OneSignalRemoteParams.access$100(OneSignalRemoteParams.java:12)
       at com.onesignal.OneSignalRemoteParams$1.onSuccess(OneSignalRemoteParams.java:150)
       at com.onesignal.OneSignalRestClient$5.run(OneSignalRestClient.java:269)
       at java.lang.Thread.run(Thread.java:929)
```
Maybe, if add an try/catch on this method
https://github.com/OneSignal/OneSignal-Android-SDK/blob/main/OneSignalSDK/onesignal/src/main/java/com/onesignal/OSUtils.java#L287
like this one
https://github.com/OneSignal/OneSignal-Android-SDK/blob/main/OneSignalSDK/onesignal/src/main/java/com/onesignal/OSUtils.java#L160
or check if `HuaweiApiAvailability` exists inside `supportsHMS()`, help to solve the problem

This erros are more frequently on huawei phones
![image](https://user-images.githubusercontent.com/51706700/130986143-2471a2e7-c4d1-4d40-9010-9d9e074f5b25.png)

**Comment by fillipeoliveira-hotmart** [comment]
Update to version `4.6.0` and the problem persists

**Comment by jkasten2** [comment]
@fillipeoliveira-hotmart Thanks for reporting.
I believe Dexguard is removing the `hasHMSAvailabilityLibrary()` and `hasAllHMSLibrariesForPushKit()` checks since it believes they are not needed. Could you share your Dexguard config so we can test with the same configuration as your project to try to come up with a solution?

In the mean time you can use the following in your Proguard config to keep minifying most of the OneSignal code but keep the problematic `com.onesignal.OSUtils` code as-is:
```pro
-keep class com.onesignal.OSUtils** {*;}
```

**Comment by fillipeoliveira-hotmart** [comment]
Hi @jkasten2 
We already try with `-keep class com.onesignal.** {*;}` but nothing changed.

I can try with this one you said and report back when get some results.

**Comment by fillipeoliveira-hotmart** [comment]
Hi @jkasten2 
We release the new version of the app with this change on dexguard yesterday and we already started to receive the crash again.
```
Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/huawei/hms/api/HuaweiApiAvailability;
       at com.onesignal.OSUtils.isHMSCoreInstalledAndEnabled(OSUtils.java:288)
       at com.onesignal.OSUtils.supportsHMS(OSUtils.java:316)
       at com.onesignal.OSUtils.getDeviceType(OSUtils.java:348)
       at com.onesignal.OSUtils.initializationChecker(OSUtils.java:111)
       at com.onesignal.OneSignal.init(OneSignal.java:797)
       at com.onesignal.OneSignal.setAppId(OneSignal.java:693)
       at com.onesignal.OneSignal.reassignDelayedInitParams(OneSignal.java:1137)
       at com.onesignal.OneSignal.onRemoteParamSet(OneSignal.java:845)
       at com.onesignal.OneSignal$6.complete(OneSignal.java:1078)
       at com.onesignal.OneSignalRemoteParams.processJson(OneSignalRemoteParams.java:206)
       at com.onesignal.OneSignalRemoteParams.access$100(OneSignalRemoteParams.java:12)
       at com.onesignal.OneSignalRemoteParams$1.onSuccess(OneSignalRemoteParams.java:151)
       at com.onesignal.OneSignalRestClient$5.run(OneSignalRestClient.java:283)
       at java.lang.Thread.run(Thread.java:929)
```
```
Caused by java.lang.ClassNotFoundException: com.huawei.hms.api.HuaweiApiAvailability
       at com.onesignal.OSUtils.isHMSCoreInstalledAndEnabled(OSUtils.java:288)
       at com.onesignal.OSUtils.supportsHMS(OSUtils.java:316)
       at com.onesignal.OSUtils.getDeviceType(OSUtils.java:348)
       at com.onesignal.OSUtils.initializationChecker(OSUtils.java:111)
       at com.onesignal.OneSignal.init(OneSignal.java:797)
       at com.onesignal.OneSignal.setAppId(OneSignal.java:693)
       at com.onesignal.OneSignal.reassignDelayedInitParams(OneSignal.java:1137)
       at com.onesignal.OneSignal.onRemoteParamSet(OneSignal.java:845)
       at com.onesignal.OneSignal$6.complete(OneSignal.java:1078)
       at com.onesignal.OneSignalRemoteParams.processJson(OneSignalRemoteParams.java:206)
       at com.onesignal.OneSignalRemoteParams.access$100(OneSignalRemoteParams.java:12)
       at com.onesignal.OneSignalRemoteParams$1.onSuccess(OneSignalRemoteParams.java:151)
       at com.onesignal.OneSignalRestClient$5.run(OneSignalRestClient.java:283)
       at java.lang.Thread.run(Thread.java:929)
```

we are using this version of oneSignal now
```
object OneSignal {
        const val base = "4.6.2"
        const val plugin = "0.13.4"
    }
```

The dexguard config file you requested, I sent directly to support team by email.

**Comment by jkasten2** [comment]
@fillipeoliveira-hotmart I found that `-assumenosideeffects` seems to override the `-keep` in some cases. Stripping out `getName()` can't be used on the current version of OneSignal because of the way the SDK uses it with `NoClassDefFoundError` in `com.onesignal.OSUtils` to detect if some classes exists.

## Workaround for OneSignal 4.6.3 & older
Remove the following `getName()` rule from your `.pro` proguard / dexguard rule file.
```.pro
-assumenosideeffects public final class java.lang.Class {
    // Comment out this getName() line
    public java.lang.String getName();
}
```

## Fix
For future versions of OneSignal removing this rule won't be required, it is being addressed in commit b5bfd597210051ea38d98309989576ef0f801d95 and will be in a future release (4.6.4 and/or 4.7.0)

**Comment by fillipeoliveira-hotmart** [comment]
Hi @jkasten2 
That's are good news!

I have not find yet a way to do this workaround on Dexguard, but if in the next version the problem is fixed, thats not a problem.

When we release a new version with the workaround or with the new version, I return with the results.
Thx for your help!

**Comment by raghav2945** [comment]
This problem has resurfaced with your version: 4.6.3. for us [[Audiomack](https://github.com/audiomack/audiomack-android/issues/3551)]. The stacks looks similar but still I am uploading the latest stack-trace from Firebase.

Stack-trace

> Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/huawei/hms/api/HuaweiApiAvailability;
       at com.onesignal.OSUtils.isHMSCoreInstalledAndEnabled(OSUtils.java:289)
       at com.onesignal.OSUtils.supportsHMS(OSUtils.java:317)
       at com.onesignal.OSUtils.getDeviceType(OSUtils.java:349)
       at com.onesignal.OSUtils.initializationChecker(OSUtils.java:112)
       at com.onesignal.OneSignal.init(OneSignal.java:796)
       at com.onesignal.OneSignal.setAppId(OneSignal.java:692)
       at com.onesignal.OneSignal.reassignDelayedInitParams(OneSignal.java:1136)
       at com.onesignal.OneSignal.onRemoteParamSet(OneSignal.java:844)
       at com.onesignal.OneSignal$6.complete(OneSignal.java:1077)
       at com.onesignal.OneSignalRemoteParams.processJson(OneSignalRemoteParams.java:206)
       at com.onesignal.OneSignalRemoteParams.access$100(OneSignalRemoteParams.java:12)
       at com.onesignal.OneSignalRemoteParams$1.onSuccess(OneSignalRemoteParams.java:151)
       at com.onesignal.OneSignalRestClient$5.run(OneSignalRestClient.java:283)
       at java.lang.Thread.run(Thread.java:818)



> Caused by java.lang.ClassNotFoundException: Didn't find class "com.huawei.hms.api.HuaweiApiAvailability" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.audiomack-1/base.apk"],nativeLibraryDirectories=[/data/app/com.audiomack-1/lib/arm64, /data/app/com.audiomack-1/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
       at com.onesignal.OSUtils.isHMSCoreInstalledAndEnabled(OSUtils.java:289)
       at com.onesignal.OSUtils.supportsHMS(OSUtils.java:317)
       at com.onesignal.OSUtils.getDeviceType(OSUtils.java:349)
       at com.onesignal.OSUtils.initializationChecker(OSUtils.java:112)
       at com.onesignal.OneSignal.init(OneSignal.java:796)
       at com.onesignal.OneSignal.setAppId(OneSignal.java:692)
       at com.onesignal.OneSignal.reassignDelayedInitParams(OneSignal.java:1136)
       at com.onesignal.OneSignal.onRemoteParamSet(OneSignal.java:844)
       at com.onesignal.OneSignal$6.complete(OneSignal.java:1077)
       at com.onesignal.OneSignalRemoteParams.processJson(OneSignalRemoteParams.java:206)
       at com.onesignal.OneSignalRemoteParams.access$100(OneSignalRemoteParams.java:12)
       at com.onesignal.OneSignalRemoteParams$1.onSuccess(OneSignalRemoteParams.java:151)
       at com.onesignal.OneSignalRestClient$5.run(OneSignalRestClient.java:283)
       at java.lang.Thread.run(Thread.java:818)

**Comment by fillipeoliveira-hotmart** [comment]
Hi @raghav2945 , the fix for this bug is in [4.6.4](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/4.6.4), but I not tested it yet.
https://github.com/OneSignal/OneSignal-Android-SDK/pull/1492

**Comment by raghav2945** [comment]
> Hi @raghav2945 , the fix for this bug is in [4.6.5](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/4.6.5), but I not tested it yet. #1492

We will update the SDK and monitor it, and if everything goes well, we will inform you here.

**Comment by fillipeoliveira-hotmart** [comment]
Everything working on version 4.6.5.
Thx @jkasten2 for your help!

**Comment by zohaib-ahmad1020** [comment]
Fatal Exception: java.lang.NullPointerException: context must not be null.
       at com.huawei.hms.utils.Checker.checkNonNull(Checker.java:2)
       at com.huawei.hms.api.HuaweiApiAvailabilityImpl.isHuaweiMobileServicesAvailable(HuaweiApiAvailabilityImpl.java:1)
       at com.huawei.hms.rn.safetydetect.huaweiapi.HuaweiApiService.isHuaweiMobileServicesAvailable(HuaweiApiService.java:30)
       at com.huawei.hms.rn.safetydetect.huaweiapi.HuaweiApiModule.isHuaweiMobileServicesAvailable(HuaweiApiModule.java:42)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
       at com.facebook.jni.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loopOnce(Looper.java:243)
       at android.os.Looper.loop(Looper.java:338)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
       at java.lang.Thread.run(Thread.java:1012)
