### ISSUE TITLE
OneSignal AppId format is invalid

### ISSUE THREAD

**Issue by raphaelcoder** [OneSignal/OneSignal-Android-SDK#143]
For some reason, i can't seem to get OneSignal to initialize in my app. Here's my build.gradle

```groovy 
android {
    compileSdkVersion 24
    buildToolsVersion "24.0.0"
    defaultConfig {
        applicationId "com.letsbillion"
        manifestPlaceholders = ["onesignal_app_id": "I"VE PUT MY APP ID HERE", "onesignal_google_project_number": "GOOGLE PROJECT NUMBER HERE"]
        minSdkVersion 14
        targetSdkVersion 24
        versionCode 1
        versionName "1.0"
        multiDexEnabled true

    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    productFlavors {}
}  
```

I'm using   ```compile 'com.onesignal:OneSignal:3.+@aar'``` 

``` E/OneSignal: OneSignal AppId format is invalid.
                     Example: 'b2f7f966-d8cc-11e4-bed1-df8f05be55ba'
           java.lang.NullPointerException: uuid == null
           at java.util.UUID.fromString(UUID.java:182)
      at com.onesignal.OSUtils.initializationChecker(OSUtils.java:52)
   at com.onesignal.OneSignal.init(OneSignal.java:238)
 at com.onesignal.OneSignal.init(OneSignal.java:215)

```

**Comment by santoshmodi** [comment]
Same error i m receiving how you fixed this?

**Comment by raphaelcoder** [comment]
There're three other init methods in the Onesignal class. Use it as you please.

```java  

 public static void init(Context context, String googleProjectNumber, String oneSignalAppId)

public static void init(Context context, String googleProjectNumber, String oneSignalAppId, NotificationOpenedHandler notificationOpenedHandler)

public static void init(Context context, String googleProjectNumber, String oneSignalAppId, NotificationOpenedHandler notificationOpenedHandler, NotificationReceivedHandler notificationReceivedHandler);

**Comment by jkasten2** [comment]
@raphaelcoder @santoshmodi I believe the issue is related to your `buildTypes` and `productFlavors`. Can you try adding the `manifestPlaceholders` as shown in issue #9?

**Comment by jkasten2** [comment]
@raphaelcoder @santoshmodi Closing this issue due to inactivity. Please feel free to reopen it if you are still have an issue.

**Comment by dev-JE02** [comment]
Still getting this issue in `4.0.0-SNAPSHOT`

**Comment by jkasten2** [comment]
@dev-JE02 Can you provide more details about your project?
Do you have `buildTypes` and/or `productFlavors` in your `app/gradle.build`?
Do you have `tools:node="replace"` in your `AndroidManifest.xml`?

**Comment by dev-JE02** [comment]
Here is my app/build.gradle file. I used this, and I also tried putting it inside the `buildTypes > defaultConfig` clause but OneSignal still can't see the `onesignal_app_id`

```
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-kapt'
apply plugin: 'idea'

android {
    compileSdkVersion 26
    buildToolsVersion '26.0.0'
    defaultConfig {
        applicationId "com.oracle.develop"
        manifestPlaceholders = ["onesignal_app_id": "I"VE PUT MY APP ID HERE", "onesignal_google_project_number": "GOOGLE PROJECT NUMBER HERE"]
        minSdkVersion 21

        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
        test.java.srcDirs += 'src/test/kotlin'
        androidTest.java.srcDirs += 'src/androidTest/kotlin'
    }
    packagingOptions {
        exclude 'META-INF/rxjava.properties'
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile 'com.google.code.findbugs:jsr305:3.0.1'
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:26.0.0'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    testCompile 'junit:junit:4.12'

    // Kotlin
    compile "org.jetbrains.kotlin:kotlin-stdlib-jre7:$kotlin_version"

    // Firebase
    compile 'com.google.firebase:firebase-core:11.0.4'
    compile 'com.google.firebase:firebase-auth:11.0.4'
    compile 'com.google.firebase:firebase-database:11.0.4'
    compile 'com.google.firebase:firebase-storage:11.0.4'
    compile 'com.google.firebase:firebase-messaging:11.0.4'
    compile 'com.firebaseui:firebase-ui:2.0.1'

    // Rx2Firebase
    compile 'com.github.frangsierra:rx2firebase:1.1.3'

    // Android Design Library
    compile 'com.android.support:design:26.0.0'

    // RecyclerView
    compile 'com.android.support:recyclerview-v7:26.0.0'

    // CardView
    compile 'com.android.support:cardview-v7:26.0.0'

    //Android Multidex
    compile 'com.android.support:multidex:1.0.2'

    // Dagger 2
    compile 'com.google.dagger:dagger:2.4'
    kapt 'com.squareup:javapoet:1.8.0'
    kapt 'com.google.dagger:dagger-compiler:2.4'
    provided 'org.glassfish:javax.annotation:10.0-b28'

    // Butterknife
    compile 'com.jakewharton:butterknife:8.4.0'
    kapt 'com.jakewharton:butterknife-compiler:8.4.0'

    // Timber
    compile 'com.jakewharton.timber:timber:4.3.1'

    // SwipyRefreshLayout
    compile 'com.github.orangegangsters:swipy:1.2.3@aar'

    // Glide
    compile 'com.github.bumptech.glide:glide:4.0.0-RC1'
    kapt 'com.github.bumptech.glide:compiler:4.0.0-RC1'

    // Lorem Ipsum Generator
    compile 'de.sven-jacobs:loremipsum:1.0'

    // Pretty Time
    compile 'org.ocpsoft.prettytime:prettytime:4.0.1.Final'

    // Flexible Adapters
    compile 'eu.davidea:flexible-adapter:5.0.0-rc2'

    // No Nonsense File Picker
    compile 'com.nononsenseapps:filepicker:3.1.0'

    //PhoneNumberUtil
    compile 'com.googlecode.libphonenumber:libphonenumber:8.5.0'

    //OkHttp 3
    compile 'com.squareup.okhttp3:okhttp:3.5.0'
    compile 'com.squareup.okhttp3:logging-interceptor:3.5.0'

    // RxJava 2
    compile 'io.reactivex.rxjava2:rxjava:2.1.0'
    compile 'io.reactivex.rxjava2:rxkotlin:2.0.3'

    // RxAndroid 2
    compile 'io.reactivex.rxjava2:rxandroid:2.0.1'

    // RxLifecycle 2
    compile 'com.trello.rxlifecycle2:rxlifecycle-android:2.0.1'

    // RxBinding 2
    compile 'com.jakewharton.rxbinding2:rxbinding:2.0.0'

    // Parceler
    compile 'org.parceler:parceler-api:1.1.6'
    kapt 'org.parceler:parceler:1.1.6'

    // Android View Animations
    compile 'com.daimajia.easing:library:2.0@aar'
    compile 'com.daimajia.androidanimations:library:2.2@aar'

    // Floating Action Button
    compile 'com.github.clans:fab:1.6.4'

    // Autofit TextView
    compile 'me.grantland:autofittextview:0.2.1'

    // Rich Text Editor
    compile 'jp.wasabeef:richeditor-android:1.2.2'

    // Material Dialogs
    compile 'com.afollestad.material-dialogs:core:0.9.4.5'
    compile 'com.afollestad.material-dialogs:commons:0.9.4.5'

    // Android Image Cropper
    compile 'com.theartofdev.edmodo:android-image-cropper:2.4.6'

    // HTML TextView
    compile 'org.sufficientlysecure:html-textview:3.4'

    // Smart Tab Layout
    compile 'com.ogaclejapan.smarttablayout:library:1.6.1@aar'
    compile 'com.ogaclejapan.smarttablayout:utils-v4:1.6.1@aar'

    // Bubble Layout
    compile 'com.github.lguipeng:BubbleView:1.0.1'

    // Android View Animations
    compile 'com.daimajia.easing:library:2.0@aar'
    compile 'com.daimajia.androidanimations:library:2.2@aar'

    // Apache Commons Lang Package
    compile group: 'org.apache.commons', name: 'commons-lang3', version: '3.6'

    // CircleImageView
    compile 'de.hdodenhof:circleimageview:2.1.0'

    // MPAndroidCharts
    compile 'com.github.PhilJay:MPAndroidChart:v3.0.2'

    // Android Word Cloud
    compile 'net.alhazmy13.wordcloud:library:0.2.0-beta'

    // EventBus
    compile 'org.greenrobot:eventbus:3.0.0'

    // OneSignal
    compile 'com.onesignal:OneSignal:4.0.0-SNAPSHOT'
}

// At the moment for non-Android projects you need to explicitly
// mark the code generated by kapt as 'generated source code'
// for correct highlighting and resolve in IDE.
idea {
    module {
        sourceDirs += file('build/generated/source/kapt/main')
        generatedSourceDirs += file('build/generated/source/kapt/main')
    }
}
apply plugin: 'com.google.gms.google-services'
```

And here is my project build.gradle file

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext.kotlin_version = '1.1.3-2'
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.0-alpha9'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "org.jetbrains.kotlin:kotlin-android-extensions:$kotlin_version"
        classpath 'com.google.gms:google-services:3.1.0'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
        mavenCentral()
        maven { url 'https://jitpack.io' }
        maven { url 'https://dl.bintray.com/kotlin/kotlin-eap-1.1' }
        maven { url 'https://maven.google.com' }
        maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

```
