### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException TCL devices android 7

### ISSUE THREAD

**Issue by MKelman** [OneSignal/OneSignal-Android-SDK#1438]
**Description:**
Crash occurring to hundreds of users daily to TCL specific devices on Android 7. Starting occurring September 15th, 2021. 

**Environment**
1. SDK version: 4.4.0
2. maven

**Anything else:**

From firebase crashlytics: 

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'org.json.JSONObject org.json.JSONObject.put(java.lang.String, java.lang.Object)' on a null object reference
       at com.onesignal.UserState.putOnDependValues(UserState.java:159)
       at com.onesignal.UserStatePushSynchronizer.setPermission(UserStatePushSynchronizer.java:164)
       at com.onesignal.OneSignalStateSynchronizer.setPermission(OneSignalStateSynchronizer.java:174)
       at com.onesignal.OSPermissionChangedInternalObserver.handleInternalChanges(OSPermissionChangedInternalObserver.java:39)
       at com.onesignal.OneSignal.init(OneSignal.java:794)
       at com.onesignal.OneSignal.setAppId(OneSignal.java:685)
       at com.onesignal.OneSignal.reassignDelayedInitParams(OneSignal.java:1096)
       at com.onesignal.OneSignal.onRemoteParamSet(OneSignal.java:819)
       at com.onesignal.OneSignal$5.complete(OneSignal.java:1037)
       at com.onesignal.OneSignalRemoteParams.processJson(OneSignalRemoteParams.java:206)
       at com.onesignal.OneSignalRemoteParams.access$100(OneSignalRemoteParams.java:12)
       at com.onesignal.OneSignalRemoteParams$1.onSuccess(OneSignalRemoteParams.java:151)
       at com.onesignal.OneSignalRestClient$5.run(OneSignalRestClient.java:269)
       at java.lang.Thread.run(Thread.java:761)

**Comment by MKelman** [comment]
@jkasten2 it looks like its occuring on all Alcatel_5044C devices. No we odnt have that device to test on. Yes only on Android 7.

**Comment by nan-li** [comment]
Hi @MKelman, I am checking in on this issue. Is this still an active crash for your Alcatel_5044C Android 7 users?

**Comment by MKelman** [comment]
@nan-li everything seems fine now, i do now see any massive issues as of now. ill reopen if it does come back up
