### ISSUE TITLE
Many crashes at com.onesignal.GenerateNotification.createSummaryNotification

### ISSUE THREAD

**Issue by niusounds** [OneSignal/OneSignal-Android-SDK#1446]
**Description:**

Many crash reports caused by `com.onesignal.GenerateNotification.createSummaryNotification` since 4.4.2 (?).
(It appeared since upgrading to SDK 4.4.2 but previous version using in my app was 4.0.0 so I don't know accurate version which appeared first.)

**Environment**

- Android SDK version: 30
- OneSignal SDK 4.6.0
- Crashing devices: Android 7 ~ 11
- 87% background

**Steps to Reproduce Issue:**

I could not reproduce this crash by myself but Crashlytics records many FCM message logs before crash.

**Anything else:**

Crash log: (with OneSignal SDK 4.6.0)

```
Fatal Exception: java.lang.RuntimeException: android.os.DeadSystemException
       at android.app.NotificationManager.notifyAsUser(NotificationManager.java:320)
       at android.app.NotificationManager.notify(NotificationManager.java:289)
       at androidx.core.app.NotificationManagerCompat.notify(NotificationManagerCompat.java:223)
       at androidx.core.app.NotificationManagerCompat.notify(NotificationManagerCompat.java:205)
       at com.onesignal.GenerateNotification.createSummaryNotification(GenerateNotification.java:687)
       at com.onesignal.GenerateNotification.showNotification(GenerateNotification.java:328)
       at com.onesignal.GenerateNotification.displayNotification(GenerateNotification.java:103)
       at com.onesignal.NotificationBundleProcessor.processJobForDisplay(NotificationBundleProcessor.java:156)
       at com.onesignal.NotificationBundleProcessor.processJobForDisplay(NotificationBundleProcessor.java:133)
       at com.onesignal.OSNotificationController.processNotification(OSNotificationController.java:97)
       at com.onesignal.OSNotificationReceivedEvent.processNotification(OSNotificationReceivedEvent.java:95)
       at com.onesignal.OSNotificationReceivedEvent.access$000(OSNotificationReceivedEvent.java:35)
       at com.onesignal.OSNotificationReceivedEvent$2.run(OSNotificationReceivedEvent.java:84)
       at java.lang.Thread.run(Thread.java:764)
Caused by android.os.TransactionTooLargeException: data parcel size 636628 bytes
       at android.os.BinderProxy.transactNative(BinderProxy.java)
       at android.os.BinderProxy.transact(BinderProxy.java:513)
       at android.app.INotificationManager$Stub$Proxy.enqueueNotificationWithTag(INotificationManager.java:2887)
       at android.app.NotificationManager.notifyAsUser(NotificationManager.java:500)
       at android.app.NotificationManager.notify(NotificationManager.java:450)
       at androidx.core.app.NotificationManagerCompat.notify(NotificationManagerCompat.java:223)
       at androidx.core.app.NotificationManagerCompat.notify(NotificationManagerCompat.java:205)
       at com.onesignal.GenerateNotification.createSummaryNotification(GenerateNotification.java:687)
       at com.onesignal.GenerateNotification.showNotification(GenerateNotification.java:328)
       at com.onesignal.GenerateNotification.displayNotification(GenerateNotification.java:103)
       at com.onesignal.NotificationBundleProcessor.processJobForDisplay(NotificationBundleProcessor.java:156)
       at com.onesignal.NotificationBundleProcessor.processJobForDisplay(NotificationBundleProcessor.java:133)
       at com.onesignal.OSNotificationController.processNotification(OSNotificationController.java:97)
       at com.onesignal.OSNotificationReceivedEvent.processNotification(OSNotificationReceivedEvent.java:95)
       at com.onesignal.OSNotificationReceivedEvent.access$000(OSNotificationReceivedEvent.java:35)
       at com.onesignal.OSNotificationReceivedEvent$2.run(OSNotificationReceivedEvent.java:84)
       at java.lang.Thread.run(Thread.java:919)
```

```
Fatal Exception: java.lang.RuntimeException: android.os.DeadSystemException
       at android.app.NotificationManager.notifyAsUser(NotificationManager.java:320)
       at android.app.NotificationManager.notify(NotificationManager.java:289)
       at androidx.core.app.NotificationManagerCompat.notify(NotificationManagerCompat.java:223)
       at androidx.core.app.NotificationManagerCompat.notify(NotificationManagerCompat.java:205)
       at com.onesignal.GenerateNotification.createSummaryNotification(GenerateNotification.java:687)
       at com.onesignal.GenerateNotification.showNotification(GenerateNotification.java:328)
       at com.onesignal.GenerateNotification.displayNotification(GenerateNotification.java:103)
       at com.onesignal.NotificationBundleProcessor.processJobForDisplay(NotificationBundleProcessor.java:156)
       at com.onesignal.NotificationBundleProcessor.processJobForDisplay(NotificationBundleProcessor.java:133)
       at com.onesignal.OSNotificationController.processNotification(OSNotificationController.java:97)
       at com.onesignal.OSNotificationReceivedEvent.processNotification(OSNotificationReceivedEvent.java:95)
       at com.onesignal.OSNotificationReceivedEvent.access$000(OSNotificationReceivedEvent.java:35)
       at com.onesignal.OSNotificationReceivedEvent$2.run(OSNotificationReceivedEvent.java:84)
       at java.lang.Thread.run(Thread.java:764)
Caused by android.os.DeadSystemException
       at android.app.NotificationManager.notifyAsUser(NotificationManager.java:320)
       at android.app.NotificationManager.notify(NotificationManager.java:289)
       at androidx.core.app.NotificationManagerCompat.notify(NotificationManagerCompat.java:223)
       at androidx.core.app.NotificationManagerCompat.notify(NotificationManagerCompat.java:205)
       at com.onesignal.GenerateNotification.createSummaryNotification(GenerateNotification.java:687)
       at com.onesignal.GenerateNotification.showNotification(GenerateNotification.java:328)
       at com.onesignal.GenerateNotification.displayNotification(GenerateNotification.java:103)
       at com.onesignal.NotificationBundleProcessor.processJobForDisplay(NotificationBundleProcessor.java:156)
       at com.onesignal.NotificationBundleProcessor.processJobForDisplay(NotificationBundleProcessor.java:133)
       at com.onesignal.OSNotificationController.processNotification(OSNotificationController.java:97)
       at com.onesignal.OSNotificationReceivedEvent.processNotification(OSNotificationReceivedEvent.java:95)
       at com.onesignal.OSNotificationReceivedEvent.access$000(OSNotificationReceivedEvent.java:35)
       at com.onesignal.OSNotificationReceivedEvent$2.run(OSNotificationReceivedEvent.java:84)
       at java.lang.Thread.run(Thread.java:764)
```

**Comment by jkasten2** [comment]
@niusounds Thanks for reporting with stack traces. The `DeadSystemException` could be due to your app already shutdown done to another issue or a bug in Android that is causing the core Android runtime to restart. Could you also note the notification features you are using such as images, action buttons, etc? This could be related to the crash. Also let us know if you also started to use any new notification features around the time you updated the Android SDK.
