### ISSUE TITLE
MissingWebViewPackageException

### ISSUE THREAD

**Issue by KristapsKrumins** [OneSignal/OneSignal-Android-SDK#1453]
OneSignal version 4.4.1.
Samsung Android 11.

```
Caused by android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
       at android.webkit.WebViewFactory.getWebViewContextAndSetProvider(WebViewFactory.java:339)
       at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:402)
       at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:252)
       at android.webkit.WebView.getFactory(WebView.java:2576)
       at android.webkit.WebView.ensureProviderCreated(WebView.java:2570)
       at android.webkit.WebView.setOverScrollMode(WebView.java:2657)
       at android.view.View.<init>(View.java:5697)
       at android.view.View.<init>(View.java:5886)
       at android.view.ViewGroup.<init>(ViewGroup.java:715)
       at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:59)
       at android.webkit.WebView.<init>(WebView.java:413)
       at android.webkit.WebView.<init>(WebView.java:355)
       at android.webkit.WebView.<init>(WebView.java:337)
       at android.webkit.WebView.<init>(WebView.java:324)
       at android.webkit.WebView.<init>(WebView.java:314)
       at com.onesignal.OSWebView.<init>(OSWebView.java:10)
       at com.onesignal.WebViewManager.setupWebView(WebViewManager.java:359)
       at com.onesignal.WebViewManager.access$100(WebViewManager.java:36)
       at com.onesignal.WebViewManager$3.run(WebViewManager.java:141)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8528)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

Can You please add a check if WebView is available? Or how can I handle this exception?

**Comment by jkasten2** [comment]
@KristapsKrumins Thanks for reporting, this would be rare but this is something we can handle to prevent the crash.
