### ISSUE TITLE
FATAL EXCEPTION: OS_REST_SUCCESS_CALLBACK

### ISSUE THREAD

**Issue by javierbentez** [OneSignal/OneSignal-Android-SDK#1459]
**Description:**

When my app try to set onesignal app id, it crash and I get this error:

```
2021-10-17 18:17:45.645 28353-28672/? E/AndroidRuntime: FATAL EXCEPTION: OS_REST_SUCCESS_CALLBACK
    Process: example.com, PID: 28353
    java.lang.VerifyError: Verifier rejected class androidx.work.impl.OperationImpl: com.google.common.util.concurrent.ListenableFuture androidx.work.impl.OperationImpl.getResult() failed to verify: com.google.common.util.concurrent.ListenableFuture androidx.work.impl.OperationImpl.getResult(): [0x2]  can't resolve returned type 'Unresolved Reference: com.google.common.util.concurrent.ListenableFuture' or 'Unresolved Reference: androidx.work.impl.utils.futures.SettableFuture' (declaration of 'androidx.work.impl.OperationImpl' appears in /data/app/~~J82UPx1RDDQpWm9c0fgoBQ==/example.com-vE1sYQs06t8TnXNdY1nwbg==/base.apk)
        at androidx.work.impl.utils.EnqueueRunnable.<init>(EnqueueRunnable.java:79)
        at androidx.work.impl.WorkContinuationImpl.enqueue(WorkContinuationImpl.java:186)
        at androidx.work.impl.WorkManagerImpl.enqueueUniqueWork(WorkManagerImpl.java:407)
        at androidx.work.WorkManager.enqueueUniqueWork(WorkManager.java:351)
        at com.onesignal.OSNotificationRestoreWorkManager.beginEnqueueingWork(OSNotificationRestoreWorkManager.java:49)
        at com.onesignal.OneSignal.handleActivityLifecycleHandler(OneSignal.java:931)
        at com.onesignal.OneSignal.init(OneSignal.java:808)
        at com.onesignal.OneSignal.setAppId(OneSignal.java:691)
        at com.onesignal.OneSignal.reassignDelayedInitParams(OneSignal.java:1127)
        at com.onesignal.OneSignal.onRemoteParamSet(OneSignal.java:845)
        at com.onesignal.OneSignal$6.complete(OneSignal.java:1068)
        at com.onesignal.OneSignalRemoteParams.processJson(OneSignalRemoteParams.java:206)
        at com.onesignal.OneSignalRemoteParams.access$100(OneSignalRemoteParams.java:12)
        at com.onesignal.OneSignalRemoteParams$1.onSuccess(OneSignalRemoteParams.java:151)
        at com.onesignal.OneSignalRestClient$5.run(OneSignalRestClient.java:269)
        at java.lang.Thread.run(Thread.java:923)
```

**Environment**

minSdkVersion 23
targetSdkVersion 30 (I've tried to change it to 31 also)
I've added reproducing the steps in the android docs.
Yesterday, with the same code, worked.

**Steps to Reproduce Issue:**

1. Execute the line:
`OneSignal.setAppId("HERE IS MY APP ID");`

**Comment by nan-li** [comment]
Hi @elmundomusical4,

Can you share the following information please:
1. The OneSignal SDK version
2. Your root `buildle.gradle` and your `app/build.gradle`

Also, it's worth trying these steps:

1. Exit Studio.
2. Delete `.idea/`, `build/`, `app/build` directories.
3. Start Studio
4. Clean & rebuild project.

**Comment by nan-li** [comment]
Hi @elmundomusical4, 

It looks like this dependency `implementation 'com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava'` is causing the issue where it can't resolve ListenableFuture, which seems to be coming from `com.google.guava:listenablefuture` when I look in Studio .

Remove that dependency and it should work.

**Comment by elmundomusical4** [comment]
So thanks!! It is now fixed!! 😃😃
