### ISSUE TITLE
Crash happening with android.app.RemoteServiceException on android 11

### ISSUE THREAD

**Issue by rnjt-sp6** [OneSignal/OneSignal-Android-SDK#1464]
**Description:**
We facing a huge amount of  fatal exceptions after updating our app with updated onesignal sdk. It is happening only on specific devices like samsung and Redmi devices (Android 11). Will share the details below.

**Environment**
Android compile and target sdk : 30
OneSignal Version : com.onesignal:OneSignal:[4.0.0, 4.99.99]')
Have updated onesignal sdk from [3.13.2, 3.99.99] to [4.0.0, 4.99.99]

**Crashlog:**

Fatal Exception: android.app.RemoteServiceException: Bad notification(tag=null, id=101010) posted from package net.atlas.b, crashing app(uid=10286, pid=9122): Couldn't create icon StatusBarIcon(icon=Icon(typ=RESOURCE pkg=net.atlas.b id=0x7f08013b) visible user=0 )
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2240)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8512)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1139)

Have checked the previous issue that are related to bad notification. Kindly suggest some ways to fix this

**Comment by nan-li** [comment]
Hi @rnjt-sp6, I'm following up to ask if this is still an issue for you? After some searching, it may have to do with the smallIcon you have for the notification.

**Comment by jkasten2** [comment]
Closing due to no response.
