### ISSUE TITLE
Android 12 crash -  java.lang.IllegalArgumentException for pending intents

### ISSUE THREAD

**Issue by VladMurz** [OneSignal/OneSignal-Android-SDK#1489]
**Description:**
the app crashes on Android 12 with the following error: \
`Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent. Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.`

**Environment**

  compileSdkVersion 31
  minSdkVersion 24 
  targetSdkVersion 31
  implementation group: 'com.onesignal', name: 'OneSignal', version: '4.4.1'

**Steps to Reproduce Issue:**

**Anything else:**

```
Fatal Exception: java.lang.IllegalArgumentException: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
       at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
       at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:458)
       at android.app.PendingIntent.getActivity(PendingIntent.java:444)
       at android.app.PendingIntent.getActivity(PendingIntent.java:408)
       at com.onesignal.GenerateNotification.getNewActionPendingIntent(GenerateNotification.java:4)
       at com.onesignal.GenerateNotification.createGenericPendingIntentsForNotif(GenerateNotification.java:23)
       at com.onesignal.GenerateNotification.showNotification(GenerateNotification.java:134)
       at com.onesignal.GenerateNotification.displayNotification(GenerateNotification.java:10)
       at com.onesignal.NotificationBundleProcessor.processJobForDisplay(NotificationBundleProcessor.java:71)
       at com.onesignal.NotificationBundleProcessor.processJobForDisplay(NotificationBundleProcessor.java:1)
       at com.onesignal.OSNotificationController.processNotification(OSNotificationController.java:23)
       at com.onesignal.OSNotificationReceivedEvent.processNotification(OSNotificationReceivedEvent.java:16)
       at com.onesignal.OSNotificationReceivedEvent.access$000(OSNotificationReceivedEvent.java)
       at com.onesignal.OSNotificationReceivedEvent$2.run(OSNotificationReceivedEvent.java:4)
       at java.lang.Thread.run(Thread.java:920)
```

**Comment by arjun1194** [comment]
hey why did you close this ?
Can you share how you fixed this error

**Comment by C-Sinclair** [comment]
Plus one on the above. Can anyone answer how to fix this issue with Android 12?

**Comment by VladMurz** [comment]
Hey, just use the latest version on the library and the issue is no longer
reproducible.

**Comment by jkasten2** [comment]
In order for OneSignal to be compatible with apps that have `targetSdkVersion 31` and are run on Android 12 you must use version 4.6.2 or newer:
https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/4.6.2
