### ISSUE TITLE
The SDK crashes during the initialization on Amazon devices with the AppStore SDK in version 3.0.2

### ISSUE THREAD

**Issue by ludovicroland** [OneSignal/OneSignal-Android-SDK#1516]
**Description:**

On a Fire HD 8 tablet, the OneSignal SDK crashes during the initialization with the following stacktrace:

```
java.lang.NullPointerException: null receiver
        at java.lang.reflect.Method.invoke(Native Method)
        at com.onesignal.k3.<init>(TrackAmazonPurchase.java:68)
        at com.onesignal.p2.w0(OneSignal.java:940)
        at com.onesignal.p2.F0(OneSignal.java:817)
        at com.onesignal.p2.s1(OneSignal.java:692)
        at com.onesignal.p2.a1(OneSignal.java:1136)
        at com.onesignal.p2.W0(OneSignal.java:844)
        at com.onesignal.p2$n.a(OneSignal.java:1077)
        at com.onesignal.z2.f(OneSignalRemoteParams.java:206)
        at com.onesignal.z2.c(OneSignalRemoteParams.java:12)
        at com.onesignal.z2$a.b(OneSignalRemoteParams.java:151)
        at com.onesignal.a3$e.run(OneSignalRestClient.java:292)
        at java.lang.Thread.run(Thread.java:764)
```

**Environment**

1. OneSignal 4.6.5
2. amazon-appstore-sdk 3.0.2
3. Fire HD 8 (generation 10)
4. Fire OS 7.3.2.2
5. Android SDK API 31

**Steps to Reproduce Issue:**

1. Follow the OneSignal documentation in order to integrate OneSignal onAndroid and then on Amazon device
2. launch the app

**Anything else:**

```
java.lang.NullPointerException: null receiver
        at java.lang.reflect.Method.invoke(Native Method)
        at com.onesignal.k3.<init>(TrackAmazonPurchase.java:68)
        at com.onesignal.p2.w0(OneSignal.java:940)
        at com.onesignal.p2.F0(OneSignal.java:817)
        at com.onesignal.p2.s1(OneSignal.java:692)
        at com.onesignal.p2.a1(OneSignal.java:1136)
        at com.onesignal.p2.W0(OneSignal.java:844)
        at com.onesignal.p2$n.a(OneSignal.java:1077)
        at com.onesignal.z2.f(OneSignalRemoteParams.java:206)
        at com.onesignal.z2.c(OneSignalRemoteParams.java:12)
        at com.onesignal.z2$a.b(OneSignalRemoteParams.java:151)
        at com.onesignal.a3$e.run(OneSignalRestClient.java:292)
        at java.lang.Thread.run(Thread.java:764)
```

According to my own investigation, it crashes in the line 68 of the `TrackAmazonPurchase` class:

```java
Class<?> listenerHandlerClass = Class.forName("com.amazon.device.iap.internal.d");
listenerHandlerObject = listenerHandlerClass.getMethod("d").invoke(null); // line 68
listenerHandlerField = listenerHandlerClass.getDeclaredField("f");
listenerHandlerField.setAccessible(true);
```

The issue is probably due to the fact that in the Amazon AppStore SDK 3.0.2 the `d` method (the constructor) is private:

```java
package com.amazon.device.iap.internal;

import android.app.Application;
import android.content.Context;
import android.content.Intent;
import com.amazon.a.a;
import com.amazon.a.a.o.f;
import com.amazon.device.iap.PurchasingListener;
import com.amazon.device.iap.internal.util.b;
import com.amazon.device.iap.model.FulfillmentResult;
import com.amazon.device.iap.model.RequestId;
import java.util.Iterator;
import java.util.LinkedHashSet;
import java.util.Set;

public class d {
  private static String a = d.class.getSimpleName();
  private static String b = "sku";
  private static d c = new d();
  private e d;
  private Context e;
  private PurchasingListener f;

  private d() {
  }

//...
```

**Comment by ludovicroland** [comment]
I am closing this issue since my PR has been merged :)
