### ISSUE TITLE
Amazon ADM - FATAL EXCEPTION: IntentService[ADMMessageHandler]

### ISSUE THREAD

**Issue by gitton** [OneSignal/OneSignal-Android-SDK#154]
Getting following error on configuring Amazon ADM. Device : Amazon Fire HD 6 (4th Generation)  
```Java
FATAL EXCEPTION: IntentService[ADMMessageHandler]
java.lang.AbstractMethodError: abstract method "void com.amazon.device.messaging.ADMMessageHandlerBase.onRegistered(java.lang.String)"
      at com.amazon.device.messaging.ADMMessageHandlerBase.handleNewRegistrationID(ADMMessageHandlerBase.java:116)
                                                       at com.amazon.device.messaging.ADMMessageHandlerBase.handleRegistrationChange(ADMMessageHandlerBase.java:106)
                                                       at com.amazon.device.messaging.ADMMessageHandlerBase.onHandleIntent(ADMMessageHandlerBase.java:81)
                                                       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:135)
                                                       at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by gitton** [comment]
Proguard enabled 
-keep class com.onesignal.** { *; }  solved the issue.

**Comment by jkasten2** [comment]
@gitton Thanks for the details, can you try the following instead? This should allow the rest of the OneSignal SDK to be minified while still keeping the required OneSignal class.

```gradle
-keep public class * extends com.amazon.device.messaging.ADMMessageReceiver
-keep public class * extends com.amazon.device.messaging.ADMMessageHandlerBase
```

It is odd either are needed however as proguard is pretty good about keeping classes when they are used in the `AndroidManifest.xml`.
```xml
<service android:name="com.onesignal.ADMMessageHandler" android:exported="false" />
<receiver android:name="com.onesignal.ADMMessageHandler$Receiver"
          android:permission="com.amazon.device.messaging.permission.SEND" >
```

**Comment by jkasten2** [comment]
@gitton @vernazza If you want most of the OneSignal SDK to be minified by progaurd then the following is all you need.
```gradle
-keep public class com.onesignal.ADMMessageHandler {*;}
```

This will be added automatically in the 3.4.4 release.

**Comment by EmilAlipiev** [comment]
@jkasten2 below how my manifest looks like for google app, not amazon. If i want to minimize usage with proguard. should i do any special set up.
 
```
		<service android:name="com.onesignal.GcmIntentService" />
		<service android:name="com.onesignal.SyncService" android:stopWithTask="false" />
		<activity android:name="com.onesignal.PermissionsActivity" android:theme="@android:style/Theme.Translucent.NoTitleBar" />
		<activity android:name="com.google.android.gms.ads.AdActivity" android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize" android:theme="@android:style/Theme.Translucent" />
	
```

I have had proguard like below.  Does it make sense?
```

## Onesignal

-dontwarn com.onesignal.**
-keep class com.onesignal.** { *; } 
-keep class com.google.android.gms.common.api.GoogleApiClient {
    void connect();
    void disconnect();
}
-keep public interface android.app.OnActivityPausedListener {*;}
-keep class com.onesignal.ActivityLifecycleListenerCompat** {*;}
-keep class com.onesignal.OSSubscriptionState {
    void changed(com.onesignal.OSPermissionState);
}

-keep class com.onesignal.OSSubscriptionState {
    void changed(com.onesignal.OSPermissionState);
}

-keep class com.onesignal.OSPermissionChangedInternalObserver {
    void changed(com.onesignal.OSPermissionState);
}

-keep class com.onesignal.OSSubscriptionChangedInternalObserver {
    void changed(com.onesignal.OSSubscriptionState);
}

-keep class ** implements com.onesignal.OSPermissionObserver {
    void onOSPermissionChanged(com.onesignal.OSPermissionStateChanges);
}

-keep class ** implements com.onesignal.OSSubscriptionObserver {
    void onOSSubscriptionChanged(com.onesignal.OSSubscriptionStateChanges);
}

-keep class com.onesignal.shortcutbadger.impl.AdwHomeBadger { <init>(...); }
-keep class com.onesignal.shortcutbadger.impl.ApexHomeBadger { <init>(...); }
-keep class com.onesignal.shortcutbadger.impl.AsusHomeLauncher { <init>(...); }
-keep class com.onesignal.shortcutbadger.impl.DefaultBadger { <init>(...); }
-keep class com.onesignal.shortcutbadger.impl.EverythingMeHomeBadger { <init>(...); }
-keep class com.onesignal.shortcutbadger.impl.HuaweiHomeBadger { <init>(...); }
-keep class com.onesignal.shortcutbadger.impl.LGHomeBadger { <init>(...); }
-keep class com.onesignal.shortcutbadger.impl.NewHtcHomeBadger { <init>(...); }
-keep class com.onesignal.shortcutbadger.impl.NovaHomeBadger { <init>(...); }
-keep class com.onesignal.shortcutbadger.impl.OPPOHomeBader { <init>(...); }
-keep class com.onesignal.shortcutbadger.impl.SamsungHomeBadger { <init>(...); }
-keep class com.onesignal.shortcutbadger.impl.SonyHomeBadger { <init>(...); }
-keep class com.onesignal.shortcutbadger.impl.VivoHomeBadger { <init>(...); }
-keep class com.onesignal.shortcutbadger.impl.XiaomiHomeBadger { <init>(...); }
-keep class com.onesignal.shortcutbadger.impl.ZukHomeBadger { <init>(...); }
 
```
