### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.onesignal.OSOutcomeEventsController.sendSavedOutcomes()' on a null object reference

### ISSUE THREAD

**Issue by TaoGEe** [OneSignal/OneSignal-Android-SDK#1551]
**Description:**

hi, I found this crash from firebase crashlytics, i can not reproduct it.please have a look

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.onesignal.OSOutcomeEventsController.sendSavedOutcomes()' on a null object reference
       at com.onesignal.OneSignal.init(OneSignal.java:837)
       at com.onesignal.OneSignal.setAppId(OneSignal.java:692)
       at com.onesignal.OneSignal.reassignDelayedInitParams(OneSignal.java:1136)
       at com.onesignal.OneSignal.onRemoteParamSet(OneSignal.java:844)
       at com.onesignal.OneSignal$6.complete(OneSignal.java:1077)
       at com.onesignal.OneSignalRemoteParams.processJson(OneSignalRemoteParams.java:206)
       at com.onesignal.OneSignalRemoteParams.access$100(OneSignalRemoteParams.java:12)
       at com.onesignal.OneSignalRemoteParams$1.onSuccess(OneSignalRemoteParams.java:151)
       at com.onesignal.OneSignalRestClient$5.run(OneSignalRestClient.java:283)
       at java.lang.Thread.run(Thread.java:764)

**Environment**

OneSignal:4.6.3

<img width="1457" alt="image" src="https://user-images.githubusercontent.com/11844963/158993612-46e2251a-814c-4bc3-a203-53710bd9bb85.png">
<img width="390" alt="image" src="https://user-images.githubusercontent.com/11844963/158993652-33690c4f-e22e-4546-ab3f-605bc3e0ce8b.png">

**Comment by nan-li** [comment]
Hi @TaoGEe,

Thank you for reporting. This issue has been reported by others and tracked here: #1514. 

Can you share some information? 
Did you start seeing this crash after updating the OneSignal-Android-SDK? If this started after updating, what version were you on before?

**Comment by TaoGEe** [comment]
I think the cause of this issue is put the onesignal initialization code into other thread.
<img width="926" alt="image" src="https://user-images.githubusercontent.com/11844963/159202317-765a6e4f-2642-4c59-9c03-69983fa75146.png">

**Comment by nan-li** [comment]
Hi @TaoGEe,

A fix for this crash has been released in [version 4.7.1](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/4.7.1).

I will close this issue for now, please upgrade and reach out if you are still experiencing crashes.
