### ISSUE TITLE
java.lang.IllegalStateException: The file system on the device is in a bad state

### ISSUE THREAD

**Issue by TaoGEe** [OneSignal/OneSignal-Android-SDK#1552]
One user crashed 319 times. 

I found a piece of information about this crash,
https://stackoverflow.com/questions/63434025/the-file-system-on-the-device-is-in-a-bad-state-workmanager-cannot-access-the-a
<img width="1474" alt="image" src="https://user-images.githubusercontent.com/11844963/159205611-a3184433-1969-4fa6-ade8-aa140e17d707.png">
```java
Fatal Exception: java.lang.IllegalStateException: The file system on the device is in a bad state. WorkManager cannot access the app's internal data store.
       at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:128)
       at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)

Caused by android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file (code 14 SQLITE_CANTOPEN): , while compiling: PRAGMA journal_mode
       at android.database.sqlite.SQLiteConnection.nativePrepareStatement(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1045)
       at android.database.sqlite.SQLiteConnection.executeForString(SQLiteConnection.java:788)
       at android.database.sqlite.SQLiteConnection.setJournalMode(SQLiteConnection.java:405)
       at android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:335)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:258)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:205)
       at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:505)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:206)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:198)
       at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:918)
       at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:898)
       at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:762)
       at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:751)
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:373)
       at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:316)
       at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:145)
       at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:106)
       at androidx.room.RoomDatabase.inTransaction(RoomDatabase.java:476)
       at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java:281)
       at androidx.work.impl.model.SystemIdInfoDao_Impl.getWorkSpecIds(SystemIdInfoDao_Impl.java:120)
       at androidx.work.impl.background.systemjob.SystemJobScheduler.reconcileJobs(SystemJobScheduler.java:298)
       at androidx.work.impl.utils.ForceStopRunnable.cleanUp(ForceStopRunnable.java:249)
       at androidx.work.impl.utils.ForceStopRunnable.forceStopRunnable(ForceStopRunnable.java:215)
       at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:110)
       at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
```

<img width="1242" alt="image" src="https://user-images.githubusercontent.com/11844963/159205658-7aaf8533-2e22-4000-aafd-adbba234801d.png">

**Comment by jkasten2** [comment]
@TaoGEe Thanks for reporting, I have a few follow up questions: 
1. Is this crash only happening on the Redmi Note 10S?
2. Are you able to reproduce this crash on your device?
3. What version of the OneSignal SDK are you using?
   - Please try the latest 4.7.4 and let us know if you still see the issue.
5. What version of the `androidx.work:work-runtime` are you using in your app?
  - You can run `./gradlew app:dependencies` to get this.
  - Recommend upgrading to 2.7.1 if possible by [adding it directly to your project](https://developer.android.com/jetpack/androidx/releases/work)

**Comment by jennantilla** [comment]
Closing this issue due to no response. Please @ mention me if you still have questions or concerns.

Also noting that we have an updated major release available for our Android SDK with many improvements and enhancements! Please refer to the [migration guide](https://github.com/OneSignal/OneSignal-Android-SDK/blob/user-model/main/MIGRATION_GUIDE.md) for more information on upgrading.

Thanks!

**Comment by richanshah** [comment]
@TaoGEe any update on this?

**Comment by alihamza1729** [comment]
any update?
