### ISSUE TITLE
java.lang.NullPointerException: Attempt to write to field 'int android.view.ViewGroup$LayoutParams.height' on a null object reference

### ISSUE THREAD

**Issue by EugeneSHApoval** [OneSignal/OneSignal-Android-SDK#1554]
**Description:**

Hello there.
Receiving from time to time such crash to crashlytics but currently unable to reproduce myself.

Fatal Exception: java.lang.RuntimeException: Unable to resume activity {com.folioltd/com.yourid.app.ui.applock.PinLockActivity}: java.lang.NullPointerException: Attempt to write to field 'int android.view.ViewGroup$LayoutParams.height' on a null object reference
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5229)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5268)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2440)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8641)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)

Caused by java.lang.NullPointerException: Attempt to write to field 'int android.view.ViewGroup$LayoutParams.height' on a null object reference
       at com.onesignal.InAppMessageView$1.run(InAppMessageView.java:135)
       at com.onesignal.OSUtils.runOnMainUIThread(OSUtils.java:472)
       at com.onesignal.InAppMessageView.updateHeight(InAppMessageView.java:124)
       at com.onesignal.WebViewManager.showMessageView(WebViewManager.java:349)
       at com.onesignal.WebViewManager.available(WebViewManager.java:316)
       at com.onesignal.ActivityLifecycleHandler.setCurActivity(ActivityLifecycleHandler.java:230)
       at com.onesignal.ActivityLifecycleHandler.onActivityResumed(ActivityLifecycleHandler.java:86)
       at com.onesignal.ActivityLifecycleListener.onActivityResumed(ActivityLifecycleListener.java:91)
       at android.app.Application.dispatchActivityResumed(Application.java:435)
       at android.app.Activity.dispatchActivityResumed(Activity.java:1437)
       at android.app.Activity.onResume(Activity.java:1994)
       at androidx.fragment.app.FragmentActivity.onResume(FragmentActivity.java:434)
       at moxy.MvpAppCompatActivity.onResume(MvpAppCompatActivity.java:39)
       at com.yourid.core.di.BaseCoreActivity.onResume(BaseCoreActivity.kt:123)
       at com.yourid.app.ui.applock.BaseLockActivity.onResume(BaseLockActivity.kt:51)
       at com.yourid.app.ui.applock.PinLockActivity.onResume(PinLockActivity.kt:54)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1476)
       at android.app.Activity.performResume(Activity.java:8433)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5202)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5268)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2440)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8641)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)

**Environment**

OneSignal:4.4.2

![Crashlytics](https://user-images.githubusercontent.com/102509351/160356157-2605a401-a23b-4231-bc4e-70ae3e97b843.PNG)

**Comment by nan-li** [comment]
Hi @EugeneSHApoval,

Thank you for reporting this issue. I see you are on version `4.4.2` and this crash has a speculative fix in [release 4.6.6](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/4.6.6). 

Please update your OneSignal-Android-SDK and reach out if this crash persists.
