### ISSUE TITLE
Lots of crash in JSONUtils.java line 66, Only samsung devices with Android 7.0

### ISSUE THREAD

**Issue by shubhamvashisht** [OneSignal/OneSignal-Android-SDK#1558]
**Description:**
Seeing a lots of crashes with following logs:

```
Fatal Exception: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Number
       at com.onesignal.JSONUtils.generateJsonDiff(JSONUtils.java:66)
       at com.onesignal.UserState.generateJsonDiffFromIntoSyncValued(UserState.java:395)
       at com.onesignal.UserStateSynchronizer.updateDeviceInfo(UserStateSynchronizer.java:509)
       at com.onesignal.OneSignalStateSynchronizer.updateDeviceInfo(OneSignalStateSynchronizer.java:222)
       at com.onesignal.OneSignal.registerUserTask(OneSignal.java:1474)
       at com.onesignal.OneSignal.access$1500(OneSignal.java:84)
       at com.onesignal.OneSignal$9.run(OneSignal.java:1441)
       at java.lang.Thread.run(Thread.java:762)
```

**Environment**
onesignal version = 4.6.3
onesignal Plugin version = 0.13.4

**Steps to Reproduce Issue:**
1. App crashes on launch

**Comment by nan-li** [comment]
Hi @shubhamvashisht,

Thank you for reporting this crash, and for the details about device information. 

It seems you are able to reproduce this? 
If so, can you share your log around the time the app is launching? 
Make sure to enable VERBOSE logging with `OneSignal.setLogLevel` (https://documentation.onesignal.com/docs/sdk-reference#setloglevel-method).

Your crash is the same as the one reported in https://github.com/OneSignal/OneSignal-Android-SDK/issues/1553, so please follow up there. I will close this one.
