### ISSUE TITLE
NullPointerException: Attempt to invoke interface method 'void com.onesignal.PushRegistrator.registerForPush

### ISSUE THREAD

**Issue by azartx** [OneSignal/OneSignal-Android-SDK#1564]
**Description:**

Hi! I got the problem when i setup android onesignal sdk for android native (kotlin) app.

I'v got crash when i start the app:
`
E/AndroidRuntime: FATAL EXCEPTION: OS_REST_SUCCESS_CALLBACK
    Process: ***, PID: 30232
    java.lang.NullPointerException: Attempt to invoke interface method 'void com.onesignal.PushRegistrator.registerForPush(android.content.Context, java.lang.String, com.onesignal.PushRegistrator$RegisteredHandler)' on a null object reference
        at com.onesignal.OneSignal.registerForPushToken(OneSignal.java:1057)
        at com.onesignal.OneSignal.startRegistrationOrOnSession(OneSignal.java:1007)
        at com.onesignal.OneSignal.doSessionInit(OneSignal.java:990)
        at com.onesignal.OneSignal.init(OneSignal.java:844)
        at com.onesignal.OneSignal.setAppId(OneSignal.java:713)
        at com.onesignal.OneSignal.reassignDelayedInitParams(OneSignal.java:1158)
        at com.onesignal.OneSignal.onRemoteParamSet(OneSignal.java:865)
        at com.onesignal.OneSignal$6.complete(OneSignal.java:1099)
        at com.onesignal.OneSignalRemoteParams.processJson(OneSignalRemoteParams.java:206)
        at com.onesignal.OneSignalRemoteParams.access$100(OneSignalRemoteParams.java:12)
        at com.onesignal.OneSignalRemoteParams$1.onSuccess(OneSignalRemoteParams.java:151)
        at com.onesignal.OneSignalRestClient$5.run(OneSignalRestClient.java:292)
        at java.lang.Thread.run(Thread.java:920)
`
My project build.gradle
![image](https://user-images.githubusercontent.com/66694997/163191984-ddc9996b-2298-44a8-9852-ce5baafa8691.png)

My  app build.gradle
![image](https://user-images.githubusercontent.com/66694997/163192074-1f65921f-c00b-40d1-b036-1dc87eb1bf48.png)
![image](https://user-images.githubusercontent.com/66694997/163192119-02d3ed6f-6ab5-407f-add1-3f388ec8b254.png)

firebase sdk used only for remote configs logic.

My Application
![image](https://user-images.githubusercontent.com/66694997/163192496-baa24a46-d71d-4717-ab63-22c9f5db2b45.png)

**Environment**
Android SDK min 23 max 31
tests on android 12, android 9

**Steps to Reproduce Issue:**

  1. Add the OneSignal SDK to your project
  2. Place your App ID in the application's gradle file
  3. Launch the app

This is used for HMS pushes.

**Comment by alexandreerick** [comment]
Same issue here with react native.

**Comment by jennantilla** [comment]
Hello everyone! Apologies that this issue was missed. Since it has been quite some time since the original report, I'm going to close this out as stale. 

If any of you are still having this issue, please @ mention me here with the following details:

- Current SDK version you are using
- Whether is this only happening on HMS implementations or also for GMS
- Full [logs](https://documentation.onesignal.com/docs/capturing-a-debug-log) capturing the issue

Thank you so much!
