### ISSUE TITLE
IAP error - ClassCastException: Integer cannot be cast to Bundle

### ISSUE THREAD

**Issue by jkasten2** [OneSignal/OneSignal-Android-SDK#160]
Sometimes the following error will be logged to the logcat.

```Java
01-08 11:10:26.675: W/OneSignal(2499): Failed to track IAP purchases
01-08 11:10:26.675: W/OneSignal(2499): java.lang.ClassCastException: java.lang.Integer cannot be cast to android.os.Bundle
01-08 11:10:26.675: W/OneSignal(2499): at com.onesignal.TrackGooglePurchase.sendPurchases(TrackGooglePurchase.java:198)
01-08 11:10:26.675: W/OneSignal(2499): at com.onesignal.TrackGooglePurchase.access$1000(TrackGooglePurchase.java:53)
01-08 11:10:26.675: W/OneSignal(2499): at com.onesignal.TrackGooglePurchase$2.run(TrackGooglePurchase.java:172)
01-08 11:10:26.675: W/OneSignal(2499): at java.lang.Thread.run(Thread.java:818)
```

**Comment by jkasten2** [comment]
Fixed in commit 82900a23124cc6d76a52f1f8b044f286b69a855d
