### ISSUE TITLE
'java.lang.String com.onesignal.language.LanguageContext.getLanguage()' on a null object reference

### ISSUE THREAD

**Issue by 9468lgy** [OneSignal/OneSignal-Android-SDK#1605]
**Description:**
We integrated version 4.7.3, and when we went live OneSignal had a NullPointerException, which had not happened in previous SDK versions

**Environment**

implementation 'com.onesignal:OneSignal:4.7.3'

**Anything else:**

```java
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.onesignal.language.LanguageContext.getLanguage()' on a null object reference
       at com.onesignal.OSInAppMessageController.variantIdForMessage(OSInAppMessageController.java:277)
       at com.onesignal.OSInAppMessageController.displayMessage(OSInAppMessageController.java:807)
       at com.onesignal.OSInAppMessageController.attemptToShowInAppMessage(OSInAppMessageController.java:649)
       at com.onesignal.OSInAppMessageController.queueMessageForDisplay(OSInAppMessageController.java:633)
       at com.onesignal.OSInAppMessageController.evaluateInAppMessages(OSInAppMessageController.java:270)
       at com.onesignal.OSInAppMessageController.processInAppMessageJson(OSInAppMessageController.java:247)
       at com.onesignal.OSInAppMessageController.access$500(OSInAppMessageController.java:27)
       at com.onesignal.OSInAppMessageController$3.run(OSInAppMessageController.java:218)
       at com.onesignal.OSInAppMessageController.executeRedisplayIAMDataDependantTask(OSInAppMessageController.java:168)
       at com.onesignal.OSInAppMessageController.receivedInAppMessageJson(OSInAppMessageController.java:213)
       at com.onesignal.UserStateSynchronizer$4.onSuccess(UserStateSynchronizer.java:444)
       at com.onesignal.OneSignalRestClient$5.run(OneSignalRestClient.java:279)
       at java.lang.Thread.run(Thread.java:920)
```

**Comment by 9468lgy** [comment]
Well, I will try to modify it to 4.7.1 and observe it later when it goes online.
