### ISSUE TITLE
Unknown error getting FCM Token

### ISSUE THREAD

**Issue by FoloosiApps** [OneSignal/OneSignal-Android-SDK#1609]
**Description:**

E/OneSignal: Unknown error getting FCM Token
    java.util.concurrent.ExecutionException: java.io.IOException: SERVICE_NOT_AVAILABLE
        at com.google.android.gms.tasks.Tasks.zza(com.google.android.gms:play-services-tasks@@17.2.0:69)
        at com.google.android.gms.tasks.Tasks.await(com.google.android.gms:play-services-tasks@@17.2.0:23)
        at com.onesignal.PushRegistratorFCM.getTokenWithClassFirebaseMessaging(PushRegistratorFCM.java:161)
        at com.onesignal.PushRegistratorFCM.getToken(PushRegistratorFCM.java:110)
        at com.onesignal.PushRegistratorAbstractGoogle.attemptRegistration(PushRegistratorAbstractGoogle.java:97)
        at com.onesignal.PushRegistratorAbstractGoogle.access$100(PushRegistratorAbstractGoogle.java:37)
        at com.onesignal.PushRegistratorAbstractGoogle$1.run(PushRegistratorAbstractGoogle.java:84)
        at java.lang.Thread.run(Thread.java:929)
     Caused by: java.io.IOException: SERVICE_NOT_AVAILABLE
        at com.google.android.gms.cloudmessaging.Rpc.zza(com.google.android.gms:play-services-cloud-messaging@@16.0.0:157)
        at com.google.android.gms.cloudmessaging.zzt.then(Unknown Source:0)
        at com.google.android.gms.tasks.zze.run(com.google.android.gms:play-services-tasks@@17.2.0:5)
        at com.google.android.gms.cloudmessaging.zzz.execute(Unknown Source:0)
        at com.google.android.gms.tasks.zzc.zza(com.google.android.gms:play-services-tasks@@17.2.0:6)
        at com.google.android.gms.tasks.zzq.zza(com.google.android.gms:play-services-tasks@@17.2.0:19)
        at com.google.android.gms.tasks.zzu.zza(com.google.android.gms:play-services-tasks@@17.2.0:120)
        at com.google.android.gms.tasks.TaskCompletionSource.setException(com.google.android.gms:play-services-tasks@@17.2.0:11)
        at com.google.android.gms.cloudmessaging.zzq.zza(com.google.android.gms:play-services-cloud-messaging@@16.0.0:13)
        at com.google.android.gms.cloudmessaging.zzf.zza(com.google.android.gms:play-services-cloud-messaging@@16.0.0:67)
        at com.google.android.gms.cloudmessaging.zzf.zzc(com.google.android.gms:play-services-cloud-messaging@@16.0.0:88)
        at com.google.android.gms.cloudmessaging.zzh.run(Unknown Source:2)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.google.android.gms.common.util.concurrent.zza.run(com.google.android.gms:play-services-basement@@18.0.0:2)
        at java.lang.Thread.run(Thread.java:929) 
     Caused by: com.google.android.gms.cloudmessaging.zzp: Timed out while binding
        at com.google.android.gms.cloudmessaging.zzf.zza(com.google.android.gms:play-services-cloud-messaging@@16.0.0:65)
        at com.google.android.gms.cloudmessaging.zzf.zzc(com.google.android.gms:play-services-cloud-messaging@@16.0.0:88) 
        at com.google.android.gms.cloudmessaging.zzh.run(Unknown Source:2) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at com.google.android.gms.common.util.concurrent.zza.run(com.google.android.gms:play-services-basement@@18.0.0:2) 
        at java.lang.Thread.run(Thread.java:929) 
**Environment**

**Steps to Reproduce Issue:**

1. (your steps here)
2.
3.

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by jkasten2** [comment]
@FoloosiApps Thanks for details. This is a duplicate of https://github.com/OneSignal/OneSignal-Android-SDK/issues/620

The `SERVICE_NOT_AVAILABL`E is thrown from the Firebase / Google play services library. This happens when the "Google Play services" app does not response or runs into some error when getting a push token. There isn't anything the app developer can do, getting this errors means the device will have being other issues with Google services
https://stackoverflow.com/a/17189160/1244574
