### ISSUE TITLE
[Bug]:java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.onesignal.influence.domain.OSInfluenceType.isDirect()' on a null object reference

### ISSUE THREAD

**Issue by TaoGEe** [OneSignal/OneSignal-Android-SDK#1613]
### What happened?

I saw the crash from firebase.

![image](https://user-images.githubusercontent.com/11844963/179445275-5814446b-0cee-4989-91cb-342f2df44aa9.png)

```java
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.diamondlife.slots.vegas.free/com.onesignal.NotificationOpenedReceiver}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.onesignal.influence.domain.OSInfluenceType.isDirect()' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3616)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3780)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2251)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:233)
       at android.app.ActivityThread.main(ActivityThread.java:8063)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)



Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.onesignal.influence.domain.OSInfluenceType.isDirect()' on a null object reference
       at com.onesignal.OSSessionManager.attemptSessionUpgrade(OSSessionManager.java:160)
       at com.onesignal.OSSessionManager.onDirectInfluenceFromNotificationOpen(OSSessionManager.java:111)
       at com.onesignal.OneSignal.applicationOpenedByNotification(OneSignal.java:2461)
       at com.onesignal.OneSignal.handleNotificationOpen(OneSignal.java:2408)
       at com.onesignal.NotificationOpenedProcessor.processIntent(NotificationOpenedProcessor.java:116)
       at com.onesignal.NotificationOpenedProcessor.processFromContext(NotificationOpenedProcessor.java:64)
       at com.onesignal.NotificationOpenedReceiverBase.onCreate(NotificationOpenedReceiverBase.kt:36)
       at android.app.Activity.performCreate(Activity.java:8006)
       at android.app.Activity.performCreate(Activity.java:7990)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3589)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3780)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2251)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:233)
       at android.app.ActivityThread.main(ActivityThread.java:8063)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
```

### Steps to reproduce?

```Markdown
Cannot reproduce
```

### What did you expect to happen?

no crash

### OneSignal Android SDK version

4.7.3

### Android version

12

### Specific Android models

```Markdown
Galaxy S21 FE 5G
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Hi @TaoGEe,
Thank you for reporting and I apologize for the delay. https://github.com/OneSignal/OneSignal-Android-SDK/blob/4.7.3/OneSignalSDK/onesignal/src/main/java/com/onesignal/influence/data/OSChannelTracker.kt#L14 `OSInfluenceType` could be `null` in some cases if it is not set or initialized. 

We will investigate when it can be `null`.

**Comment by zainriaz** [comment]
same crash with

`implementation 'com.onesignal:OneSignal:4.8.1'`

**Comment by Office-Murtaza** [comment]
crashes 

implementation 'com.onesignal:OneSignal:4.8.1'

**Comment by nan-li** [comment]
Hi all, apologies this issue has gone stale; the team is no longer actively supporting and patching the v4 major version of this SDK.

I recommend to upgrade to v5 of our SDK. Please let us know if we can help you with the transition.
