### ISSUE TITLE
[Bug]: Unable to start activity ComponentInfo{com.xx.xxx/com.onesignal.PermissionsActivity}

### ISSUE THREAD

**Issue by muraliganesan88** [OneSignal/OneSignal-Android-SDK#1632]
### What happened?

I can see a crash in Crashlytics Unable to start activity ComponentInfo{com.xx.xxx/com.onesignal.PermissionsActivity}

AndroidSupportV4Compat.java line 87
com.onesignal.AndroidSupportV4Compat$ActivityCompatApi23.shouldShowRequestPermissionRationale

### Steps to reproduce?

```Markdown
1. Install OneSignal 4.8.2
2. Run the app on Android 11, Google Pixel 4a (as I can see in Crashlytics).
```

### What did you expect to happen?

Expected not getting crash

### OneSignal Android SDK version

4.8.2

### Android version

11

### Specific Android models

Google Pixel 4a

### Relevant log output

      Fatal Exception: java.lang.RuntimeException: Unable to start activity 
      ComponentInfo{com.pdl.stsh/com.onesignal.PermissionsActivity}: java.lang.NullPointerException: Attempt to invoke 
      virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3431)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7664)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
       
       Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
       at android.os.Parcel.createExceptionOrNull(Parcel.java:2379)
       at android.os.Parcel.createException(Parcel.java:2357)
       at android.os.Parcel.readException(Parcel.java:2340)
       at android.os.Parcel.readException(Parcel.java:2282)
       at android.permission.IPermissionManager$Stub$Proxy.shouldShowRequestPermissionRationale(IPermissionManager.java:1616)
       at android.app.ApplicationPackageManager.shouldShowRequestPermissionRationale(ApplicationPackageManager.java:886)
       at android.app.Activity.shouldShowRequestPermissionRationale(Activity.java:5256)
       at androidx.core.app.ActivityCompat$Api23Impl.shouldShowRequestPermissionRationale(ActivityCompat.java:855)
       at androidx.core.app.ActivityCompat.shouldShowRequestPermissionRationale(ActivityCompat.java:557)
       at com.onesignal.AndroidSupportV4Compat$ActivityCompatApi23.shouldShowRequestPermissionRationale(AndroidSupportV4Compat.java:87)
       at com.onesignal.AndroidSupportV4Compat$ActivityCompat.shouldShowRequestPermissionRationale(AndroidSupportV4Compat.java:74)
       at com.onesignal.PermissionsActivity.requestPermission(PermissionsActivity.java:90)
       at com.onesignal.PermissionsActivity.onCreate(PermissionsActivity.java:68)
       at android.app.Activity.performCreate(Activity.java:7994)
       at android.app.Activity.performCreate(Activity.java:7978)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7664)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
       
       Caused by android.os.RemoteException: Remote stack trace:
	at com.android.server.pm.permission.PermissionManagerService.shouldShowRequestPermissionRationale(PermissionManagerService.java:2094)
	at android.permission.IPermissionManager$Stub.onTransact(IPermissionManager.java:792)
	at android.os.Binder.execTransactInternal(Binder.java:1154)
	at android.os.Binder.execTransact(Binder.java:1123)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment]
@muraliganesan88 Hello are you able to reproduce this crash and how many are you seeing? It looks like a crash in Android's permission library. Any help reproducing is much appreciated!

**Comment by muraliganesan88** [comment]
> com.onesignal.PermissionsActivity

its seems like issue in com.onesignal.PermissionsActivity i'm not able to reproduce it. we are getting error log output from crashlytics

**Comment by deputat007** [comment]
We are also getting this error log output from crashlytics on LGE (Nexus 5X)

**Comment by qsdigor** [comment]
I got the same error in my app.

**Comment by deputat007** [comment]
### What happened?
I can see a crash in Crashlytics Unable to start activity ComponentInfo{com.xx.xxx/com.onesignal.PermissionsActivity}
 java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.os.BaseBundle.getString(java.lang.String)' on a null object reference
### Steps to reproduce?
1. Install OneSignal 4.8.4
2. Run the app on Android 8.1.0, Nexus 5X (as I can see in Crashlytics).
### What did you expect to happen?
Expected not getting crash
### OneSignal Android SDK version
4.8.4
### Android version
8.1.0
### Specific Android models
Nexus 5X
### Relevant log output
```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xx.xxx/com.onesignal.PermissionsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.os.BaseBundle.getString(java.lang.String)' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```
```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.os.BaseBundle.getString(java.lang.String)' on a null object reference
       at com.onesignal.PermissionsActivity.reregisterCallbackHandlers(PermissionsActivity.java:109)
       at com.onesignal.PermissionsActivity.handleBundleParams(PermissionsActivity.java:100)
       at com.onesignal.PermissionsActivity.onCreate(PermissionsActivity.java:82)
       at android.app.Activity.performCreate(Activity.java:7009)
       at android.app.Activity.performCreate(Activity.java:7000)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```
### Code of Conduct
- [ ]  I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hello everyone! Apologies that this issue has gone stale. Much of our work in the last few quarters have been on a new major release where many improvements and enhancements are introduced. We will continue to investigate 4.x.x bugs, though we encourage you to update to our [latest release](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.1.6) as that will be the most-supported release going forward. Please see our [migration guide](https://github.com/OneSignal/OneSignal-Android-SDK/blob/main/MIGRATION_GUIDE.md) for full details on upgrading.

If this crash is still a current concern, please provide updated reproduction steps and we'll be happy to investigate further. Thanks!
