### ISSUE TITLE
[Bug]: anr when initWithContext

### ISSUE THREAD

**Issue by TaoGEe** [OneSignal/OneSignal-Android-SDK#1653]
### What happened?

a lot of anr when initWithContext

### Steps to reproduce?

```Markdown
can not reproduce
```

### What did you expect to happen?

no anr
can i put initWithContext to other thread or  delay init in main thread?

### OneSignal Android SDK version

4.6.3

### Android version

11

### Specific Android models

```Markdown
Galaxy Tab A (8.0", 2019)
```

### Relevant log output

```Shell
main (runnable): tid=1 systid=29603 
       at kotlin.text.StringsKt__StringsJVMKt.equals(StringsJVM.kt)
       at com.onesignal.influence.domain.OSInfluenceType$Companion.fromString(OSInfluenceType.kt:23)
       at com.onesignal.influence.data.OSInfluenceDataRepository.getIamCachedInfluenceType(OSInfluenceDataRepository.kt:62)
       at com.onesignal.influence.data.OSInAppMessageTracker.initInfluencedTypeFromCache(OSInAppMessageTracker.kt:60)
       at com.onesignal.influence.data.OSTrackerFactory.initFromCache(OSTrackerFactory.kt:46)
       at com.onesignal.OSSessionManager.initSessionFromCache(OSSessionManager.java:46)
       at com.onesignal.OneSignal.setupContextListeners(OneSignal.java:873)
       at com.onesignal.OneSignal.initWithContext(OneSignal.java:714)
       at org.cocos2dx.bole.BoleApplication.initOneSignal(BoleApplication.java:103)
       at org.cocos2dx.bole.BoleApplication.onCreate(BoleApplication.java:94)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
       at android.app.ActivityThread.handleMakeApplication(ActivityThread.java:7545)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7484)
       at android.app.ActivityThread.access$1400(ActivityThread.java:301)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2156)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8550)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)



main (runnable): tid=1 systid=7298 
       at com.onesignal.OneSignal.setLogLevel(OneSignal.java:1189)
       at org.cocos2dx.bole.BoleApplication.initOneSignal(BoleApplication.java:100)
       at org.cocos2dx.bole.BoleApplication.onCreate(BoleApplication.java:94)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6754)
       at android.app.ActivityThread.access$1400(ActivityThread.java:244)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1952)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:230)
       at android.app.ActivityThread.main(ActivityThread.java:7700)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)

main (waiting): tid=1 systid=26614 
       at java.lang.Object.wait(Native method)
       at java.lang.Object.wait(Object.java:442)
       at java.lang.Object.wait(Object.java:568)
       at android.app.SharedPreferencesImpl.awaitLoadedLocked(SharedPreferencesImpl.java:279)
       at android.app.SharedPreferencesImpl.getString(SharedPreferencesImpl.java:301)
       at com.onesignal.OneSignalPrefs.get(OneSignalPrefs.java:304)
       at com.onesignal.OneSignalPrefs.getString(OneSignalPrefs.java:265)
       at com.onesignal.OSSharedPreferencesWrapper.getString(OSSharedPreferencesWrapper.java:22)
       at com.onesignal.language.LanguageContext.<init>(LanguageContext.java:23)
       at com.onesignal.OneSignal.setupContextListeners(OneSignal.java:856)
       at com.onesignal.OneSignal.initWithContext(OneSignal.java:714)
       at org.cocos2dx.bole.BoleApplication.initOneSignal(BoleApplication.java:103)
       at org.cocos2dx.bole.BoleApplication.onCreate(BoleApplication.java:94)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1193)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6921)
       at android.app.ActivityThread.access$1400(ActivityThread.java:244)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1931)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7888)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)


main (runnable): tid=1 systid=13257 
#00 pc 0x5376cc libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, BacktraceMap*, char const*, art::ArtMethod*, void*, bool) + 128)
#01 pc 0x6f0e24 libart.so (art::Thread::DumpStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool, BacktraceMap*, bool) const + 236)
#02 pc 0x6fe6b0 libart.so (art::DumpCheckpoint::Run(art::Thread*) + 208)
#03 pc 0x402858 libart.so (art::Thread::RunCheckpointFunction() + 140)
#04 pc 0x397c58 libart.so (art::ClassLinker::LoadClass(art::Thread*, art::DexFile const&, art::dex::ClassDef const&, art::Handle<art::mirror::Class>) + 4744)
#05 pc 0x391074 libart.so (art::ClassLinker::DefineClass(art::Thread*, char const*, unsigned long, art::Handle<art::mirror::ClassLoader>, art::DexFile const&, art::dex::ClassDef const&) + 1688)
#06 pc 0x38e720 libart.so (art::ClassLinker::FindClassInBaseDexClassLoader(art::ScopedObjectAccessAlreadyRunnable&, art::Thread*, char const*, unsigned long, art::Handle<art::mirror::ClassLoader>, art::ObjPtr<art::mirror::Class>*) + 1036)
#07 pc 0x38a68c libart.so (art::ClassLinker::FindClass(art::Thread*, char const*, art::Handle<art::mirror::ClassLoader>) + 1032)
#08 pc 0x60344c libart.so (art::Class_classForName(_JNIEnv*, _jclass*, _jstring*, unsigned char, _jobject*) (.__uniq.181829539739573773940154555818377431209) + 276)
#09 pc 0x440554 libart.so (art_quick_generic_jni_trampoline + 148)
#10 pc 0x212462c memfd:jit-zygote-cache (java.lang.Class.forName + 108)
       at java.lang.Class.classForName(Native method)
       at java.lang.Class.forName(Class.java:454)
       at java.lang.Class.forName(Class.java:379)
       at com.onesignal.OSNotificationController.setupNotificationServiceExtension(OSNotificationController.java:190)
       at com.onesignal.OneSignal.init(OneSignal.java:774)
       at com.onesignal.OneSignal.setAppId(OneSignal.java:692)
       at com.onesignal.OneSignal.initWithContext(OneSignal.java:724)
       at org.cocos2dx.bole.BoleApplication.initOneSignal(BoleApplication.java:103)
       at org.cocos2dx.bole.BoleApplication.onCreate(BoleApplication.java:94)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6764)
       at android.app.ActivityThread.access$1600(ActivityThread.java:253)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2090)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7880)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:568)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hi @TaoGEe - just to clarify, are you saying that you get an ANR when initializing OneSignal?

Can you please make sure you are testing on the [latest version](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/4.8.2) of our SDK?

If still having issues, the best way to dig into these ANR issues is to check the full stacktrace of all threads. Starting at the top of each stacktrace and working down, it will help guide you on which event occurred last to trigger the ANR.

More about ANR troubleshooting [here](https://documentation.onesignal.com/docs/troubleshooting-android#anr-troubleshooting).

We do have a [method](https://documentation.onesignal.com/docs/sdk-reference#setrequiresuserprivacyconsent-method) to delay OneSignal initialization, usually for privacy consent purposes. Is that what you're looking for?

Thanks for the additional details!

**Comment by deputat007** [comment]
### What happened?
ANR triggered by slow operations in main thread at com.onesignal.OneSignal.initWithContext(OneSignal.java:759)
### Steps to reproduce?

1. Install OneSignal 4.8.4
2. Run the app on Android 11, Xiaomi Mi A3 (as I can see in Crashlytics).
### What did you expect to happen?
no ANR
### OneSignal Android SDK version
4.8.4
### Android version
11
### Specific Android models
Xiaomi Mi A3
### Relevant log output
```
main (runnable):tid=1 systid=4767 
       at com.onesignal.OneSignalDbHelper.<clinit>(OneSignalDbHelper.java:99)
       at com.onesignal.OneSignal.getDBHelperInstance(OneSignal.java:3314)
       at com.onesignal.OneSignal.setupContextListeners(OneSignal.java:907)
       at com.onesignal.OneSignal.initWithContext(OneSignal.java:759)
       at com.xxx.xxx.core.analytics.impl.onesignal.OneSignalInitializer.create(OneSignalInitializer.kt:21)
       at com.xxx.xxx.core.analytics.impl.onesignal.OneSignalInitializer.create(OneSignalInitializer.kt:12)
       at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:180)
       at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:238)
       at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:206)
       at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:45)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:2388)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:2358)
       at android.app.ActivityThread.installProvider(ActivityThread.java:7280)
       at android.app.ActivityThread.installContentProviders(ActivityThread.java:6821)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6716)
       at android.app.ActivityThread.access$1300(ActivityThread.java:238)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1914)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7698)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
```
### Code of Conduct
- [ ]  I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hello! We have recently updated to a new [major release](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.0.0) of our Android SDK that reworks a large portion of our code.

Are you able to update to SDK version 5.0.0 and open a new issue if you are still having this problem on the latest SDK?

Thanks!
