### ISSUE TITLE
[Bug]: Package manager has died

### ISSUE THREAD

**Issue by CharlieZheng** [OneSignal/OneSignal-Android-SDK#1669]
### What happened?

```
Fatal Exception: java.lang.RuntimeException: Package manager has died
       at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:164)
       at com.onesignal.OSUtils.packageInstalledAndEnabled(OSUtils.java:272)
       at com.onesignal.OSUtils.isGMSInstalledAndEnabled(OSUtils.java:284)
       at com.onesignal.OSUtils.supportsGooglePush(OSUtils.java:326)
       at com.onesignal.OSUtils.getDeviceType(OSUtils.java:345)
       at com.onesignal.OSUtils.isAndroidDeviceType(OSUtils.java:367)
       at com.onesignal.LocationController.isGooglePlayServicesAvailable(LocationController.java:337)
       at com.onesignal.LocationController.fireFailedComplete(LocationController.java:349)
       at com.onesignal.GMSLocationController$1.run(GMSLocationController.java:88)
       at java.lang.Thread.run(Thread.java:818)
```

### Steps to reproduce?

```Markdown
unable to reproduce
```

### What did you expect to happen?

bug fix

### OneSignal Android SDK version

Release 4.6.3

### Android version

5.0

### Specific Android models

```Markdown
* Galaxy S6 Edge+
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Hi @CharlieZheng,

Thanks for reporting. The stacktrace is not showing the cause of `Fatal Exception: java.lang.RuntimeException: Package manager has died`. 

I would expect there to be a `Caused by ...` section like the example below, otherwise there is not enough information. Do you have information about the root cause?

![Screen Shot 2022-10-18 at 9 56 33 PM](https://user-images.githubusercontent.com/4022291/196601243-e3e87cf1-9e51-4d71-9b40-8c5318cd5027.png)

**Comment by jkasten2** [comment]
Closing due to no response, if you have more details feel free to reply and we can reopen.

**Comment by shefich** [comment]
Also happens in my project.

Stacktrace:
`Fatal Exception: java.lang.RuntimeException
Package manager has died
android.app.ApplicationPackageManager.getPackageInfo (ApplicationPackageManager.java:134)
com.onesignal.OneSignal.registerUserTask (OneSignal.java:1521)
com.onesignal.OneSignal.access$1500 (OneSignal.java:86)
com.onesignal.OneSignal$10.run (OneSignal.java:1495)
java.lang.Thread.run (Thread.java:818)

Caused by android.os.DeadObjectException
android.os.BinderProxy.transactNative (Binder.java)
android.os.BinderProxy.transact (Binder.java:503)
android.content.pm.IPackageManager$Stub$Proxy.getPackageInfo (IPackageManager.java:2163)
android.app.ApplicationPackageManager.getPackageInfo (ApplicationPackageManager.java:129)
com.onesignal.OneSignal.registerUserTask (OneSignal.java:1521)
com.onesignal.OneSignal.access$1500 (OneSignal.java:86)
com.onesignal.OneSignal$10.run (OneSignal.java:1495)
java.lang.Thread.run (Thread.java:818)`

Unity 2021.3.23
OneSignal 3.0.10
