### ISSUE TITLE
[question]: Fatal Exception: java.lang.VerifyError

### ISSUE THREAD

**Issue by Hitesh3M** [OneSignal/OneSignal-Android-SDK#1694]
### How can we help?

Fatal Exception: java.lang.VerifyError: com/onesignal/u0
       at com.onesignal.OneSignal.onAppFocusLogic(OneSignal.java)
       at com.onesignal.OneSignal.onAppFocus(OneSignal.java)
       at com.onesignal.OSFocusHandler.startOnFocusWork(OSFocusHandler.java)
       at com.onesignal.ActivityLifecycleHandler.handleFocus(ActivityLifecycleHandler.java)
       at com.onesignal.ActivityLifecycleHandler.onActivityResumed(ActivityLifecycleHandler.java)
       at com.onesignal.ActivityLifecycleListener.onActivityResumed(ActivityLifecycleListener.java)
       at android.app.Application.dispatchActivityResumed(Application.java:227)
       at android.app.Activity.onResume(Activity.java:1114)
       at androidx.fragment.app.FragmentActivity.onResume(FragmentActivity.java)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1200)
       at android.app.Activity.performResume(Activity.java:5365)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3008)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3064)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2350)
       at android.app.ActivityThread.access$1100(ActivityThread.java:139)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5314)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
       at dalvik.system.NativeStart.main(NativeStart.java)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkasten2** [comment]
@Hitesh3M Thanks for reporting however we will need more details before we can look into this issue. Please provide:
1. Exact OneSignal SDK version
2. Android versions the crash happens on.
3. Can you reproduce the issue? If so, please provided step-by-step details.
4. Can you provide a stack trace with exact line numbers? (this will help narrow down the crash greatly)

**Comment by jkasten2** [comment]
@Hitesh3M I noticed this is the same issue as https://github.com/OneSignal/OneSignal-Android-SDK/issues/1657, please provide those details there.
