### ISSUE TITLE
[question]: Android integration tagsAvailable method from OSGetTagsHandler is called after 5-10 minutes after OneSignal.getTags(this)

### ISSUE THREAD

**Issue by ValentinCerneanu** [OneSignal/OneSignal-Android-SDK#1734]
### How can we help?

Hello, 

I am an Android developer and I am working on integrating OneSignal push notifications.
My implementation is using Tags.
I try to do a OneSignal.getTags(this) but the tagsAvailable method from OSGetTagsHandler is called after 5-10 minutes.
I started working on this in December and back then the OSGetTagsHandler was called after 3-4 seconds

build.gradle
`implementation 'com.onesignal:OneSignal:[4.0.0, 4.99.99]'`

MainApplication.kt
`       OneSignal.initWithContext(this)
        OneSignal.setAppId(ONESIGNAL_APP_ID)
        OneSignal.setNotificationWillShowInForegroundHandler {
			//stuff
        }  
        OneSignal.setNotificationOpenedHandler {
			//stuff
        }`

GetTagsActivity.kt
`	override fun onCreate(savedInstanceState: Bundle?) {
		OneSignal.getTags(this)
	}  

	override fun tagsAvailable(tags: JSONObject?) {
        if(tags != null){
            val iter: Iterator<String> = tags.keys()
            while (iter.hasNext()) {
                val key = iter.next()
            }
        }
    }`

Possible important logs:
E/OneSignal: Waiting for remote params. Moving setExternalUserId() operation to a pending task queue.
E/OneSignal: Waiting for remote params. Moving sendTag() operation to a pending task queue.
E/OneSignal: Waiting for remote params. Moving sendTag() operation to a pending task queue.
E/OneSignal: Waiting for remote params. Moving sendTag() operation to a pending task queue.
E/OneSignal: Waiting for remote params. Moving getTags() operation to a pending queue.
E/OneSignal: Waiting for remote params. Moving onAppLostFocus() operation to a pending task queue.

W/OneSignal: OneSignalRestClient: null Error thrown from network stack. 
    java.io.InterruptedIOException: thread interrupted
        at com.android.okhttp.okio.Timeout.throwIfReached(Timeout.java:147)
        at com.android.okhttp.okio.Okio$1.write(Okio.java:75)
        at com.android.okhttp.okio.AsyncTimeout$1.write(AsyncTimeout.java:157)
        at com.android.okhttp.okio.RealBufferedSink.flush(RealBufferedSink.java:222)
        at com.android.okhttp.internal.http.Http1xStream.finishRequest(Http1xStream.java:163)
        at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:748)
        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:622)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:106)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:30)
        at com.onesignal.OneSignalRestClient.startHTTPConnection(OneSignalRestClient.java:193)
        at com.onesignal.OneSignalRestClient.access$100(OneSignalRestClient.java:46)
        at com.onesignal.OneSignalRestClient$4.run(OneSignalRestClient.java:114)
        at java.lang.Thread.run(Thread.java:1012)

It is clear for me that getTags() method takes that much time (5 minutes) to execute because in the logs it is telling me that the operation is in a pending queue. 

Like I mentioned before in December the process worked as a charm. 
What has been changed from December? 
Should I try to use a different OneSignal sdk version? 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkasten2** [comment]
@ValentinCerneanu Thanks for reporting!

## Network Delay
The log shows there is timeout trying to make a network request which I believe it the root of the delay you are seeing.

```java
W/OneSignal: OneSignalRestClient: null Error thrown from network stack.
java.io.InterruptedIOException: thread interrupted
at com.android.okhttp.okio.Timeout.throwIfReached(Timeout.java:147)
at com.android.okhttp.okio.Okio$1.write(Okio.java:75)
at com.android.okhttp.okio.AsyncTimeout$1.write(AsyncTimeout.java:157)
at com.android.okhttp.okio.RealBufferedSink.flush(RealBufferedSink.java:222)
at com.android.okhttp.internal.http.Http1xStream.finishRequest(Http1xStream.java:163)
at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:748)
at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:622)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:106)
at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:30)
at com.onesignal.OneSignalRestClient.startHTTPConnection(OneSignalRestClient.java:193)
at com.onesignal.OneSignalRestClient.access$100(OneSignalRestClient.java:46)
at com.onesignal.OneSignalRestClient$4.run(OneSignalRestClient.java:114)
at java.lang.Thread.run(Thread.java:1012)
```

This is most likely an issue with something blocking the network call to onesignal.com. Do you have a VPN or firewall that could be blocking or dropping your connection? Can you try a different network and / or different devices to narrow down the issue? I also recommend making sure those devices can open onesignal.com in a web browser.

## Get Tags
Could you let us know the use-case you have for `OneSignal.getTags`? Normally tags are only written from the SDK `OneSignal.sendTags` and then you use them to create segments on the OneSignal dashboard. Are you using `OneSignal.getTags` just for debugging? Or something else?

**Comment by jennantilla** [comment]
Closing issue due to no response. Please @ mention me if we need to revisit this issue.

We have an updated major release available for our Android SDK with many improvements and enhancements! Please refer to the [migration guide](https://github.com/OneSignal/OneSignal-Android-SDK/blob/user-model/main/MIGRATION_GUIDE.md) for more information on upgrading.

Thanks!
