### ISSUE TITLE
[Bug]:  Not allowed to bind to service Intent

### ISSUE THREAD

**Issue by areehafarooq** [OneSignal/OneSignal-Android-SDK#1759]
### What happened?

We are receiving crashes in our application due to the following error 
Fatal Exception: java.lang.SecurityException: Not allowed to bind to service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms }

[Issue](https://github.com/firebase/firebase-android-sdk/issues/2062) was reported for firebase and was fixed in com.google.firebase:firebase-messaging:23.0.0.  Preferred version of com.google.firebase:firebase-messaging is 22.0.0 in one signal sdk. As a result we are facing the crash. 

### Steps to reproduce?

```Markdown
I am not able to reproduce the issue but it was reported in crashlytics.
```

### What did you expect to happen?

I expected the app to not crash.

### OneSignal Android SDK version

4.6.3

### Android version

10

### Specific Android models

```Markdown
Q Mobile - FIH Foxconn (View Max Pro)
```

### Relevant log output

```Shell
Fatal Exception: java.lang.SecurityException: Not allowed to bind to service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms }
       at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1741)
       at android.app.ContextImpl.bindService(ContextImpl.java:1651)
       at android.content.ContextWrapper.bindService(ContextWrapper.java:705)
       at com.google.android.gms.common.stats.ConnectionTracker.zze(ConnectionTracker.java:82)
       at com.google.android.gms.common.stats.ConnectionTracker.zzc(ConnectionTracker.java:82)
       at com.google.android.gms.common.stats.ConnectionTracker.bindService(ConnectionTracker.java:13)
       at com.google.android.gms.cloudmessaging.zzf.zza(zzf.java:127)
       at com.google.android.gms.cloudmessaging.zze.b(zze.java:45)
       at com.google.android.gms.cloudmessaging.zze.zza(zze.java:53)
       at com.google.android.gms.cloudmessaging.CloudMessagingReceiver.zzb(CloudMessagingReceiver.java:53)
       at com.google.android.gms.cloudmessaging.CloudMessagingReceiver.zza(CloudMessagingReceiver.java:49)
       at com.google.android.gms.cloudmessaging.zzd.run(zzd.java:49)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.android.gms.common.util.concurrent.zza.run(zza.java:293)
       at java.lang.Thread.run(Thread.java:919)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment]
@areehafarooq Thank you for reporting we will work on getting this dependency updated
