### ISSUE TITLE
Bad array lengths com.onesignal.GenerateNotification.showNotification

### ISSUE THREAD

**Issue by powerthazan** [OneSignal/OneSignal-Android-SDK#176]
I am getting this error around 200 devices. Error: Fatal Exception: java.lang.RuntimeException bad array lengths com.onesignal.GenerateNotification.showNotification.

One signal version: latest
```Java
Fatal Exception: java.lang.RuntimeException: bad array lengths
       at android.os.Parcel.readIntArray(Parcel.java:789)
       at android.app.INotificationManager$Stub$Proxy.enqueueNotificationWithTag(INotificationManager.java:229)
       at android.app.NotificationManager.notify(NotificationManager.java:132)
       at android.support.v4.app.NotificationManagerCompat$ImplBase.postNotification(SourceFile:179)
       at android.support.v4.app.NotificationManagerCompat.notify(SourceFile:290)
       at android.support.v4.app.NotificationManagerCompat.notify(SourceFile:274)
       at com.onesignal.GenerateNotification.showNotification(SourceFile:320)
       at com.onesignal.GenerateNotification.fromJsonPayload(SourceFile:101)
       at com.onesignal.NotificationBundleProcessor.Process(SourceFile:86)
       at com.onesignal.NotificationBundleProcessor.ProcessFromGCMIntentService(SourceFile:71)
       at com.onesignal.GcmIntentService.onHandleIntent(SourceFile:58)
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:194)
       at android.os.HandlerThread.run(HandlerThread.java:60)
```

**Comment by powerthazan** [comment]
<img width="1075" alt="screen shot 2017-02-20 at 7 20 40 am" src="https://cloud.githubusercontent.com/assets/2088136/23109224/1e03ae22-f73d-11e6-87aa-de130e31e3c4.png">

**Comment by jkasten2** [comment]
@powerthazan Could you let us know the options with values you have set on the notification? Please attach the full JSON payload if you are using the REST API. If this is from the dashboard please link OneSignal support to this issue and include the notification id that reproduced this issue.

**Comment by powerthazan** [comment]
It is from dashboard. I used simple notification. No Background Data. Anyway, I contacted you via Support!!

**Comment by jkasten2** [comment]
Notification that triggered the `GenerateNotification.showNotification` crash had `big_picture`, `contents` and `headings` set with emojis. Nothing unusual compared to other notifications.

The Android support library is in the crash stack. Could you let us know the exact version your app is using?

**Comment by powerthazan** [comment]
All versions are latest. 
Onesignal: ` compile 'com.onesignal:OneSignal:3.+@aar'`
Android Support library: ` compile 'com.android.support:appcompat-v7:25.2.0'`

**Comment by jkasten2** [comment]
Upgrading to `com.android.support:appcompat-v7:25.3.1'` may fix the issue.

**Comment by powerthazan** [comment]
yah. It was fixed.
