### ISSUE TITLE
[Bug]: Parameter specified as non-null is null: method com.onesignal.outcomes.data.OSOutcomeEventsV1Repository.requestMeasureOutcomeEvent, parameter appId

### ISSUE THREAD

**Issue by erkki-lukk** [OneSignal/OneSignal-Android-SDK#1763]
### What happened?

Sentry has detected our React Native Android app crashing with the below exception:

```
java.lang.NullPointerException: Parameter specified as non-null is null: method com.onesignal.outcomes.data.OSOutcomeEventsV1Repository.requestMeasureOutcomeEvent, parameter appId
    at com.onesignal.outcomes.data.OSOutcomeEventsV1Repository.requestMeasureOutcomeEvent
    at com.onesignal.OSOutcomeEventsController.sendAndCreateOutcomeEvent(OSOutcomeEventsController.java:275)
    at com.onesignal.OSOutcomeEventsController.sendOutcomeEvent(OSOutcomeEventsController.java:134)
    at com.onesignal.OneSignal.sendOutcome(OneSignal.java:3385)
    at com.geektime.rnonesignalandroid.RNOneSignal.sendOutcome(RNOneSignal.java:770)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
    at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
    at com.facebook.jni.NativeRunnable.run(NativeRunnable.java)
    at android.os.Handler.handleCallback(Handler.java:942)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
    at java.lang.Thread.run(Thread.java:1012)
```

It doesn't seem to be our app calling anything specific at the time of the exception so I'm assuming it's internal to the SDK processes. 

All exceptions so far have happened Samsung devices running Android 13.

### Steps to reproduce?

```Markdown
Seems to be happening quite randomly from our React Native app's point of view.
```

### What did you expect to happen?

Expecting no exception and app crash

### OneSignal Android SDK version

Release 4.8.5

### Android version

13

### Specific Android models

```Markdown
Android 13
Samsung
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment]
@erkki-lukk Thank you for reporting I am assuming you have not been able to reproduce the issue? Does you app use the send outcomes feature at all?

**Comment by erkki-lukk** [comment]
I haven't been able to reproduce it unfortunately @emawby . Having looked a little deeper in our code it seems like we do call `OneSignal.sendOutcomeWithValue`, but only after `OneSignal.setAppId` has been called. We are also calling `OneSignal.setRequiresUserPrivacyConsent` if that's of any relevance to this process. Suspiciously the error appears to be happening only on Samsung devices running Android 13.

**Comment by tmaly1980** [comment]
@jennantilla This is happening for me on 5.2.13. Specifically com.onesignal.OneSignal.login
