### ISSUE TITLE
[Bug]: AndroidJavaException: java.lang.ClassNotFoundException: com.onesignal.OneSignal

### ISSUE THREAD

**Issue by Ilya171** [OneSignal/OneSignal-Android-SDK#1785]
### What happened?

error in logs

### Steps to reproduce?

```Markdown
import unitypackage

write code:  OneSignal.Initialize(appId);

build apk
```

### What did you expect to happen?

that everything will work: OneSignal is initialized

### OneSignal Android SDK version

v5 -beta3

### Android version

13, 12, 11, 10, 9, 8, 7.1, 7.0, 6, 5.1, 5.0, 4.4

### Relevant log output

```Shell
AndroidJavaException: java.lang.ClassNotFoundException: com.onesignal.OneSignal
07-14 12:33:31.880  1253  1270 E Unity   : java.lang.ClassNotFoundException: com.onesignal.OneSignal
07-14 12:33:31.880  1253  1270 E Unity   :      at java.lang.Class.classForName(Native Method)
07-14 12:33:31.880  1253  1270 E Unity   :      at java.lang.Class.forName(Class.java:453)
07-14 12:33:31.880  1253  1270 E Unity   :      at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
07-14 12:33:31.880  1253  1270 E Unity   :      at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)
07-14 12:33:31.880  1253  1270 E Unity   :      at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)
07-14 12:33:31.880  1253  1270 E Unity   :      at android.os.Handler.dispatchMessage(Handler.java:102)
07-14 12:33:31.880  1253  1270 E Unity   :      at android.os.Looper.loop(Looper.java:216)
07-14 12:33:31.880  1253  1270 E Unity   :      at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
07-14 12:33:31.880  1253  1270 E Unity   : Caused by: java.lang.ClassNotFoundException: Didn't find class "com.onesignal.OneSignal" on path: DexPathList[[zip file "/data/app/com.BajiLive.cricket-01qzhmpHQJHMEBkLGKVRbw==/base.apk"],nativeLibraryDirectories=[/data/app/com.BajiLive.cricket-01qzhmpHQJHMEBkLGKVRbw==/lib/arm, /data/app/com.BajiLive.cricket-01qzhmpHQJHMEBkLGKVRbw==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
07-14 12:33:31.880  1253  1270 E Unity   :      at dalvik.system.BaseDexClassLoader.
07-14 12:33:31.957  1253  1270 E Unity   : AndroidJavaException: java.lang.ClassNotFoundException: com.onesignal.OneSignal
07-14 12:33:31.957  1253  1270 E Unity   : java.lang.ClassNotFoundException: com.onesignal.OneSignal
07-14 12:33:31.957  1253  1270 E Unity   :      at java.lang.Class.classForName(Native Method)
07-14 12:33:31.957  1253  1270 E Unity   :      at java.lang.Class.forName(Class.java:453)
07-14 12:33:31.957  1253  1270 E Unity   :      at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
07-14 12:33:31.957  1253  1270 E Unity   :      at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)
07-14 12:33:31.957  1253  1270 E Unity   :      at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)
07-14 12:33:31.957  1253  1270 E Unity   :      at android.os.Handler.dispatchMessage(Handler.java:102)
07-14 12:33:31.957  1253  1270 E Unity   :      at android.os.Looper.loop(Looper.java:216)
07-14 12:33:31.957  1253  1270 E Unity   :      at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
07-14 12:33:31.957  1253  1270 E Unity   : Caused by: java.lang.ClassNotFoundException: Didn't find class "com.onesignal.OneSignal" on path: DexPathList[[zip file "/data/app/com.BajiLive.cricket-01qzhmpHQJHMEBkLGKVRbw==/base.apk"],nativeLibraryDirectories=[/data/app/com.BajiLive.cricket-01qzhmpHQJHMEBkLGKVRbw==/lib/arm, /data/app/com.BajiLive.cricket-01qzhmpHQJHMEBkLGKVRbw==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hello @Ilya171 thanks for reaching out! It sounds like you are using our Unity SDK, is that correct? Are you using Proguard?

If so, this could be similar to [this Unity issue](https://github.com/OneSignal/OneSignal-Unity-SDK/issues/562#issuecomment-1536457023).

Could you please try the workaround proposed there and let us know your results?

Thanks!

**Comment by jennantilla** [comment]
Closing due to no response. Please let us know if you are still having any issues.

We have a new [major release](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.0.2) available that includes many improvements and enhancements. Note that there are breaking changes with the update so please refer to the migration guide [here](https://github.com/OneSignal/OneSignal-Android-SDK/blob/user-model/main/MIGRATION_GUIDE.md).

Thanks!
