### ISSUE TITLE
[Bug]: Verion 4.8.6 crash when use non http/https link in launch url like hello://newmessage

### ISSUE THREAD

**Issue by mnk98** [OneSignal/OneSignal-Android-SDK#1795]
### What happened?

I wanna use a custom made url but when pass launch url with custom made like hello://newmessage 
app get crash while opening notification and gets below error
`FATAL EXCEPTION: main
                                                                                                    Process: com.onesignal.sdktest, PID: 1635
                                                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.onesignal.sdktest/com.onesignal.NotificationOpenedReceiver}: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=hello://newmessage/... flg=0x10000000 }
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3644)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3781)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2306)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7918)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                                                                                                    Caused by: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=hello://newmessage/... flg=0x10000000 }
                                                                                                    	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2200)
                                                                                                    	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1839)
                                                                                                    	at android.app.Activity.startActivityForResult(Activity.java:5507)
                                                                                                    	at android.app.Activity.startActivityForResult(Activity.java:5465)
                                                                                                    	at android.app.Activity.startActivity(Activity.java:5963)
                                                                                                    	at android.app.Activity.startActivity(Activity.java:5930)
                                                                                                    	at com.onesignal.OneSignal.openDestinationActivity(OneSignal.java:2443)
                                                                                                    	at com.onesignal.OneSignal.handleNotificationOpen(OneSignal.java:2423)
                                                                                                    	at com.onesignal.NotificationOpenedProcessor.processIntent(NotificationOpenedProcessor.java:116)
                                                                                                    	at com.onesignal.NotificationOpenedProcessor.processFromContext(NotificationOpenedProcessor.java:64)
                                                                                                    	at com.onesignal.NotificationOpenedReceiverBase.onCreate(NotificationOpenedReceiverBase.kt:36)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8342)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8321)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3625)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3781) 
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2306) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201) 
                                                                                                    	at android.os.Looper.loop(Looper.java:288) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7918) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936) `

but when i downgrade onesignal to 4.6.3 , it's working fine
any idea.

### Steps to reproduce?

```Markdown
1. Run example project of onesignal from this repo
2. Upgrade onesignal to 4.8.6
3. Send notification using launch url - hello://newmessage
4. click on notification from phone
5. you will see crash
6. Now downgrade to 4.6.3 
7. repeat step 3 and step 4
8. Crash does not happen
```

### What did you expect to happen?

I expect that with upgrade version of onesignal, app should not crash when use non http/https url in launch url field

### OneSignal Android SDK version

4.8.6

### Android version

13, 12

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hi @mnk98 thanks for your patience! Deep linking should work for any valid activity in your app. Our demo app does not currently have the activity `hello://newmessage`.

You can read more about setting up deep linking [here](https://documentation.onesignal.com/docs/links#deep-linking). It is recommended to create a custom scheme specific for your app like `your-app-name://the-identifier-for-the-page-to-go-to`

Let us know if you have any additional questions or concerns!

**Comment by jennantilla** [comment]
@mnk98 rereading this issue, I think perhaps you are requesting handling of an invalid launch URL so that it does not result in a crash?

**Comment by mnk98** [comment]
@jennantilla Correct, at least with the invalid URL, it should not crash the app.

**Comment by jennantilla** [comment]
Thanks for clarifying! We're working on this. You can track progress [here](https://github.com/OneSignal/OneSignal-Android-SDK/issues/1827). I'll close out this issue for consolidation.
