### ISSUE TITLE
[Bug]: 829377 crash when receiving a push notifications with two buttons

### ISSUE THREAD

**Issue by felixmede** [OneSignal/OneSignal-Android-SDK#1815]
### What happened?

The app crashes upon receiving a push notification with two buttons with the error

java.lang.IllegalArgumentException: Unsupported value: 'com.onesignal.notifications.internal.Notification$ActionButton@9b88d51' of type 'class com.onesignal.notifications.internal.Notification$ActionButton'

### Steps to reproduce?

```Markdown
1. setup a device to receive a push message
2. start up the flutter(android) app
2. send a test message with two buttons and actions
```

### What did you expect to happen?

the message getting displayed in the notifications

### OneSignal Android SDK version

5.0.0

### Android version

10

### Specific Android models

```Markdown
Samsung Galaxy S9
```

### Relevant log output

```Shell
/OneSignal(20974): [main] initWithContext(context: android.app.ReceiverRestrictedContext@bf8e31f, appId: null)
D/OneSignal(20974): [main] Retrieving service interface com.onesignal.notifications.internal.bundle.INotificationBundleProcessor
D/OneSignal(20974): [main] Already instantiated: com.onesignal.notifications.internal.bundle.impl.NotificationBundleProcessor@723fe2b
D/OneSignal(20974): [main] NotificationWorkManager enqueueing notification work with notificationId: ba543840-111c-4295-947c-49ef7baf1ff3 and jsonPayload: {"google.delivered_priority":"normal","google.sent_time":1692950902217,"google.ttl":259200,"google.original_priority":"normal","custom":"{\"i\":\"ba543840-111c-4295-947c-49ef7baf1ff3\",\"a\":{\"actionButtons\":[{\"icon_type\":\"custom\",\"id\":\"testAction\",\"text\":\"test\"},{\"icon_type\":\"custom\",\"id\":\"testAction2\",\"text\":\"testAction\"}],\"actionId\":\"__DEFAULT__\"}}","pri":"5","vis":"1","from":"982098383328","alert":"test message","title":"test title","google.message_id":"0:1692950902239422%d30ed4fdf9fd7ecd","google.c.sender.id":"982098383328"}
D/OneSignal(20974): [DefaultDispatcher-worker-1] Retrieving service interface com.onesignal.notifications.internal.generation.INotificationGenerationProcessor
D/OneSignal(20974): [DefaultDispatcher-worker-1] Already instantiated: com.onesignal.notifications.internal.generation.impl.NotificationGenerationProcessor@6d086e6
D/OneSignal(20974): [DefaultDispatcher-worker-1] NotificationWorker running doWork with data: Data {json_payload : {"google.delivered_priority":"normal","google.sent_time":1692950902217,"google.ttl":259200,"google.original_priority":"normal","custom":"{\"i\":\"ba543840-111c-4295-947c-49ef7baf1ff3\",\"a\":{\"actionButtons\":[{\"icon_type\":\"custom\",\"id\":\"testAction\",\"text\":\"test\"},{\"icon_type\":\"custom\",\"id\":\"testAction2\",\"text\":\"testAction\"}],\"actionId\":\"__DEFAULT__\"}}","pri":"5","vis":"1","from":"982098383328","alert":"test message","title":"test title","google.message_id":"0:1692950902239422%d30ed4fdf9fd7ecd","google.c.sender.id":"982098383328"}, android_notif_id : 0, is_restoring : false, os_notif_id : ba543840-111c-4295-947c-49ef7baf1ff3, timestamp : 1692950902, }
I/OneSignal(20974): [DefaultDispatcher-worker-6] Fire remoteNotificationReceived
I/OneSignal(20974): [DefaultDispatcher-worker-5] Fire notificationWillShowInForegroundHandler
D/OneSignal(20974): [DefaultDispatcher-worker-1] NotificationWillDisplayEvent.preventDefault()
D/AndroidRuntime(20974): Shutting down VM
E/AndroidRuntime(20974): FATAL EXCEPTION: main
E/AndroidRuntime(20974): Process: com.medel.ai.redi.dev, PID: 20974
E/AndroidRuntime(20974): java.lang.IllegalArgumentException: Unsupported value: 'com.onesignal.notifications.internal.Notification$ActionButton@9b88d51' of type 'class com.onesignal.notifications.internal.Notification$ActionButton'
E/AndroidRuntime(20974): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:297)
E/AndroidRuntime(20974): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:277)
E/AndroidRuntime(20974): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:285)
E/AndroidRuntime(20974): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:285)
E/AndroidRuntime(20974): 	at io.flutter.plugin.common.StandardMethodCodec.encodeMethodCall(StandardMethodCodec.java:38)
E/AndroidRuntime(20974): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:119)
E/AndroidRuntime(20974): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:102)
E/AndroidRuntime(20974): 	at com.onesignal.flutter.FlutterRegistrarResponder$4.run(FlutterRegistrarResponder.java:76)
E/AndroidRuntime(20974): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime(20974): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime(20974): 	at android.os.Looper.loop(Looper.java:237)
E/AndroidRuntime(20974): 	at android.app.ActivityThread.main(ActivityThread.java:8167)
E/AndroidRuntime(20974): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(20974): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
E/AndroidRuntime(20974): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
@felixmede thanks for reaching out! I've been able to reproduce this, so we'll get working on a solution right away!

**Comment by Aksoyhlc** [comment]
i have the same problem

**Comment by jennantilla** [comment]
@Aksoyhlc thanks for the report! Can you please confirm which SDK you are using--so far, I've only been able to reproduce this on Flutter, so if you are experiencing this with the native Android SDK or another wrapper, please let us know!

**Comment by Aksoyhlc** [comment]
@jennantilla Hello, I am also getting this error in Flutter.  I tried onesignal_flutter 5.0.0 on Xiaomi and Emulator devices, the application was stopped on all of them and I received the reported error.

**Comment by emawby** [comment]
Fixed in https://github.com/OneSignal/OneSignal-Flutter-SDK/pull/743

**Comment by jennantilla** [comment]
@felixmede thank you for your patience. We have a fix for this on the latest Flutter release, [5.0.2](https://github.com/OneSignal/OneSignal-Flutter-SDK/releases/tag/5.0.2).

Please let us know if you have any additional questions or concerns.
