### ISSUE TITLE
[Bug]: ActivityNotFoundException: No Activity found to handle Intent https

### ISSUE THREAD

**Issue by chokokatana** [OneSignal/OneSignal-Android-SDK#1836]
### What happened?

Push with `https://twitter.com/...` link tried to open an intent to view the https link and crashed.

### Steps to reproduce?

```Markdown
1. Install 4.8.6
2. Send push with https link
3. Try to open push on LG Stylo 5 (apparently Android 10)
```

### What did you expect to happen?

Either open the link or not open the link, but definitely not crash.

### OneSignal Android SDK version

4.8.6

### Android version

10

### Specific Android models

```Markdown
LG Stylo 5
```

### Relevant log output

```Shell
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.geodb.wallace/com.onesignal.NotificationOpenedReceiver}: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://twitter.com/... flg=0x10000000 }
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3323)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3462)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2063)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7615)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

Caused by android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://twitter.com/... flg=0x10000000 }
       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2064)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1718)
       at android.app.Activity.startActivityForResult(Activity.java:5221)
       at android.app.Activity.startActivityForResult(Activity.java:5179)
       at android.app.Activity.startActivity(Activity.java:5550)
       at android.app.Activity.startActivity(Activity.java:5518)
       at com.onesignal.OneSignal.openDestinationActivity(OneSignal.java:2443)
       at com.onesignal.OneSignal.handleNotificationOpen(OneSignal.java:2423)
       at com.onesignal.NotificationOpenedProcessor.processIntent(NotificationOpenedProcessor.java:116)
       at com.onesignal.NotificationOpenedProcessor.processFromContext(NotificationOpenedProcessor.java:64)
       at com.onesignal.NotificationOpenedReceiverBase.onCreate(NotificationOpenedReceiverBase.kt:36)
       at android.app.Activity.performCreate(Activity.java:7835)
       at android.app.Activity.performCreate(Activity.java:7824)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3298)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3462)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2063)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7615)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hello @chokokatana thanks for reaching out! Can you share more about how you are sending the notification--is it through the API or through the OneSignal dashboard? It appears that you might be trying to deep link to an activity in your app instead of provide an external link. Any additional information on steps to reproduce would be appreciated!

**Comment by chokokatana** [comment]
Message was sent through the dashboard, [this is the message](https://dashboard.onesignal.com/apps/0c742eb5-5728-4fb1-bb69-ae023b6a9166/notifications/1a5040f2-c57f-4bdb-93ca-7e14bd98d782#outcomes=os__click__count). No deep linking, the launch url is `https://twitter.com/wallace_wallet/status/1697679369458590203`.

**Comment by jennantilla** [comment]
@chokokatana just a heads up that I'll be working on this in early Q1. We have had a couple reports of this issue, so I'm consolidating them [here](https://github.com/OneSignal/OneSignal-Android-SDK/issues/1827). Feel free to keep an eye on this issue for when a fix is released. Thanks!

**Comment by shivamCobu** [comment]
Hey Guys any update on this issue its crashing our app.
