### ISSUE TITLE
[Bug]: crash during onesignal 4.8.6 initialisation on [NPE from com.onesignal.LocationController.backgroundLocationPermissionLogic(LocationController.java:284)]

### ISSUE THREAD

**Issue by chokokatana** [OneSignal/OneSignal-Android-SDK#1877]
### What happened?

Getting crashes from devices on field, logs indicate they are just opening the app and have practically no time to do anything else because the app is crashing on them.

### Steps to reproduce?

```Markdown
Open app on Galaxy Z Fold3 5G with Android 13. According to app logs these are devices without Google Play Services:

> Couldn't get ad id info java.io.IOException: Google Play services not available (no exception)
```

### What did you expect to happen?

Hopefully not crash.

### OneSignal Android SDK version

4.8.6

### Android version

13

### Specific Android models

```Markdown
Galaxy Z Fold3 5G
```

### Relevant log output

```Shell
Fatal Exception: java.lang.NullPointerException:
       at java.util.Objects.requireNonNull(Objects.java:220)
       at java.util.Arrays$ArrayList.<init>(Arrays.java:4248)
       at java.util.Arrays.asList(Arrays.java:4235)
       at com.onesignal.LocationController.backgroundLocationPermissionLogic(LocationController.java:284)
       at com.onesignal.LocationController.getLocation(LocationController.java:268)
       at com.onesignal.OneSignal.startLocationUpdate(OneSignal.java:1049)
       at com.onesignal.OneSignal.startRegistrationOrOnSession(OneSignal.java:1024)
       at com.onesignal.OneSignal.doSessionInit(OneSignal.java:1013)
       at com.onesignal.OneSignal.init(OneSignal.java:868)
       at com.onesignal.OneSignal.setAppId(OneSignal.java:737)
       at com.onesignal.OneSignal.reassignDelayedInitParams(OneSignal.java:1181)
       at com.onesignal.OneSignal.onRemoteParamSet(OneSignal.java:889)
       at com.onesignal.OneSignal$7.complete(OneSignal.java:1122)
       at com.onesignal.OneSignalRemoteParams.processJson(OneSignalRemoteParams.java:211)
       at com.onesignal.OneSignalRemoteParams.access$100(OneSignalRemoteParams.java:12)
       at com.onesignal.OneSignalRemoteParams$1.onSuccess(OneSignalRemoteParams.java:156)
       at com.onesignal.OneSignalRestClient$5.run(OneSignalRestClient.java:279)
       at java.lang.Thread.run(Thread.java:1012)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment]
@chokokatana Thank you for reporting. Just to confirm this is only happening on the Galaxy Z Fold devices? We investigate to see what is different about that devices lifecycle.

**Comment by chokokatana** [comment]
Yes, only had this on those devices and the logs showed lack of google play services. Got 4 crashlytics crash reports from 2 users, but given the times it's most likely a single user who installed the app, tried to open it twice, deleted the app, reinstalled, tried twice again, and probably we won't see him ever again.

**Comment by nan-li** [comment]
Hi all, apologies this issue has gone stale; the team is no longer actively supporting and patching the v4 major version of this SDK.

I recommend to upgrade to v5 of our SDK. Please let us know if we can help you with the transition.
