### ISSUE TITLE
[Bug]: Crash ModelStore.add java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by chokokatana** [OneSignal/OneSignal-Android-SDK#1898]
### What happened?

Received a crashes after upgrading to 5.0.3.

### Steps to reproduce?

```Markdown
Upgrade to 5.0.3 from 4.8.6.
```

### What did you expect to happen?

No crashes.

### OneSignal Android SDK version

5.0.3

### Android version

9

### Specific Android models

```Markdown
* Samsung Galaxy S8 Android 9
```

### Relevant log output

```Shell
Fatal Exception: java.util.ConcurrentModificationException:
       at java.util.ArrayList$Itr.next(ArrayList.java:860)
       at kotlin.collections.CollectionsKt___CollectionsKt.firstOrNull(CollectionsKt___Collections.kt:288)
       at com.onesignal.common.modeling.ModelStore.add(ModelStore.kt:41)
       at com.onesignal.common.modeling.IModelStore$DefaultImpls.add$default(IModelStore.kt:37)
       at com.onesignal.core.internal.operations.impl.OperationRepo.internalEnqueue(OperationRepo.kt:76)
       at com.onesignal.core.internal.operations.impl.OperationRepo.enqueueAndWait(OperationRepo.kt:68)
       at com.onesignal.internal.OneSignalImp$login$2.invokeSuspend(OneSignalImp.kt:299)
       at com.onesignal.internal.OneSignalImp$login$2.invoke(OneSignalImp.kt:1)
       at com.onesignal.internal.OneSignalImp$login$2.invoke(OneSignalImp.kt:2)
       at com.onesignal.common.threading.ThreadUtilsKt$suspendifyOnThread$1$1.invokeSuspend(ThreadUtils.kt:61)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
       at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
       at kotlinx.coroutines.BlockingCoroutine.joinBlocking(BlockingCoroutine.java:85)
       at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(BuildersKt__Builders.kt:59)
       at kotlinx.coroutines.BuildersKt.runBlocking(Builders.kt:1)
       at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(BuildersKt__Builders.kt:38)
       at kotlinx.coroutines.BuildersKt.runBlocking$default(Builders.kt:1)
       at com.onesignal.common.threading.ThreadUtilsKt$suspendifyOnThread$1.invoke(ThreadUtils.kt:60)
       at com.onesignal.common.threading.ThreadUtilsKt$suspendifyOnThread$1.invoke(ThreadUtils.kt:59)
       at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Threads.kt:30)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment]
Closing as duplicate and as already fixed. Will be available in the next release
