### ISSUE TITLE
[Bug]: ANR triggered due to lock contention at OperationRepo.processQueueForever

### ISSUE THREAD

**Issue by fanwgwg** [OneSignal/OneSignal-Android-SDK#1918]
### What happened?

As reported on Firebase Crashlytics, ANR was triggered because `com.onesignal.core.internal.operations.impl.OperationRepo.processQueueForever (OperationRepo.kt:106)` is blocking the thread.

## Root blocking
```
OpRepo (runnable):tid=45 systid=5619 
       at java.util.ArrayList$Itr.next(ArrayList.java:982)
       at kotlin.collections.CollectionsKt___CollectionsKt.firstOrNull(CollectionsKt___Collections.kt:288)
       at com.onesignal.core.internal.operations.impl.OperationRepo.processQueueForever(OperationRepo.kt:106)
       at com.onesignal.core.internal.operations.impl.OperationRepo.access$executeOperations(OperationRepo.kt)
       at com.onesignal.core.internal.operations.impl.OperationRepo.access$processQueueForever(OperationRepo.kt)
       at com.onesignal.core.internal.operations.impl.OperationRepo$processQueueForever$1.invokeSuspend(OperationRepo.kt:11)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:233)
       at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
       at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:474)
       at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:508)
       at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:497)
       at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:595)
       at kotlinx.coroutines.EventLoopImplBase$DelayedResumeTask.run(EventLoop.common.kt:493)
       at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
       at kotlinx.coroutines.BlockingCoroutine.joinBlocking(BlockingCoroutine.java:85)
       at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(BuildersKt__Builders.kt:59)
       at kotlinx.coroutines.BuildersKt.runBlocking(Builders.kt:1)
       at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(BuildersKt__Builders.kt:38)
       at kotlinx.coroutines.BuildersKt.runBlocking$default(Builders.kt:1)
       at com.onesignal.common.threading.ThreadUtilsKt$suspendifyOnThread$2.invoke(ThreadUtils.kt:91)
       at com.onesignal.common.threading.ThreadUtilsKt$suspendifyOnThread$2.invoke(ThreadUtils.kt:89)
       at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Threads.kt:30)
```

## Triggered ANR (main thread)
```
main (blocked):tid=1 systid=1256 | waiting to lock <0x0465fda1> (java.util.ArrayList) held by thread 45
       at com.onesignal.core.internal.operations.impl.OperationRepo.internalEnqueue(OperationRepo.kt:82)
       at com.onesignal.core.internal.operations.impl.OperationRepo.enqueue(OperationRepo.kt:62)
       at com.onesignal.internal.OneSignalImp.login(OneSignalImp.kt:319)
       at com.onesignal.IOneSignal$DefaultImpls.login(IOneSignal.java:117)
       at com.onesignal.internal.OneSignalImp.login(OneSignalImp.kt:52)
       at com.onesignal.OneSignal.login(OneSignal.java:157)
       at com.yygg.note.app.notification.AppNotificationManager.refreshUserAndSubscription(AppNotificationManager.java:36)
       at com.yygg.note.app.home.HomeViewModel.onResume(HomeViewModel.java:290)
       at androidx.lifecycle.DefaultLifecycleObserverAdapter.onStateChanged(DefaultLifecycleObserverAdapter.kt:26)
       at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.kt:314)
       at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.kt:251)
       at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.kt:287)
       at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.kt:136)
       at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.kt:119)
       at androidx.fragment.app.Fragment.performResume(Fragment.java:3210)
       at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:646)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:296)
       at androidx.fragment.app.SpecialEffectsController$FragmentStateManagerOperation.complete(SpecialEffectsController.kt:664)
       at androidx.fragment.app.SpecialEffectsController$Operation.completeSpecialEffect(SpecialEffectsController.kt:587)
       at androidx.fragment.app.DefaultSpecialEffectsController$SpecialEffectsInfo.completeSpecialEffect(DefaultSpecialEffectsController.java:774)
       at androidx.fragment.app.DefaultSpecialEffectsController.startAnimations(DefaultSpecialEffectsController.kt:150)
       at androidx.fragment.app.DefaultSpecialEffectsController.executeOperations(DefaultSpecialEffectsController.kt:101)
       at androidx.fragment.app.DefaultSpecialEffectsController.startAnimations(DefaultSpecialEffectsController.kt:234)
       at androidx.fragment.app.SpecialEffectsController.executePendingOperations(SpecialEffectsController.java:234)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1956)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1845)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1782)
       at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:565)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7941)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:553)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```
![image](https://github.com/OneSignal/OneSignal-Android-SDK/assets/14089267/9fe5dd70-8e54-49c3-8db3-4ed6c33496d7)

## Not specific to any device or Android version:
![image](https://github.com/OneSignal/OneSignal-Android-SDK/assets/14089267/40c0fa52-2c89-4ed3-af68-abb262b7c929)

### Steps to reproduce?

Happening to around 0.1% of users. Not sure how to reproduce. From main thread it's happening at `OneSignal.logIn` call.

### What did you expect to happen?

OneSignal library shouldn't block apps' main thread

### OneSignal Android SDK version

5.0.4

### Android version

13

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Thank you for reaching out! We'll investigate this.

**Comment by jennantilla** [comment]
Hello @fanwgwg thanks for your patience. We recently made some updates to prevent deadlocks and concurrent modifications. Could you please update the SDK to [5.1.6](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.1.6) and let us know if this still an issue for you? We appreciate it!
