### ISSUE TITLE
[Bug]: Crash NPE in InAppMessagesManager.fetchMessages

### ISSUE THREAD

**Issue by sarbyn** [OneSignal/OneSignal-Android-SDK#1921]
### What happened?

Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
       at com.onesignal.inAppMessages.internal.InAppMessagesManager.fetchMessages(InAppMessagesManager.kt:215)
       at com.onesignal.inAppMessages.internal.InAppMessagesManager.access$showMultiplePrompts(InAppMessagesManager.kt:50)
       at com.onesignal.inAppMessages.internal.InAppMessagesManager.access$fetchMessages(InAppMessagesManager.kt:50)
       at com.onesignal.inAppMessages.internal.InAppMessagesManager$onModelReplaced$1.invokeSuspend(InAppMessagesManager.kt:181)
       at com.onesignal.inAppMessages.internal.InAppMessagesManager$onModelReplaced$1.invoke(InAppMessagesManager.kt:2)
       at com.onesignal.inAppMessages.internal.InAppMessagesManager$onModelReplaced$1.invoke(InAppMessagesManager.kt:1)
       at com.onesignal.common.threading.ThreadUtilsKt$suspendifyOnThread$1$1.invokeSuspend(ThreadUtils.kt:61)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
       at kotlinx.coroutines.BlockingCoroutine.joinBlocking(BlockingCoroutine.java:85)
       at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(BuildersKt__Builders.kt:59)
       at kotlinx.coroutines.BuildersKt.runBlocking(Builders.kt:1)
       at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(BuildersKt__Builders.kt:38)
       at kotlinx.coroutines.BuildersKt.runBlocking$default(Builders.kt:1)
       at com.onesignal.common.threading.ThreadUtilsKt$suspendifyOnThread$1.invoke(ThreadUtils.kt:60)
       at com.onesignal.common.threading.ThreadUtilsKt$suspendifyOnThread$1.invoke(ThreadUtils.kt:59)
       at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)

### Steps to reproduce?

```Markdown
Version 5.0.2
We find this kind of crash on production, not on our test devices
```

### What did you expect to happen?

No crash

### OneSignal Android SDK version

5.0.2

### Android version

13, 12, 11, 10, 9, 8, 7.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
@sarbyn thanks for reaching out! We'll investigate this and get back to you as soon as possible.

**Comment by jfishman1** [comment]
This should be fixed in the latest 5.1.2 https://github.com/OneSignal/OneSignal-Android-SDK/releases

Please let us know if you continue to see this issue and provide the full crash log including affected devices and operating system versions.
