### ISSUE TITLE
[Bug]: NullPointerException Attempt to invoke virtual method 'int android.view.View.getLeft()' on a null object reference

### ISSUE THREAD

**Issue by chokokatana** [OneSignal/OneSignal-Android-SDK#1953]
### What happened?

Reported crash.

### Steps to reproduce?

```Markdown
Not reproducible, maybe user tried to interact with some in app push.
```

### What did you expect to happen?

No crash.

### OneSignal Android SDK version

4.8.6

### Android version

7.1

### Specific Android models

```Markdown
Samsung Galaxy J5(2016), Android 7.1.1.
```

### Relevant log output

```Shell
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getLeft()' on a null object reference
       at androidx.customview.widget.ViewDragHelper.continueSettling(ViewDragHelper.java:768)
       at com.onesignal.DraggableRelativeLayout.computeScroll(DraggableRelativeLayout.java:187)
       at android.view.View.updateDisplayListIfDirty(View.java:17540)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3930)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3910)
       at android.view.View.updateDisplayListIfDirty(View.java:17516)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3930)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3910)
       at android.view.View.updateDisplayListIfDirty(View.java:17516)
       at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3930)
       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3910)
       at android.view.View.updateDisplayListIfDirty(View.java:17516)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:711)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:717)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:825)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:3209)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2996)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2584)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1569)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7301)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:930)
       at android.view.Choreographer.doCallbacks(Choreographer.java:705)
       at android.view.Choreographer.doFrame(Choreographer.java:640)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:916)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6816)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)

Firebase-Messaging-Topics-Io:
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor$(Thread.java:2128)
       at sun.misc.Unsafe.park(Unsafe.java:325)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:161)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2035)
       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1091)
       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1084)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1058)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1118)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at com.google.android.gms.common.util.concurrent.zza.run(zza.java:2)
       at java.lang.Thread.run(Thread.java:762)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
@chokokatana thank you for reaching out. We will investigate this and get back to you as soon as possible.

**Comment by arikanf** [comment]
is there any news ?
