### ISSUE TITLE
Crash because of missing NEW_TASK flag in PushnotificationHandler

### ISSUE THREAD

**Issue by martyglaubitz** [OneSignal/OneSignal-Android-SDK#199]
Recently we're getting a lot of crashes like this:
```java

java.lang.RuntimeException: Unable to start receiver com.onesignal.NotificationOpenedReceiver: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2832)
	at android.app.ActivityThread.access$1700(ActivityThread.java:178)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1547)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5631)
	at java.lang.reflect.Method.invoke(Method.java)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
Caused by: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
	at android.app.ContextImpl.startActivity(ContextImpl.java:1351)
	at android.app.ContextImpl.startActivity(ContextImpl.java:1338)
	at goflow.app.push.PushNotificationOpenedHandler.notificationOpened(PushNotificationOpenedHandler.java:34)
	at com.onesignal.OneSignal.fireNotificationOpenedHandler(OneSignal.java:1009)
	at com.onesignal.OneSignal.runNotificationOpenedCallback$785e2db1(OneSignal.java:954)
	at com.onesignal.OneSignal.handleNotificationOpen(OneSignal.java:1041)
	at com.onesignal.NotificationOpenedProcessor.processIntent(NotificationOpenedProcessor.java:101)
	at com.onesignal.NotificationOpenedProcessor.processFromActivity(NotificationOpenedProcessor.java:57)
	at com.onesignal.NotificationOpenedReceiver.onReceive(NotificationOpenedReceiver.java:11)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2825)
	... 9 more
```

**Comment by jkasten2** [comment]
@martyglaubitz The crash is coming from the following line in your code.
```Java
goflow.app.push.PushNotificationOpenedHandler.notificationOpened(PushNotificationOpenedHandler.java:34)
```

You need to add `FLAG_ACTIVITY_NEW_TASK` to your flags as part of the `Intent` passed to `startActivity` or use a `Activity` for the `Context`.
I recommend checking out the following article which explains different types of Contexts and their limitations well.
https://possiblemobile.com/2013/06/context/

**Comment by martyglaubitz** [comment]
Argh... sorry - our fault ^^

**Comment by tribitinfotech** [comment]
You need to set New Task flag in your intent before start activity call.

resultIntent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_CLEAR_TASK);
