### ISSUE TITLE
[Bug]: com.onesignal.notifications.internal.generation.impl.NotificationGenerationWorkManager.beginEnqueueingWork ANR triggered by slow operations in main thread

### ISSUE THREAD

**Issue by ayushi-sk** [OneSignal/OneSignal-Android-SDK#1998]
### What happened?

ANR

### Steps to reproduce?

```Markdown
OneSignal integration
```

### What did you expect to happen?

No ANR please

### OneSignal Android SDK version

5.1.2 and all others

### Android version

13, 12, 11

### Relevant log output

```Shell
at com.onesignal.notifications.internal.generation.impl.NotificationGenerationWorkManager.beginEnqueueingWork(NotificationGenerationWorkManager.kt:50)
       at com.onesignal.notifications.internal.bundle.impl.NotificationBundleProcessor.processBundleFromReceiver(NotificationBundleProcessor.kt:99)
       at com.onesignal.notifications.receivers.FCMBroadcastReceiver.onReceive(FCMBroadcastReceiver.kt:37)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ayushi-sk** [comment]
1. Couldn't reproduce it
2. 

```
main (runnable):tid=1 systid=9182 
       at java.util.HashSet.add(HashSet.java:219)
       at kotlin.collections.ArraysKt___ArraysKt.toCollection(ArraysKt___Arrays.kt:9523)
       at kotlin.collections.SetsKt__SetsKt.mutableSetOf(SetsKt__Sets.kt:78)
       at androidx.work.WorkRequest$Builder.<init>(WorkRequest.kt:72)
       at androidx.work.OneTimeWorkRequest$Builder.<init>(OneTimeWorkRequest.java:36)
       at com.onesignal.notifications.internal.generation.impl.NotificationGenerationWorkManager.beginEnqueueingWork(NotificationGenerationWorkManager.kt:52)
       at com.onesignal.notifications.internal.bundle.impl.NotificationBundleProcessor.processBundleFromReceiver(NotificationBundleProcessor.kt:99)
       at com.onesignal.notifications.receivers.FCMBroadcastReceiver.onReceive(FCMBroadcastReceiver.kt:37)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4369)
       at android.app.ActivityThread.access$1700(ActivityThread.java:265)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2180)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:257)
       at android.app.ActivityThread.main(ActivityThread.java:8220)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)
```

3. All android version and all device models

**Comment by jinliu9508** [comment]
Closing this issue as it has been resolved in the latest SDK version, and there are no further updates. If anyone is still experiencing this issue, please try upgrading to the latest SDK and open a new issue if the problem persists after upgrading.
