### ISSUE TITLE
[Bug]: Android app crashes on click of notification with error: "No Activity found to handle Intent"

### ISSUE THREAD

**Issue by shivamCobu** [OneSignal/OneSignal-Android-SDK#2011]
### What happened?

This issue is happening only for android.
Its because of option "app_url" of rest api - "https://onesignal.com/api/v1/notifications" which is used for deep linking inside the app. When "app_url" is omitted we don't face any issues.

When click on received notification the app crashed with the following error trace:

android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=cobu://chat/... flg=0x10000000 }
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3645)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7872)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=cobu://chat/... flg=0x10000000 }
at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2200)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1839)
at android.app.Activity.startActivityForResult(Activity.java:5471)
at android.app.Activity.startActivityForResult(Activity.java:5429)
at android.app.Activity.startActivity(Activity.java:5927)
at android.app.Activity.startActivity(Activity.java:5894)
at com.onesignal.OneSignal.openDestinationActivity(OneSignal.java:2443)
at com.onesignal.OneSignal.handleNotificationOpen(OneSignal.java:2423)
at com.onesignal.NotificationOpenedProcessor.processIntent(NotificationOpenedProcessor.java:116)
at com.onesignal.NotificationOpenedProcessor.processFromContext(NotificationOpenedProcessor.java:64)
at com.onesignal.NotificationOpenedReceiverBase.onCreate(NotificationOpenedReceiverBase.kt:36)
at android.app.Activity.performCreate(Activity.java:8305)
at android.app.Activity.performCreate(Activity.java:8284)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3626)

### Steps to reproduce?

```Markdown
1. send notification via rest api: https://onesignal.com/api/v1/notifications
2. add deep link url via option "app_url" in the API
3. click on the notification received
4. App doesn't open since it got crashed with the above trace error.
```

### What did you expect to happen?

On click of notification it should open the app.

### OneSignal Android SDK version

"react-native-onesignal": "^4.0.6",

### Android version

13, 12, 11, 10

### Specific Android models

```Markdown
All android models
```

### Relevant log output

```Shell
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=cobu://chat/... flg=0x10000000 }
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3645)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7872)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=cobu://chat/... flg=0x10000000 }
at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2200)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1839)
at android.app.Activity.startActivityForResult(Activity.java:5471)
at android.app.Activity.startActivityForResult(Activity.java:5429)
at android.app.Activity.startActivity(Activity.java:5927)
at android.app.Activity.startActivity(Activity.java:5894)
at com.onesignal.OneSignal.openDestinationActivity(OneSignal.java:2443)
at com.onesignal.OneSignal.handleNotificationOpen(OneSignal.java:2423)
at com.onesignal.NotificationOpenedProcessor.processIntent(NotificationOpenedProcessor.java:116)
at com.onesignal.NotificationOpenedProcessor.processFromContext(NotificationOpenedProcessor.java:64)
at com.onesignal.NotificationOpenedReceiverBase.onCreate(NotificationOpenedReceiverBase.kt:36)
at android.app.Activity.performCreate(Activity.java:8305)
at android.app.Activity.performCreate(Activity.java:8284)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3626)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
@shivamCobu thank you for your patience! What is the app url you are using? It is likely invalid. We are working on a fix to prevent crashes when invalid launch URLs are provided.

Thanks!

**Comment by jennantilla** [comment]
Closing due to no response. We are tracking invalid launch url issue [here](https://github.com/OneSignal/OneSignal-Android-SDK/issues/1827).

Thanks!
