### ISSUE TITLE
[Bug]: android.view.WindowManager$BadTokenException - Unable to add window

### ISSUE THREAD

**Issue by albertoderodrigo** [OneSignal/OneSignal-Android-SDK#2014]
### What happened?

I see this error on firebase from your SDK

```
Fatal Exception: android.view.WindowManager$BadTokenException
Unable to add window -- token android.os.BinderProxy@8c472c5 is not valid; is your activity running?
```

This could help https://stackoverflow.com/questions/7811993/error-binderproxy45d459c0-is-not-valid-is-your-activity-running

Full log:

[io.socialgamesonline.slotcom_issue_e128821ca7d4cb21571b73e42c6bd165_crash_session_65E5B6C4004300016D57E2D4CA33E9FD_DNE_0_v2_stacktrace.txt](https://github.com/OneSignal/OneSignal-Android-SDK/files/14481743/io.socialgamesonline.slotcom_issue_e128821ca7d4cb21571b73e42c6bd165_crash_session_65E5B6C4004300016D57E2D4CA33E9FD_DNE_0_v2_stacktrace.txt)

### Steps to reproduce?

```Markdown
We are unable to reproduce it manually
```

### What did you expect to happen?

No errors

### OneSignal Android SDK version

5.1.6

### Android version

13, 12

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
@albertoderodrigo thank you for reporting; we'll look into this.

**Comment by yosefBazaart** [comment]
same here, only see it in Google's Play store vitals.
this is our top crash so please fix it. 

`Exception android.view.WindowManager$BadTokenException:
  at android.view.ViewRootImpl.setView (ViewRootImpl.java:1743)
  at android.view.WindowManagerGlobal.addView (WindowManagerGlobal.java:524)
  at android.view.WindowManagerImpl.addView (WindowManagerImpl.java:150)
  at android.app.Dialog.show (Dialog.java:512)
  at android.app.AlertDialog$Builder.show (AlertDialog.java:1153)
  at com.onesignal.core.internal.permissions.AlertDialogPrepromptForAndroidSettings.show (AlertDialogPrepromptForAndroidSettings.kt)
  at com.onesignal.notifications.internal.permissions.impl.NotificationPermissionController.showFallbackAlertDialog (NotificationPermissionController.kt)
  at com.onesignal.notifications.internal.permissions.impl.NotificationPermissionController.onReject (NotificationPermissionController.kt)
  at com.onesignal.core.activities.PermissionsActivity.onRequestPermissionsResult$lambda-0 (PermissionsActivity.kt)
  at android.os.Handler.handleCallback (Handler.java:958)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loopOnce (Looper.java:230)
  at android.os.Looper.loop (Looper.java:319)
  at android.app.ActivityThread.main (ActivityThread.java:8893)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:608)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1103)`

**Comment by yosefBazaart** [comment]
any news? this is our number 1 crash. please fix it.

**Comment by KChernenko** [comment]
We faced the same problem, and it's our number 1 crash as well (application with millions of active users). 
@jennantilla any updates on this?

**Comment by marclucraft** [comment]
Can you confirm whether you have tried updating to the [latest release](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.1.9), and if the issues persist?

Have you also reviewed #2048?

**Comment by KChernenko** [comment]
@marclucraft, we are using version 5.1.8. The fix for this issue is not mentioned in the changelog for 5.1.9.

**Comment by mrRedSun** [comment]
We receive many bug reports like this:

<details><summary>Stack trace</summary>
<p>

```
Fatal Exception: android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@316ca97 is not valid; is your activity running?
       at android.view.ViewRootImpl.setView(ViewRootImpl.java:1508)
       at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:426)
       at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:150)
       at android.app.Dialog.show(Dialog.java:370)
       at android.app.AlertDialog$Builder.show(AlertDialog.java:1137)
       at com.onesignal.core.internal.permissions.AlertDialogPrepromptForAndroidSettings.show(AlertDialogPrepromptForAndroidSettings.java:112)
       at com.onesignal.notifications.internal.permissions.impl.NotificationPermissionController.showFallbackAlertDialog(NotificationPermissionController.java:39)
       at com.onesignal.notifications.internal.permissions.impl.NotificationPermissionController.onReject(NotificationPermissionController.java:2)
       at com.onesignal.core.activities.PermissionsActivity.onRequestPermissionsResult$lambda-0(PermissionsActivity.java:76)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:257)
       at android.os.Looper.loop(Looper.java:368)
       at android.app.ActivityThread.main(ActivityThread.java:8826)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
```

</p>
</details> 

Currently running 5.1.3, upgraded to 5.1.6, will let you know if this is not resolved, and hopefully won't forget to tell you that it is

**Comment by yosefBazaart** [comment]
running `5.1.9` and still happens

**Comment by shukerullah** [comment]
I am using "react-native-onesignal": "^5.2.2".

```
Fatal Exception: android.view.WindowManager$BadTokenException
Unable to add window -- token android.os.BinderProxy@d90586b is not valid; is your activity running?

       Fatal Exception: android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@d90586b is not valid; is your activity running?
       at android.view.ViewRootImpl.setView(ViewRootImpl.java:1764)
       at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:567)
       at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:148)
       at android.app.Dialog.show(Dialog.java:521)
       at android.app.AlertDialog$Builder.show(AlertDialog.java:1153)
       at com.onesignal.core.internal.permissions.AlertDialogPrepromptForAndroidSettings.show(AlertDialogPrepromptForAndroidSettings.kt:68)
       at com.onesignal.notifications.internal.permissions.impl.NotificationPermissionController.showFallbackAlertDialog(NotificationPermissionController.kt:196)
       at com.onesignal.notifications.internal.permissions.impl.NotificationPermissionController.onReject(NotificationPermissionController.kt:182)
       at com.onesignal.core.activities.PermissionsActivity.onRequestPermissionsResult$lambda-0(PermissionsActivity.kt:114)
       at com.onesignal.core.activities.PermissionsActivity.$r8$lambda$_fGz_SOmbIhPQvxRD-41f99MrRo()
       at com.onesignal.core.activities.PermissionsActivity$$ExternalSyntheticLambda0.run(:4)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8762)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```
<img width="849" alt="Screenshot 2024-08-05 at 1 46 55 AM" src="https://github.com/user-attachments/assets/972d7024-0d82-46fa-8591-13572bfbc808">
<img width="985" alt="Screenshot 2024-08-05 at 1 44 38 AM" src="https://github.com/user-attachments/assets/e0bad016-dfdc-45a6-a1af-898318066536">
<img width="1126" alt="Screenshot 2024-08-05 at 1 45 33 AM" src="https://github.com/user-attachments/assets/27162327-e574-4557-8a39-5411888d3229">

**Comment by Sergeo-sel** [comment]
@marclucraft, Hi! Could you tell me what your plans are regarding this crash? The last four months this issue is the most significant crashe on my project.

**Comment by marclucraft** [comment]
@Sergeo-sel – Unfortunately, I am only part of the Support team at OneSignal and cannot answer your question.

@jennantilla – anything you can add to this?

**Comment by walkinrey** [comment]
any updates?

**Comment by jinliu9508** [comment]
A new release [5.1.24](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.1.24) is out and it will fix the crash. Please upgrade to our latest SDK version and let us know if you still see this error.
