### ISSUE TITLE
[ANR]: com.onesignal.core.internal.preferences.impl.PreferencesService.get

### ISSUE THREAD

**Issue by ayushi-sk** [OneSignal/OneSignal-Android-SDK#2045]
### What happened?

ANR

### Steps to reproduce?

```Markdown
Not reproducable
```

### What did you expect to happen?

![image](https://github.com/OneSignal/OneSignal-Android-SDK/assets/96478151/69dfdd17-72a3-4bdb-90bf-8d5797c2dc22)

### OneSignal Android SDK version

5.1.6

### Android version

13, 12, 11

### Specific Android models

```Markdown
All
```

### Relevant log output

```Shell
main (waiting):tid=1 systid=3213 
       at java.lang.Object.wait(Native method)
       at java.lang.Object.wait(Object.java:442)
       at java.lang.Object.wait(Object.java:568)
       at android.app.SharedPreferencesImpl.awaitLoadedLocked(SharedPreferencesImpl.java:279)
       at android.app.SharedPreferencesImpl.getString(SharedPreferencesImpl.java:301)
       at com.onesignal.core.internal.preferences.impl.PreferencesService.get(PreferencesService.kt:138)
       at com.onesignal.core.internal.preferences.impl.PreferencesService.getString(PreferencesService.kt:42)
       at com.onesignal.common.modeling.ModelStore.load(ModelStore.kt:159)
       at com.onesignal.common.modeling.SimpleModelStore.<init>(SimpleModelStore.kt:23)
       at com.onesignal.core.internal.config.ConfigModelStore.<init>(ConfigModelStore.kt:8)
       at java.lang.reflect.Constructor.newInstance0(Native method)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
       at com.onesignal.common.services.ServiceRegistrationReflection.resolve(ServiceRegistration.kt:89)
       at com.onesignal.common.services.ServiceProvider.getServiceOrNull(ServiceProvider.kt:79)
       at com.onesignal.common.services.ServiceProvider.getService(ServiceProvider.kt:67)
       at com.onesignal.common.services.ServiceProvider.getService$com_onesignal_core(ServiceProvider.kt:35)
       at com.onesignal.internal.OneSignalImp.initWithContext(OneSignalImp.kt:200)
       at com.onesignal.OneSignal.initWithContext(OneSignal.kt:208)
       at com.onesignal.notifications.receivers.FCMBroadcastReceiver.onReceive(FCMBroadcastReceiver.kt:26)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4376)
       at android.app.ActivityThread.access$1600(ActivityThread.java:257)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2103)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7911)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jinliu9508** [comment]
Hello @ayushi-sk, thank you for reporting. It appears that this ANR is caused by a deadlock when accessing SharedPreference upon receiving a notification. Could you please share the complete stack trace, including information on other threads that may potentially cause a deadlock?

**Comment by ArsalTech** [comment]
java.util.ArrayList$Itr.checkForComodification (ArrayList.java:1029)
java.util.ArrayList$Itr.next (ArrayList.java:982)
kotlin.collections.IndexingIterator.next (Iterators.kt:41)
kotlin.collections.IndexingIterator.next (Iterators.kt:38)
com.onesignal.core.internal.operations.impl.OperationRepo.loadSavedOperations$com_onesignal_core (OperationRepo.kt:413)
com.onesignal.core.internal.operations.impl.OperationRepo$start$1.invokeSuspend (OperationRepo.kt:112)
kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (ContinuationImpl.kt:33)
kotlinx.coroutines.DispatchedTask.run (DispatchedTask.kt:106)
java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:487)
java.util.concurrent.FutureTask.run (FutureTask.java:264)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run (ScheduledThreadPoolExecutor.java:307)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1145)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:644)
java.lang.Thread.run (Thread.java:1012)   i encounter that issue repeatedly in very big number of my app users . please solve this . i am using   implementation 'com.onesignal:OneSignal:[5.0.0, 5.99.99]'

**Comment by jinliu9508** [comment]
@ArsalTech This error is specific to version 5.1.11 and is fixed in 5.1.12. Please update the SDK version to 5.1.12 and let us know if the error still persists. https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.1.12

**Comment by aaaking** [comment]
> @ArsalTech This error is specific to version 5.1.11 and is fixed in 5.1.12. Please update the SDK version to 5.1.12 and let us know if the error still persists. https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.1.12

how do you solve this problem?  what is the commitid?
