### ISSUE TITLE
Fabric Issue: com.onesignal.OneSignal.removeNotificationOpenedHandler

### ISSUE THREAD

**Issue by pooi-pooi** [OneSignal/OneSignal-Android-SDK#206]
Hello guys, I got a crash on Fabric. Could you help me?

`onesignal-cordova-plugin 2.0.11 "OneSignal Push Notifications"`

```
OneSignal.java line 1337
com.onesignal.OneSignal.removeNotificationOpenedHandler

Fatal Exception: java.lang.RuntimeException: Unable to destroy activity {com.application/com.application.MainActivity}: java.lang.NullPointerException: Attempt to write to field 'com.onesignal.OneSignal$NotificationOpenedHandler com.onesignal.OneSignal$Builder.mNotificationOpenedHandler' on a null object reference
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5139)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5162)
       at android.app.ActivityThread.access$1700(ActivityThread.java:229)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1880)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7325)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by java.lang.NullPointerException: Attempt to write to field 'com.onesignal.OneSignal$NotificationOpenedHandler com.onesignal.OneSignal$Builder.mNotificationOpenedHandler' on a null object reference
```

Stack trace: 

[issue_7_crash_58E934D5025A000169BE54DD23EFFF60_047e15c1c0334851a5de1d9f91da8840_0_v1.txt](https://github.com/OneSignal/OneSignal-Android-SDK/files/913442/issue_7_crash_58E934D5025A000169BE54DD23EFFF60_047e15c1c0334851a5de1d9f91da8840_0_v1.txt)

[issue_7_crash_58ECCE7E016100017D4C5F03A1A2A274_d9e6080c4e6144d793800442b300924a_0_v1.txt](https://github.com/OneSignal/OneSignal-Android-SDK/files/913441/issue_7_crash_58ECCE7E016100017D4C5F03A1A2A274_d9e6080c4e6144d793800442b300924a_0_v1.txt)

**Comment by jkasten2** [comment]
@pooi-pooi This is due to OneSignal init not being called from the first page in your app and the app being closed. It will be fixed in the next SDK version.

There is a Cordova issue already open for this so below so close this one.
https://github.com/OneSignal/OneSignal-Cordova-SDK/issues/131
