### ISSUE TITLE
Notification Icon Creation Failure in OneSignal Integration [Bug]: 

### ISSUE THREAD

**Issue by Nass33m** [OneSignal/OneSignal-Android-SDK#2090]
### What happened?

We are experiencing a RemoteServiceException with the message "Bad notification posted from package..." followed by "Couldn't create icon". This issue seems to occur when trying to display notifications in our app, particularly when using OneSignal for push notifications. The error message indicates a failure in creating the notification icon, which leads to the app crashing.

### Steps to reproduce?

```Markdown
No idea of how to reproduce, in testing everything worked fine... but in production some users got this crash
```

### What did you expect to happen?

I believed that OneSignal handled the icon faillure/not existing in their code

### OneSignal Android SDK version

5.1.12

### Android version

13, 12

### Relevant log output

```Shell
Fatal Exception: android.app.RemoteServiceException: Bad notification posted from package com.XXXXX.XXXX.XXXX: Couldn't create icon: StatusBarIcon(icon=Icon(typ=RESOURCE pkg=com.XXXXX.XXXX.XXXX id=0x7f0700bc) visible user=0 )
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2204)
       at android.os.Handler.dispatchMessage(Handler.java:108)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7529)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment]
@Nass33m What icon format are you using? Do you use png icons?

**Comment by Nass33m** [comment]
@emawby Yes I use png icons (sorry for the late response).

**Comment by nan-li** [comment]
Hi @Nass33m , apologies your question has gone stale. We have made several SDK updates since this was reported. If this report is still relevant today, please open a new issue with updated details and we will get fresh eyes on it.

Thank you
