### ISSUE TITLE
[Bug]: Crash in com.onesignal.language.LanguageContext.getLanguage after calling pauseInAppMessages()

### ISSUE THREAD

**Issue by chokokatana** [OneSignal/OneSignal-Android-SDK#2105]
### What happened?

Got crash from user in the field who after reaching a certain part of the registration flow called `pauseInAppMessages(false)` to enable in app messages.

### Steps to reproduce?

```Markdown
No reproducible steps.
```

### What did you expect to happen?

No crash.

### OneSignal Android SDK version

4.8.9

### Android version

13

### Specific Android models

```Markdown
* It's actually Android version 14, but your selector only goes up to 13.
* Google Pixel 8
```

### Relevant log output

```Shell
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'java.lang.Object n3.c.H' on a null object reference in method 'java.lang.String com.onesignal.k0.r0(com.onesignal.l0)'
       at com.onesignal.language.LanguageContext.getLanguage(LanguageContext.java:38)
       at com.onesignal.OSInAppMessageController.variantIdForMessage(OSInAppMessageController.java:277)
       at com.onesignal.OSInAppMessageController.displayMessage(OSInAppMessageController.java:807)
       at com.onesignal.OSInAppMessageController.attemptToShowInAppMessage(OSInAppMessageController.java:649)
       at com.onesignal.OSInAppMessageController.queueMessageForDisplay(OSInAppMessageController.java:633)
       at com.onesignal.OSInAppMessageController.evaluateInAppMessages(OSInAppMessageController.java:270)
       at com.onesignal.OSInAppMessageController.setInAppMessagingEnabled(OSInAppMessageController.java:1029)
       at com.onesignal.OneSignal.pauseInAppMessages(OneSignal.java:3163)
       at com.geodb.wallace.utils.SlowSignal$Companion$activateInAppMessages$1$1$1.invokeSuspend(SlowSignal.kt:100)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
       at android.os.Handler.handleCallback(Handler.java:959)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loopOnce(Looper.java:232)
       at android.os.Looper.loop(Looper.java:317)
       at android.app.ActivityThread.main(ActivityThread.java:8501)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Thanks for reaching out @chokokatana! We'll look into this and get back to you as soon as possible.

**Comment by jkasten2** [comment]
@chokokatana do you call `OneSignal.setLanguage()` in your app?

Do you see this issue if you upgrade to the latest OneSignal-Android-SDK 5.x.x version?

**Comment by chokokatana** [comment]
- No
- Can't test.
