### ISSUE TITLE
[Bug]: com.onesignal.OneSignal$oneSignal$2.invoke ANR issue

### ISSUE THREAD

**Issue by catalin-zambalic-ma** [OneSignal/OneSignal-Android-SDK#2126]
### What happened?

ANR

### Steps to reproduce?

```Markdown
No reproduction steps.
```

### What did you expect to happen?

No ANR encountered.

### OneSignal Android SDK version

Unity OneSignal Android SDK v5.1.6

### Android version

12

### Specific Android models

```Markdown
Xiaomi Poco C50
```

### Relevant log output

```Shell
main (runnable):tid=1 systid=20940 
       at com.onesignal.OneSignal$oneSignal$2.invoke(OneSignal.kt:196)
       at com.onesignal.OneSignal$oneSignal$2.invoke(OneSignal.kt:195)
       at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
       at com.onesignal.OneSignal.getOneSignal(OneSignal.kt:195)
       at com.onesignal.OneSignal.initWithContext(OneSignal.kt:208)
       at com.onesignal.notifications.receivers.FCMBroadcastReceiver.onReceive(FCMBroadcastReceiver.kt:26)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4348)
       at android.app.ActivityThread.access$1700(ActivityThread.java:253)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2101)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7886)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:568)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkasten2** [comment]
@catalin-zambalic-ma can you let know the number of times you are seeing this ANR and or the percentages of devices?

Do you see any other ANR stacktraces with OneSignal in it?

**Comment by catalin-zambalic-ma** [comment]
I didn't found any other ANR stacktraces related to OneSignal.
Until now, looks like a rare case, we encountered it on a specific device, an looks that when the app was in background.
I will keep updated the thread with more data, in case I gather more info.
![image](https://github.com/OneSignal/OneSignal-Android-SDK/assets/155958200/bd02503a-b44f-4802-813d-a487452baa81)
