### ISSUE TITLE
NullPointException occur

### ISSUE THREAD

**Issue by katisia** [OneSignal/OneSignal-Android-SDK#215]
com.onesignal.OneSignalChromeTab$OneSignalCustomTabsServiceConnection.onCustomTabsServiceConnected (OneSignalChromeTab.java:99)
android.support.customtabs.CustomTabsServiceConnection.onServiceConnected (CustomTabsServiceConnection.java:32)

**Comment by poojagarje** [comment]
I am getting below error:

 java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.support.customtabs.CustomTabsSession.mayLaunchUrl(android.net.Uri, android.os.Bundle, java.util.List)' on a null object reference
                                                                       at com.onesignal.OneSignalChromeTab$OneSignalCustomTabsServiceConnection.onCustomTabsServiceConnected(OneSignalChromeTab.java:99)
                                                                       at android.support.customtabs.CustomTabsServiceConnection.onServiceConnected(CustomTabsServiceConnection.java:32)
                                                                       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1223)
                                                                       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1240)
                                                                       at android.os.Handler.handleCallback(Handler.java:746)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                       at android.os.Looper.loop(Looper.java:148)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Comment by jkasten2** [comment]
@katisia @poojagarje Thanks for reporting. Fixed in commit 39df04841e8f2a1afceffbc1b40713af919ee0d3 and will be included in the next release.

**Comment by mmarshak** [comment]
I also see this error, when the next release will be and what will be its number?

**Comment by jkasten2** [comment]
@mmarshak The fix was released in 3.5.1 on April 28th. 
https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/3.5.1

I recommend following `build.gradle` dependency entry to make sure you have the latest version.
``` 
compile 'com.onesignal:OneSignal:[3.5.3,4.0.0)'
```

**Comment by mmarshak** [comment]
I added to build.gradle and now I got a complain that I am mixing play-service 9.6.1 and 9.8.0.
Does your new build require version 9.8.0? My current app use 9.6.1.

**Comment by jkasten2** [comment]
@mmarshak I recommend upgrading to `play-service` `10.0.1` which will remove this warning as well.

If you need to stay on `9.6.1` you can exclude them and set your matching versions.
```Gradle
    compile('com.onesignal:OneSignal:[3.5.3,4.0.0)') {
       exclude group: 'com.google.android.gms', module: 'play-services-gcm'
       exclude group: 'com.google.android.gms', module: 'play-services-location'
    }

    compile "com.google.android.gms:play-services-gcm:9.6.1"
    compile "com.google.android.gms:play-services-location:9.6.1"
```

**Comment by mmarshak** [comment]
Thanks! This worked.
