### ISSUE TITLE
[Bug]: ANR initOneSignal

### ISSUE THREAD

**Issue by ayushi-sk** [OneSignal/OneSignal-Android-SDK#2161]
### What happened?

ANR happening on OneSignal init

### Steps to reproduce?

```Markdown
Initialise OneSignal from Application class in Android
```

### What did you expect to happen?

No ANRs

### OneSignal Android SDK version

5.1.2 and all others

### Android version

14, 13, 12

### Relevant log output

```Shell
main (runnable):tid=1 systid=19460 
#00 pc 0x5c074 libc.so (syscall + 32)
#01 pc 0x14a873 libart.so (art::ConditionVariable::WaitHoldingLocks(art::Thread*) + 82)
#02 pc 0x4492b1 libart.so (art::Thread::FullSuspendCheck() + 484)
#03 pc 0x4d6f77 libart.so (art::JniMethodFastEndWithReference(_jobject*, unsigned int, art::Thread*) + 122)
       at java.lang.reflect.Executable.getMethodNameInternal(Native method)
       at java.lang.reflect.Method.getName(Method.java:115)
       at java.lang.reflect.Method$1.compare(Method.java:72)
       at java.lang.reflect.Method$1.compare(Method.java:67)
       at java.util.TimSort.mergeHi(TimSort.java:837)
       at java.util.TimSort.mergeAt(TimSort.java:516)
       at java.util.TimSort.mergeCollapse(TimSort.java:441)
       at java.util.TimSort.sort(TimSort.java:245)
       at java.util.Arrays.sort(Arrays.java:1492)
       at java.util.ArrayList.sort(ArrayList.java:1470)
       at java.util.Collections.sort(Collections.java:206)
       at libcore.util.CollectionUtils.removeDuplicates(CollectionUtils.java:86)
       at java.lang.Class.getMethods(Class.java:1524)
       at com.onesignal.common.modeling.Model.initializeFromJson(Model.kt:98)
       at com.onesignal.common.modeling.SimpleModelStore.create(SimpleModelStore.kt:30)
       at com.onesignal.common.modeling.ModelStore.load(ModelStore.kt:168)
       at com.onesignal.common.modeling.SimpleModelStore.<init>(SimpleModelStore.kt:23)
       at com.onesignal.user.internal.subscriptions.SubscriptionModelStore.<init>(SubscriptionModelStore.kt:7)
       at java.lang.reflect.Constructor.newInstance0(Native method)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
       at com.onesignal.common.services.ServiceRegistrationReflection.resolve(ServiceRegistration.kt:89)
       at com.onesignal.common.services.ServiceProvider.getServiceOrNull(ServiceProvider.kt:79)
       at com.onesignal.common.services.ServiceProvider.getService(ServiceProvider.kt:67)
       at com.onesignal.common.services.ServiceRegistrationReflection.resolve(ServiceRegistration.kt:82)
       at com.onesignal.common.services.ServiceProvider.getServiceOrNull(ServiceProvider.kt:79)
       at com.onesignal.common.services.ServiceProvider.getService(ServiceProvider.kt:67)
       at com.onesignal.common.services.ServiceRegistrationReflection.resolve(ServiceRegistration.kt:82)
       at com.onesignal.common.services.ServiceProvider.getServiceOrNull(ServiceProvider.kt:79)
       at com.onesignal.common.services.ServiceProvider.getService(ServiceProvider.kt:67)
       at com.onesignal.common.services.ServiceProvider.getService$com_onesignal_core(ServiceProvider.kt:35)
       at com.onesignal.internal.OneSignalImp.initWithContext(OneSignalImp.kt:235)
       at com.onesignal.OneSignal.initWithContext(OneSignal.java:135)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jinliu9508** [comment]
Hello @ayushi-sk, thanks for reporting this issue to us. This ANR is a known problem. I recommend upgrading the SDK version to 5.1.19, which should significantly reduce its occurrence of this ANR if not completely eliminated. Please let us know if you experience this issue again.
