### ISSUE TITLE
[Bug]: Rash of ANRs coming from OneSignal SDK

### ISSUE THREAD

**Issue by isles1217** [OneSignal/OneSignal-Android-SDK#2176]
### What happened?

Based on the ANR analytics we're getting from Firebase Crashlytics, 18 of our top 25 ANRs are being attributed to OneSignal. This is putting our application in danger of crossing the "good-behavior" ANR threshold. Please don't dismiss this as something you can't reproduce (as I'm seeing in several other ANR-related open issues). I suspect there is some kind of systemic pattern of handling long-running or asynchronous operations in a way that's likely impacting the apps that use your SDK.

In the last 90 days, One Signal has gotten attributed to over 1k different ANRs (this is just counting our top 25 ANR sources).

### Steps to reproduce?

```Markdown
Monitor the ANR detection of a real production app, start seeing the ANRs.
```

### What did you expect to happen?

I would expect that this SDK would handle async and long running operations without causing ANRs. 

### OneSignal Android SDK version

5.1.14-5.1.17

### Android version

14, 13, 12, 11

### Specific Android models

```Markdown
All kinds of devices and models, lots of Samsungs and Motorolas. Mostly seeing Android 11-14, but that's likely indicative of normal distribution of OS's.
```

### Relevant log output

```Shell
Method calls that are being attributed to One Signal ANRs (in order of most occurring to least):

com.onesignal.common.modeling.Model.initializeFromJson (6 different permutations of this) 

com.onesignal.common.modeling.Model.initializeFromJson(Model.kt:98)
       at com.onesignal.core.internal.operations.impl.OperationModelStore.create(OperationModelStore.kt:68)
       at com.onesignal.core.internal.operations.impl.OperationModelStore.create(OperationModelStore.kt:30)
       at com.onesignal.common.modeling.ModelStore.load(ModelStore.kt:175)
       at com.onesignal.core.internal.operations.impl.OperationModelStore.loadOperations(OperationModelStore.kt)
       at com.onesignal.core.internal.operations.impl.OperationRepo.loadSavedOperations$com_onesignal_core(OperationRepo.kt:418)
       at com.onesignal.core.internal.operations.impl.OperationRepo$start$1.invokeSuspend(OperationRepo.kt:100)


com.onesignal.common.modeling.Model.getOptAnyProperty (8 different permutations of this)

com.onesignal.common.modeling.ModelStore.load (3 different permutations of this)

       at java.util.Collections$SynchronizedMap.get(Collections.java:2738)
       at com.onesignal.common.modeling.Model.getOptAnyProperty(Model.kt:648)
       at com.onesignal.common.modeling.Model.getOptStringProperty(Model.kt:565)
       at com.onesignal.common.modeling.Model.getStringProperty(Model.kt:491)
       at com.onesignal.common.modeling.Model.getStringProperty$default(Model.kt:488)
       at com.onesignal.common.modeling.Model.getId(Model.kt:59)
       at com.onesignal.common.modeling.ModelStore.load(ModelStore.kt:184)
       at com.onesignal.core.internal.operations.impl.OperationModelStore.loadOperations(OperationModelStore.kt)
       at com.onesignal.core.internal.operations.impl.OperationRepo.loadSavedOperations$com_onesignal_core(OperationRepo.kt:418)
       at com.onesignal.core.internal.operations.impl.OperationRepo$start$1.invokeSuspend(OperationRepo.kt:100)


com.onesignal.common.modeling.Model.getStringProperty

       at com.onesignal.common.modeling.Model.getStringProperty(Model.kt)
       at com.onesignal.common.modeling.Model.getStringProperty$default(Model.kt)
       at com.onesignal.common.modeling.Model.getId(Model.kt)
       at com.onesignal.common.modeling.ModelStore.load(ModelStore.kt)
       at com.onesignal.core.internal.operations.impl.OperationModelStore.loadOperations(OperationModelStore.kt)
       at com.onesignal.core.internal.operations.impl.OperationRepo.loadSavedOperations$com_onesignal_core(OperationRepo.kt)
       at com.onesignal.core.internal.operations.impl.OperationRepo$start$1.invokeSuspend(OperationRepo.kt)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by michael-winkler** [comment]
You should really update to latest version 5.1.20

**Comment by jinliu9508** [comment]
Hello @isles1217, these ANRs are identified and fixed. Please update to the latest version 5.1.20 and that should eliminate most of the ANRs if not all.

**Comment by isles1217** [comment]
@jinliu9508 I'm still seeing about the same number of ANRs in recent app versions running 5.1.20. Can you look into this further?
