### ISSUE TITLE
[Bug]: Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0

### ISSUE THREAD

**Issue by LevGloba** [OneSignal/OneSignal-Android-SDK#2201]
### What happened?

When the application starts, from com.onesignal.core.activities.PermissionsActivity.onRequestPermissionsResult returns: Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0

### Steps to reproduce?

```Markdown
Launch the app on the device
```

### What did you expect to happen?

Expected the app to have a dialog fragment asking for permission to provide notifications

### OneSignal Android SDK version

5.1.18

### Android version

13

### Specific Android models

```Markdown
Camon 19
```

### Relevant log output

```Shell
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
       at com.onesignal.core.activities.PermissionsActivity.onRequestPermissionsResult$lambda-0(PermissionsActivity.kt:101)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:204)
       at android.os.Looper.loop(Looper.java:291)
       at android.app.ActivityThread.main(ActivityThread.java:8134)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:601)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1136)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jinliu9508** [comment]
Hi @LevGloba, this is a known issue occurring in version 5.1.18 and has been fixed in version 5.1.21. I recommend upgrade to the latest SDK version, and the issue should be resolved.
