### ISSUE TITLE
[Bug]: NullPointerException in PermissionsActivity.reregisterCallbackHandlers

### ISSUE THREAD

**Issue by koral--** [OneSignal/OneSignal-Android-SDK#2215]
### What happened?

App crashed due to the exception attached in the log.

It seems that the issue is here: https://github.com/OneSignal/OneSignal-Android-SDK/blob/main/OneSignalSDK/onesignal/core/src/main/java/com/onesignal/core/activities/PermissionsActivity.kt#L58
and `extras` turned out to be null.
At the line above the affected one there is a nullable parameter: https://github.com/OneSignal/OneSignal-Android-SDK/blob/main/OneSignalSDK/onesignal/core/src/main/java/com/onesignal/core/activities/PermissionsActivity.kt#L57

Regardless of the root cause it does not make sense to have a nullable parameter and then immediately use a non-null assertion operator on it. The parameter should be either non-nullable or there should be a nullcheck.

### Steps to reproduce?

```Markdown
Unknown, it's an automated crash report.
From the stacktrace I guess it is related to app start.
```

### What did you expect to happen?

No crash.

### OneSignal Android SDK version

5.1.23

### Android version

12

### Specific Android models

```Markdown
* Pixel 3a
```

### Relevant log output

```Shell
java.lang.RuntimeException: Unable to start activity ComponentInfo{<stripped app id>/com.onesignal.core.activities.PermissionsActivity}: java.lang.NullPointerException
    android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3635)

(stripped stacktrace entries from android framework)

Caused by: java.lang.NullPointerException: 
    com.onesignal.core.activities.PermissionsActivity.reregisterCallbackHandlers(PermissionsActivity.kt)
    com.onesignal.core.activities.PermissionsActivity.handleBundleParams(PermissionsActivity.kt)
    com.onesignal.core.activities.PermissionsActivity.onCreate(PermissionsActivity.kt:32)
    android.app.Activity.performCreate(Activity.java:8051)

(stripped stacktrace entries from android framework)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yeldar-nurpeissov** [comment]
Hello, is there currently a fix available for this issue?

**Comment by yeldar-nurpeissov** [comment]
Hi, thanks for following up.

This was during closed testing on Google Play Console with community testers to get production access.
On Firebase, I see 3 crashes in one release and 1 crash on the latest release, with 2–3 releases in between those occurrences.
The crash report screenshots I’ve attached correspond to these occurrences.

Device Model: OnePlus8Pro.
OS: Android 11.

<img width="1142" height="292" alt="Image" src="https://github.com/user-attachments/assets/8fb7af60-f431-4fb7-8484-9d83d7a1053e" />
<img width="1128" height="285" alt="Image" src="https://github.com/user-attachments/assets/4de73725-197f-43ec-afe5-5914adb98269" />
<img width="1157" height="292" alt="Image" src="https://github.com/user-attachments/assets/12092749-fda2-4f0f-923d-50cb9af74ad5" />
<img width="1208" height="302" alt="Image" src="https://github.com/user-attachments/assets/4229c707-ae44-4425-9fae-5a0c02027cb5" />


**The full crash text here:**
`
          Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{yeldar.nurpeissov.kelink/com.onesignal.core.activities.PermissionsActivity}: java.lang.NullPointerException
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3433)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3607)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2068)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7680)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:423)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
        `

**Comment by koral--** [comment]
It was in Nov 2024, but from what I recall:

> Are you able to confirm if this is occurring to an actual user?

Yes. It wasn't a play store robot.

> Did this occur shortly after a new upload to the Play Store?

No.

> Are you still seeing this crash occur repeatedly?

No occurrences in the retention window I have access to.

**Comment by nan-li** [comment]
Thanks all for your followups. We released a fix for this in [Android SDK 5.1.36](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/5.1.36). Please let us know if are experiencing any further issues after upgrade.
