### ISSUE TITLE
[Bug]: ANR during SDK Initialization

### ISSUE THREAD

**Issue by maximkir-fl** [OneSignal/OneSignal-Android-SDK#2226]
### What happened?

My code follows the integration instructions and initializes the OneSignal SDK during `Application.onCreate`.
After upgrading to version 5.1.25, I saw the following ANR, originating from the initialization process.

```java
main (runnable):tid=1 systid=22401 
at com.onesignal.common.events.EventProducer.access$getSubscribers$p(EventProducer.kt)
at com.onesignal.common.events.EventProducer.<init>(EventProducer.kt)
at com.onesignal.core.internal.application.impl.ApplicationService.<init>(ApplicationService.kt:31)
at java.lang.reflect.Constructor.newInstance0(Native method)
at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
at com.onesignal.common.services.ServiceRegistrationReflection.resolve(ServiceRegistration.kt:89)
at com.onesignal.common.services.ServiceProvider.getServiceOrNull(ServiceProvider.kt:79)
at com.onesignal.common.services.ServiceProvider.getService(ServiceProvider.kt:67)
at com.onesignal.common.services.ServiceProvider.getService$com_onesignal_core(ServiceProvider.kt:35)
at com.onesignal.internal.OneSignalImp.initWithContext(OneSignalImp.kt:203)
at com.onesignal.OneSignal.initWithContext(OneSignal.java:135)
at com.myapp.app.Application.onCreate(Application.kt:17)
```

### Steps to reproduce?

```Markdown
1. Follow integration instructions and run the application
```

### What did you expect to happen?

Smooth background initialization.

### OneSignal Android SDK version

5.1.25

### Android version

14

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jinliu9508** [comment]
Hello @maximkir-fl, thank you for reporting to us! To help us better understanding your issue, could you post the code where you call OneSignal.initWithContext?

**Comment by maximkir-fl** [comment]
Sure, here it is:
``` kotlin
import android.app.Application
import com.onesignal.OneSignal

open class Application : Application() {
    override fun onCreate() {
        super.onCreate()
        OneSignal.initWithContext(this, getString(R.string.one_signal_app_id))
    }
}
```

**Comment by jinliu9508** [comment]
I don't see any issues with your code here, assuming the app ID is valid. Are you able to reliably reproduce this ANR? If not, have you noticed any specific pattern when this ANR occurs? Also, have you implemented any OneSignal lifecycle listener?

**Comment by maximkir-fl** [comment]
I did not implement any lifecycle listeners.
My previous version was `5.1.22`, where we experienced app crashes due to https://github.com/OneSignal/OneSignal-Android-SDK/pull/2212

Once updated to `5.1.25` the ANRs started to show up.

**Comment by jinliu9508** [comment]
@maximkir-fl The stack trace is from the runnable main thread and did not suggest what is blocking it. Could you paste the complete stack trace that shows where the thread has been blocked?

**Comment by ayushi-sk** [comment]
main (runnable):tid=1 systid=14218 
#00 pc 0x474289 libart.so (art::DumpNativeStack + 120) (BuildId: d808a4632ec52b3694263adbd3626ecc)
#01 pc 0x51e3a7 libart.so (art::Thread::DumpStack const + 222) (BuildId: d808a4632ec52b3694263adbd3626ecc)
#02 pc 0x535f81 libart.so (art::DumpCheckpoint::Run + 664) (BuildId: d808a4632ec52b3694263adbd3626ecc)
#03 pc 0x51ee43 libart.so (art::Thread::RunCheckpointFunction + 134) (BuildId: d808a4632ec52b3694263adbd3626ecc)
#04 pc 0x2459f5 libart.so (art::Thread::CheckSuspend + 52) (BuildId: d808a4632ec52b3694263adbd3626ecc)
#05 pc 0x22ef83 libart.so (art::ClassLinker::InitializeClass + 790) (BuildId: d808a4632ec52b3694263adbd3626ecc)
#06 pc 0x215d99 libart.so (art::ClassLinker::EnsureInitialized + 84) (BuildId: d808a4632ec52b3694263adbd3626ecc)
#07 pc 0x463135 libart.so (art::Constructor_newInstance0  + 188) (BuildId: d808a4632ec52b3694263adbd3626ecc)
       at java.lang.reflect.Constructor.newInstance0(Native method)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
       at com.onesignal.common.services.ServiceRegistrationReflection.resolve(ServiceRegistration.kt:89)
       at com.onesignal.common.services.ServiceProvider.getAllServices(ServiceProvider.kt:55)
       at com.onesignal.common.services.ServiceRegistrationReflection.resolve(ServiceRegistration.kt:72)
       at com.onesignal.common.services.ServiceProvider.getServiceOrNull(ServiceProvider.kt:79)
       at com.onesignal.common.services.ServiceProvider.getService(ServiceProvider.kt:67)
       at com.onesignal.common.services.ServiceProvider.getService$com_onesignal_core(ServiceProvider.kt:35)
       at com.onesignal.internal.OneSignalImp.initWithContext(OneSignalImp.kt:212)
       at com.onesignal.OneSignal.initWithContext(OneSignal.java:135)
       at cricket.live.line.App.initOneSignal(App.kt:60)
       at cricket.live.line.App.onCreate(App.kt:32)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1266)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6826)
       at android.app.ActivityThread.-$$Nest$mhandleBindApplication(unavailable)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2171)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7941)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:569)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)

**Comment by ayushi-sk** [comment]
Possible Causes - 
- The log shows art::ClassLinker::InitializeClass, meaning OneSignal might be loading classes synchronously on the main thread, causing the freeze.
- com.onesignal.common.services.ServiceRegistrationReflection.resolve() suggests that OneSignal is using reflection, which can be slow.

**Comment by jinliu9508** [comment]
5.1.31 has a fix targeting ANRs, I would recommend upgrading to the latest version and please let us know if this still happens.
