### ISSUE TITLE
[Bug]: ANRs coming from com.onesignal.common.modeling.Model.initializeFromJson

### ISSUE THREAD

**Issue by isles1217** [OneSignal/OneSignal-Android-SDK#2236]
### What happened?

This is a follow up issue to #2230. A bulk of our ANRs have been fixed following the release of 5.1.26, but I'm still seeing ANRs with one particular stack trace. We really appreciate the work on reducing these ANRs, and I'm hoping this particular trace gets rid of the last major culprit. Thanks for the improvements so far!

### Steps to reproduce?

```Markdown
See stack trace / log output
```

### What did you expect to happen?

OneSignal to not block the main thread

### OneSignal Android SDK version

5.1.26

### Android version

13, 12, 11

### Specific Android models

```Markdown
Any
```

### Relevant log output

```Shell
com.onesignal.common.modeling.Model.initializeFromJson
ANR triggered by slow operations in blamed thread

OpRepo (runnable):
          OpRepo (runnable):tid=57 systid=18118 
#00 pc 0x4a7ee8 libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, BacktraceMap*, char const*, art::ArtMethod*, void*, bool) + 140)
#01 pc 0x5b59dc libart.so (art::Thread::DumpStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool, BacktraceMap*, bool) const + 376)
#02 pc 0x5d2b14 libart.so (art::DumpCheckpoint::Run(art::Thread*) + 924)
#03 pc 0x5b6910 libart.so (art::Thread::RunCheckpointFunction() + 176)
#04 pc 0x6739fc libart.so (art::JniMethodFastEndWithReference(_jobject*, unsigned int, art::Thread*) + 112)
       at java.lang.reflect.Executable.getMethodNameInternal(Native method)
       at java.lang.reflect.Method.getName(Method.java:115)
       at java.lang.reflect.Method$1.compare(Method.java:72)
       at java.lang.reflect.Method$1.compare(Method.java:67)
       at libcore.util.CollectionUtils.removeDuplicates(CollectionUtils.java:89)
       at java.lang.Class.getMethods(Class.java:1493)
       at com.onesignal.common.modeling.Model.initializeFromJson(Model.kt)
       at com.onesignal.core.internal.operations.impl.OperationModelStore.create(OperationModelStore.kt:67)
       at com.onesignal.core.internal.operations.impl.OperationModelStore.create(OperationModelStore.kt:30)
       at com.onesignal.common.modeling.ModelStore.load(ModelStore.kt)
       at com.onesignal.core.internal.operations.impl.OperationModelStore.loadOperations(OperationModelStore.kt)
       at com.onesignal.core.internal.operations.impl.OperationRepo.loadSavedOperations$com_onesignal_core(OperationRepo.kt)
       at com.onesignal.core.internal.operations.impl.OperationRepo$start$1.invokeSuspend(OperationRepo.kt)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)

main (blocked)
tid=1 systid=18010 | waiting to lock <0x059286bb> (java.util.ArrayList) held by thread 57
          main (blocked):tid=1 systid=18010 | waiting to lock <0x059286bb> (java.util.ArrayList) held by thread 57
       at com.onesignal.common.modeling.ModelStore.add(ModelStore.kt:45)
       at com.onesignal.common.modeling.IModelStore$DefaultImpls.add$default(IModelStore.kt:36)
       at com.onesignal.core.internal.operations.impl.OperationRepo.internalEnqueue(OperationRepo.kt)
       at com.onesignal.core.internal.operations.impl.OperationRepo.internalEnqueue$default(OperationRepo.kt)
       at com.onesignal.core.internal.operations.impl.OperationRepo.enqueue(OperationRepo.kt)
       at com.onesignal.session.internal.session.impl.SessionListener.onSessionStarted(SessionListener.kt)
       at com.onesignal.session.internal.session.impl.SessionService$onFocus$1.invoke(SessionService.kt:107)
       at com.onesignal.session.internal.session.impl.SessionService$onFocus$1.invoke(SessionService.kt:107)
       at com.onesignal.common.events.EventProducer.fire(EventProducer.kt)
       at com.onesignal.session.internal.session.impl.SessionService.onFocus(SessionService.kt)
       at com.onesignal.core.internal.application.impl.ApplicationService$handleFocus$1.invoke(ApplicationService.kt:395)
       at com.onesignal.core.internal.application.impl.ApplicationService$handleFocus$1.invoke(ApplicationService.kt:395)
       at com.onesignal.common.events.EventProducer.fire(EventProducer.kt)
       at com.onesignal.core.internal.application.impl.ApplicationService.handleFocus(ApplicationService.kt)
       at com.onesignal.core.internal.application.impl.ApplicationService.onActivityStarted(ApplicationService.kt)
       at android.app.Application.dispatchActivityStarted(Application.java:425)
       at android.app.Activity.dispatchActivityStarted(Activity.java:1382)
       at android.app.Activity.onStart(Activity.java:1873)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
       at android.app.Activity.performStart(Activity.java:8231)
       at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3872)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8653)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jinliu9508** [comment]
@isles1217 Great to hear that bulks of ANRs have been resolved in our latest release! We are currently investigating this particular stack trace and will provide an update once a new release is available.

**Comment by jinliu9508** [comment]
@isles1217 The stack trace indicates that the operation is enqueuing and waiting on the main thread. However, the 5.1.26 release has moved this step to the background thread. Could you double-check that this isn't happening in your latest version? Additionally, could you provide another stack trace that includes line numbers for these lines of code?
`main (blocked)
tid=1 systid=18010 | waiting to lock <0x059286bb> (java.util.ArrayList) held by thread 57
          main (blocked):tid=1 systid=18010 | waiting to lock <0x059286bb> (java.util.ArrayList) held by thread 57
       at com.onesignal.common.modeling.ModelStore.add(ModelStore.kt:45)
       at com.onesignal.common.modeling.IModelStore$DefaultImpls.add$default(IModelStore.kt:36)
       at com.onesignal.core.internal.operations.impl.OperationRepo.internalEnqueue(OperationRepo.kt)
       at com.onesignal.core.internal.operations.impl.OperationRepo.internalEnqueue$default(OperationRepo.kt)
       at com.onesignal.core.internal.operations.impl.OperationRepo.enqueue(OperationRepo.kt)`

**Comment by lemeshkevich** [comment]
We have a similar ANR:

```main (runnable):tid=1 systid=22519 
#00 pc 0x474289 libart.so (art::DumpNativeStack + 120) (BuildId: 26957a0c04d227e2ae43f21dd5010097)
#01 pc 0x51e3a7 libart.so (art::Thread::DumpStack const + 222) (BuildId: 26957a0c04d227e2ae43f21dd5010097)
#02 pc 0x535f81 libart.so (art::DumpCheckpoint::Run + 664) (BuildId: 26957a0c04d227e2ae43f21dd5010097)
#03 pc 0x51ee43 libart.so (art::Thread::RunCheckpointFunction + 134) (BuildId: 26957a0c04d227e2ae43f21dd5010097)
#04 pc 0x59df1f libart.so (artTestSuspendFromCode + 38) (BuildId: 26957a0c04d227e2ae43f21dd5010097)
#05 pc 0xabbe1 libart.so (art_quick_test_suspend + 32) (BuildId: 26957a0c04d227e2ae43f21dd5010097)
       at java.lang.reflect.Executable.getMethodNameInternal(Native method)
       at java.lang.reflect.Method.getName(Method.java:115)
       at java.lang.reflect.Method$1.compare(Method.java:72)
       at java.lang.reflect.Method$1.compare(Method.java:67)
       at java.util.TimSort.countRunAndMakeAscending(TimSort.java:360)
       at java.util.TimSort.sort(TimSort.java:234)
       at java.util.Arrays.sort(Arrays.java:1351)
       at java.util.ArrayList.sort(ArrayList.java:1821)
       at java.util.Collections.sort(Collections.java:207)
       at libcore.util.CollectionUtils.removeDuplicates(CollectionUtils.java:86)
       at java.lang.Class.getMethods(Class.java:2226)
       at com.onesignal.common.modeling.Model.initializeFromJson(Model.kt:98)
       at com.onesignal.common.modeling.SimpleModelStore.create(SimpleModelStore.kt:30)
       at com.onesignal.common.modeling.ModelStore.load(ModelStore.kt:175)
       at com.onesignal.common.modeling.SimpleModelStore.<init>(SimpleModelStore.kt:23)
       at com.onesignal.core.internal.config.ConfigModelStore.<init>(ConfigModelStore.kt:8)
       at java.lang.reflect.Constructor.newInstance0(Native method)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
       at com.onesignal.common.services.ServiceRegistrationReflection.resolve(ServiceRegistration.kt:89)
       at com.onesignal.common.services.ServiceProvider.getServiceOrNull(ServiceProvider.kt:79)
       at com.onesignal.common.services.ServiceProvider.getService(ServiceProvider.kt:67)
       at com.onesignal.common.services.ServiceProvider.getService$com_onesignal_core(ServiceProvider.kt:35)
       at com.onesignal.internal.OneSignalImp.initWithContext(OneSignalImp.kt:210)
       at com.onesignal.OneSignal.initWithContext(OneSignal.kt:135)
       at com.appsulove.threetiles.initializer.impl.OneSignalInitializer.initialize(OneSignalInitializer.kt:47)
       at com.appsulove.threetiles.initializer.AppInitializer.initialize(AppInitializer.kt:147)
       at com.appsulove.threetiles.core.App.safedk_App_onCreate_c914bafb536334ded5ee2f0f7ad9ccc9(App.kt:26)
       at com.appsulove.threetiles.core.App.onCreate(App.kt:30)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1316)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7080)
       at android.app.ActivityThread.-$$Nest$mhandleBindApplication(unavailable)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2262)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:205)
       at android.os.Looper.loop(Looper.java:294)
       at android.app.ActivityThread.main(ActivityThread.java:8271)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

**Comment by jinliu9508** [comment]
Another fix related to this issue has been released in 5.1.31. Please upgrade to this version if you are seeing this issue.
