### ISSUE TITLE
OneSignal.init() crashes in Jellybean devices after latest release

### ISSUE THREAD

**Issue by Eldho93** [OneSignal/OneSignal-Android-SDK#226]
There is this error in the init().
```Java
java.lang.ExceptionInInitializerError
Caused by: java.lang.NoClassDefFoundError: com.onesignal.AdvertisingIdProviderGPS
```

**Comment by Eldho93** [comment]
Sorry its actually not working in all pre-lollipop devices.

**Comment by jkasten2** [comment]
@Eldho93 Could you provide the full stack trace as well? It should include line numbers.

Also please include the the version of the "Google Play services" app on the device as well as the "Google Play services library" (GMS) that you are using in your project.

**Comment by Eldho93** [comment]
We fixed this error installing multidex in the application class using this code.

    @Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);
        MultiDex.install(this);
    }

However is removing this code, the application crashes is pre lollipop devices.
We are using compilesdk version 25,targetsdkversion 25 and buildtools version 25.0.2
The play services version is 10.2.0

classpath 'com.google.gms:google-services:3.0.0'

compile 'com.google.android.gms:play-services-gcm:10.2.0'
compile 'com.google.android.gms:play-services-location:10.2.0'

Proguard is enabled but the app is in the debug mode so that doesnt come in to play i guess. 

Here is the full logcat. 

05-10 09:52:18.527 9349-9349/com.chillarcards.campuswallet D/dalvikvm: VFY: replacing opcode 0x6e at 0x0011
05-10 09:52:18.537 9349-9349/com.chillarcards.campuswallet D/dalvikvm: DexOpt: unable to opt direct call 0xd9c9 at 0x15 in Lcom/onesignal/OneSignal;.<clinit>
05-10 09:52:18.537 9349-9349/com.chillarcards.campuswallet D/dalvikvm: DexOpt: unable to opt direct call 0xda61 at 0x72 in Lcom/onesignal/OneSignal;.Log
05-10 09:52:18.537 9349-9349/com.chillarcards.campuswallet D/dalvikvm: DexOpt: unable to opt direct call 0xda66 at 0x06 in Lcom/onesignal/OneSignal;.fireIdsAvailableCallback
05-10 09:52:18.537 9349-9349/com.chillarcards.campuswallet D/dalvikvm: DexOpt: unable to opt direct call 0xda5b at 0x02 in Lcom/onesignal/OneSignal;.fireNotificationOpenedHandler
05-10 09:52:18.537 9349-9349/com.chillarcards.campuswallet D/dalvikvm: DexOpt: unable to opt direct call 0xda34 at 0x90 in Lcom/onesignal/OneSignal;.generateOsNotificationOpenResult
05-10 09:52:18.537 9349-9349/com.chillarcards.campuswallet I/dalvikvm: DexOpt: unable to optimize instance field ref 0x79d9 at 0x97 in Lcom/onesignal/OneSignal;.generateOsNotificationOpenResult
05-10 09:52:18.537 9349-9349/com.chillarcards.campuswallet I/dalvikvm: DexOpt: unable to optimize static field ref 0x79d7 at 0x9d in Lcom/onesignal/OneSignal;.generateOsNotificationOpenResult
05-10 09:52:18.537 9349-9349/com.chillarcards.campuswallet I/dalvikvm: DexOpt: unable to optimize instance field ref 0x79da at 0x9f in Lcom/onesignal/OneSignal;.generateOsNotificationOpenResult
05-10 09:52:18.537 9349-9349/com.chillarcards.campuswallet I/dalvikvm: DexOpt: unable to optimize static field ref 0x79cf at 0xa5 in Lcom/onesignal/OneSignal;.generateOsNotificationOpenResult
05-10 09:52:18.537 9349-9349/com.chillarcards.campuswallet I/dalvikvm: DexOpt: unable to optimize static field ref 0x79d8 at 0xaa in Lcom/onesignal/OneSignal;.generateOsNotificationOpenResult
05-10 09:52:18.537 9349-9349/com.chillarcards.campuswallet I/dalvikvm: DexOpt: unable to optimize static field ref 0x79d0 at 0xaf in Lcom/onesignal/OneSignal;.generateOsNotificationOpenResult
05-10 09:52:18.537 9349-9349/com.chillarcards.campuswallet D/dalvikvm: DexOpt: unable to opt direct call 0xda48 at 0x0b in Lcom/onesignal/OneSignal;.getCurrentPermissionState
05-10 09:52:18.537 9349-9349/com.chillarcards.campuswallet I/dalvikvm: DexOpt: unable to optimize instance field ref 0x79fb at 0x12 in Lcom/onesignal/OneSignal;.getCurrentPermissionState
05-10 09:52:18.537 9349-9349/com.chillarcards.campuswallet D/dalvikvm: DexOpt: unable to opt direct call 0xda45 at 0x16 in Lcom/onesignal/OneSignal;.getCurrentPermissionState
05-10 09:52:18.537 9349-9349/com.chillarcards.campuswallet D/dalvikvm: DexOpt: unable to opt direct call 0xda4f at 0x13 in Lcom/onesignal/OneSignal;.getCurrentSubscriptionState
05-10 09:52:18.537 9349-9349/com.chillarcards.campuswallet I/dalvikvm: DexOpt: unable to optimize instance field ref 0x79fb at 0x1c in Lcom/onesignal/OneSignal;.getCurrentSubscriptionState
05-10 09:52:18.537 9349-9349/com.chillarcards.campuswallet I/dalvikvm: DexOpt: unable to optimize instance field ref 0x79fe at 0x25 in Lcom/onesignal/OneSignal;.getCurrentSubscriptionState
05-10 09:52:18.537 9349-9349/com.chillarcards.campuswallet D/dalvikvm: DexOpt: unable to opt direct call 0xda4d at 0x29 in Lcom/onesignal/OneSignal;.getCurrentSubscriptionState
05-10 09:52:18.537 9349-9349/com.chillarcards.campuswallet D/dalvikvm: DexOpt: unable to opt direct call 0xda48 at 0x0b in Lcom/onesignal/OneSignal;.getLastPermissionState
05-10 09:52:18.537 9349-9349/com.chillarcards.campuswallet D/dalvikvm: DexOpt: unable to opt direct call 0xda4f at 0x0c in Lcom/onesignal/OneSignal;.getLastSubscriptionState
05-10 09:52:18.537 9349-9349/com.chillarcards.campuswallet D/dalvikvm: DexOpt: unable to opt direct call 0xda41 at 0x0a in Lcom/onesignal/OneSignal;.getPermissionStateChangesObserver
05-10 09:52:18.537 9349-9349/com.chillarcards.campuswallet D/dalvikvm: DexOpt: unable to opt direct call 0xda4c at 0x10 in Lcom/onesignal/OneSignal;.getPermissionSubscriptionState
05-10 09:52:18.537 9349-9349/com.chillarcards.campuswallet I/dalvikvm: DexOpt: unable to optimize instance field ref 0x79fd at 0x19 in Lcom/onesignal/OneSignal;.getPermissionSubscriptionState
05-10 09:52:18.537 9349-9349/com.chillarcards.campuswallet I/dalvikvm: DexOpt: unable to optimize instance field ref 0x79fc at 0x21 in Lcom/onesignal/OneSignal;.getPermissionSubscriptionState
05-10 09:52:18.537 9349-9349/com.chillarcards.campuswallet D/dalvikvm: DexOpt: unable to opt direct call 0xda41 at 0x0a in Lcom/onesignal/OneSignal;.getSubscriptionStateChangesObserver
05-10 09:52:18.537 9349-9349/com.chillarcards.campuswallet D/dalvikvm: DexOpt: unable to opt direct call 0xda53 at 0x1c in Lcom/onesignal/OneSignal;.init
05-10 09:52:18.547 9349-9349/com.chillarcards.campuswallet D/dalvikvm: DexOpt: unable to opt direct call 0xd9c7 at 0x88 in Lcom/onesignal/OneSignal;.init
05-10 09:52:18.547 9349-9349/com.chillarcards.campuswallet D/dalvikvm: DexOpt: unable to opt direct call 0xdb6c at 0x98 in Lcom/onesignal/OneSignal;.init
05-10 09:52:18.547 9349-9349/com.chillarcards.campuswallet D/dalvikvm: DexOpt: unable to opt direct call 0xdb6e at 0xf3 in Lcom/onesignal/OneSignal;.init
05-10 09:52:18.547 9349-9349/com.chillarcards.campuswallet D/dalvikvm: DexOpt: unable to opt direct call 0xda65 at 0x07 in Lcom/onesignal/OneSignal;.internalFireGetTagsCallback
05-10 09:52:18.547 9349-9349/com.chillarcards.campuswallet D/dalvikvm: DexOpt: unable to opt direct call 0xda60 at 0x0a in Lcom/onesignal/OneSignal;.makeAndroidParamsRequest
05-10 09:52:18.547 9349-9349/com.chillarcards.campuswallet D/dalvikvm: DexOpt: unable to opt direct call 0xda5c at 0x66 in Lcom/onesignal/OneSignal;.notificationOpenedRESTCall
05-10 09:52:18.547 9349-9349/com.chillarcards.campuswallet D/dalvikvm: DexOpt: unable to opt direct call 0xda64 at 0x18 in Lcom/onesignal/OneSignal;.postNotification
05-10 09:52:18.547 9349-9349/com.chillarcards.campuswallet D/dalvikvm: DexOpt: unable to opt direct call 0xda5d at 0x12 in Lcom/onesignal/OneSignal;.promptLocation
05-10 09:52:18.547 9349-9349/com.chillarcards.campuswallet D/dalvikvm: DexOpt: unable to opt direct call 0xdb57 at 0x07 in Lcom/onesignal/OneSignal;.registerForPushToken
05-10 09:52:18.547 9349-9349/com.chillarcards.campuswallet D/dalvikvm: DexOpt: unable to opt direct call 0xda5f at 0x10 in Lcom/onesignal/OneSignal;.registerForPushToken
05-10 09:52:18.547 9349-9349/com.chillarcards.campuswallet D/dalvikvm: DexOpt: unable to opt direct call 0xdb58 at 0x19 in Lcom/onesignal/OneSignal;.registerForPushToken
05-10 09:52:18.547 9349-9349/com.chillarcards.campuswallet D/dalvikvm: DexOpt: unable to opt direct call 0xda63 at 0x46 in Lcom/onesignal/OneSignal;.registerUser
05-10 09:52:18.547 9349-9349/com.chillarcards.campuswallet D/dalvikvm: DexOpt: unable to opt direct call 0xda62 at 0x47 in Lcom/onesignal/OneSignal;.sendOnFocus
05-10 09:52:18.547 9349-9349/com.chillarcards.campuswallet D/dalvikvm: DexOpt: unable to opt direct call 0xda74 at 0x08 in Lcom/onesignal/OneSignal;.sendPurchases
05-10 09:52:18.547 9349-9349/com.chillarcards.campuswallet I/dalvikvm: DexOpt: unable to optimize instance field ref 0x7a08 at 0x0f in Lcom/onesignal/OneSignal;.sendPurchases
05-10 09:52:18.547 9349-9349/com.chillarcards.campuswallet I/dalvikvm: DexOpt: unable to optimize instance field ref 0x7a09 at 0x13 in Lcom/onesignal/OneSignal;.sendPurchases
05-10 09:52:18.547 9349-9349/com.chillarcards.campuswallet D/dalvikvm: DexOpt: unable to opt direct call 0xda5e at 0x0f in Lcom/onesignal/OneSignal;.startLocationUpdate
05-10 09:52:18.547 9349-9349/com.chillarcards.campuswallet I/dalvikvm: DexOpt: unable to optimize instance field ref 0x7a0a at 0x1a in Lcom/onesignal/OneSignal;.updateUserIdDependents
05-10 09:52:18.547 9349-9349/com.chillarcards.campuswallet I/dalvikvm: DexOpt: unable to optimize instance field ref 0x7a08 at 0x1e in Lcom/onesignal/OneSignal;.updateUserIdDependents
05-10 09:52:18.547 9349-9349/com.chillarcards.campuswallet I/dalvikvm: DexOpt: unable to optimize instance field ref 0x7a09 at 0x22 in Lcom/onesignal/OneSignal;.updateUserIdDependents
05-10 09:52:18.547 9349-9349/com.chillarcards.campuswallet W/dalvikvm: Exception Ljava/lang/NoClassDefFoundError; thrown while initializing Lcom/onesignal/OneSignal;
05-10 09:52:18.547 9349-9349/com.chillarcards.campuswallet D/AndroidRuntime: Shutting down VM
05-10 09:52:18.547 9349-9349/com.chillarcards.campuswallet W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x41b6b930)
05-10 09:52:18.547 9349-9349/com.chillarcards.campuswallet E/CustomActivityOnCrash: App has crashed, executing CustomActivityOnCrash's UncaughtExceptionHandler
                                                                                    java.lang.ExceptionInInitializerError
                                                                                        at codmob.com.campuswallet.app.CampusWallet.onCreate(CampusWallet.java:94)
                                                                                        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1017)
                                                                                        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4556)
                                                                                        at android.app.ActivityThread.access$1400(ActivityThread.java:150)
                                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1340)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                        at android.os.Looper.loop(Looper.java:137)
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:5283)
                                                                                        at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                        at java.lang.reflect.Method.invoke(Method.java:511)
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
                                                                                        at dalvik.system.NativeStart.main(Native Method)
                                                                                     Caused by: java.lang.NoClassDefFoundError: com.onesignal.AdvertisingIdProviderGPS
                                                                                        at com.onesignal.OneSignal.<clinit>(OneSignal.java:192)
                                                                                        at codmob.com.campuswallet.app.CampusWallet.onCreate(CampusWallet.java:94) 
                                                                                        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1017) 
                                                                                        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4556) 
                                                                                        at android.app.ActivityThread.access$1400(ActivityThread.java:150) 
                                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1340) 
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                        at android.os.Looper.loop(Looper.java:137) 
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:5283) 
                                                                                        at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                        at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102) 
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869) 
                                                                                        at dalvik.system.NativeStart.main(Native Method) 
05-10 09:52:18.577 9349-9349/com.chillarcards.campuswallet E/CustomActivityOnCrash: Your application class or your error activity have crashed, the custom activity will not be launched!
05-10 09:52:18.577 9349-9349/com.chillarcards.campuswallet E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             java.lang.ExceptionInInitializerError
                                                                                 at codmob.com.campuswallet.app.CampusWallet.onCreate(CampusWallet.java:94)
                                                                                 at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1017)
                                                                                 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4556)
                                                                                 at android.app.ActivityThread.access$1400(ActivityThread.java:150)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1340)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                 at android.os.Looper.loop(Looper.java:137)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5283)
                                                                                 at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:511)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
                                                                                 at dalvik.system.NativeStart.main(Native Method)
                                                                              Caused by: java.lang.NoClassDefFoundError: com.onesignal.AdvertisingIdProviderGPS
                                                                                 at com.onesignal.OneSignal.<clinit>(OneSignal.java:192)
                                                                                 at codmob.com.campuswallet.app.CampusWallet.onCreate(CampusWallet.java:94) 
                                                                                 at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1017) 
                                                                                 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4556) 
                                                                                 at android.app.ActivityThread.access$1400(ActivityThread.java:150) 
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1340) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                 at android.os.Looper.loop(Looper.java:137) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5283) 
                                                                                 at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                 at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869) 
                                                                                 at dalvik.system.NativeStart.main(Native Method)

**Comment by jkasten2** [comment]
@Eldho93 Thanks for the full details. The `java.lang.NoClassDefFoundError` error can happen on seemly random classes on pre-Lollipop devices when you add `multiDexEnabled true` to your `build.gradle` but don't add the other requirements.
1. The following line your `build.gradle` dependencies.
```Gradle
compile 'com.android.support:multidex:1.0.0'
```
2. The ` MultiDex.install(this);` line you have listed above.

More details on this stackoverflow post.
http://stackoverflow.com/questions/27340058/android-multidex-and-support-libraries

Proguard will work on debug builds if you enabled it specific for the type of build.

**Comment by Eldho93** [comment]
The push not fication is not redirected clicking on the ok button of the alert dialog.
i mean redirected to the activity i specifies on the application class
It was working. Now its not.
Im using Onesignal sdk 3.5.5
I donno why this happens. We have another app which works on compile sdk version 23 and it works perfectly fine. Issues continue to popup in this app in which we use compile sdk version 25 and all other latest support librarries. Could you please check this issue as we are running out of time?

**Comment by jkasten2** [comment]
@Eldho93 Could you open a new thread related to this issue since it doesn't seem connected to the dex issue?

Please include your `build.gradle` config, OneSignal init code with the Open Handler, and any logcat entries when you tap on the notification.

Thanks.
