### ISSUE TITLE
GCM fail register

### ISSUE THREAD

**Issue by reynaldi-lorenzo** [OneSignal/OneSignal-Android-SDK#229]
In my verbose log, i found this : 
```Java
05-15 11:28:07.140 5567-5973/com.rnonesignal E/OneSignal: Error Getting Google Registration ID
                                                          java.io.IOException: AUTHENTICATION_FAILED
                                                              at com.google.android.gms.gcm.GoogleCloudMessaging.zza(Unknown Source)
                                                              at com.google.android.gms.gcm.GoogleCloudMessaging.register(Unknown Source)
                                                              at com.onesignal.PushRegistratorGPS$2.run(PushRegistratorGPS.java:161)
                                                              at java.lang.Thread.run(Thread.java:761)
```
Is this onesignal android SDK issue caused by deprecated register function by GCM?

**Comment by jkasten2** [comment]
@reynaldi-lorenzo This seems to be an issue with the device it self or a networking issue and is thrown from the Google Play services library. Can you ensure the date and time is correct on the device and the "Google Play services" app on the device is up to date?

See this thread for more details on this error.
https://github.com/google/gcm/issues/97

**Comment by reynaldi-lorenzo** [comment]
before i see my log, i get "Google play service error" in my device in user test, and i managet to get out from that error message. So, i really curious what are log says, and when i see log and get this error, but in my user test in onesignal the status become "no push token".

**Comment by jkasten2** [comment]
@reynaldi-lorenzo The `AUTHENTICATION_FAILED` is an internal error to the Google Play services library. If this error is being thrown all other apps will have the same issue on the device. I recommend also checking the date and time on the device as this could create the error as well.

Please let us know the Google Play service library version you built your app with and the version of the "Google Play services" app on the device. I also recommend opening the Play Store on the device and signing in.

If you continue to see issues I recommend testing your app on another device.

**Comment by jkasten2** [comment]
@reynaldi-lorenzo Closing due to inactivity. Feel free to reopen this issue with more details and I'll look into it.

**Comment by brenohq** [comment]
same issue here

**Comment by jkasten2** [comment]
@brenohq This error is usually related to a device issue or a networking problem. Make sure you can open the Google Play Store on the device and it can download and install apps.

If you can reproduce the issue please provide exact steps and which device and model you are seeing the issue one. Thanks.
