### ISSUE TITLE
GoogleApiClient is not connected yet

### ISSUE THREAD

**Issue by zack-barakat** [OneSignal/OneSignal-Android-SDK#244]
Hi,
Recently we have found this issue happens in our app.
SDK Version: 3.5.6
OS Version: 5
Device Model: OPPO A37fw-International
Here is stack trace:

`Fatal Exception: java.lang.IllegalStateException: GoogleApiClient is not connected yet.
       at com.google.android.gms.internal.zzaak.zzb(Unknown Source)
       at com.google.android.gms.internal.zzaan.zzb(Unknown Source)
       at com.google.android.gms.internal.zzaal.zzb(Unknown Source)
       at com.google.android.gms.internal.zzarl.removeLocationUpdates(Unknown Source)
       at com.onesignal.LocationGMS$FusedLocationApiWrapper.removeLocationUpdates(LocationGMS.java:300)
       at com.onesignal.LocationGMS$LocationUpdateListener.onLocationChanged(LocationGMS.java:287)
       at com.google.android.gms.internal.zzart$zzb$1.zza(Unknown Source)
       at com.google.android.gms.internal.zzart$zzb$1.zzs(Unknown Source)
       at com.google.android.gms.internal.zzaaz.zzb(Unknown Source)
       at com.google.android.gms.internal.zzaaz$zza.handleMessage(Unknown Source)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:160)
       at android.app.ActivityThread.main(ActivityThread.java:5541)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)`

would appreciate it if you can help

**Comment by jkasten2** [comment]
Duplicated of issue #241, this is fixed in the 3.5.7 release.
