### ISSUE TITLE
SQLiteException: cannot rollback

### ISSUE THREAD

**Issue by zack-barakat** [OneSignal/OneSignal-Android-SDK#245]
Hi
I found this exception in Crashlytics  
SDK Version: 3.5.4
Device Model: leimin A12

Here is stack trace:

`Fatal Exception: android.database.sqlite.SQLiteException: cannot rollback - no transaction is active (code 1)
       at android.database.sqlite.SQLiteConnection.nativeExecute(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:559)
       at android.database.sqlite.SQLiteSession.endTransactionUnchecked(SQLiteSession.java:439)
       at android.database.sqlite.SQLiteSession.endTransaction(SQLiteSession.java:401)
       at android.database.sqlite.SQLiteDatabase.endTransaction(SQLiteDatabase.java:537)
       at com.onesignal.NotificationRestorer.restore(NotificationRestorer.java:76)
       at com.onesignal.NotificationRestoreService.onHandleIntent(NotificationRestoreService.java:43)
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:193)
       at android.os.HandlerThread.run(HandlerThread.java:61)`

Would appreciate if you can look into it.
Thank you

**Comment by jkasten2** [comment]
@zack-barakat This happens when a version of your app is running the OneSignal SDK 3.4.4 or newer and then is downgraded to 3.4.3 or older. If you only see a few occurrences then this would be from users side loading an older version over the top of a new one.
See issue #222 for more details.
