### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException: GoogleApiClient is not connected yet (in 3.5.7)

### ISSUE THREAD

**Issue by janbolat** [OneSignal/OneSignal-Android-SDK#247]
Hello,
I have updated OneSignal Android SDK to 3.5.7, but still, see the error:

Fatal Exception: java.lang.IllegalStateException: GoogleApiClient is not connected yet.
       at com.google.android.gms.internal.zzaas.zzb(Unknown Source)
       at com.google.android.gms.internal.zzaav.zzb(Unknown Source)
       at com.google.android.gms.internal.zzaat.zzb(Unknown Source)
       at com.google.android.gms.internal.zzary.getLastLocation(Unknown Source)
       at com.onesignal.LocationGMS$FusedLocationApiWrapper.requestLocationUpdates(LocationGMS.java:305)
       at com.onesignal.LocationGMS$LocationUpdateListener.(LocationGMS.java)
       at com.onesignal.LocationGMS$GoogleApiClientListener.onConnected(LocationGMS.java:260)
       at com.google.android.gms.common.internal.zzm.zzxX(Unknown Source)
       at com.google.android.gms.internal.zzaat.zza(Unknown Source)
       at com.google.android.gms.internal.zzaar.zzwi(Unknown Source)
       at com.google.android.gms.internal.zzaar.begin(Unknown Source)
       at com.google.android.gms.internal.zzaav.onConnected(Unknown Source)
       at com.google.android.gms.internal.zzaag.onConnected(Unknown Source)
       at com.google.android.gms.common.internal.zzl$1.onConnected(Unknown Source)
       at com.google.android.gms.common.internal.zzf$zzj.zzm(Unknown Source)
       at com.google.android.gms.common.internal.zzf$zza.zzxG(Unknown Source)
       at com.google.android.gms.common.internal.zzf$zza.zzxG(Unknown Source)
       at com.google.android.gms.common.internal.zzf$zze.zzxH(Unknown Source)
       at com.google.android.gms.common.internal.zzf$zzd.handleMessage(Unknown Source)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.os.HandlerThread.run(HandlerThread.java:61)

Devices:
Galaxy J7(2016) 6.0.1
Galaxy Grand Neo 4.2.2

**Comment by janbolat** [comment]
Also, exceptions are appearing on:
Galaxy Tab3 Lite 7.0
Galaxy E5
SM-A320F
SM-G570F
Galaxy Win Duos
LG K10 LTE
LG Prime Plus 4G
LG X Style
L Bello
LG K8 LTE
Xperia Z
ZTE
Huawei

On all android versions: 4, 5, 6, 7 

Any comments?

**Comment by janbolat** [comment]
Hi @jkasten2 ,
have you able to reproduce this issue?

**Comment by jkasten2** [comment]
@janbolat I haven't been able to reproduce this issue. Are you able to reproduce this on your test devices? Or are you just getting reports of these from Google Play?

Could you share the OneSignal init code you are using and the OneSignal methods you are calling?

**Comment by janbolat** [comment]
@jkasten2 ,
It is happening on real devices.
I am getting these reports on Crashlytics.

I init OneSignal in Application class' onCreate() method:
`OneSignal.startInit(this)
.autoPromptLocation(false) 
.disableGmsMissingPrompt(false)
.setNotificationReceivedHandler(new GcmNotificationReceivedHandler())   
.setNotificationOpenedHandler(new GcmNotificationOpenedHandler()) 
.inFocusDisplaying(OneSignal.OSInFocusDisplayOption.Notification)
.init();`

Also, in background service I call this:
`OneSignal.idsAvailable(new OneSignal.IdsAvailableHandler()
            {
                @Override
                public void idsAvailable(String userId, String registrationId)
                {
                    Crashlytics.setString("OneSignalID", userId);
                    editor = settings.edit();
                    editor.putString(ONESIGNAL_PLAYER_ID, userId);
                    editor.apply();
                    OneSignal.setSubscription(true);
                }
            });`

I am using OneSignal since last year, and I didn't see these errors before.

**Comment by jkasten2** [comment]
@janbolat This is now fixed in the 3.5.8 SDK update. Thanks.

**Comment by janbolat** [comment]
Hi @jkasten2 ,
it seems on SDK 3.6.0 it may still reach "GoogleApiClient is not connected yet." error on lines 296, 312 in
[https://github.com/OneSignal/OneSignal-Android-SDK/blob/master/OneSignalSDK/onesignal/src/main/java/com/onesignal/LocationGMS.java](https://github.com/OneSignal/OneSignal-Android-SDK/blob/master/OneSignalSDK/onesignal/src/main/java/com/onesignal/LocationGMS.java) though it is rare.

**Comment by anukools** [comment]
@jkasten2 I am also facing the same issue, crashes shown in Fabric crash analytics, specially for Samsung devices in latest release.
