### ISSUE TITLE
Too many Alarms

### ISSUE THREAD

**Issue by swratten** [OneSignal/OneSignal-Android-SDK#248]
I am seeing this on solely Samsung devices, it is the number 1 crash for my production app.
I have not yet reproduced this, but it has been reported multiple times in crashlytics.
OneSignal SDK version: 3.5.6
``` java
Fatal Exception: java.lang.SecurityException: !@Too many alarms (500) registered from uid 10377
       at android.os.Parcel.readException(Parcel.java:1693)
       at android.os.Parcel.readException(Parcel.java:1646)
       at android.app.IAlarmManager$Stub$Proxy.set(IAlarmManager.java:228)
       at android.app.AlarmManager.setImpl(AlarmManager.java:734)
       at android.app.AlarmManager.set(AlarmManager.java:390)
       at com.onesignal.SyncService.scheduleServiceSyncTask(SourceFile:180)
       at com.onesignal.LocationGMS.scheduleUpdate(SourceFile:94)
       at com.onesignal.LocationGMS.receivedLocationPoint(SourceFile:243)
       at com.onesignal.LocationGMS.access$200(SourceFile:56)
       at com.onesignal.LocationGMS$GoogleApiClientListener.onConnected(SourceFile:256)
       at com.google.android.gms.common.internal.zzm.zzq(Unknown Source)
       at com.google.android.gms.internal.zzaat.zzo(Unknown Source)
       at com.google.android.gms.internal.zzaar.zzwi(Unknown Source)
       at com.google.android.gms.internal.zzaar.onConnected(Unknown Source)
       at com.google.android.gms.internal.zzaav.onConnected(Unknown Source)
       at com.google.android.gms.internal.zzaag.onConnected(Unknown Source)
       at com.google.android.gms.common.internal.zzl$1.onConnected(Unknown Source)
       at com.google.android.gms.common.internal.zzf$zzj.zzxG(Unknown Source)
       at com.google.android.gms.common.internal.zzf$zza.zzb(Unknown Source)
       at com.google.android.gms.common.internal.zzf$zza.zzu(Unknown Source)
       at com.google.android.gms.common.internal.zzf$zze.zzxH(Unknown Source)
       at com.google.android.gms.common.internal.zzf$zzd.handleMessage(Unknown Source)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by jkasten2** [comment]
@swratten Thanks for reporting, from our research the `!@Too many alarms (500) registered` only happens on Samsung devices as you have noted. However we put a fix in 3.4.4 that should have prevent this.

Did you have version 3.4.3 or older in your app? If so after upgrading did you see less occurrences? Could you share your crashlytics page here or with OneSignal support linking to this github issue?

**Comment by swratten** [comment]
Hi there,

No I have only started using your SDK in the past month and have followed the setup guidelines and have always used the newest SDK version.
Sure I'll share a link for the issue here.
[http://crashes.to/s/4cedfaf29c2](Crashlytics)

**Comment by jkasten2** [comment]
@swratten I notice the crashes have decreased dramatically based on the Crashlytics link you attached. Did you change anything in your app?

**Comment by jkasten2** [comment]
@swratten Closing due to inactivity, feel free to reply with more details if you are still seeing this issue.
