### ISSUE TITLE
App crash when expanding notification

### ISSUE THREAD

**Issue by zack-barakat** [OneSignal/OneSignal-Android-SDK#254]
I've received several crash reports saying the notification remote view couldn't be expanded status icon was not found.

It happens on these Samsung devices:
- SM-G950F
- Galaxy A5(2016)
- SM-G955
OS: 7.0
stack-trace:

`Fatal Exception: android.app.RemoteServiceException: Bad notification posted from package com.gobike.consumer: Couldn't expand RemoteViews for: StatusBarNotification(pkg=com.gobike.consumer user=UserHandle{0} id=-1488611481 tag=null key=0|com.gobike.consumer|-1488611481|null|10209: Notification(pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x10 color=0xfffb8f3e vis=PUBLIC semFlags=0x0 semPriority=0))
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1813)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)`

let me know if you need more details.

**Comment by jkasten2** [comment]
@zack-barakat There is a good chance this issue is the same a s your #255 issue. Can you check the small icon? If this isn't the issue please attach the full list of notification options you are using.
