### ISSUE TITLE
Fatal Exception: java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed:

### ISSUE THREAD

**Issue by ominfowave** [OneSignal/OneSignal-Android-SDK#258]
```Java
Fatal Exception: java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
       at java.lang.Thread.nativeCreate(Thread.java)
       at java.lang.Thread.start(Thread.java:1063)
       at com.onesignal.OneSignalRestClient.makeRequest(OneSignalRestClient.java:98)
       at com.onesignal.OneSignalRestClient.postSync(OneSignalRestClient.java:86)
       at com.onesignal.OneSignalStateSynchronizer.syncUserState(OneSignalStateSynchronizer.java:616)
       at com.onesignal.OneSignalStateSynchronizer$NetworkHandlerThread$1.run(OneSignalStateSynchronizer.java:532)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:234)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```
on Version 3.5.8@aar

**Comment by jkasten2** [comment]
@ominfowave We haven't had any other `OutOfMemoryError` exceptions reported before. Can you profile the memory of your app with Android Studio to make sure you don't have a leak somewhere in your app's code?

Is the error reproducible? Can you include the device model and Android version the error happened on?

**Comment by ominfowave** [comment]
![image 1](https://user-images.githubusercontent.com/4697885/27982024-75ef2b86-63b5-11e7-962b-0d812ed450f4.png)
![image 2](https://user-images.githubusercontent.com/4697885/27982025-75f384ce-63b5-11e7-891f-aa534b4b2c2f.png)

**Comment by jkasten2** [comment]
@ominfowave Can you let us know how many occurrences of this crash you are seeing in your app?

Could you provide a link to Crashlytics page? We can look into all threads that are running with your app.

**Comment by ominfowave** [comment]
Here is report http://crashes.to/s/b82f8ea1f4e

**Comment by jkasten2** [comment]
@ominfowave We haven't had any other reports of this issue, are you still see this crash?

**Comment by jkasten2** [comment]
Closing due to inactivity. Feel free to reply however and we can reopen

**Comment by jkasten2** [comment]
OneSignal doesn't use much memory so this isn't a root cause of the problem. There is most likely another crash in your app for another `OutOfMemoryError`. (unless you are catching it and silencing it)

However if you update the the latest v5 SDK you should no longer see this at all, since new threads are no longer being created there. Please try updating and let us know if if fixes the issue completely. If not please open a new issue with the new stack trace.
