### ISSUE TITLE
Error null pointer exception

### ISSUE THREAD

**Issue by zack-barakat** [OneSignal/OneSignal-Android-SDK#273]
Hi just saw null pinter exception crash on my Crashlytics.
I'm using the latest version of one signal SDK.
Device name: Galaxy J7
Android OS: 6.0.1
error stack trace:

```Java
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Bundle android.content.Intent.getExtras()' on a null object reference
       at com.onesignal.NotificationExtenderService.processIntent(NotificationExtenderService.java:115)
       at com.onesignal.NotificationExtenderService.onHandleIntent(NotificationExtenderService.java:110)
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

would really appreciate if you can look at it.

**Comment by jkasten2** [comment]
@zack-barakat The `NotificationExtenderService` class shouldn't be fired with a `null` `Intent` as it is always sent with one from our SDK. However it is possible the service isn't being started by the OneSignal SDK or Android is restarting the service without one.

We will add a `null` check to the class to prevent any cases for this crash.

**Comment by zack-barakat** [comment]
@jkasten2  I guess it's caused by android restarting the service with null intent.
Thank you for your help, looking for the new update.
