### ISSUE TITLE
Crash on boot with Android O 

### ISSUE THREAD

**Issue by g123k** [OneSignal/OneSignal-Android-SDK#274]
Hello,

With Android 0 (DP4 in my case) and the 3.5.8 version of SDK, I have a crash on every boot of the device. The crash is the following :

```java
Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.frandroid.app/com.onesignal.NotificationRestoreService (has extras) }: app is in background uid UidRecord{c74919a u0a125 RCVR idle procs:1 seq(0,0,0)}
                                                                     at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1505)
                                                                     at android.app.ContextImpl.startService(ContextImpl.java:1461)
                                                                     at android.content.ContextWrapper.startService(ContextWrapper.java:644)
                                                                     at android.content.ContextWrapper.startService(ContextWrapper.java:644)
                                                                     at android.support.v4.content.WakefulBroadcastReceiver.startWakefulService(WakefulBroadcastReceiver.java:100)
                                                                     at com.onesignal.BootUpReceiver.onReceive(BootUpReceiver.java:42)
                                                                     at android.app.ActivityThread.handleReceiver(ActivityThread.java:3252)
                                                                     at android.app.ActivityThread.-wrap17(Unknown Source:0) 
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1677) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                                     at android.os.Looper.loop(Looper.java:164) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:6541) 
                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
```

This crash is related to Android O / 8.0. You can find further information [here](https://stackoverflow.com/questions/44502229/runtime-exception-android-o-with-boot-completed).

**Comment by jkasten2** [comment]
@g123k We are working on compatible SDK when targeting api 26. In the next few days we will update this thread with a beta version of the SDK to try out.

**Comment by jkasten2** [comment]
@g123k You can use the following in your build.gradle to try out our beta of our SDK which includes support for Android O when targeting API 26.

```gradle

// Add snapshots repo if you don't have it already
repositories {
    maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
}

compile 'com.onesignal:OneSignal:4.0.0-SNAPSHOT'
```

To see a full index of snapshots:
https://oss.sonatype.org/content/repositories/snapshots/com/onesignal/OneSignal/4.0.0-SNAPSHOT/

**Comment by g123k** [comment]
Hello,

Thanks for the version, I will try it ASAP.

Is-it production ready? Or should I wait for the final 4.0.0 version?
Do you have any release date?

Thanks

**Comment by jkasten2** [comment]
@g123k From feedback from others and our own testing the beta has been stable. We are finishing our final testing and we are shooting for a release sometime next week.

Thanks.

**Comment by g123k** [comment]
Ok thanks for the schedule.

I am not sure, if I have to open a new ticket, but with the current snapshot and Android O, I have to reinstall the app to receive pushes. Otherwise, I have absolutely nothing.

With the stable version of your SDK and Android <= 7.1, everything is working fine.

**Comment by jkasten2** [comment]
@g123k I just tested this upgrade path on a Nexus 6P with Android O Beta4 without any issues.
1. Installed app with `targetSdkVersion` set to `25` and OneSignal SDK `3.5.8`.
2. Sent a few test notifications which displayed correctly.
3. Switched to  `targetSdkVersion` set to `26` and the OneSignal SNAPSHOT SDK.
4. Redeployed app to the phone without uninstalling.
5. Sent a few more notifications and they also displayed correctly.

We just released one more snapshot today. Can you use the following gradle entry instead of the one above to ensure you have this very latest version?
```
compile 'com.onesignal:OneSignal:4.0.0-20170811.003211-4'
```

**Comment by jkasten2** [comment]
3.6.0 has been released and resolves the crashes reported here.
