### ISSUE TITLE
getting error when notification received

### ISSUE THREAD

**Issue by nikhil19patil** [OneSignal/OneSignal-Android-SDK#276]
I am getting NoSuchMethodError when I am using following configuration in apps build.graddle

	configurations.all {
		resolutionStrategy.eachDependency { DependencyResolveDetails details ->
		    def requested = details.requested
		    if (requested.group == 'com.android.support') {
		        if (!requested.name.startsWith("multidex")) {
		            details.useVersion '25.3.1'
		        }
		    }
		}
	}

when I don't use above code in gradle then my projects doesn't get compiled and says that all support libraries must use same version. Also I am not able to avoid writing above code in gradle as I am using multiple libraries where, there is possibility of usage of different support library versions.

    Fatal Exception: java.lang.NoSuchMethodError: No direct method <init>(Landroid/content/Context;Ljava/lang/String;)V in class Landroid/support/v4/app/NotificationCompat$Builder; or its super classes (declaration of 'android.support.v4.app.NotificationCompat$Builder' appears in /data/app/com.roidtechnologies.appbrowzer-1/base.apk)
		   at com.onesignal.GenerateNotification.getBaseOneSignalNotificationBuilder(GenerateNotification.java:249)
		   at com.onesignal.GenerateNotification.showNotification(GenerateNotification.java:332)
		   at com.onesignal.GenerateNotification.fromJsonPayload(GenerateNotification.java:111)
		   at com.onesignal.NotificationBundleProcessor.Process(NotificationBundleProcessor.java:87)
		   at com.onesignal.NotificationExtenderService.processJsonObject(NotificationExtenderService.java:186)
		   at com.onesignal.NotificationExtenderService.processIntent(NotificationExtenderService.java:142)
		   at com.onesignal.NotificationExtenderService.onHandleIntent(NotificationExtenderService.java:110)
		   at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
		   at android.os.Handler.dispatchMessage(Handler.java:102)
		   at android.os.Looper.loop(Looper.java:154)
		   at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by nikhil19patil** [comment]
If I don't add above code I am getting following error
	Error:Execution failed for task ':app:processDebugManifest'.
	> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(26.0.0-alpha1) from [com.android.support:customtabs:26.0.0-alpha1] AndroidManifest.xml:24:9-38
	  	is also present at [com.android.support:recyclerview-v7:25.3.1] AndroidManifest.xml:24:9-31 value=(25.3.1).
	  	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:22:5-24:41 to override.

**Comment by jkasten2** [comment]
@nikhil19patil Looks like you are using the beta version of our OneSignal SDK. It depends on having the Android Support library 26.0.0-beta2 or newer to support Android O. There is now a 26.0.0 release so it is recommend to use this over the beta2 version however.

Please share your root `build.gradle` and `app/buidle.gradle` if you are still seeing any issue.

**Comment by jkasten2** [comment]
@nikhil19patil The 3.6.0 SDK now depends on version 26.0.0 of `com.android.support:support-v4` so this should no longer be an issue. Please feel free to reopen this thread if you are still having an issue.

Thanks!
