### ISSUE TITLE
 Unable to start receiver com.onesignal.GcmBroadcastReceiver

### ISSUE THREAD

**Issue by ominfowave** [OneSignal/OneSignal-Android-SDK#280]
```Java
Fatal Exception: java.lang.RuntimeException: Unable to start receiver com.onesignal.GcmBroadcastReceiver: java.lang.SecurityException: Not allowed to start service Intent { act=com.onesignal.NotificationExtender pkg=com.watchlivetv.onlineradioapp (has extras) } without permission not exported from uid 10082
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2426)
       at android.app.ActivityThread.access$1700(ActivityThread.java:135)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1272)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5021)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:827)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:643)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.SecurityException: Not allowed to start service Intent { act=com.onesignal.NotificationExtender pkg=com.watchlivetv.onlineradioapp (has extras) } without permission not exported from uid 10082
       at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1527)
       at android.app.ContextImpl.startService(ContextImpl.java:1504)
       at android.content.ContextWrapper.startService(ContextWrapper.java:494)
       at android.content.ContextWrapper.startService(ContextWrapper.java:494)
       at android.support.v4.content.WakefulBroadcastReceiver.startWakefulService(WakefulBroadcastReceiver.java:91)
       at com.onesignal.NotificationBundleProcessor.processBundle(NotificationBundleProcessor.java:385)
       at com.onesignal.GcmBroadcastReceiver.processOrderBroadcast(GcmBroadcastReceiver.java:95)
       at com.onesignal.GcmBroadcastReceiver.onReceive(GcmBroadcastReceiver.java:61)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2419)
       at android.app.ActivityThread.access$1700(ActivityThread.java:135)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1272)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5021)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:827)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:643)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by jkasten2** [comment]
@ominfowave Make sure the service you added the action `com.onesignal.NotificationExtender` to in your `AndroidManifest.xml` is has `android:exported="false"`
```XML
<service
   android:name=".YOUR_CLASS_NAME"
   android:exported="false">
   <intent-filter>
      <action android:name="com.onesignal.NotificationExtender" />
   </intent-filter>
</service>
```
https://documentation.onesignal.com/docs/android-customizations#section-background-data-and-notification-overriding

**Comment by jkasten2** [comment]
@ominfowave Feel free to reply / reopen this thread if the above wasn't your issue.

**Comment by ominfowave** [comment]
@jkasten2 it's not case,i have already declared this content in mainfest.xml ,there is issue with only one user, on fabric there are more then 50 report for same user.

**Comment by ominfowave** [comment]
@jkasten2  now issue is increased with more number of users please see this http://crashes.to/s/9c056a969fb

**Comment by Alamgir** [comment]
@ominfowave since it appears that this issue is linked to a single user, can you confirm if that user has google play services installed/updated?

**Comment by Alamgir** [comment]
@ominfowave can you post your manifest declaration of your subclass of NotificationExtenderService?

**Comment by ominfowave** [comment]
<service
            android:name=".modules.oneSignal.NotificationExtenderBareBones"
            android:exported="false">
            <intent-filter>
                <action android:name="com.onesignal.NotificationExtender" />
            </intent-filter>
        </service>

**Comment by Alamgir** [comment]
@ominfowave your manifest declaration of the extender looks fine. Can you post your app's gradle build file? This could be an issue with the version of play services that you're using...

also, can you verify that your defaultConfig's `applicationId` is correctly configured?

**Comment by ominfowave** [comment]
here is dependencies that i have added in app gradle file
`compile 'com.google.android.gms:play-services-ads:11.2.2'
    compile 'com.google.android.gms:play-services-location:11.2.2'
    compile 'com.google.android.gms:play-services-gcm:11.2.2'
    compile 'com.google.firebase:firebase-appindexing:11.2.2'
    compile 'com.google.firebase:firebase-core:11.2.2'
  compile 'com.onesignal:OneSignal:[3.6.2, 3.99.99]'`

**Comment by Alamgir** [comment]
@ominfowave can you make sure you're using the latest 3.6.4 version of OneSignal - we introduced fixes for Android O with regards to background processing

**Comment by jkasten2** [comment]
@ominfowave Closing due to inactivity. Please feel free to reopen this issue if the latest SDK update does not solve this issue.

**Comment by Khaled-Almoukhtar** [comment]
@jkasten2 
I am having the same issue when using latest Unity SDK version 2.7.2
How can I add this
https://documentation.onesignal.com/docs/android-native-sdk#section--notificationextenderservice-
in Unity without using Java
what should I write for "YOUR_CLASS_NAME"
`android:name=".YOUR_CLASS_NAME"`

**Comment by Jack2jm** [comment]
![screenshot 243](https://user-images.githubusercontent.com/9676304/43129986-3afac1be-8f53-11e8-9045-acc3c086d35b.png)
I am having the same issue when using One signal Notification. 

App Target SDK is 26.
Onesignal android version : 3.9.1
Plugin Version :  0.10

**Comment by jkasten2** [comment]
@Jack2jm Thanks for reporting, your stack trace is actually the same as issue #498
