### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/internal/zzjb;

### ISSUE THREAD

**Issue by hynra** [OneSignal/OneSignal-Android-SDK#298]
I got error :

```Java
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/internal/zzjb;
at com.google.android.gms.internal.zzli.zza(Unknown Source)
at com.google.android.gms.internal.zzli.zza(Unknown Source)
at com.google.android.gms.ads.BaseAdView.loadAd(Unknown Source)
at com.google.android.gms.ads.AdView.loadAd(Unknown Source)
at id.videoplaylistapp.MainActivity.onCreate(MainActivity.java:136)
at android.app.Activity.performCreate(Activity.java:6679)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
at android.app.ActivityThread.-wrap12(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6119)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

Caused by: java.lang.ClassNotFoundException: com.google.android.gms.internal.zzjb
at java.lang.VMClassLoader.findLoadedClass(Native Method)
at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
at com.google.android.gms.internal.zzli.zza(Unknown Source) 
at com.google.android.gms.internal.zzli.zza(Unknown Source) 
at com.google.android.gms.ads.BaseAdView.loadAd(Unknown Source) 
at com.google.android.gms.ads.AdView.loadAd(Unknown Source) 
at krealoka.id.videoplaylistapp.MainActivity.onCreate(MainActivity.java:136) 
at android.app.Activity.performCreate(Activity.java:6679) 
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118) 
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618) 
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
at android.app.ActivityThread.-wrap12(ActivityThread.java) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:154) 
at android.app.ActivityThread.main(ActivityThread.java:6119) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 

Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/safeparcel/zza;
at com.google.android.gms.internal.zzli.zza(Unknown Source) 
at com.google.android.gms.internal.zzli.zza(Unknown Source) 
at com.google.android.gms.ads.BaseAdView.loadAd(Unknown Source) 
at com.google.android.gms.ads.AdView.loadAd(Unknown Source) 
at krealoka.id.videoplaylistapp.MainActivity.onCreate(MainActivity.java:136) 
at android.app.Activity.performCreate(Activity.java:6679) 
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118) 
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618) 
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
at android.app.ActivityThread.-wrap12(ActivityThread.java) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:154) 
at android.app.ActivityThread.main(ActivityThread.java:6119) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 

Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.internal.safeparcel.zza" on path: DexPathList[[zip file "/data/app/------/base.apk"],nativeLibraryDirectories=[/data/app/----2/lib/x86, /system/lib, /vendor/lib]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
at com.google.android.gms.internal.zzli.zza(Unknown Source) 
at com.google.android.gms.internal.zzli.zza(Unknown Source) 
at com.google.android.gms.ads.BaseAdView.loadAd(Unknown Source) 
at com.google.android.gms.ads.AdView.loadAd(Unknown Source) 
at id.videoplaylistapp.MainActivity.onCreate(MainActivity.java:136) 
at android.app.Activity.performCreate(Activity.java:6679) 
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118) 
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618) 
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
at android.app.ActivityThread.-wrap12(ActivityThread.java) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:154) 
at android.app.ActivityThread.main(ActivityThread.java:6119) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
```
This message show when admob loaded :

```java
MobileAds.initialize(this, Constants.ADMOB_APP_ID);
        AdView mAdView = (AdView) findViewById(R.id.adView);
        final AdRequest adRequest = new AdRequest.Builder()
                .addTestDevice(AdRequest.DEVICE_ID_EMULATOR)
                .build();
        mAdView.loadAd(adRequest);
```

`build.gradle` project :

```gradle
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.3'
        classpath 'com.google.gms:google-services:3.1.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
        maven { url 'https://maven.google.com' }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

`build.gradle` app :
```gradle
apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    buildToolsVersion "26.0.0"
    useLibrary 'org.apache.http.legacy'
    defaultConfig {
        applicationId "my.app"
        manifestPlaceholders = [onesignal_app_id: "xxx",
                                // Project number pulled from dashboard, local value is ignored.
                                onesignal_google_project_number: "REMOTE"]
        minSdkVersion 17
        targetSdkVersion 26
        versionCode 6
        versionName "1.2"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        vectorDrawables.useSupportLibrary = true
        multiDexEnabled true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    //   compile "com.mikepenz:iconics-views:2.9.0@aar"
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.android.support:design:25.3.1'
    compile 'com.android.support:support-vector-drawable:25.3.1'
    compile 'com.google.code.gson:gson:2.2.4'
    compile 'com.github.wrdlbrnft:sorted-list-adapter:0.2.0.19'
    compile 'com.android.support:recyclerview-v7:25.3.1'
    compile 'com.android.support:cardview-v7:25.3.1'
    compile 'com.github.PierfrancescoSoffritti:AndroidYouTubePlayer:0.7.2'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.mikepenz:iconics-core:2.8.2@aar'
    compile 'com.mikepenz:google-material-typeface:3.0.1.1.original@aar'
    compile 'com.loopj.android:android-async-http:1.4.9'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile 'com.firebase:firebase-jobdispatcher:0.7.0'
    compile 'org.apache.commons:commons-lang3:3.5'
    compile 'com.google.firebase:firebase-ads:11.2.0'
    compile 'com.google.android.gms:play-services-gcm:11.2.0'
    compile 'com.synnapps:carouselview:0.1.4'
    compile 'com.github.oliveiradev:image-zoom:0.4.0'
    compile 'com.github.RaviKoradiya:ZoomableImageView:1.0.2'
    compile 'com.onesignal:OneSignal:3.6.0'
    testCompile 'junit:junit:4.12'
}





apply plugin: 'com.google.gms.google-services'
```

How I fix that ?

Thank You.

**Comment by DimaKoz** [comment]
You have problem with Google ads, but not with OneSignal.
Why do you ask about Google ads here?
Nevertheless, try to change 
`compile 'com.google.firebase:firebase-ads:11.2.0'` to  
`compile 'com.google.android.gms:play-services-ads:11.2.0' `
May be it help you.

**Comment by hynra** [comment]
@DimaKoz Thank you for your answer. Sorry for that, because I got the error after following OneSignal SDK setup, before that my app is running normal. So I think it's relatable to post the issue here.

I've change `com.google.firebase:firebase-ads:11.2.0` to `com.google.android.gms:play-services-ads:11.2.0` and still get error :

```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/internal/zzjb;
                                                                           at com.google.android.gms.internal.zzli.zza(Unknown Source)
                                                                           at com.google.android.gms.internal.zzli.zza(Unknown Source)
                                                                           at com.google.android.gms.ads.BaseAdView.loadAd(Unknown Source)
                                                                           at com.google.android.gms.ads.AdView.loadAd(Unknown Source)
                                                                           at id.videoplaylistapp.MainActivity.onCreate(MainActivity.java:136)
                                                                           at android.app.Activity.performCreate(Activity.java:6679)
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                                           at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:154)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                                        Caused by: java.lang.ClassNotFoundException: com.google.android.gms.internal.zzjb
                                                                           at java.lang.VMClassLoader.findLoadedClass(Native Method)
                                                                           at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
                                                                           at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
                                                                           at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                           at com.google.android.gms.internal.zzli.zza(Unknown Source) 
                                                                           at com.google.android.gms.internal.zzli.zza(Unknown Source) 
                                                                           at com.google.android.gms.ads.BaseAdView.loadAd(Unknown Source) 
                                                                           at com.google.android.gms.ads.AdView.loadAd(Unknown Source) 
                                                                           at id.videoplaylistapp.MainActivity.onCreate(MainActivity.java:136) 
                                                                           at android.app.Activity.performCreate(Activity.java:6679) 
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118) 
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618) 
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
                                                                           at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                           at android.os.Looper.loop(Looper.java:154) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6119) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
                                                                        Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/safeparcel/zza;
                                                                           at com.google.android.gms.internal.zzli.zza(Unknown Source) 
                                                                           at com.google.android.gms.internal.zzli.zza(Unknown Source) 
                                                                           at com.google.android.gms.ads.BaseAdView.loadAd(Unknown Source) 
                                                                           at com.google.android.gms.ads.AdView.loadAd(Unknown Source) 
                                                                           at krealoka.id.videoplaylistapp.MainActivity.onCreate(MainActivity.java:136) 
                                                                           at android.app.Activity.performCreate(Activity.java:6679) 
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118) 
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618) 
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
                                                                           at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                           at android.os.Looper.loop(Looper.java:154) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6119) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
                                                                        Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.internal.safeparcel.zza" on path: DexPathList[[zip file "/data/app/app.krealoka.videoviral-1/base.apk"],nativeLibraryDirectories=[/data/app/app.krealoka.videoviral-1/lib/x86, /system/lib, /vendor/lib]]
                                                                           at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                           at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                                           at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                           at com.google.android.gms.internal.zzli.zza(Unknown Source) 
                                                                           at com.google.android.gms.internal.zzli.zza(Unknown Source) 
                                                                           at com.google.android.gms.ads.BaseAdView.loadAd(Unknown Source) 
                                                                           at com.google.android.gms.ads.AdView.loadAd(Unknown Source) 
                                                                           at id.videoplaylistapp.MainActivity.onCreate(MainActivity.java:136) 
                                                                           at android.app.Activity.performCreate(Activity.java:6679) 
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118) 
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618) 
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
                                                                           at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                           at android.os.Looper.loop(Looper.java:154) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6119) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
```

**Comment by DimaKoz** [comment]
The size and number of included libraries requires Multidex.  Note that [three steps are required](https://developer.android.com/studio/build/multidex.html#mdex-gradle), including a change to the manifest.

**Comment by umutg4d** [comment]
Any news about the solution? @hynra

**Comment by umutg4d** [comment]
I changed my `compile 'com.google.android.gms:play-services-ads:11.2.0'` to previous one `compile 'com.google.android.gms:play-services-ads:11.2.2'` i used before onesignal plugin added and error has gone. @hynra @DimaKoz

**Comment by mustafa-demir** [comment]
I had a very similar problem. I solved it by adding following lines in my build.gradle for app module. 

`buildscript {
    repositories {
        maven { url 'https://plugins.gradle.org/m2/'}
    }
    dependencies {
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.11.0, 0.99.99]'
    }
}
apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'

repositories {
    maven { url 'https://maven.google.com' }
}`

Make sure you are adding and applying OneSignal gradle plugin. You can check up to date versions from [OneSignal Android SDK](https://documentation.onesignal.com/docs/android-sdk-setup) documentation.

**Comment by pacozaa** [comment]
@mustafa-demir Where did you put it in project?

**Comment by pacozaa** [comment]
@mustafa-demir Do you have example of your file?

**Comment by jkasten2** [comment]
@pacozaa The entries should be added to the very top of your `app/build.gradle (Module: app)` per the [Android SDK Setup - 1. Gradle Setup](https://documentation.onesignal.com/docs/android-sdk-setup#section-1-gradle-setup) instructions

**Comment by amit2amitsoni** [comment]
Process: justfind.org, PID: 9441
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/api/Api$zzf;
        at com.google.android.gms.auth.api.Auth.<clinit>(Unknown Source:0)
        at com.facebook.accountkit.ui.AccountKitActivity.onCreate(AccountKitActivity.java:281)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.api.Api$zzf" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/justfind.org-O3zXC2UGlx-Z0AfYjmYLLg==/base.apk"],nativeLibraryDirectories=[/data/app/justfind.org-O3zXC2UGlx-Z0AfYjmYLLg==/lib/x86, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.google.android.gms.auth.api.Auth.<clinit>(Unknown Source:0) 
        at com.facebook.accountkit.ui.AccountKitActivity.onCreate(AccountKitActivity.java:281) 
        at android.app.Activity.performCreate(Activity.java:7136) 
        at android.app.Activity.performCreate(Activity.java:7127) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
2018-10-13 09:28:13.176 1844-1912/? E/InputDispatcher: channel 'f11f5fa justfind.org/justfind.org.activity.SignInActivity (server)'

**Comment by amit2amitsoni** [comment]
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.0.0-alpha1'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.0-alpha3'
    implementation 'com.mcxiaoke.volley:library:1.0.19'
    implementation 'com.google.firebase:firebase-core:16.0.0'
    implementation group: 'com.pubnub', name: 'pubnub-gson', version: '4.10.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.0-alpha3'
    implementation 'com.android.support:recyclerview-v7:28.0.0'
    implementation 'me.dm7.barcodescanner:zxing:1.9.4'
    implementation 'com.google.android.material:material:1.0.0-beta01'
    implementation 'com.facebook.android:account-kit-sdk:4.+'
}

**Comment by jkasten2** [comment]
@amit2amitsoni Thanks for the full logcat crash and your `build.gradle` config. However it looks like your dependencies doesn't include OneSignal. Can you check you have add the correct `build.gradle` here?

**Comment by LogeshwariMurugan** [comment]
Still im getting the same issue .

My build gradle:
apply plugin: 'com.android.application'


android {
    compileSdkVersion 27
    defaultConfig {
        applicationId "com.innoart.justcopy"
        minSdkVersion 21
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        vectorDrawables.useSupportLibrary = true
        multiDexEnabled true
    }
    packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/ASL2.0'
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:cardview-v7:27.1.1'
    implementation 'com.itextpdf:itextg:5.5.10'
    implementation 'com.android.support:recyclerview-v7:27.1.1'
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support:design:27.1.1'

    implementation 'com.google.firebase:firebase-core:16.0.1'
    implementation 'com.google.firebase:firebase-auth:16.0.3'
    implementation 'com.google.android.gms:play-services-auth:16.0.0'
    implementation 'com.firebaseui:firebase-ui-auth:3.3.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.2'
    implementation 'com.amazonaws:aws-android-sdk-cognitoidentityprovider:2.8.+'
    implementation 'com.android.support:support-v4:27.1.1'
    implementation 'com.android.support:support-vector-drawable:27.1.1'
    testImplementation 'junit:junit:4.12'
    implementation 'com.rmtheis:tess-two:5.4.1'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation project(':edgedetection')
    implementation project(':openCVLibrary340')
    implementation 'com.jakewharton:butterknife:8.8.1'
    implementation 'com.karumi:dexter:4.1.0'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.8.1'
    implementation 'info.androidhive:imagefilters:1.0.7'
    // for dropbox
    implementation 'com.dropbox.core:dropbox-core-sdk:2.0.1'
    // for facebook
    implementation 'com.facebook.android:facebook-login:[4,5)'
    implementation project(':linkedin-sdk')

//    implementation 'com.google.android.gms:play-services-drive:11.6.0'
//    implementation 'com.google.api-client:google-api-client:1.25.0'
//    implementation "com.google.android.gms:play-services-drive:11.6.0"
//    implementation 'com.google.api-client:google-api-client:1.23.0'
//    implementation 'com.google.oauth-client:google-oauth-client-jetty:1.23.0'
//    implementation 'com.google.apis:google-api-services-drive:v3-rev110-1.23.0'
//    implementation 'com.google.http-client:google-http-client-gson:1.26.0'
//    implementation('com.google.api-client:google-api-client-android:1.26.0') {
//        exclude group: 'org.apache.httpcomponents'
//    }
//    implementation('com.google.apis:google-api-services-drive:v3-rev136-1.25.0') {
//        exclude group: 'org.apache.httpcomponents'
//    }
    //implementation 'com.google.android.gms:play-services-drive:9.0.2'
    implementation 'com.google.android.gms:play-services-drive:8.4.0'
    implementation('com.google.api-client:google-api-client-android:1.23.0') {
        exclude group: 'org.apache.httpcomponents'
    }
    implementation 'com.google.api-client:google-api-client:1.25.0'
    implementation('com.google.apis:google-api-services-drive:v3-rev29-1.22.0') {
        exclude group: 'org.apache.httpcomponents'
    }

    implementation 'com.google.oauth-client:google-oauth-client-jetty:1.23.0'
}

apply plugin: 'com.google.gms.google-services'


Issue:
--------------
on saving file to drive it throws  ->  java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/api/Api$zzc;
        at com.google.android.gms.drive.Drive.<clinit>(Unknown Source:0)

class:
-------


Drive.DriveApi.newDriveContents(mGoogleApiClient).setResultCallback(new ResultCallback<DriveContentsResult>() {
            @Override
            public void onResult(DriveContentsResult result) {
                // If the operation wasn't successful, return
                if (!result.getStatus().isSuccess()) {
                    Log.e(TAG, "Failed to create new content!.");
                    return;
                }
                Log.i(TAG, "New content has been created.");
                // Get an output stream for the contents.
                OutputStream outputStream = result.getDriveContents().getOutputStream();
                // Write the bitmap data from it.
                ByteArrayOutputStream bitmapStream = new ByteArrayOutputStream();
                image.compress(Bitmap.CompressFormat.PNG, 100, bitmapStream);
                try {
                    outputStream.write(bitmapStream.toByteArray());
                } catch (IOException e1) {
                    Log.i(TAG, "Unable to write file contents.");
                }
                // Create the initial metadata - MIME type and title.
                // Note that the user will be able to change the title later.
                MetadataChangeSet metadataChangeSet = new MetadataChangeSet.Builder()
                        .setMimeType("image/jpeg").setTitle("myPhoto.png").build();
                // Create an intent for the file chooser, and start it.
                IntentSender intentSender = Drive.DriveApi
                        .newCreateFileActivityBuilder()
                        .setInitialMetadata(metadataChangeSet)
                        .setInitialDriveContents(result.getDriveContents())
                        .build(mGoogleApiClient);
                try {
                    startIntentSenderForResult(
                            intentSender, REQUEST_CODE_CREATOR, null, 0, 0, 0);
                } catch (SendIntentException e) {
                    Log.i(TAG, "Failed to launch file chooser.");
                }
            }
        });

**Comment by LogeshwariMurugan** [comment]
Please help me to get solved . Because im doing research for more than 3 days for drive upload from my new android app.

**Comment by lcustodio** [comment]
Hey @LogeshwariMurugan 
I found dependencies of one signal into gms

![image](https://user-images.githubusercontent.com/585672/51645686-50436080-1f6d-11e9-87a4-bf9e298a6306.png)

Adding the base services resolved the main dependencies in my case, maybe worth a try?

```
dependencies {
    compile 'com.google.android.gms:play-services-base:16.1.0'
    compile project(':react-native-onesignal')
    ....
    ....
}
```

**Comment by hadnazzar** [comment]
@pacozaa 

you should put 

`buildscript {
    repositories {
        maven { url 'https://plugins.gradle.org/m2/' } // Gradle Plugin Portal 
    }
    dependencies {
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.1, 0.99.99]'
    }
}

apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'
`

Top of the **app/build.gradle** file

**Comment by tanmayrsm** [comment]
> I had a very similar problem. I solved it by adding following lines in my build.gradle for app module.
> 
> ```
> buildscript {
>     repositories {
>         maven { url 'https://plugins.gradle.org/m2/'}
>     }
>     dependencies {
>         classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.11.0, 0.99.99]'
>     }
> }
> apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'
> 
> repositories {
>     maven { url 'https://maven.google.com' }
> }
> ```
> 
> Make sure you are adding and applying OneSignal gradle plugin. You can check up to date versions from [OneSignal Android SDK](https://documentation.onesignal.com/docs/android-sdk-setup) documentation.

Got htis -> ERROR: Plugin with id 'com.onesignal.androidsdk.onesignal-gradle-plugin' not found.
