### ISSUE TITLE
Error:Execution failed for task ':app:processDebugManifest'.

### ISSUE THREAD

**Issue by umutg4d** [OneSignal/OneSignal-Android-SDK#300]
I am getting error when building gradle for my project and i think it is related to onesignal plugin because when i extract it , build completes succesfully . Here's the full output message. 

Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(25.4.0) from [com.android.support:design:25.3.1] AndroidManifest.xml:27:9-31
  	is also present at [com.android.support:support-v4:26.1.0] AndroidManifest.xml:28:13-35 value=(26.1.0).
  	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:26:9-28:38 to override.

This is the app.gradle for my project.

```gradle
apply plugin: 'com.android.application'
apply plugin: 'io.fabric'

repositories {
    maven { url 'https://maven.fabric.io/public' }
}

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.3"

    defaultConfig {
        applicationId "com.tilda.tv8"
        minSdkVersion 19
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        manifestPlaceholders = [onesignal_app_id               : "72a4da4e-0a6e-422b-892b-fd60436c702e",
                                // Project number pulled from dashboard, local value is ignored.
                                onesignal_google_project_number: "REMOTE"]
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])

    compile('com.crashlytics.sdk.android:crashlytics:2.6.8@aar') {
        transitive = true;
    }
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.android.support:design:25.3.1'
    compile 'com.android.support:support-v4:25.3.1'
    compile 'com.google.code.gson:gson:2.4'
    compile 'com.android.volley:volley:1.0.0'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.android.support:cardview-v7:25.3.1'
    compile 'com.google.ads.interactivemedia.v3:interactivemedia:3.6.0'
    compile 'com.google.android.gms:play-services-ads:11.2.0'
    compile 'com.devbrackets.android:exomedia:4.0.3'
    compile 'de.hdodenhof:circleimageview:2.1.0'
    compile 'pl.droidsonroids.gif:android-gif-drawable:1.2.+'
    compile 'com.google.android.gms:play-services-analytics:11.2.0'
    compile 'com.onesignal:OneSignal:[3.6.0, 3.99.99]'
    testCompile 'junit:junit:4.12'
}
```

Also i did the suggested solution in trobuleshooting, but it doesn't work. 'https://documentation.onesignal.com/docs/troubleshooting-android#section-error-failed-to-resolve-com-android-support-customtabs-26-0-0-26-1-0-'

**Comment by jkasten2** [comment]
@umutg4d You need to updated all your `com.android.support:` entries to version 26.1.0. This is required for version 26 of the support library is required for version 3.6.0 of OneSignal

**Comment by umutg4d** [comment]
I did what you said and it builds succesfully but now this error shows up.

> FATAL EXCEPTION: main
                                                             Process: com.tilda.tv8, PID: 2713
                                                             java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/safeparcel/zza;
                                                                 at com.google.android.gms.ads.InterstitialAd.<init>(Unknown Source)
                                                                 at com.tilda.tv8.MainActivity.onCreate(MainActivity.java:182)
                                                                 at android.app.Activity.performCreate(Activity.java:6662)
                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
                                                                 at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                 at android.os.Looper.loop(Looper.java:154)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
                                                              Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.internal.safeparcel.zza" on path: DexPathList[[zip file "/data/app/com.tilda.tv8-2/base.apk", zip file "/data/app/com.tilda.tv8-2/split_lib_dependencies_apk.apk", zip file "/data/app/com.tilda.tv8-2/split_lib_slice_0_apk.apk", zip file "/data/app/com.tilda.tv8-2/split_lib_slice_1_apk.apk", zip file "/data/app/com.tilda.tv8-2/split_lib_slice_2_apk.apk", zip file "/data/app/com.tilda.tv8-2/split_lib_slice_3_apk.apk", zip file "/data/app/com.tilda.tv8-2/split_lib_slice_4_apk.apk", zip file "/data/app/com.tilda.tv8-2/split_lib_slice_5_apk.apk", zip file "/data/app/com.tilda.tv8-2/split_lib_slice_6_apk.apk", zip file "/data/app/com.tilda.tv8-2/split_lib_slice_7_apk.apk", zip file "/data/app/com.tilda.tv8-2/split_lib_slice_8_apk.apk", zip file "/data/app/com.tilda.tv8-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.tilda.tv8-2/lib/x86_64, /data/app/com.tilda.tv8-2/base.apk!/lib/x86_64, /data/app/com.tilda.tv8-2/split_lib_dependencies_apk.apk!/lib/x86_64, /data/app/com.tilda.tv8-2/split_lib_slice_0_apk.apk!/lib/x86_64, /data/app/com.tilda.tv8-2/split_lib_slice_1_apk.apk!/lib/x86_64, /data/app/com.tilda.tv8-2/split_lib_slice_2_apk.apk!/lib/x86_64, /data/app/com.tilda.tv8-2/split_lib_slice_3_apk.apk!/lib/x86_64, /data/app/com.tilda.tv8-2/split_lib_slice_4_apk.apk!/lib/x86_64, /data/app/com.tilda.tv8-2/split_lib_slice_5_apk.apk!/lib/x86_64, /data/app/com.tilda.tv8-2/split_lib_slice_6_apk.apk!/lib/x86_64, /data/app/com.tilda.tv8-2/split_lib_slice_7_apk.apk!/lib/x86_64, /data/app/com.tilda.tv8-2/split_lib_slice_8_apk.apk!/lib/x86_64, /data/app/com.tilda.tv8-2/split_lib_slice_9_apk.apk!/lib/x86_64, /system/lib64, /vendor/lib64]]
                                                                 at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                 at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                                 at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                 at com.google.android.gms.ads.InterstitialAd.<init>(Unknown Source) 
                                                                 at com.tilda.tv8.MainActivity.onCreate(MainActivity.java:182) 
                                                                 at android.app.Activity.performCreate(Activity.java:6662) 
                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118) 
                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599) 
                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707) 
                                                                 at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460) 
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                 at android.os.Looper.loop(Looper.java:154) 
                                                                 at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) 
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756) 
09-16 01:28:56.523 2713-2764/com.tilda.tv8 E/GAv4: Successfully bound to service but never got onServiceConnected callback

There is open issue about this problem here https://github.com/OneSignal/OneSignal-Android-SDK/issues/298
