### ISSUE TITLE
transformClassesWithDexForRelease

### ISSUE THREAD

**Issue by Axladrian** [OneSignal/OneSignal-Android-SDK#341]
Having an issue with oneSignal when building my apk for release. Getting the following error:
```
Error:Execution failed for task ':app:transformClassesWithDexForProductionRelease'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Translation has been interrupted
```
In build.gradle I have:
```
manifestPlaceholders = [onesignal_app_id               : "MY_KEY_IS_HERE",
    // Project number pulled from dashboard, local value is ignored.
    onesignal_google_project_number: "REMOTE"]
```
and
```    compile 'com.onesignal:OneSignal:3.6.4'```

If I remove all references to OneSignal, the APK compiles with no problem. Multidex is enabled.

**Comment by jkasten2** [comment]
@Axladrian Can you make sure you have copied the full error? It should provide more details.

Can you copy in your full `build.gradle` as well?

Lastly what version of Android Studio are you using?

Thanks.

**Comment by Axladrian** [comment]
Getting this error on Android Studio 2 (2.3.3) and 3 (RC2 + Beta 7). 
Tried to clean, rebuild, invalidate cache, restart AS, restart mac. Getting it 100% of the time.

Unfortunately, that was the full error. Ran the gradle process now maybe I'm gonna get more info with the --stacktrace option.

Until it finishes, my build.gradle:

```
apply plugin: 'com.android.application'
apply plugin: 'io.fabric'
apply plugin: 'android-apt'
apply plugin: 'me.tatarka.retrolambda'


android {
    compileSdkVersion project.compileSdkVersion
    buildToolsVersion project.buildToolsVersion
    defaultConfig {
        applicationId "myAppid"
        minSdkVersion project.minSdkVersion
        targetSdkVersion project.targetSdkVersion
        multiDexEnabled true
        versionCode 18
        versionName "1.1.0"

        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

        manifestPlaceholders = [onesignal_app_id               : "MY_KEY_IS_HERE",
                                // Project number pulled from dashboard, local value is ignored.
                                onesignal_google_project_number: "REMOTE"]
    }
    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    lintOptions {
        checkReleaseBuilds false
    }
    packagingOptions {
        exclude 'publicsuffixes.gz'
    }

}

repositories {
    maven { url "https://jitpack.io" }
    maven { url 'https://maven.fabric.io/public' }
    maven { url "https://maven.google.com" }
}


dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.facebook.android:facebook-android-sdk:4.26.0'
    compile 'com.onesignal:OneSignal:3.6.4'

    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile "com.android.support:support-v4:${project.supportLibraryVersion}"
    compile "com.android.support:appcompat-v7:${project.supportLibraryVersion}"
    compile "com.android.support:support-v13:${project.supportLibraryVersion}"
    compile "com.android.support:design:${project.supportLibraryVersion}"
    compile "com.android.support:cardview-v7:${project.supportLibraryVersion}"

    compile "com.google.firebase:firebase-messaging:${project.googleServicesVersion}"
    compile "com.google.firebase:firebase-core:${project.googleServicesVersion}"
    compile "com.google.firebase:firebase-auth:${project.googleServicesVersion}"
    compile "com.google.android.gms:play-services-vision:${project.googleServicesVersion}"
    compile "com.google.android.gms:play-services-auth:${project.googleServicesVersion}"

    //networking
    compile 'com.squareup.retrofit2:retrofit:2.3.0'
    compile 'com.squareup.retrofit2:converter-gson:2.3.0'
    compile 'com.squareup.retrofit2:converter-scalars:2.1.0'
    compile 'com.squareup.retrofit2:adapter-rxjava:2.1.0'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.github.mrmike:Ok2Curl:0.3.0'

    //reactive
    compile 'io.reactivex:rxandroid:1.2.1'
    compile 'io.reactivex:rxjava:1.2.6'
    compile 'com.tbruyelle.rxpermissions:rxpermissions:0.9.4@aar'

    //helpers
    compile 'com.android.support:multidex:1.0.1'
    compile 'com.github.bumptech.glide:glide:4.0.0'
    compile 'net.opacapp:multiline-collapsingtoolbar:1.3.1'
    compile 'uk.co.chrisjenx:calligraphy:2.3.0'
    compile 'com.googlecode.libphonenumber:libphonenumber:7.0.9'
    compile 'com.google.android:flexbox:0.2.5'
    compile 'org.florescu.android.rangeseekbar:rangeseekbar-library:0.3.0'
    compile 'org.zakariya.stickyheaders:stickyheaders:0.7.6'
    compile 'com.afollestad:sectioned-recyclerview:0.5.0'
    compile 'com.jakewharton:butterknife:8.6.0'
    apt 'com.jakewharton:butterknife-compiler:8.6.0'

    compile 'io.intercom.android:intercom-sdk-base:4+'
    compile 'io.intercom.android:intercom-sdk-fcm:4+'

    //debug
    debugCompile 'com.squareup.leakcanary:leakcanary-android:1.5.1'
    releaseCompile 'com.squareup.leakcanary:leakcanary-android-no-op:1.5.1'
    compile 'com.facebook.stetho:stetho:1.5.0'
    compile 'com.facebook.stetho:stetho-okhttp3:1.5.0'
    compile 'com.github.tony19:timber-loggly:1.0.1'
    compile('com.crashlytics.sdk.android:crashlytics:2.6.8@aar') {
        transitive = true;
    }

    testCompile 'junit:junit:4.12'

}
apply plugin: 'com.google.gms.google-services'
```

```
project.ext {
    minSdkVersion = 16
    targetSdkVersion = 25
    compileSdkVersion = 26
    buildToolsVersion = "26.0.1"
    supportLibraryVersion = "26.1.0"
    googleServicesVersion = "11.4.0"
}
```

**Comment by Axladrian** [comment]
Full stacktrace for transformClassesWithDexForProductionRelease
```
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformClassesWithDexForProductionRelease'.
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
    at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:63)
    at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
    at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
    at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
    at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
    at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
    at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
    at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
    at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
    at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
    at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
    at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
    at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
    at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
    at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
    at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
    at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:124)
    at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:80)
    at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:105)
    at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:99)
    at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:625)
    at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:580)
    at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:99)
    at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
    at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
    at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.RuntimeException: com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Translation has been interrupted
    at com.android.builder.profile.Recorder$Block.handleException(Recorder.java:55)
    at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:104)
    at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:176)
    at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
    at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:173)
    at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
    at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:121)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:122)
    at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
    at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
    at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
    at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
    ... 27 more
Caused by: com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Translation has been interrupted
    at com.android.build.gradle.internal.transforms.DexTransform.transform(DexTransform.java:453)
    at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:185)
    at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:181)
    at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
    ... 39 more
Caused by: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Translation has been interrupted
    at com.android.builder.core.DexByteCodeConverter.dexInProcess(DexByteCodeConverter.java:180)
    at com.android.builder.core.DexByteCodeConverter.runDexer(DexByteCodeConverter.java:158)
    at com.android.builder.core.DexByteCodeConverter.convertByteCode(DexByteCodeConverter.java:143)
    at com.android.builder.core.AndroidBuilder.convertByteCode(AndroidBuilder.java:1345)
    at com.android.build.gradle.internal.transforms.DexTransform.transform(DexTransform.java:279)
    ... 42 more
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Translation has been interrupted
    at com.android.builder.core.DexByteCodeConverter.dexInProcess(DexByteCodeConverter.java:178)
    ... 46 more
Caused by: java.lang.RuntimeException: Translation has been interrupted
    at com.android.dx.command.dexer.Main.processAllFiles(Main.java:631)
    at com.android.dx.command.dexer.Main.runMultiDex(Main.java:376)
    at com.android.dx.command.dexer.Main.run(Main.java:290)
    at com.android.builder.internal.compiler.DexWrapper.run(DexWrapper.java:54)
    at com.android.builder.core.DexByteCodeConverter.lambda$dexInProcess$0(DexByteCodeConverter.java:174)
Caused by: java.lang.InterruptedException: Too many errors
    at com.android.dx.command.dexer.Main.processAllFiles(Main.java:623)
    ... 4 more
```

**Comment by Axladrian** [comment]
Hmmm, it seems that if I add transitive as false it's ok. Could be a mismatch between googleServices 11.4.2 and 11.2.2 used by OneSignal?

```
compile('com.onesignal:OneSignal:3.6.4') {
        transitive = false;
    }
```

**Comment by jkasten2** [comment]
@Axladrian Ah yes you are correct. OneSignal 3.6.4 includes a dependency on `com.google.android.gms:play-services-gcm:11.2.+` however the other `com.google.android.gms` libraries in your project are using 11.4.0.

The `transitive = false;` will fix your build errors however you will get runtime errors which will cause OneSignal not to work as `play-services-gcm` is no longer being included in your APK.

The manual group version alignment of gms, firebase, and the support libraries can be a pain especially with nested dependencies with Gradle. We have created a plugin that is beta that will align these automatically to resolve this issue I recommend trying.
https://github.com/OneSignal/OneSignal-Gradle-Plugin

I think you must have gotten a number of other errors before the one you pasted above. As the `Translation has been interrupted` error was due to `Too many errors`.
```Java
Caused by: java.lang.RuntimeException: Translation has been interrupted
...
Caused by: java.lang.InterruptedException: Too many errors
```

**Comment by Axladrian** [comment]
That was the whole error stack unfortunately. 

Yea, you're right. I thought that with `transitive = false` it will just use my version instead. Thanks for clearing that up 👍 indeed notifications wouldn't have worked.

Tried the plugin, working very well, could generate the apk and had no problem with notifications.

**Comment by Harivinoth** [comment]
Hi,

I got same issues when i run my project using terminal the below issues got can anyone please helpme?

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithJarMergingForRelease'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: org/apache/cordova/BuildHelper.class

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by jkasten2** [comment]
@Harivinoth The `org/apache/cordova/BuildHelper.class` entry is from Cordova itself not part of OneSignal. It seems your project got into a broken build state. I recommend following the suggested answer below to do a clean build of your project.

https://stackoverflow.com/questions/47020816/error-with-ionic-app-execution-failed-for-task-transformclasseswithjarmerging
