### ISSUE TITLE
NotificationExtenderService not working 

### ISSUE THREAD

**Issue by Yogi1994** [OneSignal/OneSignal-Android-SDK#355]
```Java
E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.projectname, PID: 17935
java.lang.VerifyError: Verifier rejected class com.packagename.NotificationExtenderOneSignal due to bad method java.lang.Object
  packagename.NotificationExtenderOneSignal.access$super(com.packagename.NotificationExtenderOneSignal, java.lang.String, java.lang.Object[])
  (declaration of 'com.packagename.NotificationExtenderOneSignal' appears in /data/app/com.projectname-2/split_lib_slice_5_apk.apk)
    at java.lang.reflect.Constructor.newInstance(Native Method)
    at java.lang.Class.newInstance(Class.java:1690)
    at android.app.ActivityThread.handleCreateService(ActivityThread.java:3639)
    at android.app.ActivityThread.access$2000(ActivityThread.java:218)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1801)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:145)
    at android.app.ActivityThread.main(ActivityThread.java:6917)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

Last week it was working nicely but today it is failing.

**Comment by jkasten2** [comment]
@Yogi1994 Are you using the latest 3.6.5 Android SDK? Can you try a clean build of your project?

Please attach you `NotificationExtenderOneSignal` class and we can take a look if the above does not help.

**Comment by Yogi1994** [comment]
@jkasten2 I think not the latest SDK. ( I mean I have not updated it in last 2 months ) 
Yes, I tried clean build, restart but nothing helped.
I even tried commenting everything from the NotificationExtenderOneSignal and left with the basic empty example given in the docs. given as follows:
```
import com.onesignal.OSNotificationPayload;
import com.onesignal.NotificationExtenderService;

public class NotificationExtenderBareBonesExample extends NotificationExtenderService {
   @Override
   protected boolean onNotificationProcessing(OSNotificationReceivedResult receivedResult) {
     	// Read properties from result.
     
      // Return true to stop the notification from displaying.
      return false;
   }
}
```

**Comment by jkasten2** [comment]
@Yogi1994 Thanks for the details, can you also attach your root `build.gradle` and your app's `app/build.gradle` files?

**Comment by Yogi1994** [comment]
Oh I updated the OneSignal SDK when I get to know that the app is crashing on receiving OneSignal notification.

```
apply plugin: 'com.android.application'
apply plugin: 'io.fabric'

repositories {
    maven { url 'https://maven.fabric.io/public' }
    maven { url 'https://maven.google.com' }
}

android {
    signingConfigs {
        testingrelease {
            // Removed 
        }
    }
    lintOptions {
        disable 'MissingTranslation'
    }
    splits {

        // Configures multiple APKs based on ABI.
        abi {

            // Enables building multiple APKs per ABI.
            enable true

            // By default all ABIs are included, so use reset() and include to specify that we only
            // want APKs for x86, armeabi-v7a, and mips.

            // Resets the list of ABIs that Gradle should create APKs for to none.
            reset()

            // Specifies a list of ABIs that Gradle should create APKs for.
//            include "x86", "armeabi-v7a", "mips"

            // Specifies that we do not want to also generate a universal APK that includes all ABIs.
            universalApk true

        }
    }
    sourceSets
            {
                main
                        {
                            jniLibs.srcDirs = [
                                    'src/main/jnilibs'
                            ]

                            res.srcDirs = [
                                    'src/main/res/layouts/components/navbar',
                                    'src/main/res/layouts/screens',
                                    'src/main/res/layouts/activities',
                                    'src/main/res/layouts/components/list_cards',
                                    'src/main/res/layouts/components/form_fields',
                                    'src/main/res/layouts',
                                    'src/main/res'
                            ]
                        }
                //Another code
            }
    compileSdkVersion 26
    buildToolsVersion '26.0.0'
    defaultConfig {
        applicationId "com.projectname"
        minSdkVersion 16
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

        multiDexEnabled true


        manifestPlaceholders = ["onesignal_app_id"               : "MY_APP_ID ",
                                "onesignal_google_project_number": 'My_G_Project_Num']
//        jackOptions {
//            enabled true
//        }
    }
    flavorDimensions "biometric_interface", "testing_distribution"
    productFlavors {
        usb {
            dimension "biometric_interface"
//            buildConfigField "String", "flavour_usb", "usb"


        }
        bluetooth
                {
                    dimension "biometric_interface"
//                    buildConfigField "boolean", "DRAW_VIEWS_FOR_TESTING", "false"


                }
        distribution {
            dimension "testing_distribution"

            buildConfigField "boolean", "DRAW_VIEWS_FOR_TESTING", "false"

        }

        flavoreTesting {
            dimension "testing_distribution"

            buildConfigField "boolean", "DRAW_VIEWS_FOR_TESTING", "true"
        }


    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
//
//    compileOptions {
//        targetCompatibility 1.8
//        sourceCompatibility 1.8
//    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    //    compile fileTree(dir: "$buildDir/native-libs", include: 'native-libs.jar')
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile('com.crashlytics.sdk.android:crashlytics:2.6.8@aar') {
        transitive = true;
    }
    compile files('libs/Analogics_Bt_Biometrics_1.3.jar')
    compile files('libs/org-apache-commons-codec.jar')
    compile 'com.github.stfalcon:smsverifycatcher:0.3.1'
    compile 'com.android.support:appcompat-v7:26.0.2'
    compile 'de.hdodenhof:circleimageview:2.1.0'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile 'com.android.support:design:26.0.2'
    compile 'org.greenrobot:greendao:3.2.0'
    compile 'com.android.support:support-v4:26.0.2'
    compile 'eu.the4thfloor.volley:com.android.volley:2015.05.28'
    compile 'com.google.code.gson:gson:2.8.1'
    compile 'com.google.firebase:firebase-messaging:11.2.+'
    compile 'com.google.firebase:firebase-crash:11.2.+'
    compile 'com.google.android.gms:play-services-gcm:11.2.+'
    compile 'com.google.android.gms:play-services-location:11.2.+'
    compile 'com.android.support:multidex:1.0.1'
    compile 'com.android.support:cardview-v7:26.0.2'
    compile 'com.android.support:recyclerview-v7:26.0.2'
    compile 'com.onesignal:OneSignal:[3.6.4, 3.99.99]' // Today updated it from 3.6.2 to 3.6.4 after getting error.
    testCompile 'junit:junit:4.12'
}

configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        def requested = details.requested
        if (requested.group == 'com.android.support') {
            if (!requested.name.startsWith("multidex")) {
                details.useVersion '26.0.2'
            }
        }
    }
}


apply plugin: 'com.google.gms.google-services'
```

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
        maven { url 'https://maven.fabric.io/public' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.3'
        classpath 'org.greenrobot:greendao-gradle-plugin:3.2.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
        classpath 'com.google.gms:google-services:3.1.0'
        classpath 'io.fabric.tools:gradle:1.+'
    }
}

allprojects {
    repositories {
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

I don't think there is any problem in gradle files  though. :/

**Comment by Yogi1994** [comment]
Hello @jkasten2 I have changed gradle file as per the latest documentation but now I think I am getting some error due to gradle used in OneSignal. 
``` Cannot change strategy configuration ':app: FLAVOUR_VARIENT_WearApp' after it has been resolved```
can anyone tell help me out here.

**Comment by jkasten2** [comment]
@Yogi1994 This is due to an issue with OneSignal gradle plugin you can track here.
https://github.com/OneSignal/OneSignal-Gradle-Plugin/issues/7

**Comment by jkasten2** [comment]
@Yogi1994 The `FLAVOUR_VARIENT_WearApp` error has been fixed in the [OneSignal-Gradle-Plugin version 0.8.0](https://github.com/OneSignal/OneSignal-Gradle-Plugin/releases/tag/0.8.0). Updating and rebuilding your project should fix this error.
