### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException bad array lengths

### ISSUE THREAD

**Issue by naseeb8950925214** [OneSignal/OneSignal-Android-SDK#394]
```java
**Fatal Exception: java.lang.RuntimeException: bad array lengths**
       at android.os.Parcel.readIntArray(Parcel.java:789)
       at android.app.INotificationManager$Stub$Proxy.enqueueNotificationWithTag(INotificationManager.java:314)
       at android.app.NotificationManager.notify(NotificationManager.java:127)
       at android.support.v4.app.NotificationManagerCompat.notify(SourceFile:207)
       at android.support.v4.app.NotificationManagerCompat.notify(SourceFile:191)
       at com.onesignal.j.d(SourceFile:380)
       at com.onesignal.j.a(SourceFile:106)
       at com.onesignal.m.a(SourceFile:101)
       at com.onesignal.m.a(SourceFile:78)
       at com.onesignal.GcmIntentService.onHandleIntent(SourceFile:60)
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:177)
       at android.os.HandlerThread.run(HandlerThread.java:60)
```

**Comment by naseeb8950925214** [comment]
Using this version of support library:
implementation 'com.android.support:appcompat-v7:26.1.0'

**Comment by jkasten2** [comment]
@naseeb8950925214 Are you able to reproduce this crash on a test device? Could you let us know which version of the OneSignal SDK and the Android version of the device?

Could you also link this issue to OneSignal support and let them know which notification id triggered the crash?

**Comment by denisshikunets** [comment]
have the same issues, support library 27.0.2, one signal version 3.8.1
reproduced only on android 4, most popular devices is Galaxy Tab3 Lite 7.0

**Comment by jkasten2** [comment]
@naseeb8950925214 @denisshikunets We just released [version 3.8.2](https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/3.8.2) which may have fixed this issue, which might be related to issue #263. Let us know if it does or does not and we can dig in further. Thanks!

**Comment by jkasten2** [comment]
Crash from a Android 6.0 device, model Vibrance RQ-560

```java
#0. Crashed: AsyncTask #1
       at android.os.AsyncTask$3.done(AsyncTask.java:300)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:848)

--

Fatal Exception: java.lang.RuntimeException: An error occured while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:300)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:848)

Caused by java.lang.RuntimeException: bad array lengths
       at android.os.Parcel.readIntArray(Parcel.java:820)
       at android.app.INotificationManager$Stub$Proxy.enqueueNotificationWithTag(INotificationManager.java:332)
       at android.app.NotificationManager.notify(NotificationManager.java:136)
       at android.support.v4.app.NotificationManagerCompat.notify(NotificationManagerCompat.java:210)
       at android.support.v4.app.NotificationManagerCompat.notify(NotificationManagerCompat.java:194)
       at com.onesignal.GenerateNotification.showNotification(GenerateNotification.java:369)
       at com.onesignal.GenerateNotification.fromJsonPayload(GenerateNotification.java:106)
       at com.onesignal.NotificationBundleProcessor.ProcessJobForDisplay(NotificationBundleProcessor.java:101)
       at com.onesignal.NotificationExtenderService.processJsonObject(NotificationExtenderService.java:203)
       at com.onesignal.NotificationExtenderService.processIntent(NotificationExtenderService.java:155)
       at com.onesignal.NotificationExtenderService.onHandleWork(NotificationExtenderService.java:123)
       at com.onesignal.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:386)
       at com.onesignal.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:377)
       at android.os.AsyncTask$2.call(AsyncTask.java:288)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:848)
```

**Comment by jkasten2** [comment]
@jgersindemir Thanks for reporting.

@jgersindemir @naseeb8950925214 Almost all devices we have seen reporting this issue have been 7.0 so I believe the changes we made for #263 also fixed this issue. We also haven't seen any recent reports of this issue. Closing this as resolved.
