### ISSUE TITLE
Exception in NotificationServiceExtender

### ISSUE THREAD

**Issue by fedorcomander** [OneSignal/OneSignal-Android-SDK#396]
```java
 Error saving notification record! 
12-15 14:36:44.754  3228  3538 E OneSignal: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
12-15 14:36:44.754  3228  3538 E OneSignal: 	at com.onesignal.NotificationGenerationJob.getAndroidIdWithoutCreate(NotificationGenerationJob.java:82)
12-15 14:36:44.754  3228  3538 E OneSignal: 	at com.onesignal.NotificationBundleProcessor.saveNotification(NotificationBundleProcessor.java:156)
12-15 14:36:44.754  3228  3538 E OneSignal: 	at com.onesignal.NotificationBundleProcessor.ProcessJobForDisplay(NotificationBundleProcessor.java:104)
12-15 14:36:44.754  3228  3538 E OneSignal: 	at com.onesignal.NotificationExtenderService.displayNotification(NotificationExtenderService.java:110)
12-15 14:36:44.754  3228  3538 E OneSignal: 	at com.onesignal.AcousticProtocolNotificationListener.onNotificationProcessing(AcousticProtocolNotificationListener.java:241)
12-15 14:36:44.754  3228  3538 E OneSignal: 	at com.onesignal.NotificationExtenderService.processJsonObject(NotificationExtenderService.java:170)
12-15 14:36:44.754  3228  3538 E OneSignal: 	at com.onesignal.NotificationExtenderService.processIntent(NotificationExtenderService.java:155)
12-15 14:36:44.754  3228  3538 E OneSignal: 	at com.onesignal.NotificationExtenderService.onHandleWork(NotificationExtenderService.java:123)
12-15 14:36:44.754  3228  3538 E OneSignal: 	at com.onesignal.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:386)
12-15 14:36:44.754  3228  3538 E OneSignal: 	at com.onesignal.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:377)
12-15 14:36:44.754  3228  3538 E OneSignal: 	at android.os.AsyncTask$2.call(AsyncTask.java:305)
12-15 14:36:44.754  3228  3538 E OneSignal: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
12-15 14:36:44.754  3228  3538 E OneSignal: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
12-15 14:36:44.754  3228  3538 E OneSignal: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
12-15 14:36:44.754  3228  3538 E OneSignal: 	at java.lang.Thread.run(Thread.java:761)
12-15 14:36:44.755  3228  3538 D OneSignalExample: Notification displayed with id: 1550495347
```

**Comment by fedorcomander** [comment]
Any help?

**Comment by jkasten2** [comment]
@fedorcomander Can you share you `AcousticProtocolNotificationListener.onNotificationProcessing` code as well?

**Comment by jkasten2** [comment]
@fedorcomander This issue occurs when a message body `contents` is set on the notification sent from OneSignal. Can you make sure this is always set? You can still just replace the full contains in your extender.

I'll still mark this as a bug as the SDK should still handle this edge case through in the future.
