### ISSUE TITLE
Android Oreo 8.0.0 push notification issue..app crashes

### ISSUE THREAD

**Issue by kichushanil** [OneSignal/OneSignal-Android-SDK#405]
E/OneSignal: The included Android Support Library is to old or incomplete. Please update to the 26.0.0 revision or newer.
                                            java.lang.ClassNotFoundException: android.support.v4.app.JobIntentService
                                                at java.lang.Class.classForName(Native Method)
                                                at java.lang.Class.forName(Class.java:453)
                                                at java.lang.Class.forName(Class.java:378)
                                                at com.onesignal.OSUtils.initializationChecker(OSUtils.java:99)
                                                at com.onesignal.OneSignal.init(OneSignal.java:492)
                                                at com.onesignal.OneSignal.init(OneSignal.java:468)
                                                at com.onesignal.OneSignal.access$000(OneSignal.java:79)
                                                at com.onesignal.OneSignal$Builder.init(OneSignal.java:283)
                                                at codmob.com.campuswallet.app.CampusWallet.onCreate(CampusWallet.java:74)
                                                at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
                                                at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5827)
                                                at android.app.ActivityThread.-wrap1(Unknown Source:0)
                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1673)
                                                at android.os.Handler.dispatchMessage(Handler.java:105)
                                                at android.os.Looper.loop(Looper.java:172)
                                                at android.app.ActivityThread.main(ActivityThread.java:6637)
                                                at java.lang.reflect.Method.invoke(Native Method)
                                                at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                             Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.app.JobIntentService" on path: DexPathList[[zip file "/data/app/com.chillarcards.campuswallet-AVeEnMxk7b1O8H7af3-euw==/base.apk"],nativeLibraryDirectories=[/data/app/com.chillarcards.campuswallet-AVeEnMxk7b1O8H7af3-euw==/lib/arm64, /data/app/com.chillarcards.campuswallet-AVeEnMxk7b1O8H7af3-euw==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
                                                at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
                                                at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                at java.lang.Class.classForName(Native Method) 
                                                at java.lang.Class.forName(Class.java:453) 
                                                at java.lang.Class.forName(Class.java:378) 
                                                at com.onesignal.OSUtils.initializationChecker(OSUtils.java:99) 
                                                at com.onesignal.OneSignal.init(OneSignal.java:492) 
                                                at com.onesignal.OneSignal.init(OneSignal.java:468) 
                                                at com.onesignal.OneSignal.access$000(OneSignal.java:79) 
                                                at com.onesignal.OneSignal$Builder.init(OneSignal.java:283) 
                                                at codmob.com.campuswallet.app.CampusWallet.onCreate(CampusWallet.java:74) 
                                                at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119) 
                                                at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5827) 
                                                at android.app.ActivityThread.-wrap1(Unknown Source:0) 
                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1673) 
                                                at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                at android.os.Looper.loop(Looper.java:172) 
                                                at android.app.ActivityThread.main(ActivityThread.java:6637) 
                                                at java.lang.reflect.Method.invoke(Native Method) 
                                                at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by jkasten2** [comment]
@kichushanil Make sure you add the following at the very top of your `app/build.gradle`.
```gradle
plugins {
    id 'com.onesignal.androidsdk.onesignal-gradle-plugin' version '0.8.0'
}
apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'
```

This will make sure all the required dependencies are added and are the correct versions.

**Comment by ashfaqbinnazar** [comment]
Added this but still app crashes and push is not receiving

plugins {
    id 'com.onesignal.androidsdk.onesignal-gradle-plugin' version '0.8.0'
}
apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'

**Comment by jkasten2** [comment]
@ashfaqbinnazar Is the error and stacktrace the same on the crash?

Do you have any code in your `build.gradle` using `resolutionStrategy` that is lowering the version number of android.support.v4? Can you share your full `app/build.gradle` and your root `build.gradle` here?

**Comment by ashfaqbinnazar** [comment]
issue solved.
Sincerely,Ashfaq bin nazar
 

    On Wednesday, January 17, 2018, 4:06:29 AM GMT+5:30, Josh Kasten <notifications@github.com> wrote:  
 
 
@ashfaqbinnazar Is the error and stacktrace the same on the crash?

Do you have any code in your build.gradle using resolutionStrategy that is lowering the version number of android.support.v4? Can you share your full app/build.gradle and your root build.gradle here?

**Comment by vigneshr87** [comment]
I am facing the same issue and my resolution strategy is

configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        def requested = details.requested
        if (requested.group == 'com.android.support') {
            if (!requested.name.startsWith("multidex")) {
                details.useVersion '25.3.0'
            }
        }
    }
}

**Comment by jkasten2** [comment]
@vigneshr87 `25.3.0` will be to low if you are using `targetSdkVersion` 26 or higher. I recommend on removing your `resolutionStrategy` code and use the `onesignal-gradle-plugin` instead as this has it's own `resolutionStrategy` that will always pick the correct version.

Add the following to the top of your `app/build.gradle` to use it.
```gradle
buildscript {
    repositories {
        maven { url 'https://plugins.gradle.org/m2/'}
    }
    dependencies {
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:0.8.1'
    }
}
apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'
```

**Comment by vigneshr87** [comment]
@jkasten2   After removing resolutionStrategy , the above exception disappeared but my app crash while receiving notification
                 java.lang.AbstractMethodError: abstract method "void com.google.firebase.iid.zzb.zzd(android.content.Intent)"
                                                                          at com.google.firebase.iid.zzg.run(Unknown Source:29)
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                          at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:7)
                                                                          at java.lang.Thread.run(Thread.java:764)

**Comment by jkasten2** [comment]
@vigneshr87 It looks like your firebase dependencies may have not been aligned. I just released a new version of `onesignal-gradle-plugin` which might fix the issue. Can you try updating this section to:
```gradle
    dependencies {
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.9.0, 0.99.99]'
    }
```

If this didn't help please create an issue here filling out all the sections so we can try reproduction the issue on our end.
https://github.com/OneSignal/OneSignal-Gradle-Plugin/issues/new
