### ISSUE TITLE
Some of the devices not  receiving push Notification from OneSignal .

### ISSUE THREAD

**Issue by krishna2122** [OneSignal/OneSignal-Android-SDK#411]
I have tried to debug one use case : some of the devices not receiving push notification sent from OneSignal . When ever I tried to debug I receive the notification but when I run it in normal mode I don't receive the push notification from OneSignal .

Below is the Log .
```java
 16:25:25.269 29113-29544/com.onmo.discover:discoverservice W/OneSignal: OneSignalRestClient: PUT Error thrown from network stack. 
                                                                              javax.net.ssl.SSLProtocolException: Read error: ssl=0x7613d49c00: Failure in SSL library, usually a protocol error
                                                                              error:100000d7:SSL routines:OPENSSL_internal:SSL_HANDSHAKE_FAILURE (external/boringssl/src/ssl/s3_pkt.c:428 0x762c8a62d7:0x00000000)
                                                                                  at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
                                                                                  at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:758)
                                                                                  at com.android.okhttp.okio.Okio$2.read(Okio.java:141)
                                                                                  at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
                                                                                  at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:316)
                                                                                  at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:310)
                                                                                  at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:206)
                                                                                  at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:239)
                                                                                  at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:104)
                                                                                  at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:1156)
                                                                                  at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:976)
                                                                                  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:509)
                                                                                  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:438)
                                                                                  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:567)
                                                                                  at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
                                                                                  at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java)
                                                                                  at com.onesignal.OneSignalRestClient.startHTTPConnection(OneSignalRestClient.java:146)
                                                                                  at com.onesignal.OneSignalRestClient.access$100(OneSignalRestClient.java:38)
                                                                                  at com.onesignal.OneSignalRestClient$4.run(OneSignalRestClient.java:94)
                                                                                  at java.lang.Thread.run(Thread.java:762)
01-16 16:25:25.272 29113-30314/com.onmo.discover:discoverservice W/OneSignal: Failed last request. statusCode: -1
                                                                              response: null
```

**Comment by jkasten2** [comment]
@krishna2122 The `SSL_HANDSHAKE_FAILURE` error can occur if the date and time is incorrect on the device or if there is a network stability issue. Also using a proxy or VPN that isn't configured correctly could cause this.

What device and version of Android did you get this error on? Can you try another device or another network connection as well?

**Comment by jkasten2** [comment]
Closing due to inactivity. Please confirm the above and provide any more detail you can and we'll reopen this issue and look into it in more detail. Thanks!

**Comment by fatemeh2sh** [comment]
krishna2122  i have this problem. do you solve problem?

**Comment by oliveriobw** [comment]
Also seeing this on v3.8.1 Android 7.0

_05-24 15:02:56.736 2971-3381/com.secoti.prod W/OneSignal: OneSignalRestClient: PUT Error thrown from network stack. 
    java.net.SocketTimeoutException: timeout
        at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:221)
        at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:250)
        at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:217)
        at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:316)
        at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:310)
        at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:206)
        at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:239)
        at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:104)
        at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:1156)
        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:976)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:509)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:438)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:567)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java)
        at com.onesignal.OneSignalRestClient.startHTTPConnection(OneSignalRestClient.java:146)
        at com.onesignal.OneSignalRestClient.access$100(OneSignalRestClient.java:38)
        at com.onesignal.OneSignalRestClient$4.run(OneSignalRestClient.java:94)
        at java.lang.Thread.run(Thread.java:762)
05-24 15:02:56.743 2971-3562/com.secoti.prod W/OneSignal: Failed last request. statusCode: -1
    response: null
_

**Comment by jkasten2** [comment]
@oliveriobw This timeout may have been due some delayed requests on OneSignal's end around the time you post this. The issue is now resolved
