### ISSUE TITLE
No such service (com.onesignal.SyncJobService) crash on HTC running on Android 8.0

### ISSUE THREAD

**Issue by insacc** [OneSignal/OneSignal-Android-SDK#420]
We realized that our app crashes on HTC smartphones that are running on Android 8.0. Below is the crash report from the Fabric

> Caused by java.lang.IllegalArgumentException: No such service ComponentInfo{com.*****.******/com.onesignal.SyncJobService}
       at android.os.Parcel.readException(Parcel.java:1955)
       at android.os.Parcel.readException(Parcel.java:1897)
       at android.app.job.IJobScheduler$Stub$Proxy.schedule(IJobScheduler.java:180)
       at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:72)
       at com.onesignal.OneSignalSyncUtils.scheduleSyncTask(OneSignalSyncUtils.java:46)
       at com.onesignal.LocationGMS.scheduleUpdate(LocationGMS.java:93)
       at com.onesignal.SyncService.onTaskRemoved(SyncService.java:130)
       at com.onesignal.SyncService.onTaskRemoved(SyncService.java:101)
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3733)
       at android.app.ActivityThread.-wrap20(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1767)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:180)
       at android.app.ActivityThread.main(ActivityThread.java:6950)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:835)

**Comment by jkasten2** [comment]
@insacc Did you add our SDK with our [Gradle / Android Studio instructions](https://documentation.onesignal.com/docs/android-sdk-setup) or our .jar directly?

If you have `compile 'com.onesignal:OneSignal:[3.7.1, 3.99.99]'` then this should be getting added correctly. See the entry that is aded by our SDK.
https://github.com/OneSignal/OneSignal-Android-SDK/blob/3.7.1/OneSignalSDK/onesignal/src/main/AndroidManifest.xml#L72-L73

* How many crashes are you seeing with this error and what percentage of your users is it effecting?
* Are you able to reproduce this issue on your test device?

If it is only a few devices and you are not able to reproduce is there someone on your team that could have a different build of your app where this AndroidManifest.xml entry was force removed? It is also possible a user in the wild could have modified your app on their device.

**Comment by insacc** [comment]
@jkasten2 thank you for the response.
We are currently using `compile 'com.onesignal:OneSignal:3.6.4@aar'` to add the sdk.  We were not reproduce this error, because we currently do no have a HTC phone that works on Android 8.0 . This crash affected 14 users in the past 7 days. All of the devices seems to be the HTC and working on 8.0

**Comment by jkasten2** [comment]
@insacc We haven't see any other reports of `SyncJobService` like this.

Is it possible it could have from any other test builds you may have sent out where OneSignal was mis configured?

It is also possible someone in the wild could have been modifying your app's APK and removed the `SyncJobService`. Repeated reinstalls would have shown up and multiple users from a single device.

If you are still seeing this issue or have more details reply here and I can open this thread back up. Thanks.

**Comment by insacc** [comment]
We started to get more crashes because of a similar exception. This time it's not limited to the Android Oreo& above devices, it also affects pre Oreo devices, any idea how to solve it?

> Caused by java.lang.IllegalArgumentException: No such service ComponentInfo{com*****/com.onesignal.SyncJobService}
       at android.os.Parcel.readException(Parcel.java:1696)
       at android.os.Parcel.readException(Parcel.java:1645)
       at android.app.job.IJobScheduler$Stub$Proxy.schedule(IJobScheduler.java:158)
       at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:70)
       at com.onesignal.OneSignalSyncServiceUtils.scheduleSyncServiceAsJob(OneSignalSyncServiceUtils.java:137)
       at com.onesignal.OneSignalSyncServiceUtils.scheduleSyncTask(OneSignalSyncServiceUtils.java:113)
       at com.onesignal.OneSignalSyncServiceUtils.scheduleLocationUpdateTask(OneSignalSyncServiceUtils.java:55)
       at com.onesignal.LocationGMS.scheduleUpdate(LocationGMS.java:100)
       at com.onesignal.OneSignalSyncServiceUtils.cancelSyncTask(OneSignalSyncServiceUtils.java:66)
       at com.onesignal.OneSignal.onAppFocus(OneSignal.java:1069)
       at com.onesignal.ActivityLifecycleHandler.handleFocus(ActivityLifecycleHandler.java:120)
       at com.onesignal.ActivityLifecycleHandler.onActivityResumed(ActivityLifecycleHandler.java:74)
       at com.onesignal.ActivityLifecycleListener.onActivityResumed(ActivityLifecycleListener.java:48)
       at android.app.Application.dispatchActivityResumed(Application.java:225)
       at android.app.Activity.onResume(Activity.java:1256)
       at android.support.v4.app.FragmentActivity.onResume(FragmentActivity.java:485)
       at com.fivehundredpx.viewer.main.MainActivity.onResume(MainActivity.java:148)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1337)
       at android.app.Activity.performResume(Activity.java:6777)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3596)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3665)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2792)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1501)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:173)
       at android.app.ActivityThread.main(ActivityThread.java:6459)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:938)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:828)

**Comment by insacc** [comment]
Thanks, I'll change build.gradle and try it out, if it doesn't solve it I'll let you know about. Fortunately it affect only a small portion of our DAU. It's also a sign that this isn't a `proguard` issue, because  I guess otherwise it'd affect everyone.

**Comment by jkasten2** [comment]
Closing due to inactivity. Feel free to reply however if the above didn't help and we can take a 2nd look. Thanks.

**Comment by DLevai94** [comment]
For me it isn't working on React Native.

When I put the app to background I see this error on logcat:
 ``` 
java.lang.IllegalArgumentException: No such service ComponentInfo{com.bybes.app/com.onesignal.SyncJobService}
```

**Comment by jkasten2** [comment]
@DLevai94 Can you check all your `AndroidManifests.xml` in your project for `tools:node="replace"` in any `<application ...>` tags? This is will cause this exact error as well as a number of other `** ComponentInfo` errors with other plugins as well.

**Comment by TusharAswal** [comment]
> @DLevai94 Can you check all your `AndroidManifests.xml` in your project for `tools:node="replace"` in any `<application ...>` tags? This is will cause this exact error as well as a number of other `** ComponentInfo` errors with other plugins as well.

Thanks @DLevai94 you are a lifesaver
