### ISSUE TITLE
crash app on android 6

### ISSUE THREAD

**Issue by rasoulinejad** [OneSignal/OneSignal-Android-SDK#422]
```java
java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List android.content.pm.ParceledListSlice.getList()' on a null object reference
	at android.app.NotificationManager.getActiveNotifications(NotificationManager.java:683)
	at com.onesignal.NotificationRestorer.restore(NotificationRestorer.java:118)
	at com.onesignal.NotificationRestorer$1.run(NotificationRestorer.java:72)
	at java.lang.Thread.run(Thread.java:833)
```

![untitled](https://user-images.githubusercontent.com/21033999/35612432-0143d4aa-067e-11e8-8ff4-f0d9497e7107.png)

**Comment by jkasten2** [comment]
@rasoulinejad Thanks for reporting, will look into this.

**Comment by jkasten2** [comment]
@rasoulinejad Did some digging on this stack trace and others have run into using `NotificationManager.getActiveNotifications` on Android 6.0.x devices as well. I added a try-catch around it's usage to work around the Android bug. The fix will be included in the next SDK release.
