### ISSUE TITLE
Non-fatal Exception: java.lang.InternalError:Thread starting during runtime shutdown

### ISSUE THREAD

**Issue by CoLang** [OneSignal/OneSignal-Android-SDK#435]
Found too many occurrences on Crashlytics platform.

Please find the full stack trace below
```java
Non-fatal Exception: java.lang.InternalError: Thread starting during runtime shutdown
       at java.lang.Thread.nativeCreate(Thread.java)
       at java.lang.Thread.start(Thread.java:1063)
       at com.onesignal.OneSignalRestClient.callResponseHandlerOnFailure(OneSignalRestClient.java:221)
       at com.onesignal.OneSignalRestClient.startHTTPConnection(OneSignalRestClient.java:185)
       at com.onesignal.OneSignalRestClient.access$100(OneSignalRestClient.java:38)
       at com.onesignal.OneSignalRestClient$4.run(OneSignalRestClient.java:94)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by jkasten2** [comment]
@CoLang Thanks for reporting. Going to merge this issue with #287 as it the same exception.
