### ISSUE TITLE
Anyone please help me about this issue?  i am getting this issue around 500times in a week.

### ISSUE THREAD

**Issue by ishratkhan** [OneSignal/OneSignal-Android-SDK#439]
```Java
Fatal Exception: java.lang.InternalError: Thread starting during runtime shutdown
       at java.lang.Thread.nativeCreate(Thread.java)
       at java.lang.Thread.start(Thread.java:733)
       at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:970)
       at java.util.concurrent.ThreadPoolExecutor.ensurePrestart(ThreadPoolExecutor.java:1611)
       at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:342)
       at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:562)
       at java.util.concurrent.ScheduledThreadPoolExecutor.execute(ScheduledThreadPoolExecutor.java:654)
       at com.onesignal.OneSignalPrefs.saveString(OneSignalPrefs.java:105)
       at com.onesignal.OneSignalStateSynchronizer$UserState.persistState(OneSignalStateSynchronizer.java:423)
       at com.onesignal.OneSignalStateSynchronizer$UserState.persistStateAfterSync(OneSignalStateSynchronizer.java:469)
       at com.onesignal.OneSignalStateSynchronizer$UserState.access$700(OneSignalStateSynchronizer.java:236)
       at com.onesignal.OneSignalStateSynchronizer.syncUserState(OneSignalStateSynchronizer.java:587)
       at com.onesignal.OneSignalStateSynchronizer$NetworkHandlerThread$1.run(OneSignalStateSynchronizer.java:538)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by jkasten2** [comment]
@ishratkhan A `Thread starting during runtime shutdown` should be extremely rare as this could only happen when the whole process for the app is about to be stoped.

Do you have anything in your code force killing your app? Such as `android.os.Process.killProcess`?

**Comment by ishratkhan** [comment]
No! we don't have anything to kill process, we made some changes in our app, update you on this issue after few days.

Thank you

**Comment by jkasten2** [comment]
Could you share what Android versions you seen the error on? Do you have have a log with the stack trace of all other threads at the time of the crash?

**Comment by ishratkhan** [comment]
No, Possible log i catch is

`ONESIGNAL_EXECUTOR_27961
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor$(Thread.java:2135)
       at sun.misc.Unsafe.park(Unsafe.java:358)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2059)
       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1120)
       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1087)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1147)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)`

**Comment by jkasten2** [comment]
@ishratkhan Thanks for the full log with all threads. I wasn't able to find anything that would create this error from it. By chance are you using `Thread.setDefaultUncaughtExceptionHandler` in your app code in-addition  to Crashlytics?

Going to merge this one into issue #443 as it is the same stack trace. Please follow up with us there. Thanks.
