### ISSUE TITLE
Thread starting during runtime shutdown crash. [can't reproduce]

### ISSUE THREAD

**Issue by Goran1708** [OneSignal/OneSignal-Android-SDK#443]
Bunch of crashes with this stack trace, but we can't reproduce it. Using latest version

```
Fatal Exception: java.lang.InternalError: Thread starting during runtime shutdown
       at java.lang.Thread.nativeCreate(Thread.java)
       at java.lang.Thread.start(Thread.java:733)
       at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:970)
       at java.util.concurrent.ThreadPoolExecutor.ensurePrestart(ThreadPoolExecutor.java:1611)
       at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:342)
       at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:562)
       at java.util.concurrent.ScheduledThreadPoolExecutor.execute(ScheduledThreadPoolExecutor.java:654)
       at com.onesignal.OneSignalPrefs.saveString(OneSignalPrefs.java:105)
       at com.onesignal.OneSignalStateSynchronizer$UserState.persistState(OneSignalStateSynchronizer.java:423)
       at com.onesignal.OneSignalStateSynchronizer$UserState.persistStateAfterSync(OneSignalStateSynchronizer.java:469)
       at com.onesignal.OneSignalStateSynchronizer$UserState.access$700(OneSignalStateSynchronizer.java:236)
       at com.onesignal.OneSignalStateSynchronizer.syncUserState(OneSignalStateSynchronizer.java:587)
       at com.onesignal.OneSignalStateSynchronizer$NetworkHandlerThread$1.run(OneSignalStateSynchronizer.java:538)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by Goran1708** [comment]
have this logic. Will check tomorrow if this might be the reason app is getting fatal exception.

```
defaultUEH = Thread.getDefaultUncaughtExceptionHandler();
    Thread.setDefaultUncaughtExceptionHandler((thread, throwable) -> {
      //some logic here
      defaultUEH.uncaughtException(thread, throwable);
    });
```

**Comment by jkasten2** [comment]
@Goran1708 We don't use `setDefaultUncaughtExceptionHandler` in the OneSignal SDK. I did try experimenting with it however in a test app with the OneSignal SDK and wasn't able to reproduce any issues on a 7.1.2 Android device.

Could you share what Android versions you seen the error on? Do you have have a log with the stack trace of all other threads at the time of the crash?

**Comment by Goran1708** [comment]
Bunch of phones. Samsungs, huawei's, LG's, google pixels.

**Comment by Goran1708** [comment]
I think I figured it out. We are using this to log any Throwable that get thrown in app:
```defaultUEH = Thread.getDefaultUncaughtExceptionHandler();
    Thread.setDefaultUncaughtExceptionHandler((thread, throwable) -> {
      //some logging logic here
      defaultUEH.uncaughtException(thread, throwable);
    });
```
Which seems some error gets thrown on different thread, which might not crash the app. 
Not sure whats happening in OneSignal though.

**Comment by Goran1708** [comment]
[one_signal_crash.txt](https://github.com/OneSignal/OneSignal-Android-SDK/files/1739947/one_signal_crash.txt)

that `setDefaultUncaughtExceptionHandler` is in custom `App` class `com.default.App`. You can search for it in text file.

**Comment by jkasten2** [comment]
@Goran1708 Thanks for the log, I reviewed but don't see anything key to the state of other threads that would create this crash. Just to confirm you have Crashlytics and are using your own global exception handler with `Thread.setDefaultUncaughtExceptionHandler`? Not sure if this would put the process in a shutdown state on the uncaught exceptions is thrown but it is a possibility. The key will be producing the issue so we can do the same and confirm any fix we may try.

We are evaluating moving some Java Thread creation into some `HandlerThread`s as an optimization. This will most likely also solve the `Thread starting during runtime shutdown` errors so this could be one possible solution.

**Comment by Goran1708** [comment]
@jkasten2 The issue seems to be fixed, but we do not know how it was fixed and we were not able to reproduce the issue. What we did remove is the `Thread.setDefaultUncaughtExceptionHandler`. https://github.com/segmentio/analytics-android/issues/490 this thread also mentions that `setDefaultUncaughtExceptionHandler` could be causing it.

**Comment by jkasten2** [comment]
@Goran1708 Thanks for the update and the link, let us know if the issue comes up again.

**Comment by amalnafia** [comment]
> @jkasten2 The issue seems to be fixed, but we do not know how it was fixed and we were not able to reproduce the issue. What we did remove is the `Thread.setDefaultUncaughtExceptionHandler`. [segmentio/analytics-android#490](https://github.com/segmentio/analytics-android/issues/490) this thread also mentions that `setDefaultUncaughtExceptionHandler` could be causing it.

can someone please explain why setDefaultUncaughtExceptionHandler is the reason of the issue
