### ISSUE TITLE
Another crash, can't reproduce

### ISSUE THREAD

**Issue by Goran1708** [OneSignal/OneSignal-Android-SDK#444]
Another crash by others, can't reproduce.

```
Fatal Exception: java.lang.InternalError: Thread starting during runtime shutdown
       at java.lang.Thread.nativeCreate(Thread.java)
       at java.lang.Thread.start(Thread.java:731)
       at com.onesignal.OneSignalRestClient.callResponseHandlerOnFailure(OneSignalRestClient.java:221)
       at com.onesignal.OneSignalRestClient.startHTTPConnection(OneSignalRestClient.java:185)
       at com.onesignal.OneSignalRestClient.access$100(OneSignalRestClient.java:38)
       at com.onesignal.OneSignalRestClient$4.run(OneSignalRestClient.java:94)
       at java.lang.Thread.run(Thread.java:762)
```

**Comment by jkasten2** [comment]
@Goran1708 Let's merge this with your other issue #443, since this is the same exception and is most likely related.
