### ISSUE TITLE
Unable to start receiver

### ISSUE THREAD

**Issue by eugenio-caicedo** [OneSignal/OneSignal-Android-SDK#467]
I got this error in my application. Although I'm not sure how it happened or why.

```java
Fatal Exception: java.lang.RuntimeException: Unable to start receiver com.onesignal.BootUpReceiver: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.curbcall.connectandroid.ccproduction/com.onesignal.NotificationRestoreService (has extras) }: app is in background uid UidRecord{1f8ef79 u0a227 RCVR idle change:uncached procs:1 seq(0,0,0)}
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3194)
       at android.app.ActivityThread.-wrap17(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1672)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

Caused by java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.curbcall.connectandroid.ccproduction/com.onesignal.NotificationRestoreService (has extras) }: app is in background uid UidRecord{1f8ef79 u0a227 RCVR idle change:uncached procs:1 seq(0,0,0)}
       at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1521)
       at android.app.ContextImpl.startService(ContextImpl.java:1477)
       at android.content.ContextWrapper.startService(ContextWrapper.java:650)
       at android.content.ContextWrapper.startService(ContextWrapper.java:650)
       at android.support.v4.content.WakefulBroadcastReceiver.startWakefulService(WakefulBroadcastReceiver.java:99)
       at com.onesignal.BootUpReceiver.onReceive(BootUpReceiver.java:42)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3187)
       at android.app.ActivityThread.-wrap17(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1672)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

I'm using the next version of the library.

```gradle
compile("com.onesignal:OneSignal:3.5.8"){
        exclude group: 'com.android.support'
    }
```

**Comment by jkasten2** [comment]
@eugenio-caicedo It looks like you are targeting Android API level 26 and this is a crash on a Android 8.0+ Oreo device.

You will need to updated to at least [OneSignal version 3.6.5)(https://github.com/OneSignal/OneSignal-Android-SDK/releases/tag/3.6.5) for full Android 8 Oreo support but we recommend you use the following line to keep your app updated to the latest 3.x version.
```gradle
compile 'com.onesignal:OneSignal:[3.7.1, 3.99.99]'
```

**Side note:**
Also adding the following to the top of your `app/build.gradle` will keep your `com.android.support`, Google play services, and firebase decencies  aligned so you don't need at `exclude group` to all your compile lines.
```gradle
plugins {
    id 'com.onesignal.androidsdk.onesignal-gradle-plugin' version '0.8.1'
}
apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'
```

**Comment by eugenio-caicedo** [comment]
@jkasten2 Perfect, I'm going to try this. Thank you very much.

**Comment by jkasten2** [comment]
@eugenio-caicedo Closing as resolved. Feel free to reply with more details if this did not help and we can reopen. Thanks
