### ISSUE TITLE
java.lang.IllegalArgumentException in JobIntentService on Android 8.0

### ISSUE THREAD

**Issue by xcaEi** [OneSignal/OneSignal-Android-SDK#482]
I updated my app to use SDK 3.8.2. I'm seeing some issues on Android 8.0 on different devices (S8, Mate 9, OnePlus 5T) with the following exception
```
java.lang.RuntimeException: 
    at android.app.ActivityThread.handleReceiver (ActivityThread.java:3397)
    at android.app.ActivityThread.-wrap18 (Unknown Source)
    at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1780)
    at android.os.Handler.dispatchMessage (Handler.java:105)
    at android.os.Looper.loop (Looper.java:164)
    at android.app.ActivityThread.main (ActivityThread.java:6938)
    at java.lang.reflect.Method.invoke (Native Method)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:327)
    at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1374)
Caused by: java.lang.IllegalArgumentException: 
    at android.os.Parcel.readException (Parcel.java:1962)
    at android.os.Parcel.readException (Parcel.java:1904)
    at android.app.job.IJobScheduler$Stub$Proxy.enqueue (IJobScheduler.java:211)
    at android.app.JobSchedulerImpl.enqueue (JobSchedulerImpl.java:53)
    at com.onesignal.JobIntentService$JobWorkEnqueuer.enqueueWork (JobIntentService.java:337)
    at com.onesignal.JobIntentService.enqueueWork (JobIntentService.java:515)
    at com.onesignal.NotificationBundleProcessor.startExtenderService (NotificationBundleProcessor.java:463)
    at com.onesignal.NotificationBundleProcessor.processBundleFromReceiver (NotificationBundleProcessor.java:429)
    at com.onesignal.GcmBroadcastReceiver.processOrderBroadcast (GcmBroadcastReceiver.java:110)
    at com.onesignal.GcmBroadcastReceiver.onReceive (GcmBroadcastReceiver.java:67)
    at android.app.ActivityThread.handleReceiver (ActivityThread.java:3390)
```

**Comment by jkasten2** [comment]
@xcaEi It looks like you setup a `com.onesignal.NotificationExtender` but didn't add the required `android:permission="android.permission.BIND_JOB_SERVICE"` setting.
See this comment for exact details.
https://github.com/OneSignal/OneSignal-Android-SDK/issues/351#issuecomment-340552046

Let us know if this does not help and we can reopen

**Comment by nishkul** [comment]
I am also getting the same  error one thing I got to know that most of them crash is coming in Oero devices  
Library version is 
 // OneSignal SDK
    implementation 'com.onesignal:OneSignal:[3.10.1, 3.99.99]'


 ```  
Define in Manifiest 

  <service
            android:name=".firebase.onesignal.MyOneSignalNotificationExtenderService"
            android:exported="false"
            android:permission="android.permission.BIND_JOB_SERVICE">
            <intent-filter>
                <action android:name="com.onesignal.NotificationExtender" />
            </intent-filter>
        </service>
```
```
java.lang.RuntimeException: 
  at android.os.AsyncTask$3.done (AsyncTask.java:353)
  at java.util.concurrent.FutureTask.finishCompletion (FutureTask.java:383)
  at java.util.concurrent.FutureTask.setException (FutureTask.java:252)
  at java.util.concurrent.FutureTask.run (FutureTask.java:271)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1162)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:636)
  at java.lang.Thread.run (Thread.java:764)
Caused by: java.lang.SecurityException: 
  at android.os.Parcel.readException (Parcel.java:2005)
  at android.os.Parcel.readException (Parcel.java:1951)
  at android.app.job.IJobCallback$Stub$Proxy.dequeueWork (IJobCallback.java:191)
  at android.app.job.JobParameters.dequeueWork (JobParameters.java:208)
  at com.onesignal.JobIntentService$JobServiceEngineImpl.dequeueWork (JobIntentService.java:337)
  at com.onesignal.JobIntentService.dequeueWork (JobIntentService.java:652)
  at com.onesignal.JobIntentService$CommandProcessor.doInBackground (JobIntentService.java:412)
  at com.onesignal.JobIntentService$CommandProcessor.doInBackground (JobIntentService.java:405)
  at android.os.AsyncTask$2.call (AsyncTask.java:333)
  at java.util.concurrent.FutureTask.run (FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1162)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:636)
  at java.lang.Thread.run (Thread.java:764)
```

**Comment by jkasten2** [comment]
@nishkul Someone else opened issue #649 noting the same issue started with the 3.10.2 update. If this only started after then can you follow up on that issue with the information we are looking for noted there?

**Comment by mvisionapps** [comment]
@jkasten2 continuing from issue #649 
Right now i only have stacktraces from Play console and Crashlytics that i got just yesterday. Not able to reproduce them on real devices.

Here are the stacktraces from Crashlytics:

Caused by java.lang.IllegalStateException: Not allowed to start service Intent { act=com.onesignal.NotificationExtender pkg=com.package.xxx cmp=com.package.xxx /.util.NotificationExtender (has extras) }: app is in background uid UidRecord{f123688 u0a187 RCVR idle procs:1 seq(0,0,0)}
       at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1538)
       at android.app.ContextImpl.startService(ContextImpl.java:1484)
       at android.content.ContextWrapper.startService(ContextWrapper.java:663)
       at com.onesignal.JobIntentService$CompatWorkEnqueuer.enqueueWork(JobIntentService.java:204)
       at com.onesignal.JobIntentService.enqueueWork(JobIntentService.java:534)
       at com.onesignal.NotificationBundleProcessor.startExtenderService(NotificationBundleProcessor.java:465)
       at com.onesignal.NotificationBundleProcessor.processBundleFromReceiver(NotificationBundleProcessor.java:430)
       at com.onesignal.GcmBroadcastReceiver.processOrderBroadcast(GcmBroadcastReceiver.java:125)
       at com.onesignal.GcmBroadcastReceiver.onReceive(GcmBroadcastReceiver.java:72)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3392)
       at android.app.ActivityThread.-wrap18(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1780)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6944)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by sajibhasan3343** [comment]
Ok
