### ISSUE TITLE
NullPointerException on Intent.getExtra(String, Int) WakefulBroadcastReceiver

### ISSUE THREAD

**Issue by rameshkumarkhatri** [OneSignal/OneSignal-Android-SDK#488]
Hi, I am getting crash through crashlytics here is stack trace on device running Android 7:

```java
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Intent.getIntExtra(java.lang.String, int)' on a null object reference
       at android.support.v4.content.WakefulBroadcastReceiver.completeWakefulIntent(Unknown Source)
       at com.onesignal.NotificationRestoreService.onHandleIntent(Unknown Source)
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:67)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:203)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

Fabric tools:        classpath 'io.fabric.tools:gradle:1.+'
gradle file:     implementation 'com.onesignal:OneSignal:[3.6.5, 3.99.99]'

**Comment by jkasten2** [comment]
@rameshkumarkhatri Thanks for reporting, we fixed the issue in the PR above. It will be included in the next SDK release.
