### ISSUE TITLE
ArrayIndexOutOfBoundsException thrown from com.android.okio.Util.checkOffsetAndCount on Android 5.x

### ISSUE THREAD

**Issue by jkasten2** [OneSignal/OneSignal-Android-SDK#490]
This is a very rare crash but is happening on a number of Android 5.x devices of different manufactures 

```java
Fatal Exception: java.lang.Error: FATAL EXCEPTION [OS_HTTPConnection]
Unity version     : 2017.3.1p4
Device model      : TCL 4045A
Device fingerprint: TCL/4045A/alto4_8g:5.0.2/LRX22G/v5LHI-0:user/release-keys

Caused by java.lang.ArrayIndexOutOfBoundsException
       at com.android.okio.Util.checkOffsetAndCount(Util.java:29)
       at com.android.okio.OkBuffer.getByte(OkBuffer.java:161)
       at com.android.okio.OkBuffer.readUtf8Line(OkBuffer.java:322)
       at com.android.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:96)
       at com.android.okhttp.internal.http.HttpConnection$ChunkedSource.readChunkSize(HttpConnection.java:508)
       at com.android.okhttp.internal.http.HttpConnection$ChunkedSource.read(HttpConnection.java:491)
       at com.android.okhttp.internal.Util.skipAll(Util.java:227)
       at com.android.okhttp.internal.http.HttpConnection.discard(HttpConnection.java:212)
       at com.android.okhttp.internal.http.HttpConnection$ChunkedSource.close(HttpConnection.java:536)
       at com.android.okio.RealBufferedSource.close(RealBufferedSource.java:198)
       at com.android.okio.InflaterSource.close(InflaterSource.java:122)
       at com.android.okio.GzipSource.close(GzipSource.java:178)
       at com.android.okhttp.internal.Util.closeQuietly(Util.java:97)
       at com.android.okhttp.internal.http.HttpEngine.close(HttpEngine.java:433)
       at com.android.okhttp.internal.http.HttpURLConnectionImpl.disconnect(HttpURLConnectionImpl.java:113)
       at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.disconnect(DelegatingHttpsURLConnection.java:93)
       at com.android.okhttp.internal.http.HttpsURLConnectionImpl.disconnect(HttpsURLConnectionImpl.java:25)
       at com.onesignal.OneSignalRestClient.startHTTPConnection(OneSignalRestClient.java:189)
       at com.onesignal.OneSignalRestClient.access$100(OneSignalRestClient.java:38)
       at com.onesignal.OneSignalRestClient$4.run(OneSignalRestClient.java:94)
       at java.lang.Thread.run(Thread.java:818)
```

This looks to be an internal bug with `com.android.okio` due to the stack and only happening on 5.X devices. Solution will most likely be a try-catch for this.

**Comment by ImDroidGuy** [comment]
**OneSignalRestClient.java line 193
com.onesignal.OneSignalRestClient.startHTTPConnection**

> Fatal Exception: java.lang.ArrayIndexOutOfBoundsException
>        at com.android.okio.Util.checkOffsetAndCount(Util.java:29)
>        at com.android.okio.OkBuffer.getByte(OkBuffer.java:161)
>        at com.android.okio.OkBuffer.readUtf8Line(OkBuffer.java:322)
>        at com.android.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:99)
>        at com.android.okhttp.internal.http.HttpConnection$ChunkedSource.readChunkSize(HttpConnection.java:531)
>        at com.android.okhttp.internal.http.HttpConnection$ChunkedSource.read(HttpConnection.java:514)
>        at com.android.okhttp.internal.Util.skipAll(Util.java:227)
>        at com.android.okhttp.internal.http.HttpConnection.discard(HttpConnection.java:235)
>        at com.android.okhttp.internal.http.HttpConnection$ChunkedSource.close(HttpConnection.java:559)
>        at com.android.okio.RealBufferedSource.close(RealBufferedSource.java:204)
>        at com.android.okio.InflaterSource.close(InflaterSource.java:122)
>        at com.android.okio.GzipSource.close(GzipSource.java:178)
>        at com.android.okhttp.internal.Util.closeQuietly(Util.java:97)
>        at com.android.okhttp.internal.http.HttpEngine.close(HttpEngine.java:580)
>        at com.android.okhttp.internal.http.HttpURLConnectionImpl.disconnect(HttpURLConnectionImpl.java:113)
>        at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.disconnect(DelegatingHttpsURLConnection.java:93)
>        at com.android.okhttp.internal.http.HttpsURLConnectionImpl.disconnect(HttpsURLConnectionImpl.java:25)
>        at com.onesignal.OneSignalRestClient.startHTTPConnection(OneSignalRestClient.java:193)
>        at com.onesignal.OneSignalRestClient.access$100(OneSignalRestClient.java:38)
>        at com.onesignal.OneSignalRestClient$4.run(OneSignalRestClient.java:98)
>        at java.lang.Thread.run(Thread.java:818)

SAME ISSUE HERE !!

**DEVICE TYPE** : SAMSUNG GALAXY S4
**OS** : 5

**Comment by rgomezp** [comment]
Closing. Being tracked internally
