### ISSUE TITLE
Verify error : 

### ISSUE THREAD

**Issue by akuma34** [OneSignal/OneSignal-Android-SDK#508]
4-21 17:55:15.332 10445-10445/? E/AndroidRuntime: **FATAL EXCEPTION**: main
                                                   Process: parent1.kidstriangle.com.chromewebview, PID: 10445
                                                   java.lang.VerifyError: com/onesignal/LocationGMS
                                                       at com.onesignal.OneSignal.onAppFocus(OneSignal.java:1050)
                                                       at com.onesignal.ActivityLifecycleHandler.handleFocus(ActivityLifecycleHandler.java:120)
                                                       at com.onesignal.ActivityLifecycleHandler.onActivityResumed(ActivityLifecycleHandler.java:74)
                                                       at com.onesignal.ActivityLifecycleListener.onActivityResumed(ActivityLifecycleListener.java:48)
                                                       at android.app.Application.dispatchActivityResumed(Application.java:208)
                                                       at android.app.Activity.onResume(Activity.java:1097)
                                                       at parent1.kidstriangle.com.chromewebview.MainActivity.onResume(MainActivity.java:2138)
                                                       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1192)
                                                       at android.app.Activity.performResume(Activity.java:5310)
                                                       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2778)
                                                       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2817)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2250)
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:135)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:136)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5017)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                       at dalvik.system.NativeStart.main(Native Method)

**Comment by akuma34** [comment]
Happening only on Kitkat 4.4, App crash while launch, others android version works fine.

**Comment by jkasten2** [comment]
@akuma34 The `java.lang.VerifyError` error normally means you have hit the 65k method limit which is only an issue on Android 4.4 and older.
https://stackoverflow.com/a/100134/1244574

To fix the issue you will need to setup mutlidex in your app with the instructions below.
https://developer.android.com/studio/build/multidex.html
If you have this already in your project double check your code in the `attachBaseContext` method to ensure you have it correct

**Comment by jkasten2** [comment]
Closing due to inactivity. Let us know if the above does not help and we can reopen this issue.

**Comment by trungnguyennam** [comment]
I have the same issue. I used eclipse sample project and it only crash on 4.4 device( is ok with gradle but my partner still use Eclipse :( ) . Can you provide multidex for Eclipse or the "right" google_play_services ? @jkasten2 . Thanks

**Comment by jkasten2** [comment]
@trungnguyennam You can check out this guide for including Google Play Services for Eclipse.
https://stackoverflow.com/questions/42979484/how-to-add-google-play-services-to-my-eclipse-adt-project

There isn't many guides for using multidex with Eclipse and haven't done so myself but this site looks to have a complete guide you can try.
http://docs.repro.io/en/dev/sdk/getstarted/android-multidex-eclipse.html#id2
