### ISSUE TITLE
Build failed with an exception after upgrading from version 3.8.4 to 3.9.0.

### ISSUE THREAD

**Issue by xdgimf** [OneSignal/OneSignal-Android-SDK#537]
**Description:**

Early this morning our build suddenly failed without any changes in our codebase. Upon checking all our dependencies we realized that the OneSignal version is a range and from version 3.8.4 it automatically upgraded to 3.9.0.

**Environment**
1. What version of the Android SDK are you using?
```
Android Studio 3.1.2
compileSdkVersion = 27
buildToolsVersion = '27.0.3'
minSdkVersion = 16
targetSdkVersion = 27
```
2. How did you add the SDK to your project (eg. maven)
```gradle
implementation 'com.onesignal:OneSignal:[3.8.4, 3.99.99]'
```

**Steps to Reproduce Issue:**
 1. Upgrade from version 3.8.4 to 3.9.0

**Anything else:**

Stacktrace

```
:app:transformClassesWithDesugarForDevReleaseException in thread "main" java.lang.IllegalArgumentException
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:108)
        at com.google.devtools.build.android.desugar.DefaultMethodClassFixer$DefaultMethodFinder.visit(DefaultMethodClassFixer.java:483)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:621)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:500)
        at com.google.devtools.build.android.desugar.DefaultMethodClassFixer.defaultMethodsDefined(DefaultMethodClassFixer.java:331)
        at com.google.devtools.build.android.desugar.DefaultMethodClassFixer.visitEnd(DefaultMethodClassFixer.java:91)
        at org.objectweb.asm.ClassVisitor.visitEnd(ClassVisitor.java:339)
        at com.google.devtools.build.android.desugar.InterfaceDesugaring.visitEnd(InterfaceDesugaring.java:112)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:702)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:500)
        at com.google.devtools.build.android.desugar.Desugar.desugarClassesInInput(Desugar.java:477)
        at com.google.devtools.build.android.desugar.Desugar.desugarOneInput(Desugar.java:361)
        at com.google.devtools.build.android.desugar.Desugar.desugar(Desugar.java:314)
        at com.google.devtools.build.android.desugar.Desugar.main(Desugar.java:711)

 FAILED

FAILURE: Build failed with an exception.
```

Other Dependencies
```
final PLAY_SERVICES_VERSION = '15.0.0'

// Google Play Services
implementation "com.google.android.gms:play-services-base:$PLAY_SERVICES_VERSION"
implementation "com.google.android.gms:play-services-gcm:$PLAY_SERVICES_VERSION"
implementation "com.google.android.gms:play-services-location:$PLAY_SERVICES_VERSION"
implementation "com.google.android.gms:play-services-maps:$PLAY_SERVICES_VERSION"
implementation "com.google.android.gms:play-services-vision:$PLAY_SERVICES_VERSION"
implementation "com.google.android.gms:play-services-ads:$PLAY_SERVICES_VERSION"
implementation 'com.google.maps.android:android-maps-utils:0.5'

// Fabric
implementation('com.crashlytics.sdk.android:crashlytics:2.6.8@aar') {
  transitive = true;
}

// Support -> 27.1.1
implementation "com.android.support:design:$project.ext.supportLibraryVersion"
implementation "com.android.support:customtabs:$project.ext.supportLibraryVersion"
implementation "com.android.support:support-v4:$project.ext.supportLibraryVersion"
implementation "com.android.support:support-v13:$project.ext.supportLibraryVersion"
implementation "com.android.support:appcompat-v7:$project.ext.supportLibraryVersion"
implementation "com.android.support:recyclerview-v7:$project.ext.supportLibraryVersion"
implementation "com.android.support:cardview-v7:$project.ext.supportLibraryVersion"
implementation "com.android.support:exifinterface:$project.ext.supportLibraryVersion"
implementation 'com.android.support.constraint:constraint-layout:1.1.0'
implementation 'com.android.support:multidex:1.0.3'

final DAGGER_VERSION = '2.14.1'

implementation "com.google.dagger:dagger-android:$DAGGER_VERSION"
implementation "com.google.dagger:dagger-android-support:$DAGGER_VERSION"
annotationProcessor "com.google.dagger:dagger-android-processor:$DAGGER_VERSION"
```

I'm not sure if the error is caused by OneSignal SDK or its dependencies. Downgrading to 3.8.4 seems to fixed the issue.

**Comment by jkasten2** [comment]
@xdgimf The OneSignal SDK version 3.9.0 only imports versions 12.0.1 of com.google.android.gms and `com.google.android.gms` and `com.google.firebase`. It is recommend that you use 12.0.1 for your other decencies `com.google.android.gms` so these all line up to prevent build issues. In the future we will be updating the OneSignal SDK dependencies to 15.+.

If you still see an issue please remove Java 8 from your build.gradle temporarily then rebuild. A better build error to help debug instead the `Desugar` error you are seeing now.

Note that aligning all `com.google.android.gms` and / or all `com.google.firebase` modules is now an anti-pattern as they wont have matching versions after `15.0.0` going forward.
https://android-developers.googleblog.com/2018/05/announcing-new-sdk-versioning.html

**Comment by jkasten2** [comment]
@xdgimf One thing I would suggest you add if you haven't already is the [OneSignal-Gradle-Plugin](https://github.com/OneSignal/OneSignal-Gradle-Plugin). It resolves issue due to conflicting versions of libraries. If this doesn't help then providing the details from my last comment above will help us pin point the issue.

I am closing due to inactivity but we can open if this is still an issue for you.
