### ISSUE TITLE
Exception thrown for apps without a Launcher Intent

### ISSUE THREAD

**Issue by jkasten2** [OneSignal/OneSignal-Android-SDK#59]
The follow exception occurs when a notification is received on an app without a Launcher Intent.

```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.ComponentName android.content.Intent.getComponent()' on a null object reference 
at com.onesignal.shortcutbadger.ShortcutBadger.initBadger(ShortcutBadger.java:92) 
at com.onesignal.shortcutbadger.ShortcutBadger.applyCountOrThrow(ShortcutBadger.java:65) 
at com.onesignal.shortcutbadger.ShortcutBadger.applyCount(ShortcutBadger.java:50) 
at com.onesignal.BadgeCountUpdater.updateCount(BadgeCountUpdater.java:72) 
at com.onesignal.BadgeCountUpdater.update(BadgeCountUpdater.java:66) 
at com.onesignal.NotificationBundleProcessor.saveNotification(NotificationBundleProcessor.java:104) 
at com.onesignal.NotificationBundleProcessor.Process(NotificationBundleProcessor.java:58) 
at com.onesignal.NotificationBundleProcessor.ProcessFromGCMIntentService(NotificationBundleProcessor.java:51) 
at com.onesignal.GcmIntentService.onHandleIntent(GcmIntentService.java:54) 
at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:136) 
at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by jkasten2** [comment]
Fixed in release 2.4.3
