### ISSUE TITLE
ANR on Activity resume

### ISSUE THREAD

**Issue by tbt-hasan** [OneSignal/OneSignal-Android-SDK#593]
**Description:**

App sometimes freezes when `LocationGMS.onFocusChange()` called.

**Environment**

**Steps to Reproduce Issue:**
  1. Run the app
  2. press Home
  3. Open it again

**Anything else:**

One Signal related threads dump:
```
"main@9369" prio=5 tid=0x2 nid=NA waiting for monitor entry
  java.lang.Thread.State: BLOCKED
	 waiting for OS_SYNCSRV_BG_SYNC@9432 to release lock on <0x24dd> (a com.onesignal.LocationGMS$1)
	  at com.onesignal.LocationGMS.c(SourceFile:293)
	  at com.onesignal.OneSigna.g(SourceFile:1113)
	  at com.onesignal.ActivityLifecycleHandler.c(SourceFile:120)
	  at com.onesignal.ActivityLifecycleHandler.c(SourceFile:74)
	  at com.onesignal.ActivityLifecycleListener.onActivityResumed(SourceFile:48)
	  at android.app.Application.dispatchActivityResumed(Application.java:216)
	  at android.app.Activity.onResume(Activity.java:1313)
....


"OS_SYNCSRV_BG_SYNC@9432" prio=5 tid=0x65ef nid=NA waiting
  java.lang.Thread.State: WAITING
	 blocks OS_SYNCSRV_BG_SYNC@9432
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Object.wait(Object.java:422)
	  at java.lang.Thread.join(Thread.java:1270)
	  - locked <0x24ff> (a java.lang.Object)
	  at com.onesignal.OneSignalRestClient.c(SourceFile:106)
	  at com.onesignal.OneSignalRestClient.c(SourceFile:82)
	  at com.onesignal.UserStateSynchronizer.a(SourceFile:255)
	  at com.onesignal.UserStateSynchronizer.b(SourceFile:189)
	  at com.onesignal.UserStateSynchronizer.d(SourceFile:160)
	  - locked <0x2500> (a com.onesignal.UserStatePushSynchronizer)
	  at com.onesignal.OneSignalStateSynchronizer.a(SourceFile:70)
	  at com.onesignal.OneSignalSyncServiceUtils$c$1.a(SourceFile:228)
	  at com.onesignal.LocationGMS.a(SourceFile:254)
	  at com.onesignal.LocationGMS.c(SourceFile:288)
	  at com.onesignal.LocationGMS.a(SourceFile:202)
	  - locked <0x24dd> (a com.onesignal.LocationGMS$1)
	  at com.onesignal.LocationGMS.a(SourceFile:172)
	  at com.onesignal.OneSignalSyncServiceUtils$c.run(SourceFile:233)
	  at java.lang.Thread.run(Thread.java:764)
....


"FocusHandlerThread@9392" prio=5 tid=0x64e7 nid=NA waiting for monitor entry
  java.lang.Thread.State: BLOCKED
	 waiting for OS_SYNCSRV_BG_SYNC@9432 to release lock on <0x24dd> (a com.onesignal.LocationGMS$1)
	  at com.onesignal.LocationGMS.c(SourceFile:293)
	  at com.onesignal.OneSignal.e(SourceFile:1020)
	  at com.onesignal.ActivityLifecycleHandler$AppFocusRunnable.run(SourceFile:171)
	  at android.os.Handler.handleCallback(Handler.java:790)
	  at android.os.Handler.dispatchMessage(Handler.java:99)
	  at android.os.Looper.loop(Looper.java:164)
	  at android.os.HandlerThread.run(HandlerThread.java:65)


....


"OS_GMS_LOCATION_FALLBACK@9433" prio=5 tid=0x65f0 nid=NA waiting for monitor entry
  java.lang.Thread.State: BLOCKED
	 waiting for OS_SYNCSRV_BG_SYNC@9432 to release lock on <0x24dd> (a com.onesignal.p$1)
	  at com.onesignal.LocationGMS.fireFailedComplete(SourceFile:233)
	  at com.onesignal.LocationGMS$2.run(SourceFile:220)
	  at java.lang.Thread.run(Thread.java:764)
	  
....


"OS_HTTPConnection@9434" prio=5 tid=0x65f1 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at libcore.io.Linux.poll(Linux.java:-1)
	  at libcore.io.BlockGuardOs.poll(BlockGuardOs.java:216)
	  at libcore.io.IoBridge.isConnected(IoBridge.java:254)
	  at libcore.io.IoBridge.connectErrno(IoBridge.java:188)
	  at libcore.io.IoBridge.connect(IoBridge.java:130)
	  at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:129)
	  at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:356)
	  - locked <0x2501> (a java.net.SocksSocketImpl)
	  at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	  at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	  at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:357)
	  at java.net.Socket.connect(Socket.java:616)
	  at com.android.okhttp.internal.Platform.connectSocket(Platform.java:145)
	  at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:141)
	  at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
	  at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
	  at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
	  at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
	  at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
	  at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
	  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
	  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
	  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:258)
	  at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
	  at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:-1)
	  at com.onesignal.OneSignalRestClient.d(SourceFile:146)
	  at com.onesignal.OneSignalRestClient.b(SourceFile:38)
	  at com.onesignal.OneSignalRestClient$4.run(SourceFile:98)
	  at java.lang.Thread.run(Thread.java:764)
```

**Comment by jkasten2** [comment]
@tbt-hasan Thanks for reporting with the relevant ANR stacks. I believe this is the same issue as #589 so going to merge this one with it and close this one. Feel free to follow up on that issue. Thanks.
