### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/zzab;

### ISSUE THREAD

**Issue by kassimjk** [OneSignal/OneSignal-Android-SDK#609]
I have this error in my log cat and can't really figure it out.

08-13 01:59:58.704 25343-25343/com.parse.starter E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.parse.starter, PID: 25343
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/zzab;
        at com.google.firebase.provider.FirebaseInitProvider.zza(Unknown Source:2)
        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source:0)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6239)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5805)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5722)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.internal.zzab" on path: DexPathList[[zip file "/data/app/com.parse.starter-s52-VBWJoG2Nd8ZBl3RWfA==/base.apk", zip file "/data/app/com.parse.starter-s52-VBWJoG2Nd8ZBl3RWfA==/split_lib_dependencies_apk.apk", zip file "/data/app/com.parse.starter-s52-VBWJoG2Nd8ZBl3RWfA==/split_lib_resources_apk.apk", zip file "/data/app/com.parse.starter-s52-VBWJoG2Nd8ZBl3RWfA==/split_lib_slice_0_apk.apk", zip file "/data/app/com.parse.starter-s52-VBWJoG2Nd8ZBl3RWfA==/split_lib_slice_1_apk.apk", zip file "/data/app/com.parse.starter-s52-VBWJoG2Nd8ZBl3RWfA==/split_lib_slice_2_apk.apk", zip file "/data/app/com.parse.starter-s52-VBWJoG2Nd8ZBl3RWfA==/split_lib_slice_3_apk.apk", zip file "/data/app/com.parse.starter-s52-VBWJoG2Nd8ZBl3RWfA==/split_lib_slice_4_apk.apk", zip file "/data/app/com.parse.starter-s52-VBWJoG2Nd8ZBl3RWfA==/split_lib_slice_5_apk.apk", zip file "/data/app/com.parse.starter-s52-VBWJoG2Nd8ZBl3RWfA==/split_lib_slice_6_apk.apk", zip file "/data/app/com.parse.starter-s52-VBWJoG2Nd8ZBl3RWfA==/split_lib_slice_7_apk.apk", zip file "/data/app/com.parse.starter-s52-VBWJoG2Nd8ZBl3RWfA==/split_lib_slice_8_apk.apk", zip file "/data/app/com.parse.starter-s52-VBWJoG2Nd8ZBl3RWfA==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.parse.starter-s52-VBWJoG2Nd8ZBl3RWfA==/lib/x86, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.google.firebase.provider.FirebaseInitProvider.zza(Unknown Source:2) 
        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source:0) 
        at android.app.ActivityThread.installProvider(ActivityThread.java:6239) 
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5805) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5722) 
        at android.app.ActivityThread.-wrap1(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
    	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/com.parse.starter-s52-VBWJoG2Nd8ZBl3RWfA==/split_lib_resources_apk.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:353)
        at dalvik.system.DexFile.<init>(DexFile.java:100)
        at dalvik.system.DexFile.<init>(DexFile.java:74)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
        at dalvik.system.DexPathList.<init>(DexPathList.java:157)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:69)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:35)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:693)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:727)
        at android.app.LoadedApk.getResources(LoadedApk.java:954)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2270)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5639)
        		... 8 more

**Comment by jkasten2** [comment]
@kassimjk Sorry for the delay. Can you make sure you have added the `onesignal-gradle-plugin` to the top of your `app/build.gradle` noted in step 1.1?
https://documentation.onesignal.com/docs/android-sdk-setup#section-1-gradle-setup

Missing this or adding it to the wrong `build.gradle` is the most common issue for this runtime error.

**Comment by kassimjk** [comment]
@jkasten2 Thank you, I found out what the problem was, i had some extra dependencies in the build.gradle.

**Comment by jkasten2** [comment]
@kassimjk Good to hear you got things working? What did you have to remove? It could help others.

**Comment by kassimjk** [comment]
The problem was I had too many unnecessary dependencies on the build.gradle. So if anyone runs in to the same problem I know for sure the problem with extra dependencies.

dependencies {
    implementation 'com.android.support.constraint:constraint-layout:1.1.2'
    //noinspection GradleCompatible
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.google.android.gms:play-services-maps:15.0.1'
    compile 'com.parse.bolts:bolts-tasks:1.4.0'
    compile 'com.parse:parse-android:1.13.0'
    compile 'com.android.support:multidex:1.0.3'
}
