### ISSUE TITLE
Unable to start receiver com.onesignal.NotificationOpenedReceiver: java.lang.SecurityException:

### ISSUE THREAD

**Issue by ominfowave** [OneSignal/OneSignal-Android-SDK#610]
I have seen many crashes from one signal Android Version, Details report http://crashes.to/s/4b799fc9804

```
Unable to start receiver com.onesignal.NotificationOpenedReceiver: java.lang.SecurityException: Permission Denial: getTasks() from pid=573, uid=10243 requires android.permission.GET_TASKS
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2701)
       at android.app.ActivityThread.access$1700(ActivityThread.java:158)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1467)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:5486)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by Nightsd01** [comment]
Hi @ominfowave , this stack trace indicates that something is crashing in your implementation of the Notification Opened handler. Specifically, it seems like your app is calling `getRunningTasks` without having the `GET_TASKS` permission. This would not be an issue with our SDK and our SDK doesn't use this functionality.
