### ISSUE TITLE
Huge Spike in OneSignal ANR on Android 5.0 device after upgrading target sdk to 26

### ISSUE THREAD

**Issue by kiddoware** [OneSignal/OneSignal-Android-SDK#628]
**Description:**

I am seeing huge spike OneSignal ANR on Android 5.0 device after upgrading target sdk to 26 regarding 
Broadcast of Intent { act=android.intent.action.MY_PACKAGE_REPLACED flg=0x4000010 pkg=com.kiddoware.kidsplace cmp=com.kiddoware.kidsplace/**com.onesignal.UpgradeReceiver** (has extras) 
Few Users have also reported app stuck on blue screen as soon as it starts after the upgrade. When I gave them the apk without onesignal SDK it worked fine. 

Issue seems to be in com.onesignal.UpgradeReceiver and confined to android 5.0 and some android 4.4 device with target SDK 26. This is critical issue as Play Store requires app developers to move to target SDK. 
Thanks,

**Environment**
 Maven

**Steps to Reproduce Issue:**

  1. Add the OneSignal SDK to your project
  2. Place your App ID in the application's gradle file
  3. Start the app 
  4. Upgrade the app

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by kiddoware** [comment]
Hi, I see this comment in the code in class com.onesignal.UpgradeReceiver

      // Return early if using Android 7.0 due to upgrade restore crash (#263)
      if (Build.VERSION.SDK_INT == Build.VERSION_CODES.N)
         return;

I think we need same logic for Android 5 (Lollipop).

**Comment by jkasten2** [comment]
@kiddoware Thanks for the report. Can you include the full stack trace of the ANR? Provide the full stack traces for all threads if you can. (Even though this will be ~1,000 lines).

The crash noted in that comment for issue #263 was due to a specific `Couldn't expand RemoteViews` crash due to some race condition bug with Android 7.0 itself.

Thanks.

**Comment by jkasten2** [comment]
@kiddoware Thanks for the full ANR. I don't see any threads running any OneSignal classes in the threads. The following from the main thread in your ANR report indicates that it is in the process of writing `SharedPreferences` to disk to save it's changes.
```java
at android.app.SharedPreferencesImpl$EditorImpl$1.run (SharedPreferencesImpl.java:366)
...
at android.app.SharedPreferencesImpl.writeToFile (SharedPreferencesImpl.java:614)
at android.app.SharedPreferencesImpl.-wrap2 (SharedPreferencesImpl.java)
at android.app.SharedPreferencesImpl$2.run (SharedPreferencesImpl.java:515)
```

Are you see any other ANRs besides ones from the `com.onesignal.UpgradeReceiver` broadcast. Or any differences in the stack traces on the main thread from other reports of this broadcast?

`com.onesignal.UpgradeReceiver` shouldn't be making any writes to `SharedPreferences`. OneSignal only writes if you change a setting for OneSignal.
Can you check the `onCreate` of your application class to see if any SharedPreferences writes are being done?

**Comment by kiddoware** [comment]
Yes, there are write preference but I am only seeing for this upgrade receiver in Play Store. There are two models of device (Android 4.4) where there are fatal crashes with this with following stack trace.  Not sure if its related but below is the stack trace:
java.lang.RuntimeException: Unable to instantiate receiver com.onesignal.UpgradeReceiver: java.lang.ClassNotFoundException: Didn't find class "com.onesignal.UpgradeReceiver" on path: DexPathList[[zip file "/data/app/com.kiddoware.kidsplace-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.kiddoware.kidsplace-2, /vendor/lib, /system/lib]]
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2545)
	at android.app.ActivityThread.access$1700(ActivityThread.java:151)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1397)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:5299)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.onesignal.UpgradeReceiver" on path: DexPathList[[zip file "/data/app/com.kiddoware.kidsplace-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.kiddoware.kidsplace-2, /vendor/lib, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2540)
	... 10 more
java.lang.ClassNotFoundException: Didn't find class "com.onesignal.UpgradeReceiver" on path: DexPathList[[zip file "/data/app/com.kiddoware.kidsplace-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.kiddoware.kidsplace-2, /vendor/lib, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2540)
	at android.app.ActivityThread.access$1700(ActivityThread.java:151)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1397)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:5299)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by jkasten2** [comment]
@kiddoware This error most likely means you hav multidex enabled for your app but the device didn't load the other dex file parts. This won't be related to your original issue with ANRs on Android 5.0 and above.
```java
java.lang.ClassNotFoundException: Didn't find class "com.onesignal.UpgradeReceiver" on path: DexPathList[[zip file "/data/app/com.kiddoware.kidsplace-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.kiddoware.kidsplace-2, /vendor/lib, /system/lib]]
```

Since it isn't happening on all pre Android 5.0 devices then it most likely isn't an issue with the way you setup multidex. However can you still double check your setup with Google's instructions.
https://developer.android.com/studio/build/multidex#mdex-gradle

You may still want to follow Google's guide section named [Declare classes required in the primary DEX file](https://developer.android.com/studio/build/multidex#keep) adding `com.onesignal.**` to if you have already confirmed you have multidex implemented correctly.

**Comment by jkasten2** [comment]
@kiddoware Closing due to inactivity, let us know if the above did not help and we take another look.
