### ISSUE TITLE
New Fatal Issue - OneSignalPrefs$WritePrefHandlerThread

### ISSUE THREAD

**Issue by afalibykea** [OneSignal/OneSignal-Android-SDK#629]
**Description:**
We have been observing this crash on our fire base console for a particular user device only. However, we are unable to reproduce this on our end. Stack trace shows that its your internal method which is causing this fatal exception. 

**Environment And Device Details**

**Device Info:**

- Model name:  InnJoo ONE LTE HD
- OS version: Android 4.4.4 (KitKat)

OneSignal SDK Version:
```
buildscript {
    repositories {
        maven { url 'https://plugins.gradle.org/m2/'}
    }
    dependencies {
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.11.0, 0.99.99]'
    }
}
apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'

dependencies {

 implementation('com.onesignal:OneSignal:[3.9.1, 3.99.99)') {
        exclude group: 'com.google.android.gms'
    }

}
```
**Stack trace Information**

```
Fatal Exception: java.lang.IllegalMonitorStateException
       at java.util.concurrent.locks.ReentrantLock$Sync.tryRelease(ReentrantLock.java:122)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer.release(AbstractQueuedSynchronizer.java:1238)
       at java.util.concurrent.locks.ReentrantLock.unlock(ReentrantLock.java:451)
       at java.util.concurrent.LinkedBlockingQueue.signalNotEmpty(LinkedBlockingQueue.java:144)
       at java.util.concurrent.LinkedBlockingQueue.offer(LinkedBlockingQueue.java:398)
       at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1331)
       at java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:583)
       at android.app.SharedPreferencesImpl.enqueueDiskWrite(SharedPreferencesImpl.java:537)
       at android.app.SharedPreferencesImpl.access$100(SharedPreferencesImpl.java:52)
       at android.app.SharedPreferencesImpl$EditorImpl.apply(SharedPreferencesImpl.java:379)
       at com.onesignal.OneSignalPrefs$WritePrefHandlerThread.flushBufferToDisk(SourceFile:138)
       at com.onesignal.OneSignalPrefs$WritePrefHandlerThread.access$000(SourceFile:82)
       at com.onesignal.OneSignalPrefs$WritePrefHandlerThread$1.run(SourceFile:110)
       at android.os.Handler.handleCallback(Handler.java:808)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:193)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

If you need more information do let me know.

**Comment by Nightsd01** [comment]
Thanks for reporting this. Generally if it's only happening on a single user's device it's possible that the device is rooted/jailbroken and has some weird setup. Is it possible for you to tell if the device this crash occurred on was rooted?

**Comment by afalibykea** [comment]
@Nightsd01 I just checked this device is not rooted. I have attached image as well.

![2018-09-18_1204](https://user-images.githubusercontent.com/41981564/45670694-e0dfdf00-bb3c-11e8-94fc-578cb544b7dd.png)
