### ISSUE TITLE
SecurityException: Caller no longer running, last stopped

### ISSUE THREAD

**Issue by fazalBykea** [OneSignal/OneSignal-Android-SDK#638]
**Description:**
We have been observing this crash on our fire base console for the users which have android 8 (Oreo) + devices. Stack trace shows that its your internal method which is causing this fatal exception.

**Environment And Device Details**

**Device Info:**

- Devices: samsung, HUAWEI, HMD Global, Xiomi, others
- OS version: Android 8.0 (Oreo), Android 9.0 (Pie) 
- Crash Percentage: Android 8.0 (99%), Android 9.0 (1%)  

OneSignal SDK Version:

```
buildscript {
    repositories {
        maven { url 'https://plugins.gradle.org/m2/'}
    }
    dependencies {
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.11.0, 0.99.99]'
    }
}
apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'

dependencies {

 implementation('com.onesignal:OneSignal:[3.9.1, 3.99.99)') {
        exclude group: 'com.google.android.gms'
    }

}
```

**Stack trace Information**
```
Caused by java.lang.SecurityException: Caller no longer running, last stopped +2s26ms because: timed out while starting
       at android.os.Parcel.readException(Parcel.java:1959)
       at android.os.Parcel.readException(Parcel.java:1905)
       at android.app.job.IJobCallback$Stub$Proxy.dequeueWork(IJobCallback.java:191)
       at android.app.job.JobParameters.dequeueWork(JobParameters.java:196)
       at android.support.v4.app.JobIntentService$JobServiceEngineImpl.dequeueWork(SourceFile:314)
       at android.support.v4.app.JobIntentService.dequeueWork(SourceFile:639)
       at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(SourceFile:389)
       at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(SourceFile:382)
       at android.os.AsyncTask$2.call(AsyncTask.java:333)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)
```
99% of our crashes are happening on Android O, with a large number of those users on Samsung devices (but this doesn't seem to be a Samsung-only issue, there are also a fair number of HTC, LG, Google, etc. devices)

If you need more information do let me know.

**Comment by nishkul** [comment]
Hello, @fazalBykea  I am also facing the same issue and most of them are coming in Android Oero 
 I am giving crash report below 
Samsung Galaxy J8 (j8y18lte), Android 8.0
Report 1

> java.lang.RuntimeException: 
>   at android.os.AsyncTask$3.done (AsyncTask.java:353)
>   at java.util.concurrent.FutureTask.finishCompletion (FutureTask.java:383)
>   at java.util.concurrent.FutureTask.setException (FutureTask.java:252)
>   at java.util.concurrent.FutureTask.run (FutureTask.java:271)
>   at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1162)
>   at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:636)
>   at java.lang.Thread.run (Thread.java:764)
> Caused by: java.lang.SecurityException: 
>   at android.os.Parcel.readException (Parcel.java:1959)
>   at android.os.Parcel.readException (Parcel.java:1905)
>   at android.app.job.IJobCallback$Stub$Proxy.dequeueWork (IJobCallback.java:191)
>   at android.app.job.JobParameters.dequeueWork (JobParameters.java:196)
>   at com.onesignal.JobIntentService$JobServiceEngineImpl.dequeueWork (JobIntentService.java:337)
>   at com.onesignal.JobIntentService.dequeueWork (JobIntentService.java:652)
>   at com.onesignal.JobIntentService$CommandProcessor.doInBackground (JobIntentService.java:412)
>   at com.onesignal.JobIntentService$CommandProcessor.doInBackground (JobIntentService.java:405)
>   at android.os.AsyncTask$2.call (AsyncTask.java:333)
>   at java.util.concurrent.FutureTask.run (FutureTask.java:266)
>   at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1162)
>   at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:636)
>   at java.lang.Thread.run (Thread.java:764)

**Comment by fazalBykea** [comment]
@nishkul Are you able to reproduce this crash?

**Comment by CodeBoyChd** [comment]
This is what i am facing these days. Getting almost 6300 crashes a day. It has to be resolved. Please let me know, what i can do to help you to fix this issue.


Caused by java.lang.SecurityException: Caller no longer running, last stopped +622ms because: last work dequeued
       at android.os.Parcel.readException(Parcel.java:1943)
       at android.os.Parcel.readException(Parcel.java:1889)
       at android.app.job.IJobCallback$Stub$Proxy.dequeueWork(IJobCallback.java:191)
       at android.app.job.JobParameters.dequeueWork(JobParameters.java:196)
       at com.onesignal.JobIntentService$JobServiceEngineImpl.dequeueWork(JobIntentService.java:339)
       at com.onesignal.JobIntentService.dequeueWork(JobIntentService.java:668)
       at com.onesignal.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:414)
       at com.onesignal.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:407)
       at android.os.AsyncTask$2.call(AsyncTask.java:333)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)

**Comment by jkasten2** [comment]
@CodeBoyChd Followed up with you on #673

**Comment by sunj** [comment]
> 您好，@ fazalBykea 我也面临同样的问题，其中大部分都是Android Oero 
> 我在
> 三星Galaxy J8（j8y18lte），Android 8.0 
> 报告1 下面给出崩溃报告
> 
> > java.lang.RuntimeException：
> > at 
> > java.util.concure.FutureTask.finishCompletion（FutureTask.java:383）
> > at java.u. FutureTask.java:252）at 
> > java.util.concurrent.FutureTask.run（FutureTask.java:271）
> > at java.util.concurrent.ThreadPoolExecutor.runWorker（ThreadPoolExecutor.java:1162）
> > at java.util.concurrent.ThreadPoolExecutor $ Worker .run（ThreadPoolExecutor.java:636）
> > at java.lang.Thread.run（Thread.java:764）
> > 引起：java.lang.SecurityException：
> > at android.os.Parcel.readException（Parcel.java:1959）
> > at android .os.Parcel.readException（Parcel.java:1905）
> > 在android.app.job.IJobCallback $ Stub $ Proxy.dequeueWork（IJobCallback.java:191）
> > at android.app.job.JobParameters.dequeueWork（JobParameters.java:196）
> > at com.onesignal.JobIntentService $ JobServiceEngineImpl.dequeueWork（JobIntentService） .java：337）
> > com.onesignal.JobIntentService.dequeueWork（JobIntentService.java:652）
> > com.onesignal.JobIntentService $ CommandProcessor.doInBackground（JobIntentService.java:412）
> > com.onesignal.JobIntentService $ CommandProcessor.doInBackground（JobIntentService。） java：405）
> > 在android.os.AsyncTask $ 2.call（AsyncTask.java:333）
> > java.util.concurrent.FutureTask.run（FutureTask.java:266）
> > java.util.concurrent.ThreadPoolExecutor.runWorker（ThreadPoolExecutor。 Java的：1162）
> > at java.util.concurrent.ThreadPoolExecutor $ Worker.run（ThreadPoolExecutor.java:636）
> > at java.lang.Thread.run（Thread.java:764）
你解决了吗？

**Comment by sunj** [comment]
请问，你问题解决了吗？
