### ISSUE TITLE
Can not receive push notifications when adding google-services.json and calling setEmail method

### ISSUE THREAD

**Issue by icsd** [OneSignal/OneSignal-Android-SDK#641]
**Description**
I can not receive Push Notifications from OneSignal if I add in my project the
_google-services.json_ from the **Firebase project ** I have created and use in my code OneSignal.setEmail method. If I don't use the OneSignal.setEmail method I can receive push notifications. 
I don't want to remove the _google-services.json_ from my project because it contains info
for another flavor of my app.

**Environment**
1. What version of the Android SDK are you using? Android SDK 25
2. How did you add the SDK to your project?  maven { url 'https://maven.google.com' }

**Steps to Reproduce Issue:**
1. Add in a project _google-services.json_ that is created from Firebase Project
2.Call OneSignal.setEmail method
3.Call OneSignal.sendTag method
4. Attempt to receive a push notification 
5. Notification never received

**Comment by muradmohdzain** [comment]
Need solution ASAP. I encounter the same problem

**Comment by jkasten2** [comment]
@icsd @muradmohdzain Can you check the logcat on the device for any errors or warnings? If you don't see any can you enable VERBOSE logging on the SDK and share all the entries it prints to your logcat?
```
OneSignal.setLogLevel(OneSignal.LOG_LEVEL.VERBOSE, OneSignal.LOG_LEVEL.NONE);
```

Also are you using the `NotificationExtenderService`? If so does disabling it have any effect?

**Comment by icsd** [comment]
I don't use the `NotificationExtenderService`

From OneSignal log I see that GCM and Firebase Libraries should not exist concurrently in the project. 
(I use GCM for Intercom, and it seems that I have to update it to a newer version that uses Firebase)
After some debugging I believe that the problem is not the call of the OneSignal.setEmail() method.
When the GCM is registered, OneSignal Notifications stop to work .

Here I want to mention that if I use in my project the old  _google-services.json_ from GCM, OneSignal notifications and GCM notifications play with no problem!

Here is the log from my device:
( I have edited some values of the log with XXX and ZZZ)

`10-06 13:42:19.826 22211-22211/XXX W/OneSignal: Both GCM & FCM Libraries detected! Please remove the deprecated GCM library.
10-06 13:42:22.222 22211-22524/XXX I/OneSignal: Device registered, push token = ZZZ
10-06 13:42:22.225 22211-22524/XXX D/OneSignal: registerUser: registerForPushFired:true, locationFired: true, awlFired: true

10-06 13:42:22.228 22211-22718/XXX W/AdvertisingIdClient: Error while reading from SharedPreferences 
    java.lang.SecurityException: MODE_WORLD_READABLE no longer supported
        at android.app.ContextImpl.checkMode(ContextImpl.java:2369)
        at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:383)
        at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:378)
        at com.google.android.gms.ads.identifier.AdvertisingIdClient.getAdvertisingIdInfo(Unknown Source)
        at com.onesignal.AdvertisingIdProviderGPS.getIdentifier(AdvertisingIdProviderGPS.java:45)
        at com.onesignal.OneSignal.registerUserTask(OneSignal.java:1223)
        at com.onesignal.OneSignal.access$2300(OneSignal.java:80)
        at com.onesignal.OneSignal$7.run(OneSignal.java:1206)
        at java.lang.Thread.run(Thread.java:762)

10-06 13:42:22.641 22211-22211/XXX D/OneSignal: curActivity is NOW: null
10-06 13:42:22.778 22211-22211/XXX D/OneSignal: curActivity is NOW: XXX.activities.StartUpActivity:XXX.activities.StartUpActivity@c56beed
10-06 13:42:23.301 22211-22211/XXX D/OneSignal: onActivityStopped: XXX.activities.SplashScreenActivity
    curActivity is NOW: XXX.activities.StartUpActivity:XXX.activities.StartUpActivity@c56beed
10-06 13:42:23.302 22211-22211/XXX D/OneSignal: onActivityDestroyed: XXX.activities.SplashScreenActivity
    curActivity is NOW: XXX.activities.StartUpActivity:XXX.activities.StartUpActivity@c56beed
10-06 13:42:27.512 22211-22727/XXX D/OneSignal: OneSignalRestClient: Making request to: https://onesignal.com/api/v1/players

10-06 13:42:27.517 22211-22727/XXX D/OneSignal: OneSignalRestClient: POST SEND JSON: {"app_id":"ZZZ","ad_id":"bdd51323-96cb-49ff-acd0-a765e347e0cd","device_os":"7.0","timezone":10800,"language":"en","sdk":"031002","sdk_type":"native","android_package":"XXX","device_model":"SM-T715","game_version":40,"pkgs_a":["kExBmh+RO6HkCK\/s2mniE6+qMhODbvBYIvLP3pW\/pO0=","u1M+zJbkN40NTzZMU871b2G50oyi0Oddb3ZkbDxGOc8=","ZY70LjvjhhmAlxL5BNMYT2wUnuqQ\/o4Vu82MhNM8ny4="],"net_type":0,"carrier":"vodafone GR","rooted":false,"identifier":"ePUqo821wMk:APA91bEkYXPYCgshCvGzp7lHMMjIauOZXLP20eXpfEn80FjRY-eQ7IEOBmFdIIwIWiAj4P8HURGogTlL821wh66HLb_pRkAXNzWsV1fcQPr_TTTfrY2b0ZzKWQUSRq88BIEeIuGb4F68","device_type":1}

10-06 13:42:27.765 22211-22727/XXX V/OneSignal: OneSignalRestClient: After con.getResponseCode  to: https://onesignal.com/api/v1/players
10-06 13:42:27.765 22211-22727/XXX D/OneSignal: OneSignalRestClient: Successfully finished request to: https://onesignal.com/api/v1/players
10-06 13:42:27.770 22211-22727/XXX D/OneSignal: POST RECEIVED JSON: {"success":true,"id":"4005f04f-0b33-4857-bb32-f66174dbc32e"}
10-06 13:42:27.788 22211-22728/XXX I/OneSignal: Device registered, UserId = 4005f04f-0b33-4857-bb32-f66174dbc32e`

**Comment by jkasten2** [comment]
@icsd Thanks for the logcat, I can see your device is successfully registering to OneSignal with a push token. If you uninstall your app and reinstall it you may get a new player_id so make sure you are sending to a new id in your testing.

If you are using `google-services.json` in your project make sure it is for the same FCM project as you are using with OneSignal. This is normally only a requirement if you are using initializing FCM outside of OneSignal but we still recommend making sure it matches if you are only using other Firebase services.

The `MODE_WORLD_READABLE no longer supported` warning from `AdvertisingIdClient` is a bug with older versions of `com.google.android.gms:play-services`. Make sure you have an updated version.

**Comment by jkasten2** [comment]
Closing due to inactivity, please provide the details above if you are still seeing this issue and we can reopen. Thanks.
