### ISSUE TITLE
crash at GenerateNotification.java line 372 

### ISSUE THREAD

**Issue by xzamirx** [OneSignal/OneSignal-Android-SDK#651]
**Description:**
Hello i have been getting a crash on 70+ devices with 1600+ crashes. I have seen that this was an old issue from 2017 that was closed but is happening in our app.

Crash at: 
```
GenerateNotification.java line 372 
com.onesignal.GenerateNotification.showNotification
```

**Environment**
1. Android SDK 27 
2. SDK is added with Gradle
3. Android support version: 27.1.1 
4. Android api 4 and 5
5. One signal: api('com.onesignal:OneSignal:[3.8.3, 3.99.99]')

**Steps to Reproduce Issue:**

1. Send a message from One signal dashboard
2. On some devices with Android 4 (83%  of the affected users) and 5( 17 %  of the affected users) the app crash when trying to show the notifications ( reported by fabric)

**Anything else:**

this is my fabric report: https://ibb.co/bFgfBL

Stack Trace:
```
Caused by java.lang.RuntimeException: bad array lengths
       at android.os.Parcel.readIntArray(Parcel.java:827)
       at android.app.INotificationManager$Stub$Proxy.enqueueNotificationWithTag(INotificationManager.java:348)
       at android.app.NotificationManager.notify(NotificationManager.java:161)
       at android.support.v4.app.NotificationManagerCompat.notify(NotificationManagerCompat.java:210)
       at android.support.v4.app.NotificationManagerCompat.notify(NotificationManagerCompat.java:194)
       at com.onesignal.GenerateNotification.showNotification(GenerateNotification.java:372)
       at com.onesignal.GenerateNotification.fromJsonPayload(GenerateNotification.java:106)
       at com.onesignal.NotificationBundleProcessor.ProcessJobForDisplay(NotificationBundleProcessor.java:96)
       at com.onesignal.NotificationBundleProcessor.ProcessFromGCMIntentService(NotificationBundleProcessor.java:75)
       at com.onesignal.RestoreJobService.onHandleWork(RestoreJobService.java:43)
       at com.onesignal.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:386)
       at com.onesignal.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:377)
       at android.os.AsyncTask$2.call(AsyncTask.java:288)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
```

**Comment by jkasten2** [comment]
@xzamirx Thanks for reporting. Can you provide the full stack trace of all threads? I believe you download this from the crash on the fabric dashboard on the issue.

Are you able to reproduce the crash? We were not able to do so in the past which is critical to us finding a fix for this issue. Thanks

**Comment by xzamirx** [comment]
@jkasten2 Hello i was not able to reproduce the crash by myself. We are trying to contact the users to see if we can find at least one device were the crash is happening.

PD: i updated my post to show the full fabric's stack traces

**Comment by xzamirx** [comment]
@jkasten2  these are the models and versions: https://imgur.com/a/IhlLTz9

**Comment by jkasten2** [comment]
@xzamirx Thanks for the details. We don't have any of these specific tests to test with but since it is wide range of devices it is most likely a bug related to ASOP itself.

The crash has `RestoreJobService` in it so this is happening when restoring notifications back to the notification shade after an app update or a device reboot. We are limiting the number of notifications to be restored to 49 in this PR which will help mitigate this bug.
https://github.com/OneSignal/OneSignal-Android-SDK/pull/645
It also has a longer delay between notification displays when they are being restored. I believe the issue is a race condition in ASOP so this also might fix the issue.

We will include that PR in next release so you can watch for a release here and give the new version a try.
https://github.com/OneSignal/OneSignal-Android-SDK/releases
