### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/internal/zzbcc; And  Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.internal.zzbcc" on path:

### ISSUE THREAD

**Issue by keat1996** [OneSignal/OneSignal-Android-SDK#654]
**Description:**

i facing an error that" java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/internal/zzbcc; "And  "Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.internal.zzbcc" on path:" after i click on scan barcode button

**Steps to Reproduce Issue:**

2018-10-24 17:00:43.242 24525-24525/com.example.johnn.lodgingservicesystemowner E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.johnn.lodgingservicesystemowner, PID: 24525
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/internal/zzbcc;
        at com.example.johnn.lodgingservicesystemowner.ScanBarcodeActivity.createCameraSource(ScanBarcodeActivity.java:34)
        at com.example.johnn.lodgingservicesystemowner.ScanBarcodeActivity.onCreate(ScanBarcodeActivity.java:30)
        at android.app.Activity.performCreate(Activity.java:7372)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3147)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3302)
        at android.app.ActivityThread.-wrap12(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7425)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.internal.zzbcc" on path: DexPathList[[zip file "/data/app/com.example.johnn.lodgingservicesystemowner-ykZR-bWgdEFzW8XMIEVBjQ==/base.apk", zip file "/data/app/com.example.johnn.lodgingservicesystemowner-ykZR-bWgdEFzW8XMIEVBjQ==/split_lib_dependencies_apk.apk", zip file "/data/app/com.example.johnn.lodgingservicesystemowner-ykZR-bWgdEFzW8XMIEVBjQ==/split_lib_resources_apk.apk", zip file "/data/app/com.example.johnn.lodgingservicesystemowner-ykZR-bWgdEFzW8XMIEVBjQ==/split_lib_slice_0_apk.apk", zip file "/data/app/com.example.johnn.lodgingservicesystemowner-ykZR-bWgdEFzW8XMIEVBjQ==/split_lib_slice_1_apk.apk", zip file "/data/app/com.example.johnn.lodgingservicesystemowner-ykZR-bWgdEFzW8XMIEVBjQ==/split_lib_slice_2_apk.apk", zip file "/data/app/com.example.johnn.lodgingservicesystemowner-ykZR-bWgdEFzW8XMIEVBjQ==/split_lib_slice_3_apk.apk", zip file "/data/app/com.example.johnn.lodgingservicesystemowner-ykZR-bWgdEFzW8XMIEVBjQ==/split_lib_slice_4_apk.apk", zip file "/data/app/com.example.johnn.lodgingservicesystemowner-ykZR-bWgdEFzW8XMIEVBjQ==/split_lib_slice_5_apk.apk", zip file "/data/app/com.example.johnn.lodgingservicesystemowner-ykZR-bWgdEFzW8XMIEVBjQ==/split_lib_slice_6_apk.apk", zip file "/data/app/com.example.johnn.lodgingservicesystemowner-ykZR-bWgdEFzW8XMIEVBjQ==/split_lib_slice_7_apk.apk", zip file "/data/app/com.example.johnn.lodgingservicesystemowner-ykZR-bWgdEFzW8XMIEVBjQ==/split_lib_slice_8_apk.apk", zip file "/data/app/com.example.johnn.lodgingservicesystemowner-ykZR-bWgdEFzW8XMIEVBjQ==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.example.johnn.lodgingservicesystemowner-ykZR-bWgdEFzW8XMIEVBjQ==/lib/arm64, /system/lib64, /vendor/lib64, /product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.example.johnn.lodgingservicesystemowner.ScanBarcodeActivity.createCameraSource(ScanBarcodeActivity.java:34) 
        at com.example.johnn.lodgingservicesystemowner.ScanBarcodeActivity.onCreate(ScanBarcodeActivity.java:30) 
        at android.app.Activity.performCreate(Activity.java:7372) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3147) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3302) 
        at android.app.ActivityThread.-wrap12(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891) 
        at android.os.Handler.dispatchMessage(Handler.java:108) 
        at android.os.Looper.loop(Looper.java:166) 
        at android.app.ActivityThread.main(ActivityThread.java:7425) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921) 
    	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/com.example.johnn.lodgingservicesystemowner-ykZR-bWgdEFzW8XMIEVBjQ==/split_lib_resources_apk.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:353)
        at dalvik.system.DexFile.<init>(DexFile.java:100)
        at dalvik.system.DexFile.<init>(DexFile.java:74)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
        at dalvik.system.DexPathList.<init>(DexPathList.java:157)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
2018-10-24 17:00:43.242 24525-24525/com.example.johnn.lodgingservicesystemowner E/AndroidRuntime:     at com.android.internal.os.PathClassLoaderFactory.createClassLoader(PathClassLoaderFactory.java:43)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:75)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:38)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:716)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:749)
        at android.app.LoadedApk.getResources(LoadedApk.java:996)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2489)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6398)
        at android.app.ActivityThread.-wrap2(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1963)
        		... 6 more

**Comment by jkasten2** [comment]
@keat1996 Can you provide the exact version of OneSignal you are using? If you can attach your `build.gradle` that would be helpful.

Make sure you have applied the OneSignal Gradle Plugin noted in step one as this will most likely fix this issue
https://documentation.onesignal.com/docs/android-sdk-setup#section-1-gradle-setup

**Comment by cearsandroid** [comment]
This error coming when i am add google ads

**Comment by jkasten2** [comment]
@cearsandroid We just released [OneSignal-Gradle-Plugin 0.12.1](https://github.com/OneSignal/OneSignal-Gradle-Plugin/releases/tag/0.12.1) which should fix this issue. Resync gradle and you should get this new version.

Let us know if upgrading this does not work and provide your `build.gradle` files and we can reopen this issue.
