### ISSUE TITLE
Fatal Exception: java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again

### ISSUE THREAD

**Issue by TuiyTuyHussein** [OneSignal/OneSignal-Android-SDK#661]
**Description:**
```java
Fatal Exception: java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
       at java.lang.Thread.nativeCreate(Thread.java)
       at java.lang.Thread.start(Thread.java:733)
       at com.onesignal.OneSignalRestClient.makeRequest(OneSignalRestClient.java:102)
       at com.onesignal.OneSignalRestClient.putSync(OneSignalRestClient.java:82)
       at com.onesignal.UserStateSynchronizer.doPutSync(UserStateSynchronizer.java:287)
       at com.onesignal.UserStateSynchronizer.internalSyncUserState(UserStateSynchronizer.java:208)
       at com.onesignal.UserStateSynchronizer.syncUserState(UserStateSynchronizer.java:170)
       at com.onesignal.OneSignalStateSynchronizer.syncUserState(OneSignalStateSynchronizer.java:71)
       at com.onesignal.OneSignalSyncServiceUtils$SyncRunnable$1.complete(OneSignalSyncServiceUtils.java:228)
       at com.onesignal.LocationGMS.fireComplete(LocationGMS.java:254)
       at com.onesignal.LocationGMS.fireFailedComplete(LocationGMS.java:239)
       at com.onesignal.LocationGMS.startGetLocation(LocationGMS.java:206)
       at com.onesignal.LocationGMS.getLocation(LocationGMS.java:172)
       at com.onesignal.OneSignalSyncServiceUtils$SyncRunnable.run(OneSignalSyncServiceUtils.java:233)
       at java.lang.Thread.run(Thread.java:764)
```

**Environment**
1. SM-J610F --> Android 8.1
2. implementation 'com.onesignal:OneSignal:3.10.2'

**Comment by jkasten2** [comment]
@TuiyTuyHussein Thanks for the full stacktrace. This is the same problem as issue #258.

This is due the your app being close the memory limit and this extra thread setting it over the edge. Are you getting any other out of memory crashes? Can you profile the memory your app is using?

We will be optimizing `OneSignalRestClient` in this SDK in the future to not create a new thread per request but is small memory optimization.

**Comment by rgomezp** [comment]
Closing due to no response. Please feel free to @ us if you have any follow up questions

**Comment by shefich** [comment]
I have the same or connected error but in OneSignal-Unity-SDK 3.0.11.
`
Non-fatal Exception: java.lang.Exception: AndroidJavaException : java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
       at java.lang.Thread.nativeCreate(java.lang.Thread)
       at java.lang.Thread.start(java.lang.Thread)
       at com.onesignal.OneSignalRestClient.post(com.onesignal.OneSignalRestClient)
       at com.onesignal.OneSignal.postNotification(com.onesignal.OneSignal)
       at com.unity3d.player.UnityPlayer.nativeRender(com.unity3d.player.UnityPlayer)
       at com.unity3d.player.UnityPlayer.access$500(com.unity3d.player.UnityPlayer)
       at com.unity3d.player.UnityPlayer$e$1.handleMessage(com.unity3d.player.UnityPlayer$e$1)
       at android.os.Handler.dispatchMessage(android.os.Handler)
       at android.os.Looper.loop(android.os.Looper)
       at com.unity3d.player.UnityPlayer$e.run(com.unity3d.player.UnityPlayer$e)
       at UnityEngine.AndroidJNISafe.CheckException(UnityEngine.AndroidJNISafe)
       at UnityEngine.AndroidJavaObject._CallStatic(UnityEngine.AndroidJavaObject)
       at OneSignalSDK.OneSignalAndroid.PostNotification(OneSignalSDK.OneSignalAndroid)
       at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[TResult].Start[TStateMachine](System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[TResult])
       at OneSignalSDK.OneSignalAndroid.PostNotification(OneSignalSDK.OneSignalAndroid)
       at OneSignalInit.NotificationForDay(OneSignalInit)
       at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[TStateMachine](System.Runtime.CompilerServices.AsyncVoidMethodBuilder)
       at OneSignalInit+<SetDailyReminder>d__12.MoveNext(OneSignalInit+<SetDailyReminder>d__12)
       at UnityEngine.SetupCoroutine.InvokeMoveNext(UnityEngine.SetupCoroutine)
       at OneSignalInit.NotificationForDay(OneSignalInit)
       at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[TStateMachine](System.Runtime.CompilerServices.AsyncVoidMethodBuilder)
       at OneSignalInit+<SetDailyReminder>d__12.MoveNext(OneSignalInit+<SetDailyReminder>d__12)
       at UnityEngine.SetupCoroutine.InvokeMoveNext(UnityEngine.SetupCoroutine)
       at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0(System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c)
       at UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke(UnityEngine.UnitySynchronizationContext+WorkRequest)
       at UnityEngine.UnitySynchronizationContext.Exec(UnityEngine.UnitySynchronizationContext)
`

Found this link: [https://stackoverflow.com/questions/35701501/throwing-outofmemoryerror-pthread-create-1040kb-stack-failed-try-again-when](url). The author of the answer tells that you need new request only if the previous one is null.
As I see in previous answers here you did smthg. like that previously, so it doesn't work as expected.

**Comment by jkasten2** [comment]
OneSignal doesn't use much memory so this isn't a root cause of the problem. There is most likely another crash in your app for another `OutOfMemoryError`. (unless you are catching it and silencing it)

However if you update the the latest v5 SDK you should no longer see this at all, since new threads are no longer being created there. Please try updating and let us know if if fixes the issue completely. If not please open a new issue with the new stack trace.

**Comment by shefich** [comment]
> OneSignal doesn't use much memory so this isn't a root cause of the problem. There is most likely another crash in your app for another `OutOfMemoryError`. (unless you are catching it and silencing it)
> 
> However if you update the the latest v5 SDK you should no longer see this at all, since new threads are no longer being created there. Please try updating and let us know if if fixes the issue completely. If not please open a new issue with the new stack trace.

"latest v5 SDK" can't send messages from the app, so it can't be used.
