### ISSUE TITLE
IllegalArgumentException in version 3.10.3

### ISSUE THREAD

**Issue by alex-techhuddle** [OneSignal/OneSignal-Android-SDK#667]
**Description:**

We get the following crash

```Java
Fatal Exception: java.lang.IllegalArgumentException: No such service ComponentInfo{com.shanga.walli/com.onesignal.SyncJobService}
       at android.os.Parcel.readException(Parcel.java:1956)
       at android.os.Parcel.readException(Parcel.java:1898)
       at android.app.job.IJobScheduler$Stub$Proxy.schedule(IJobScheduler.java:180)
       at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:72)
       at com.onesignal.OneSignalSyncServiceUtils.scheduleSyncServiceAsJob(OneSignalSyncServiceUtils.java:148)
       at com.onesignal.OneSignalSyncServiceUtils.scheduleSyncTask(OneSignalSyncServiceUtils.java:116)
       at com.onesignal.OneSignalSyncServiceUtils.scheduleSyncTask(OneSignalSyncServiceUtils.java:63)
       at com.onesignal.OneSignal.onAppLostFocus(OneSignal.java:1096)
       at com.onesignal.ActivityLifecycleHandler$AppFocusRunnable.run(ActivityLifecycleHandler.java:171)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:180)
       at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Environment**
The issue is happening exclusively on Android 8 devices. It _seems_ to happen while the app is in the background. The issue started happening with version 3.10.3, before that we were using an older version and did not get errors.

CompileSdk=TargetSdk=26
we add the onesignal library like this:
implementation 'com.onesignal:OneSignal:3.10.2@aar'

**Steps to Reproduce Issue:**
We don't know the steps to reproduce. We just see the logs.

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by jkasten2** [comment]
@alex-techhuddle The `java.lang.IllegalArgumentException: No such service ComponentInfo` error happens either when this listed service isn't defined in the `AndroidManifest.xml` at all or since you are only seeing the issue on Android Oreo then `android:permission="android.permission.BIND_JOB_SERVICE"` is most likely missing from the `com.onesignal.SyncJobService` service in the `AndroidManifest.xml`.

However this is automatically added to your `AndroidManifest.xml` as it is part of the OneSignal .aar file, source of this is below.
https://github.com/OneSignal/OneSignal-Android-SDK/blob/3.10.3/OneSignalSDK/onesignal/src/main/AndroidManifest.xml#L78-L79

The only way this could be excluded is if you have `tools:node="replace"` in your `<application>` tag and re-defining `com.onesignal.SyncJobService` in your `AndroidManifest.xm`. Can you check for this?

**Comment by jkasten2** [comment]
@alex-techhuddle Closing this issue in favor of #670 for this issue since there is more activity there. If this crash is not happening on a Lava device let us know and we can reopen this issue.
