### ISSUE TITLE
Lava Devices - [Onesignal 3.10.3]  java.lang.IllegalArgumentException  com.onesignal.OneSignalSyncServiceUtils.scheduleSyncServiceAsJob

### ISSUE THREAD

**Issue by mitonline** [OneSignal/OneSignal-Android-SDK#670]
**Description:**
On some devices, see the following exception on Onesignal sdk v 3.10.3. This was fixed in v3.10.3 but we still see these in the console.
```java
java.lang.IllegalArgumentException: 
  at android.os.Parcel.readException (Parcel.java:2009)
  at android.os.Parcel.readException (Parcel.java:1951)
  at android.app.job.IJobScheduler$Stub$Proxy.schedule (IJobScheduler.java:180)
  at android.app.JobSchedulerImpl.schedule (JobSchedulerImpl.java:44)
  at com.onesignal.OneSignalSyncServiceUtils.scheduleSyncServiceAsJob (OneSignalSyncServiceUtils.java:148)
  at com.onesignal.OneSignalSyncServiceUtils.scheduleSyncTask (OneSignalSyncServiceUtils.java:116)
  at com.onesignal.OneSignalSyncServiceUtils.scheduleSyncTask (OneSignalSyncServiceUtils.java:63)
  at com.onesignal.OneSignal.onAppLostFocus (OneSignal.java:1096)
  at com.onesignal.ActivityLifecycleHandler$AppFocusRunnable.run (ActivityLifecycleHandler.java:171)
  at android.os.Handler.handleCallback (Handler.java:790)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:164)
  at android.os.HandlerThread.run (HandlerThread.java:65)
```
(your description here)

**Environment**

We upgraded to onesignal sdk v 3.10.3 but still see the issue.
The sdk is added using build.gradle in android studio

**Steps to Reproduce Issue:**

Unable to recreate this issue. This is seen on android 7.1 and 8.1 on Z61 and Z91 devices.

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by jkasten2** [comment]
@mitonline Thanks for reporting, in the 3.10.3 release we fixed an exception related to scheduling a job with `persisted` without the app having the `RECEIVE_BOOT_COMPLETED` permission.

Could you provide the details below so we can narrow down the issue?
1. There are a few different `java.lang.IllegalArgumentException` exceptions, does the crash report indicate any more details?
2. Are you only seeing this crash on Lava devices?
3. Are you able to reproduce the issue on your devices?
4. How many users is this crash effecting?

**Comment by mitonline** [comment]
1. The console just indicates this stacktrace. There is a variation in some of them having scheduleSyncService as below
2. All crashes are seen on Lava devices and only on android versions 7.1 and 8.1. (90% of crashes are on 8.1 and 10% on 7.1)
3. We have not been able to reproduce 
4. We are having about 50 crashes every day (Looks like affecting almost all lava devices on these android versions)
java.lang.IllegalArgumentException: 
 
  at android.os.Parcel.readException (Parcel.java:2009)
 
  at android.os.Parcel.readException (Parcel.java:1951)
 
  at android.app.job.IJobScheduler$Stub$Proxy.schedule (IJobScheduler.java:180)
 
  at android.app.JobSchedulerImpl.schedule (JobSchedulerImpl.java:44)
 
  at com.onesignal.OneSignalSyncServiceUtils.scheduleSyncServiceAsJob (OneSignalSyncServiceUtils.java:148)
 
  at com.onesignal.OneSignalSyncServiceUtils.scheduleSyncTask (OneSignalSyncServiceUtils.java:116)
 
  at com.onesignal.OneSignalSyncServiceUtils.scheduleSyncTask (OneSignalSyncServiceUtils.java:63)
 
  at com.onesignal.OneSignal.scheduleSyncService (OneSignal.java:1106)
 
  at com.onesignal.OneSignal.onAppLostFocus (OneSignal.java:1082)
 
  at com.onesignal.ActivityLifecycleHandler$AppFocusRunnable.run (ActivityLifecycleHandler.java:171)
 
  at android.os.Handler.handleCallback (Handler.java:790)
 
  at android.os.Handler.dispatchMessage (Handler.java:99)
 
  at android.os.Looper.loop (Looper.java:164)
 
  at android.os.HandlerThread.run (HandlerThread.java:65)

**Comment by vishrut2207** [comment]
I had the same problem here. We are getting around 40 crashes every day.

Devices: LAVA: **Z61_2GB, Z60s, Z61, iris65, Z91, Z90, iris88**
Operating System : **7.0, 7.1.1, 8.1.0**

Fatal Exception: java.lang.IllegalArgumentException
No such service ComponentInfo{com.rollerbannermaker/com.onesignal.SyncJobService}

Fatal Exception: java.lang.IllegalArgumentException: No such service ComponentInfo{com.rollerbannermaker/com.onesignal.SyncJobService}
       at android.os.Parcel.readException(Parcel.java:2009)
       at android.os.Parcel.readException(Parcel.java:1951)
       at android.app.job.IJobScheduler$Stub$Proxy.schedule(IJobScheduler.java:180)
       at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:44)
       at com.onesignal.OneSignalSyncServiceUtils.scheduleSyncServiceAsJob(OneSignalSyncServiceUtils.java:137)
       at com.onesignal.OneSignalSyncServiceUtils.scheduleSyncTask(OneSignalSyncServiceUtils.java:113)
       at com.onesignal.OneSignalSyncServiceUtils.scheduleSyncTask(OneSignalSyncServiceUtils.java:60)
       at com.onesignal.OneSignal.onAppLostFocus(OneSignal.java:1096)
       at com.onesignal.ActivityLifecycleHandler$AppFocusRunnable.run(ActivityLifecycleHandler.java:171)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by jkasten2** [comment]
@mitonline In reply to number 3, do you have any Lava devices where you tried to reproduce this issue? Or was it on devices by other manufacturers?

@vishrut2207 Can you try to reproduce this issue? Steps to reproduce will be key fixing this issue.

**Comment by mourjan** [comment]
@jkasten2 my app (not using this library) is also facing the same problem and I too do not have a LAVA device but if I may add, I called one of the users who have a LAVA device and suffering this crash and his response was: "After installing the app everything works perfectly, but on second launch it crashes and he would re-install it once again for it to work". it is 100% related to LAVA software's hierarchy and I tried to contact LAVA's software development team without any luck.

**Comment by jkasten2** [comment]
@mourjan Thanks for the details! Every of information helps here.

I agree, it has to be something LAVA has modified with Android which as a bug in the ROMs on their devices. We can attempt to get in contact with LAVA as well to see if they are responsive.

**Comment by mayurwish** [comment]
We are using Onesignal 3.10.7 and we are facing similar issue Lava Z61-2GB
Brand: LAVA, Model: Z61-2GB, Orientation: Portrait, RAM free: 671.21 MB, Disk free: 2.9 GB, Version: 8.1.0, Orientation: Portrait, Rooted: No

Fatal Exception: java.lang.IllegalArgumentException: No such service ComponentInfo{com.gocheckapp/com.onesignal.SyncJobService}
       at android.os.Parcel.readException(Parcel.java:2009)
       at android.os.Parcel.readException(Parcel.java:1951)
       at android.app.job.IJobScheduler$Stub$Proxy.schedule(IJobScheduler.java:180)
       at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:44)
       at com.onesignal.ae.c(SourceFile:148)
       at com.onesignal.ae.b(SourceFile:116)
       at com.onesignal.ae.a(SourceFile:63)
       at com.onesignal.OneSignal.d(SourceFile:12079)
       at com.onesignal.a$b.run(SourceFile:171)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by rgomezp** [comment]
@mayurwish ,
Someone has opened this issue @ #753 . Will close this issue. Please follow it there

**Comment by nitish4005** [comment]
is there any workaround for lava devices?
