### ISSUE TITLE
ConcurrentModificationException in UserStateSynchronizer since 3.10.3 

### ISSUE THREAD

**Issue by asfdfdfd** [OneSignal/OneSignal-Android-SDK#671]
**Description:**

Nothing to add here. I had this crash since 3.10.3. You could investigate it in Crashlytics http://crashes.to/s/6373d771db0.

**Environment**

```
compileSdkVersion 28
buildToolsVersion "28.0.3"
minSdkVersion 16
targetSdkVersion 28
```

OneSignal SDK added via Gradle:

```
implementation 'com.onesignal:OneSignal:3.10.3'
```

**Steps to Reproduce Issue:**

I could not reproduce it on my device, but i've received multiple crashes via Crashlytics from users. http://crashes.to/s/6373d771db0

**Comment by jkasten2** [comment]
@asfdfdfd Thanks for the report, it looks like this crash effected 8 users on Android 7 but mostly 8. We will look into the stack trace and see if we can fix the is in future update.

Attaching the stack trace from the link for quicker reference.
```java
Fatal Exception: java.util.ConcurrentModificationException
       at java.util.ArrayList$Itr.next(ArrayList.java:866)
       at com.onesignal.UserStateSynchronizer.internalSyncUserState(UserStateSynchronizer.java:194)
       at com.onesignal.UserStateSynchronizer.syncUserState(UserStateSynchronizer.java:170)
       at com.onesignal.UserStateSynchronizer$NetworkHandlerThread$1.run(UserStateSynchronizer.java:77)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.os.HandlerThread.run(HandlerThread.java:65)
```
Only one thread with OneSignal in the stack trace `OSH_NetworkHandlerThread`
