### ISSUE TITLE
No such service ComponentInfo{com.app.manch/com.onesignal.SyncJobService}

### ISSUE THREAD

**Issue by worstkiller** [OneSignal/OneSignal-Android-SDK#676]
**Description:**
```java
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {com.app.manch/com.app.manch.activities.Splash}: java.lang.IllegalArgumentException: No such service ComponentInfo{com.app.manch/com.onesignal.SyncJobService}
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3662)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3702)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2925)
       at android.app.ActivityThread.-wrap13(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1623)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:203)
       at android.app.ActivityThread.main(ActivityThread.java:6528)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945)
```
----------- 
```java
Caused by java.lang.IllegalArgumentException: No such service ComponentInfo{com.app.manch/com.onesignal.SyncJobService}
       at android.os.Parcel.readException(Parcel.java:1688)
       at android.os.Parcel.readException(Parcel.java:1637)
       at android.app.job.IJobScheduler$Stub$Proxy.schedule(IJobScheduler.java:158)
       at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:42)
       at com.onesignal.OneSignalSyncServiceUtils.scheduleSyncServiceAsJob(OneSignalSyncServiceUtils.java:148)
       at com.onesignal.OneSignalSyncServiceUtils.scheduleSyncTask(OneSignalSyncServiceUtils.java:116)
       at com.onesignal.OneSignalSyncServiceUtils.scheduleLocationUpdateTask(OneSignalSyncServiceUtils.java:58)
       at com.onesignal.LocationGMS.scheduleUpdate(LocationGMS.java:102)
       at com.onesignal.OneSignalSyncServiceUtils.cancelSyncTask(OneSignalSyncServiceUtils.java:69)
       at com.onesignal.OneSignal.onAppFocus(OneSignal.java:1174)
       at com.onesignal.ActivityLifecycleHandler.handleFocus(ActivityLifecycleHandler.java:120)
       at com.onesignal.ActivityLifecycleHandler.onActivityResumed(ActivityLifecycleHandler.java:74)
       at com.onesignal.ActivityLifecycleListener.onActivityResumed(ActivityLifecycleListener.java:48)
       at android.app.Application.dispatchActivityResumed(Application.java:216)
       at android.app.Activity.onResume(Activity.java:1289)
       at android.support.v4.app.FragmentActivity.onResume(FragmentActivity.java:514)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1293)
       at android.app.Activity.performResume(Activity.java:6936)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3633)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3702)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2925)
       at android.app.ActivityThread.-wrap13(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1623)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:203)
       at android.app.ActivityThread.main(ActivityThread.java:6528)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945) 
```
**Environment**
Manufacturer : LAVA 
OS : 7.1.1, 8.1.0
Model : Z91, Z60s
OneSignal SDK : com.onesignal:OneSignal:3.10.3
OneSignal Plugin : 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:0.12.0'
Android SDK Target  : Max(28)  Min(16)

**Steps to Reproduce Issue:**
Not able to reproduce since it's happening only on Lava Devices which we don't have unfortunately.

  
**Anything else:**
There are existing issues similar to this but those are closed and have a PR but including latest SDK also not solves the problem. Please tell us any suggestions or work around till the fix.

**Comment by jkasten2** [comment]
@worstkiller This error `No such service ComponentInfo{.../com.onesignal.SyncJobService}` should only happen if it was missing from your `AndroidManifest.xml`. Since it is only happening on Lava devices it could be a bug with the ROM on these devices. If you are only seeing single digit number of cashes then it may just be someone running a modified version of your APK where they removed this.

**Comment by worstkiller** [comment]
Thanks for the reply, I guess we have to live with this.
Thanks, closing this

**Comment by jkasten2** [comment]
Ref #670

**Comment by ubarua123** [comment]
I got this on Firebase on LAVA. I think it's a LAVA issue.
