### ISSUE TITLE
java.lang.RuntimeException: bad array lengths exception

### ISSUE THREAD

**Issue by jkasten2** [OneSignal/OneSignal-Android-SDK#70]
The following crash happens on some Android devices. It seems to be related to the 2.5.0 release (happens in 2.5.1 as well). It may only happen with `support:appcompat-v7:23.1.1` (also try `support:appcompat-v7:24.0.0-alpha2` in testing) with custom large and big picture images set as well.

``` VB
Fatal Exception: java.lang.RuntimeException: bad array lengths
       at android.os.Parcel.readIntArray(Parcel.java:820)
       at android.app.INotificationManager$Stub$Proxy.enqueueNotificationWithTag(INotificationManager.java:348)
       at android.app.NotificationManager.notify(NotificationManager.java:152)
       at android.support.v4.app.NotificationManagerCompatEclair.postNotification(NotificationManagerCompatEclair.java:30)
       at android.support.v4.app.NotificationManagerCompat$ImplEclair.postNotification(NotificationManagerCompat.java:152)
       at android.support.v4.app.NotificationManagerCompat.notify(NotificationManagerCompat.java:225)
       at android.support.v4.app.NotificationManagerCompat.notify(NotificationManagerCompat.java:209)
       at com.onesignal.GenerateNotification.showNotification(GenerateNotification.java:320)
       at com.onesignal.GenerateNotification.fromJsonPayload(GenerateNotification.java:100)
       at com.onesignal.NotificationBundleProcessor.Process(NotificationBundleProcessor.java:77)
       at com.onesignal.NotificationBundleProcessor.ProcessFromGCMIntentService(NotificationBundleProcessor.java:62)
       at com.onesignal.GcmIntentService.onHandleIntent(GcmIntentService.java:54)
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:146)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by jkasten2** [comment]
The original issue as sent in by a developer through support. We haven't received any other reports of this. The issue is most likely related to specific `appcompat` versions and / or a modified Android framework code base on the device.
