### ISSUE TITLE
One Signal ConcurrentModificationException

### ISSUE THREAD

**Issue by Goran1708** [OneSignal/OneSignal-Android-SDK#708]
Getting bunch of crashes in production on our app with this stack trace, idk how to reproduce it

Fatal Exception: java.util.ConcurrentModificationException Raw Text
--
  | java.util.ArrayList$Itr.next (ArrayList.java:860)
  | com.onesignal.OneSignal$15.run (OneSignal.java:1710)
  | java.lang.Thread.run (Thread.java:764)

**Comment by Goran1708** [comment]
Issue still occurring

**Comment by hermant2** [comment]
https://github.com/OneSignal/OneSignal-Android-SDK/pull/703/files#diff-8f1d87ed84bc5cc2e615dcfb826df87bR1659

Not related to proguard.  The issue was happening due to the changes in the newest release. In which this `pendingGetTagsHandlers` was being modified from multiple threads.  We rolled back to the previous release for the time being in order to fix.

**Comment by rgomezp** [comment]
Hi @hermant2 ,
Thanks for reporting this. We will look into this and see if we can find an answer. If you happen to gain more clarity, please let us know!

**Comment by rgomezp** [comment]
@Goran1708 & @hermant2 ,
Haven't been able to reproduce the issue. Any ideas?

**Comment by joccjo** [comment]
Fatal Exception: java.util.ConcurrentModificationException
       at java.util.ArrayList$Itr.next(ArrayList.java:860)
       at com.onesignal.UserStateSynchronizer.doPutSync(UserStateSynchronizer.java:272)
       at com.onesignal.UserStateSynchronizer.internalSyncUserState(UserStateSynchronizer.java:208)
       at com.onesignal.UserStateSynchronizer.syncUserState(UserStateSynchronizer.java:170)
       at com.onesignal.OneSignalStateSynchronizer.syncUserState(OneSignalStateSynchronizer.java:72)
       at com.onesignal.OneSignalSyncServiceUtils$SyncRunnable$1.complete(OneSignalSyncServiceUtils.java:228)
       at com.onesignal.LocationGMS.fireComplete(LocationGMS.java:254)
       at com.onesignal.LocationGMS.fireCompleteForLocation(LocationGMS.java:288)
       at com.onesignal.LocationGMS.access$500(LocationGMS.java:55)
       at com.onesignal.LocationGMS$GoogleApiClientListener.onConnected(LocationGMS.java:317)
       at com.google.android.gms.common.internal.GmsClientEventManager.onConnectionSuccess(Unknown Source:34)
       at com.google.android.gms.common.api.internal.zaaw.zab(Unknown Source:292)
       at com.google.android.gms.common.api.internal.zaak.zaaq(Unknown Source:125)
       at com.google.android.gms.common.api.internal.zaak.onConnected(Unknown Source:105)
       at com.google.android.gms.common.api.internal.zabe.onConnected(Unknown Source:101)
       at com.google.android.gms.common.api.internal.zaq.onConnected(Unknown Source:6)
       at com.google.android.gms.common.internal.zaf.onConnected(Unknown Source:2)
       at com.google.android.gms.common.internal.BaseGmsClient$zzf.zzm(Unknown Source:24)
       at com.google.android.gms.common.internal.BaseGmsClient$zza.zza(Unknown Source:12)
       at com.google.android.gms.common.internal.BaseGmsClient$zzc.zzo(Unknown Source:11)
       at com.google.android.gms.common.internal.BaseGmsClient$zzb.handleMessage(Unknown Source:48)
       at android.os.Handler.dispatchMessage(Handler.java:108)
       at android.os.Looper.loop(Looper.java:206)
       at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by rgomezp** [comment]
@Goran1708 @hermant2 : I was able to reproduce. The reason it is likely happening is that getTags is being called again in your callback. Can you confirm this is the case? If so, I'm curious why you are doing this? You cannot do this actually because the thread/s will be stuck in the sync block at the same time. Thanks for bringing this up!

Example: 
```
OneSignal.getTags(new GetTagsHandler() {
	@Override
	public void tagsAvailable(JSONObject tags) {
		OneSignal.getTags(new OneSignal.GetTagsHandler() {
                     @Override
                     public void tagsAvailable(JSONObject tags) {

                     }
               });
	}
});
```

@joccjo : this is actually a separate issue that should be its own. please create a new issue and follow our issue template!
