### ISSUE TITLE
Rare Android 6.0 location prompt null exception

### ISSUE THREAD

**Issue by jkasten2** [OneSignal/OneSignal-Android-SDK#71]
`NullPointerException` is thrown on Android 6.0 if the user comes back to the app after back-grounding it when prompted for location permissions through `OneSignal.promptLocation()`. The crash only happens if the process was killed due to low memory (not 'forced stopped' or swiped away) and then resumed from the Recent Apps list.

```VB
Caused by java.lang.NullPointerException: Attempt to invoke interface method 'void com.onesignal.u.a(java.lang.Double, java.lang.Double, java.lang.Float, java.lang.Integer)' on a null object reference
       at com.onesignal.LocationGMS.fireComplete(SourceFile:148)
       at com.onesignal.LocationGMS.fireFailedComplete(SourceFile:142)
       at com.onesignal.PermissionsActivity.onRequestPermissionsResult(SourceFile:73)
       at android.app.Activity.requestPermissions(Activity.java:3857)
       at com.onesignal.AndroidSupportV4Compat$ActivityCompatApi23.requestPermissions(SourceFile:72)
       at com.onesignal.AndroidSupportV4Compat$ActivityCompat.requestPermissions(SourceFile:63)
       at com.onesignal.PermissionsActivity.requestPermission(SourceFile:60)
       at com.onesignal.PermissionsActivity.onCreate(SourceFile:48)
       at android.app.Activity.performCreate(Activity.java:6285)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2417)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2524)
       at android.app.ActivityThread.access$900(ActivityThread.java:154)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1391)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:224)
       at android.app.ActivityThread.main(ActivityThread.java:5526)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by jkasten2** [comment]
Fixed in commit 46d52c9c3089d56253a5ff43c4c95c8b78575a30
