### ISSUE TITLE
One Signal ConcurrentModificationException

### ISSUE THREAD

**Issue by joccjo** [OneSignal/OneSignal-Android-SDK#713]
**Description:**

Getting bunch of crashes in production on our app with this stack trace, idk how to reproduce it

**Environment**

1. Android 5: 8%
2. Android 6: 52%
3. Android 7: 14%
4. Android 8: 25%
4. Android 9: 1%

**Anything else:**

Fatal Exception: java.util.ConcurrentModificationException
       at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
       at com.onesignal.UserStateSynchronizer.doPutSync(UserStateSynchronizer.java:272)
       at com.onesignal.UserStateSynchronizer.internalSyncUserState(UserStateSynchronizer.java:208)
       at com.onesignal.UserStateSynchronizer.syncUserState(UserStateSynchronizer.java:170)
       at com.onesignal.OneSignalStateSynchronizer.syncUserState(OneSignalStateSynchronizer.java:72)
       at com.onesignal.OneSignalSyncServiceUtils$SyncRunnable$1.complete(OneSignalSyncServiceUtils.java:228)
       at com.onesignal.LocationGMS.fireComplete(LocationGMS.java:254)
       at com.onesignal.LocationGMS.fireCompleteForLocation(LocationGMS.java:288)
       at com.onesignal.LocationGMS.access$500(LocationGMS.java:55)
       at com.onesignal.LocationGMS$GoogleApiClientListener.onConnected(LocationGMS.java:317)
       at com.google.android.gms.common.internal.GmsClientEventManager.onConnectionSuccess(Unknown Source:34)
       at com.google.android.gms.common.api.internal.zaaw.zab(Unknown Source:292)
       at com.google.android.gms.common.api.internal.zaak.zaaq(Unknown Source:125)
       at com.google.android.gms.common.api.internal.zaak.onConnected(Unknown Source:105)
       at com.google.android.gms.common.api.internal.zabe.onConnected(Unknown Source:101)
       at com.google.android.gms.common.api.internal.zaq.onConnected(Unknown Source:6)
       at com.google.android.gms.common.internal.zaf.onConnected(Unknown Source:2)
       at com.google.android.gms.common.internal.BaseGmsClient$zzf.zzm(Unknown Source:24)
       at com.google.android.gms.common.internal.BaseGmsClient$zza.zza(Unknown Source:12)
       at com.google.android.gms.common.internal.BaseGmsClient$zzc.zzo(Unknown Source:11)
       at com.google.android.gms.common.internal.BaseGmsClient$zzb.handleMessage(Unknown Source:48)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by rgomezp** [comment]
Looks like you are on an old release. Please update to 3.10.6

**Comment by rgomezp** [comment]
We were able to identify the problem and will be fixed in next release. Closing due to no response
