### ISSUE TITLE
Android Instant App started Crashing on most of the user devices

### ISSUE THREAD

**Issue by drayan85** [OneSignal/OneSignal-Android-SDK#715]
**Description:**

```
Fatal Exception: java.lang.NullPointerException: Attempt to get length of null array
       at android.os.Parcel.readException(Parcel.java:1710)
       at android.os.Parcel.readException(Parcel.java:1654)
       at android.support.customtabs.ICustomTabsService$Stub$Proxy.newSession(ICustomTabsService.java:242)
       at android.support.customtabs.CustomTabsClient.newSession(CustomTabsClient.java:257)
       at com.onesignal.OneSignalChromeTab$OneSignalCustomTabsServiceConnection.onCustomTabsServiceConnected(OneSignalChromeTab.java:87)
       at android.support.customtabs.CustomTabsServiceConnection.onServiceConnected(CustomTabsServiceConnection.java:33)
       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1516)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1544)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6816)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)
```
(your description here)

**Environment**

**Steps to Reproduce Issue:**

1. Using OneSignal: 3.7.1
2. Our Instant App Somehow App is started crashing on so many of our user devices. 
3. Is OneSignal is not fully compatible in the Instant App yet ?

**Anything else:**

(crash stacktraces, as well as any other information here)

**Comment by jkasten2** [comment]
@drayan85 Can you provide the following details?
1. Can you reproduce this crash locally? If so can you provide the full steps?
2. What version of the Android Support Library or AndroidX are you using
3. Can you try updating to the latest OneSignal SDK, 3.10.6?
4. What versions of Android are in your crash report?

**Comment by jkasten2** [comment]
@drayan85 Closing due to inactivity. Please provide the details above and we can look into the crash.

**Comment by drayan85** [comment]
After Upgrade OneSignal SDK 3.10.6 no more crashes on our instant app.

OneSignal will support the push notification for Android Instant Apps?
(https://medium.com/androiddevelopers/the-android-dev-summit-2018-app-instant-app-takeaways-open-source-e5b590f78f38)
