### ISSUE TITLE
OneSignal Crash on Android os 4.4

### ISSUE THREAD

**Issue by manlok1992** [OneSignal/OneSignal-Android-SDK#728]
**Description:**

Hello, I used the Unity OneSignal SDK to build it in Android platform. I received the Crash log in Crashlytics in a few days ago. I do some research here. I saw some people said this issue is trigger in android os 4.4 device. So I double check the crash log that I saw all users are using os 4.4 device. I saw some reference that said enable the multiDex option can resolve it. I already enable it. But I cannot resolve it.

**Environment**

```
defaultConfig {
     targetSdkVersion 26
     applicationId 'com.xxxxx.xxxxxx'
     multiDexEnabled true
     versionCode 41
     versionName "1.0.30"
     minSdkVersion 16
}
```
I am using Unity OneSignal SDK v2.7.8. I think it is the latest SDK. I download the .aar file and put it into the `Assets/Plugins/Android` folder.

**Anything else:**

```
Caused by java.lang.VerifyError: com/onesignal/LocationGMS
       at com.onesignal.OneSignal.onAppLostFocus(OneSignal.java:1062)
       at com.onesignal.ActivityLifecycleHandler$AppFocusRunnable.run(ActivityLifecycleHandler.java:171)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by jkasten2** [comment]
@manlok1992 Could you post the full error? There should be some more details before `Caused by java.lang.VerifyError: com/onesignal/LocationGMS`.

There are a number of steps to setting up multidex, one important one it seems you may have missed is missing `android:name` from your `<application>` tag.
```XML
<application
    android:name="android.support.multidex.MultiDexApplication" >
</application>
```
There is a detailed guide below I recommend reviewing to make sure you have everything setup correctly with multiDex on your Unity project
https://appmediation.com/unity-enable-multidex/
