### ISSUE TITLE
NotificationChannelManager.createChannel throws IllegalArgumentException

### ISSUE THREAD

**Issue by SimonSchubert** [OneSignal/OneSignal-Android-SDK#739]
**Description:**

My app throws an execption on every start after initializing OneSignal. How could that happen? How to log what's actually inside the "bad" notification? Should the onesignal sdk handle the exception?

**Environment**
gradle:
compileSdkVersion(28)
classpath: gradle.plugin.com.onesignal:onesignal-gradle-plugin:0.12.1
implementation: com.onesignal:OneSignal:3.10.7
implementation: com.google.firebase:firebase-messaging:17.6.0

I'm also using Firebase/Mixpanel and Appsflyer, which could potential send notificaions but I don't use the notification feature.

**Steps to Reproduce Issue:**
1. I can't reproduce it, it just started happening after opening/updating an existing app. A fresh installed app won't crash.

**Anything else:**

    java.lang.IllegalArgumentException
        at android.os.Parcel.readException(Parcel.java:2033)
        at android.os.Parcel.readException(Parcel.java:1975)
        at android.app.INotificationManager$Stub$Proxy.createNotificationChannels(INotificationManager.java:1661)
        at android.app.NotificationManager.createNotificationChannels(NotificationManager.java:497)
        at android.app.NotificationManager.createNotificationChannel(NotificationManager.java:485)
        at com.onesignal.NotificationChannelManager.createChannel(NotificationChannelManager.java:162)
        at com.onesignal.NotificationChannelManager.processChannelList(NotificationChannelManager.java:204)
        at com.onesignal.OneSignal$4.complete(OneSignal.java:855)
        at com.onesignal.OneSignalRemoteParams.processJson(OneSignalRemoteParams.java:92)
        at com.onesignal.OneSignalRemoteParams.access$100(OneSignalRemoteParams.java:11)
        at com.onesignal.OneSignalRemoteParams$1.onSuccess(OneSignalRemoteParams.java:58)
        at com.onesignal.OneSignalRestClient$5.run(OneSignalRestClient.java:253)
        at java.lang.Thread.run(Thread.java:764)

**Comment by jkasten2** [comment]
@SimonSchubert Thanks for th stack trace, from it it seems that it is running into an issue with creating a notification channel from OneSignal. I recommend contacting OneSignal support so they can review your channels as it seems like there is some invalid parameter there that got passed the dashboard validation.

**Comment by rgomezp** [comment]
Closing due to no response

**Comment by SimonSchubert** [comment]
@jkasten2 Crash happens on Android 8+9 only. I never defined a category/channel for the Android notifications before. So I just did that and hope it will fix the issue for future notifications.

I still think the crash should be handled by the sdk since I have no control over it.

**Comment by mochadwi** [comment]
Is this related to the blank appName or channelId for the `NotificationChannel` object? https://stackoverflow.com/a/49078010/3763032
