### ISSUE TITLE
Fatal Exception: java.lang.IllegalArgumentException  OneSignal:3.10.8 only on phone LAVA and only on Android 8

### ISSUE THREAD

**Issue by NelipaSV** [OneSignal/OneSignal-Android-SDK#753]
Please help, have crashes only on phone LAVA and only on Android 8

Fatal Exception: java.lang.IllegalArgumentException: No such service ComponentInfo{com.diyaapp.translator/com.onesignal.SyncJobService}
       at android.os.Parcel.readException(Parcel.java:2009)
       at android.os.Parcel.readException(Parcel.java:1951)
       at android.app.job.IJobScheduler$Stub$Proxy.schedule(IJobScheduler.java:180)
       at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:44)
       at **com.onesignal.OneSignalSyncServiceUtils.syncServicePendingIntent(OneSignalSyncServiceUtils.java:66)**
       at com.onesignal.OneSignalSyncServiceUtils.cancelSyncTask(OneSignalSyncServiceUtils.java:45)
       at com.onesignal.OneSignalSyncServiceUtils.scheduleLocationUpdateTask(OneSignalSyncServiceUtils.java:10)
       at com.onesignal.OneSignal.scheduleSyncService(OneSignal.java:8)
       at com.onesignal.OneSignal.onAppLostFocus(OneSignal.java:84)
       at com.onesignal.ActivityLifecycleHandler$AppFocusRunnable.run(ActivityLifecycleHandler.java:8)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.os.HandlerThread.run(HandlerThread.java:65)

![image](https://user-images.githubusercontent.com/47348097/57231444-2f39e380-7023-11e9-806b-95e9099b860f.png)

![image](https://user-images.githubusercontent.com/47348097/57231489-47116780-7023-11e9-855b-fe3b9c591078.png)

**Comment by rgomezp** [comment]
Hello,
This issue appears to be specific to LAVA devices as you can read about in #670 . Have you attempted to contact LAVA in any way?

**Comment by NelipaSV** [comment]
@rgomezp No, there is no such opportunity

**Comment by rgomezp** [comment]
Unfortunately, this isn't something that we can fix. Contacting LAVA would be your best bet. Sorry for the inconvenience

**Comment by rameshvoltella** [comment]
@rgomezp its very hard to talk with lava it not easy, can you guys write some exception handler for lava device?

**Comment by rgomezp** [comment]
Howdy @rameshvoltella ,
I will make a note of this and we will do our best to fix it when we get a chance. If you would like this fix faster and are willing to write the handler yourself, feel free to create a pull request in this repository.

**Comment by rameshvoltella** [comment]
@rgomezp will users see this crash, i mean if this crash occurs the unfortunately stopped dialog will be visible to users? For now i am giving condition like if manufacture is not lava and version is not equal to 8.1, then only i enable onesignal. else not, but i will miss my lava users in 8.1 version.Also can you tell me what is the reason for crash in lava devices?

**Comment by rameshvoltella** [comment]
@rgomezp any info regarding the above query?

**Comment by rgomezp** [comment]
We are not sure why Lava devices see these issues but know that it is related to the customization Lava elected to do on their devices. That is a good workaround for now. My apologies that this issue can't be easily resolved

**Comment by rameshvoltella** [comment]
hi this occur other than lava it came on Lenovo K9 today in my crash log

**Comment by rameshvoltella** [comment]
@rgomezp it happen on Lenovo K9

**Comment by rgomezp** [comment]
@rameshvoltella ,
Since this seems like an isolated incident, please reach out to our support channel at onesignal.com for further help. Please include how many ocurrences ocurred on the Lenovo device

**Comment by inventionsbyhamid** [comment]
I want to prevent crashes for LAVA devices. Is there any way to disable OneSignal for LAVA devices?

**Comment by amitgroch** [comment]
Fatal Exception: java.lang.IllegalArgumentException: No such service ComponentInfo{letest.ncertbooks/com.onesignal.SyncJobService}
       at android.os.Parcel.readException(Parcel.java:2017)
       at android.os.Parcel.readException(Parcel.java:1959)
       at android.app.job.IJobScheduler$Stub$Proxy.schedule(IJobScheduler.java:180)
       at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:44)
       at com.onesignal.bl.c(OneSignalSyncServiceUtils.java:148)
       at com.onesignal.bl.b(OneSignalSyncServiceUtils.java:116)
       at com.onesignal.bl.a(OneSignalSyncServiceUtils.java:63)
       at com.onesignal.az.f(OneSignal.java:1163)
       at com.onesignal.az.e(OneSignal.java:1141)
       at com.onesignal.a$b.run(ActivityLifecycleHandler.java:256)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.os.HandlerThread.run(HandlerThread.java:65)


Devices List 
45% Z61
15% Z60S
10% Z91
22% other
Lenovo K9 

Please help me 

I am using com.onesignal:OneSignal:3.11.4

**Comment by HungNguyenBao** [comment]
Caused by java.lang.IllegalArgumentException: No such service ComponentInfo{co.talenta/com.onesignal.SyncJobService}
       at android.os.Parcel.readException(Parcel.java:2009)
       at android.os.Parcel.readException(Parcel.java:1951)
       at android.app.job.IJobScheduler$Stub$Proxy.schedule(IJobScheduler.java:180)
       at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:44)
       at com.onesignal.OneSignalSyncServiceUtils.scheduleSyncServiceAsJob(OneSignalSyncServiceUtils.java:155)
       at com.onesignal.OneSignalSyncServiceUtils.scheduleSyncTask(OneSignalSyncServiceUtils.java:124)
       at com.onesignal.OneSignalSyncServiceUtils.scheduleLocationUpdateTask(OneSignalSyncServiceUtils.java:69)
       at com.onesignal.LocationGMS.scheduleUpdate(LocationGMS.java:102)
       at com.onesignal.OneSignalSyncServiceUtils.cancelSyncTask(OneSignalSyncServiceUtils.java:79)
       at com.onesignal.OneSignal.onAppFocus(OneSignal.java:1260)
       at com.onesignal.ActivityLifecycleHandler.handleFocus(ActivityLifecycleHandler.java:213)
       at com.onesignal.ActivityLifecycleHandler.onActivityResumed(ActivityLifecycleHandler.java:127)
       at com.onesignal.ActivityLifecycleListener.onActivityResumed(ActivityLifecycleListener.java:78)
       at android.app.Application.dispatchActivityResumed(Application.java:216)
       at android.app.Activity.onResume(Activity.java:1334)
       at androidx.fragment.app.FragmentActivity.onResume(FragmentActivity.java:456)
       at co.talenta.base.BaseActivity.onResume(BaseActivity.java:312)
       at co.talenta.modul.splash.SplashActivity.onResume(SplashActivity.java:164)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1360)
       at android.app.Activity.performResume(Activity.java:7203)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3605)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3670)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2911)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1613)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6545)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)

Can you help me double check this issue

I am using OneSignal: 3.12.7

**Comment by vlad-roid** [comment]
Still getting this log from Lava devices using OneSignal 4.0.0. @jkasten2 what happened to this?  Did you try contacing LAVA? https://github.com/OneSignal/OneSignal-Android-SDK/issues/670#issuecomment-446699867
>We can attempt to get in contact with LAVA as well to see if they are responsive.
