### ISSUE TITLE
org.json.JSONObject com.onesignal.UserState.generateJsonDiff(com.onesignal.UserState, boolean)' on a null object reference

### ISSUE THREAD

**Issue by whosea** [OneSignal/OneSignal-Android-SDK#760]
**Description:**

Onesignal（v3.10.8） crashes randomly every time it runs, and online logs also record many of these errors.

java.lang.NullPointerException: Attempt to invoke virtual method 'org.json.JSONObject com.onesignal.UserState.generateJsonDiff(com.onesignal.UserState, boolean)' on a null object reference
        at com.onesignal.UserStateSynchronizer.persist(UserStateSynchronizer.java:157)
        at com.onesignal.OneSignalStateSynchronizer.persist(OneSignalStateSynchronizer.java:53)
        at com.onesignal.OneSignal.scheduleSyncService(OneSignal.java:1077)
        at com.onesignal.OneSignal.onAppLostFocus(OneSignal.java:1057)
        at com.onesignal.ActivityLifecycleHandler$AppFocusRunnable.run(ActivityLifecycleHandler.java:171)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
(your description here)

**Comment by rgomezp** [comment]
Thank you for reporting this. Could you please follow our issue template and include repro steps, environment, etc...?

**Comment by whosea** [comment]
There are no specific steps, it happens occasionally, perhaps after calling OneSignal.sendTags, or after exiting the app.
My model: Android Emulator Google 8.1.0

**Comment by rgomezp** [comment]
Ok. Unfortunately, I cannot try to resolve without being able to reproduce it. Are you willing to share your project @whosea?

**Comment by rgomezp** [comment]
Closing due to no response
