### ISSUE TITLE
NullPointerException: Attempt to get length of null array (at RootToolsInternalMethods.isRooted)

### ISSUE THREAD

**Issue by vlad-roid** [OneSignal/OneSignal-Android-SDK#778]
Fatal Exception: java.lang.NullPointerException: Attempt to get length of null array
       at com.onesignal.RootToolsInternalMethods.isRooted(RootToolsInternalMethods.java:33)
       at com.onesignal.OneSignal.registerUserTask(OneSignal.java:1214)
       at com.onesignal.OneSignal.access$1700(OneSignal.java:80)
       at com.onesignal.OneSignal$7.run(OneSignal.java:1180)
       at java.lang.Thread.run(Thread.java:818)

Rare crash using OneSignal 3.10.9, seems to be happening only on Lenovo Yoga laptops, but will **always** crash for whoever is affected.

**Comment by rgomezp** [comment]
Hello,
Thanks for reporting this. We will look into handling this exception.

**Comment by rgomezp** [comment]
Would you be able to share your APK with us through our support channel at OneSignal.com?

**Comment by jkasten2** [comment]
@vlad-roid Please follow up with OneSignal support on getting them an APK. Or if you have any more details on reproducing the issue. Closing this issue due to inactivity.
