### ISSUE TITLE
OneSignal and Firebase-firestore/ firebase-core crashes the first launch

### ISSUE THREAD

**Issue by ReferenceArmada** [OneSignal/OneSignal-Android-SDK#785]
**Description:**

When we run the build for the first time, the app crashes with a fatal error
Its about the combination firebase firestore and OneSignal

after that we can open the app and everything works as it should. 
This are the imports that conflicts:
    implementation 'com.google.firebase:firebase-firestore:19.0.1'
    implementation 'com.google.firebase:firebase-core:16.0.9'
    implementation 'com.onesignal:OneSignal:3.10.9'

**Environment**
1. sdk 28
2. build.Gradle

**Steps to Reproduce Issue:**

1. import firestore , fire core and OneSignal to your grade 
```gradle
    implementation 'com.google.firebase:firebase-firestore:19.0.1'
    implementation 'com.google.firebase:firebase-core:16.0.9'
    implementation 'com.onesignal:OneSignal:3.10.9'
```
2. Run the project for the first time
3. Crash

**Anything else:**

this is the crash

```java
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.com, PID: 31855
    java.lang.IllegalAccessError: Class com.google.firebase.iid.zzb extended by class com.google.firebase.messaging.FirebaseMessagingService is inaccessible (declaration of 'com.google.firebase.messaging.FirebaseMessagingService' appears in /data/app/....classes2.dex)
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:103)
        at android.support.v4.app.CoreComponentFactory.instantiateService(CoreComponentFactory.java:68)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3514)
        at android.app.ActivityThread.access$1300(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1666)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by krpot** [comment]
I am having same problem.

**Dependencies:**
OneSignal Plugin: [0.12.2, 0.99.99]
OneSignal SDK: [3.9.1, 3.99.99]
Firebase core: 17.0.0

**Android SDK**: 28

**Error message:**
```
java.lang.IllegalAccessError: Class com.google.firebase.iid.zzb extended by class com.google.firebase.messaging.FirebaseMessagingService is inaccessible (declaration of 'com.google.firebase.messaging.FirebaseMessagingService' appears in /data/app/com.tenderfield.android-V849WZ3u_cd4avZb5rcE2g==/base.apk)
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3386)
        at android.app.ActivityThread.-wrap4(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1683)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by krpot** [comment]
I removed com.google.firebase:firebase-common-ktx from my dependencies and still same error.

**Comment by rgomezp** [comment]
Howdy,
All your firebase dependencies have to be on the same version. Please go ahead and do that and try again. Thanks

**Comment by emailsubjekt** [comment]
I can't even use 16.0.7 16.0.8 and 16.0.9 nor 17.0.0 - I'm stuck at 16.0.7 That works for me for now.

**Comment by krpot** [comment]
I just removed firebase dependencies from build.gradle and it's working fine.

**Comment by rgomezp** [comment]
Please post your build.gradle file

**Comment by jkasten2** [comment]
@ReferenceArmada and @krpot I tried each of the 3 dependencies you listed in a new project and I was not able to reproduce the issue.

The issue is most likely an issue with how OneSignal-Gradle-Plugin is setup in your project or more than just these dependencies are required to reproduce the issue.
Can you open a new issue under that repo so the problem can be reproduced?
https://github.com/OneSignal/OneSignal-Gradle-Plugin/issues

Thanks.

**Comment by jkasten2** [comment]
Closing due to inactivity and the issue not being reproducible.
