### ISSUE TITLE
ConcurrentModificationException still happens on 2.6.0

### ISSUE THREAD

**Issue by jkasten2** [OneSignal/OneSignal-Android-SDK#80]
The fix included in 2.4.2 did not fully fix the `ConcurrentModificationException` exception as it still occurs in some cases in the latest 2.6.0 version. It maybe related methods other than the `sendTag` method that `testSendTagsConcurrentModificationException` unit test is covering.

```Java
Fatal Exception: java.util.ConcurrentModificationException
       at java.util.HashMap$HashIterator.nextEntry(HashMap.java:806)
       at java.util.HashMap$KeyIterator.next(HashMap.java:833)
       at com.onesignal.OneSignalStateSynchronizer.generateJsonDiff(OneSignalStateSynchronizer.java:75)
       at com.onesignal.OneSignalStateSynchronizer.access$200(OneSignalStateSynchronizer.java:46)
       at com.onesignal.OneSignalStateSynchronizer$UserState.generateJsonDiff(OneSignalStateSynchronizer.java:261)
       at com.onesignal.OneSignalStateSynchronizer$UserState.access$600(OneSignalStateSynchronizer.java:201)
       at com.onesignal.OneSignalStateSynchronizer.syncUserState(OneSignalStateSynchronizer.java:474)
       at com.onesignal.OneSignalStateSynchronizer$NetworkHandlerThread$1.run(OneSignalStateSynchronizer.java:438)
       at android.os.Handler.handleCallback(Handler.java:808)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:193)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

Another stack trace from version 2.0.8 that may still be present in 2.6.0 a well.

```Java
Fatal Exception: java.util.ConcurrentModificationException
       at java.util.HashMap$HashIterator.nextEntry(HashMap.java:792)
       at java.util.HashMap$EntryIterator.next(HashMap.java:829)
       at java.util.HashMap$EntryIterator.next(HashMap.java:827)
       at org.json.JSONObject.writeTo(JSONObject.java:666)
       at org.json.JSONObject.toString(JSONObject.java:636)
       at com.onesignal.OneSignalStateSynchronizer$UserState.persistState(OneSignalStateSynchronizer.java:269)
       at com.onesignal.OneSignalStateSynchronizer$UserState.access$000(OneSignalStateSynchronizer.java:124)
       at com.onesignal.OneSignalStateSynchronizer.syncUserState(OneSignalStateSynchronizer.java:359)
       at com.onesignal.OneSignalStateSynchronizer$NetworkHandlerThread$1.run(OneSignalStateSynchronizer.java:314)
       at android.os.Handler.handleCallback(Handler.java:615)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.os.HandlerThread.run(HandlerThread.java:60)
```

**Comment by drayan85** [comment]
This is happening with OneSignal 2.6.1 on Android OS 4.4.2 & 4.1.1

**Comment by jkasten2** [comment]
@drayan85 I just fixed the issue in version 2.6.2. Make sure to resync you gradle file to get the new version.

**Comment by drayan85** [comment]
Thanks @jkasten2

**Comment by jkasten2** [comment]
@drayan85 Also note it may take a few hours to show up on [maven central](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.onesignal%22%20AND%20a%3A%22OneSignal%22). You can print out `OneSignal.VERSION` to confirm it is updated in your app. It should equal `"020602"`.

**Comment by drayan85** [comment]
@jkasten2  Noted
