### ISSUE TITLE
Caused by java.lang.NoClassDefFoundError Failed resolution of: Landroid/support/v4/widget/ViewDragHelper$Callback;

### ISSUE THREAD

**Issue by maliX0024** [OneSignal/OneSignal-Android-SDK#820]
```java
Caused by java.lang.NoClassDefFoundError
Failed resolution of: Landroid/support/v4/widget/ViewDragHelper$Callback;
com.onesignal.InAppMessageView.setUpDraggableLayout (InAppMessageView.java:311)
com.onesignal.InAppMessageView.access$500 (InAppMessageView.java:47)
com.onesignal.InAppMessageView$2.run (InAppMessageView.java:245)
android.os.Handler.handleCallback (Handler.java:751)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1410)
Caused by java.lang.ClassNotFoundException
Didn't find class "android.support.v4.widget.ViewDragHelper$Callback" on path: DexPathList[[zip file "/data/app/com.crazy.car.parking.game-1/base.apk"],nativeLibraryDirectories=[/data/app/com.crazy.car.parking.game-1/lib/arm64, /data/app/com.crazy.car.parking.game-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
dalvik.system.BaseDexClassLoader.findClass (BaseDexClassLoader.java:56)
java.lang.ClassLoader.loadClass (ClassLoader.java:312)
com.onesignal.InAppMessageView.setUpDraggableLayout (InAppMessageView.java:311)
com.onesignal.InAppMessageView.access$500 (InAppMessageView.java:47)
com.onesignal.InAppMessageView$2.run (InAppMessageView.java:245)
android.os.Handler.handleCallback (Handler.java:751)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1410)
```

**Comment by jkasten2** [comment]
@maliX0024 The issue looks related to the Android Support Library being missing for your project. If you have update to AndroidX library please follow Google's migration guide making sure you also enable Jetifier.
https://developer.android.com/jetpack/androidx/migrate

**Comment by jkasten2** [comment]
Closing due to inactivity, please provide more details if the above does not help and we can take a 2nd look.

**Comment by mc100401985** [comment]
Unity: 2018.3
onesignal unity sdk: 2.8.0

app crash on android when start. here is the android studio log error.

2019-09-25 01:31:32.960 2162-2162/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.entrepreneurscolortoo.colorxo, PID: 2162
    java.lang.Error: FATAL EXCEPTION [main]
    Unity version     : 2018.3.0f2
    Device model      : TINNO 7201
    Device fingerprint: TINNO/p7201/p7201:7.1.1/NMF26F/androi08011501:user/release-keys
    
    Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/widget/ViewDragHelper$Callback;
        at com.onesignal.InAppMessageView.setUpDraggableLayout(InAppMessageView.java:311)
        at com.onesignal.InAppMessageView.access$500(InAppMessageView.java:47)
        at com.onesignal.InAppMessageView$2.run(InAppMessageView.java:245)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.widget.ViewDragHelper$Callback" on path: DexPathList[[zip file "/data/app/com.entrepreneurscolortoo.colorxo-1/base.apk"],nativeLibraryDirectories=[/data/app/com.entrepreneurscolortoo.colorxo-1/lib/arm64, /data/app/com.entrepreneurscolortoo.colorxo-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.onesignal.InAppMessageView.setUpDraggableLayout(InAppMessageView.java:311) 
        at com.onesignal.InAppMessageView.access$500(InAppMessageView.java:47) 
        at com.onesignal.InAppMessageView$2.run(InAppMessageView.java:245) 
        at android.os.Handler.handleCallback(Handler.java:751) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6119) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
