### ISSUE TITLE
com.onesignal.InAppMessageView.setWebView(android.webkit.WebView)' on a null object reference

### ISSUE THREAD

**Issue by gsksarath** [OneSignal/OneSignal-Android-SDK#822]
App crashing when sending Inapp Messages in onesignal

```
2019-08-10 17:56:22.567 9524-9524/com.example.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.app, PID: 9524
    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.onesignal.InAppMessageView.setWebView(android.webkit.WebView)' on a null object reference
        at com.onesignal.WebViewManager.showMessageView(WebViewManager.java:273)
        at com.onesignal.WebViewManager.access$900(WebViewManager.java:36)
        at com.onesignal.WebViewManager$4$1.onReceiveValue(WebViewManager.java:247)
        at com.onesignal.WebViewManager$4$1.onReceiveValue(WebViewManager.java:241)
        at uv.onResult(Unknown Source:2)
        at org.chromium.android_webview.AwContents.a(PG:997)
        at aGZ.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6715)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
```

am using onesignal `'com.onesignal:OneSignal:3.11.2'`

It can be easily reproducible in development environment when send inapp messages in TOP BANNER & BOTTOM BANNER mode

**Comment by jkasten2** [comment]
@gsksarath Thanks for the stack trace, I reviewed our code and I don't see a straightforward ways this could be `null`. It might be related to how your app is transiting between Activities.

Could you provide the following details so we can take a deeper look?

1. Does the crash happen immediately on startup? If not provide more detail on reproducing

2. Does the crash happen only sometimes or everytime?

3. Does it crash if you rotate the device? (Only a factor if allow rotation in your app)

4. Please enable full OneSignal logging and attach your logcat.
```java
OneSignal.setLogLevel(OneSignal.LOG_LEVEL.VERBOSE, OneSignal.LOG_LEVEL.NONE);
```
