### ISSUE TITLE
After Uninstall the app and install again i can't get player id 

### ISSUE THREAD

**Issue by OmniaMahmoud** [OneSignal/OneSignal-Android-SDK#847]
**Description:**

if we uninstall our app and install new version player id return null and if i tried again after a while sometimes i got the id sometimes remain null

**Steps to Reproduce Issue:**

**Here is my code** 
OneSignal.addSubscriptionObserver(  new OSSubscriptionObserver() {
               @Override
               public void onOSSubscriptionChanged(OSSubscriptionStateChanges stateChanges) {
                   if (!stateChanges.getFrom().getSubscribed() &&
                          stateChanges.getTo().getSubscribed()) {
                       String oneSignalID = stateChanges.getTo().getUserId();
                       localSettings.setPlayerID(oneSignalID);
                   }
               }
           });

**and here is the exception i get**

OneSignalRestClient: PUT Error thrown from network stack.
   javax.net.ssl.SSLHandshakeException: SSL handshake aborted: ssl=0x7db0c42088: I/O error during system call, Connection reset by peer
       at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
       at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:375)
       at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:224)
       at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:192)
       at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:149)
       at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
       at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
       at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
       at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
       at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
       at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:258)
       at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
       at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:26)
       at com.onesignal.OneSignalRestClient.startHTTPConnection(OneSignalRestClient.java:160)
       at com.onesignal.OneSignalRestClient.access$100(OneSignalRestClient.java:44)
       at com.onesignal.OneSignalRestClient$4.run(OneSignalRestClient.java:108)
       at java.lang.Thread.run(Thread.java:764)

**Anything else:**
i have the same issue in iOS and Flutter Apps 
Note: we are in Egypt and This issue happened lately with our apps it wasn't happening before

**Comment by jkasten2** [comment]
We have seen some reports of OneSignal being blocked in Egypt and are looking into the issue. I recommend following up with OneSignal support since this Github repo is detected to Android native specific issues. Thanks.

**Comment by HebaMohamed** [comment]
We still got that issue in egypt, any update to solve it please? this is a major issue
