### ISSUE TITLE
TransactionTooLargeException in onesignal

### ISSUE THREAD

**Issue by rameshvoltella** [OneSignal/OneSignal-Android-SDK#848]
Hi,
I am getting TransactionTooLargeException in onesignal

Onesignal version-3.11.1
Devices Affected-Lava z1 and Galaxy A50(osversion 9)

**android.os.TransactionTooLargeException: android.os.TransactionTooLargeException**

The stack trace i am getting

```
android.os.BinderProxy.transactNative Binder.java
android.os.BinderProxy.transact Binder.java:496
android.content.pm.IPackageManager$Stub$Proxy.queryIntentReceivers IPackageManager.java:2642
android.app.ApplicationPackageManager.queryBroadcastReceivers ApplicationPackageManager.java:614
android.app.ApplicationPackageManager.queryBroadcastReceivers ApplicationPackageManager.java:626
com.onesignal.v.a
com.onesignal.v.a
com.onesignal.P.a
com.onesignal.S.a
com.onesignal.S.b
com.onesignal.S.a
com.onesignal.JobIntentService$CommandProcessor.doInBackground
com.onesignal.JobIntentService$CommandProcessor.doInBackground
android.os.AsyncTask$2.call AsyncTask.java:292

    android.app.ApplicationPackageManager.queryBroadcastReceivers ApplicationPackageManager.java:620
    android.app.ApplicationPackageManager.queryBroadcastReceivers ApplicationPackageManager.java:626
    com.onesignal.v.a
    com.onesignal.v.a
    com.onesignal.P.a
    com.onesignal.S.a
    com.onesignal.S.b
    com.onesignal.S.a
    com.onesignal.JobIntentService$CommandProcessor.doInBackground
    com.onesignal.JobIntentService$CommandProcessor.doInBackground
    android.os.AsyncTask$2.call AsyncTask.java:292
    java.util.concurrent.FutureTask.run FutureTask.java:237
    java.util.concurrent.ThreadPoolExecutor.runWorker ThreadPoolExecutor.java:1112
    java.util.concurrent.ThreadPoolExecutor$Worker.run ThreadPoolExecutor.java:587
    java.lang.Thread.run Thread.java:818


    android.os.AsyncTask$3.done AsyncTask.java:304
    java.util.concurrent.FutureTask.finishCompletion FutureTask.java:355
    java.util.concurrent.FutureTask.setException FutureTask.java:222
    java.util.concurrent.FutureTask.run FutureTask.java:242
    java.util.concurrent.ThreadPoolExecutor.runWorker ThreadPoolExecutor.java:1112
    java.util.concurrent.ThreadPoolExecutor$Worker.run ThreadPoolExecutor.java:587
    java.lang.Thread.run Thread.java:818
```

**Comment by rameshvoltella** [comment]
Hi @jkasten2  any update?

**Comment by rgomezp** [comment]
Please provide reproduction steps. Thanks

**Comment by rgomezp** [comment]
Closing due to no response

**Comment by niusounds** [comment]
I recently updated to SDK 4.4.2. This crash appears after updating to 4.4.2 (from 4.0.0).

```
Caused by android.os.TransactionTooLargeException: data parcel size 575716 bytes
       at android.os.BinderProxy.transactNative(BinderProxy.java)
       at android.os.BinderProxy.transact(BinderProxy.java:511)
       at android.app.INotificationManager$Stub$Proxy.enqueueNotificationWithTag(INotificationManager.java:2753)
       at android.app.NotificationManager.notifyAsUser(NotificationManager.java:494)
       at android.app.NotificationManager.notify(NotificationManager.java:444)
       at androidx.core.app.NotificationManagerCompat.notify(NotificationManagerCompat.java:223)
       at androidx.core.app.NotificationManagerCompat.notify(NotificationManagerCompat.java:205)
       at com.onesignal.GenerateNotification.createSummaryNotification(GenerateNotification.java:645)
       at com.onesignal.GenerateNotification.showNotification(GenerateNotification.java:321)
       at com.onesignal.GenerateNotification.displayNotification(GenerateNotification.java:103)
       at com.onesignal.NotificationBundleProcessor.processJobForDisplay(NotificationBundleProcessor.java:156)
       at com.onesignal.NotificationBundleProcessor.processJobForDisplay(NotificationBundleProcessor.java:133)
       at com.onesignal.OSNotificationController.processNotification(OSNotificationController.java:97)
       at com.onesignal.OSNotificationReceivedEvent.processNotification(OSNotificationReceivedEvent.java:95)
       at com.onesignal.OSNotificationReceivedEvent.access$000(OSNotificationReceivedEvent.java:35)
       at com.onesignal.OSNotificationReceivedEvent$2.run(OSNotificationReceivedEvent.java:84)
       at java.lang.Thread.run(Thread.java:919)
```
