### ISSUE TITLE
One Signal Fail in initialization

### ISSUE THREAD

**Issue by AbanoubWagdyy** [OneSignal/OneSignal-Android-SDK#849]
**Description:**

I am trying to initilaize one signal inside my app using the following code : 
 OneSignal.idsAvailable { userId, registrationId ->
            var text = "OneSignal UserID:\n$userId\n\n"

            text += if (registrationId != null)
                "Google Registration Id:\n$registrationId"
            else
                "Google Registration Id:\nCould not subscribe for push"

            val textView: TextView = findViewById(R.id.debug_view)
            textView.text = text
        }

But i am getting this error in debug log : 

D/OneSignal: OneSignalRestClient: Making request to: https://onesignal.com/api/v1/apps/eca995eb-e33e-4f48-8f6d-8c0aa44c606a/android_params.js
W/OneSignal: OneSignalRestClient: null Error thrown from network stack. 
    javax.net.ssl.SSLHandshakeException: Connection closed by peer
        at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
        at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:375)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:224)
        at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:192)
        at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:149)
        at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
        at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:538)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:26)
        at com.onesignal.OneSignalRestClient.startHTTPConnection(OneSignalRestClient.java:177)
        at com.onesignal.OneSignalRestClient.access$100(OneSignalRestClient.java:44)
        at com.onesignal.OneSignalRestClient$4.run(OneSignalRestClient.java:108)
        at java.lang.Thread.run(Thread.java:764)
I/OneSignal: Failed to get Android parameters, trying again in 60 seconds.
Disconnected from the target VM, address: 'localhost:8607', transport: 'socket'

I am using Android 9 and another one with android 8 with the same issue

plz advise

**Comment by jkasten2** [comment]
We have seen some reports of OneSignal being blocked in Egypt and are looking into the issue. I recommend following up with OneSignal support since this Github repo is detected to Android native specific issues. Thanks.

**Comment by HebaMohamed** [comment]
@jkasten2 We still have that issue in egypt, any update to solve that please? this is a major issue

**Comment by baselihab** [comment]
This issue still persists in Egypt, any updates?

**Comment by MoSala95** [comment]
have exact problem in Egypt too!!
