### ISSUE TITLE
Failed to get Android parameters, trying again in x seconds.

### ISSUE THREAD

**Issue by Mohamed-Hamed** [OneSignal/OneSignal-Android-SDK#854]
**Description:**

After setting up one signal for android I am failing to get the user id as it is returning "null".
I enabled debugging to find out what is wrong with the setup and I got this error repeatedly:
Failed to get Android parameters, trying again in 40 seconds.

**Environment**

SDK version: OneSignal:3.11.1
Gradle plugin: onesignal-gradle-plugin:0.12.6

I added the sdk as gradle dependency.

**Steps to Reproduce Issue:**

1. Install the sdk using gradle.
2. Add app id in gradle file.
3. Follow the docs to setup and initalize the sdk in application class.
4. Setup the Subscription observer in main activity.
5. Sdk is returning null user id.

public void onOSSubscriptionChanged(OSSubscriptionStateChanges stateChanges) {
        // get player ID
        String deviceId = stateChanges.getTo().getUserId();
        if (deviceId != null) {
            updateDeviceId(deviceId);
        }
        Log.e(Const.LOG_TAG, "OneSignal deviceId changed: " + deviceId);
}

**Anything else:**

Here is a full sample of the log messages I get:
2019-10-05 12:25:58.726 18954-19403/com.foorera.app I/OneSignal: Failed to get Android parameters, trying again in 30 seconds.
2019-10-05 12:26:28.727 18954-19403/com.foorera.app D/OneSignal: Starting request to get Android parameters.
2019-10-05 12:26:28.741 18954-19424/com.foorera.app D/OneSignal: OneSignalRestClient: Making request to: https://onesignal.com/api/v1/apps/{app_id}/android_params.js
2019-10-05 12:28:02.356 18954-19424/com.foorera.app W/OneSignal: OneSignalRestClient: null Error thrown from network stack. 
    javax.net.ssl.SSLHandshakeException: Connection closed by peer
        at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
        at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357)
        at com.android.okhttp.Connection.connectTls(Connection.java:235)
        at com.android.okhttp.Connection.connectSocket(Connection.java:199)
        at com.android.okhttp.Connection.connect(Connection.java:172)
        at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:367)
        at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:130)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:247)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:405)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:521)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java)
        at com.onesignal.OneSignalRestClient.startHTTPConnection(OneSignalRestClient.java:177)
        at com.onesignal.OneSignalRestClient.access$100(OneSignalRestClient.java:44)
        at com.onesignal.OneSignalRestClient$4.run(OneSignalRestClient.java:108)
        at java.lang.Thread.run(Thread.java:760)
    	Suppressed: javax.net.ssl.SSLHandshakeException: Connection closed by peer
    		... 18 more
    		Suppressed: javax.net.ssl.SSLHandshakeException: Connection closed by peer

**Comment by Mohamed-Hamed** [comment]
It's worth noting that onesignal.com is not working most of the time.

**Comment by Mohamed-Hamed** [comment]
OK, it hasn't been working for few days, and just started to work now :)
