### ISSUE TITLE
SSLHandshakeException Error

### ISSUE THREAD

**Issue by Peter-Emad** [OneSignal/OneSignal-Android-SDK#859]
Hello,

I'm trying to generate a device id through OneSignal SDK (idsAvailable) but I'm getting the below error in the log cat, I've verified that the device has internet access but I still get that error and it goes on an endless loop trying to generate the device id .

The only case I got it to work and successfully generate a device id was when using a VPN, so my question is what can i do to generate an id without VPN and in case there's an error while generating the id how can i add an error listener so as not to go on an endless loop.

```
2019-10-08 14:44:00.325 29282-29325/? W/OneSignal: OneSignalRestClient: null Error thrown from network stack. 
    javax.net.ssl.SSLHandshakeException: Connection closed by peer
        at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
        at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:375)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:224)
        at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:192)
        at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:149)
        at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
        at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:538)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:26)
        at com.onesignal.OneSignalRestClient.startHTTPConnection(OneSignalRestClient.java:177)
        at com.onesignal.OneSignalRestClient.access$100(OneSignalRestClient.java:44)
        at com.onesignal.OneSignalRestClient$4.run(OneSignalRestClient.java:108)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by rgomezp** [comment]
Howdy,
It sounds like you're having a network error. Can you try on a different network? Which country are you in?

**Comment by Peter-Emad** [comment]
Hi,
I've tried multiple networks and still facing the same issue. it only works using VPN clients.
I'm in Egypt.

**Comment by rgomezp** [comment]
We are looking into how best to communicate with Egypt on how best to resolve this issue. If you want to reach out to your ISP and let them know they should unblock OneSignal, that would be helpful.

**Comment by Peter-Emad** [comment]
okay thank you.

**Comment by SuleymanovTat** [comment]
W/OneSignal: OneSignalRestClient: null Error thrown from network stack. 
    javax.net.ssl.SSLHandshakeException: Handshake failed
        at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:396)
        at com.android.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:123)
        at com.android.okhttp.Connection.connect(Connection.java:151)
        at com.android.okhttp.Connection.connect(Connection.java:187)
        at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:238)
        at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:134)
        at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:382)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:369)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:287)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:130)
