### ISSUE TITLE
App crashes when sent notification

### ISSUE THREAD

**Issue by saranshbalyan-1234** [OneSignal/OneSignal-Android-SDK#886]
App crashes when sent notification
`    Process: com.oxoo.spagreen, PID: 423
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.json.JSONObject.getString(java.lang.String)' on a null object reference
        at com.oxoo.spagreen.NotificationClickHandler.notificationOpened(NotificationClickHandler.java:35)
        at com.onesignal.OneSignal$18.run(OneSignal.java:1954)
        at com.onesignal.OSUtils.runOnMainUIThread(OSUtils.java:278)
        at com.onesignal.OneSignal.fireNotificationOpenedHandler(OneSignal.java:1951)
        at com.onesignal.OneSignal.runNotificationOpenedCallback(OneSignal.java:1900)
        at com.onesignal.OneSignal.handleNotificationOpen(OneSignal.java:1991)
        at com.onesignal.NotificationOpenedProcessor.processIntent(NotificationOpenedProcessor.java:118)
        at com.onesignal.GenerateNotification$1$1.onClick(GenerateNotification.java:146)
        at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:184)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7076)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
I/Process: Sending signal. PID: 423 SIG: 9
Application terminated.`

**Comment by rgomezp** [comment]
Please follow our issue template

**Comment by usmanat77sparx** [comment]
@rgomezp Is this issue fixed? It seems It can still see it in google play console.
