### ISSUE TITLE
NullPointerException: getWindowHeightAPI23Plus

### ISSUE THREAD

**Issue by yuji-yoshimura** [OneSignal/OneSignal-Android-SDK#896]
**Description:**
Crash may occur when in-app message display and screen transition overlap.

**Environment**
1. Android target sdk version 28
1. Android compile sdk version 28
1. com.onesignal:OneSignal:3.11.3

**Steps to Reproduce Issue:**
1. Set in-app message.
1. Open the app.
1. The screen changes as soon as the in-app message is displayed.

**Anything else:**

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.WindowInsets.getStableInsetBottom()' on a null object reference
       at com.onesignal.OSViewUtils.getWindowHeightAPI23Plus(OSViewUtils.java:96)
       at com.onesignal.OSViewUtils.getWindowHeight(OSViewUtils.java:82)
       at com.onesignal.WebViewManager.getWebViewMaxSizeY(WebViewManager.java:366)
       at com.onesignal.WebViewManager.setWebViewToMaxSize(WebViewManager.java:329)
       at com.onesignal.WebViewManager.access$000(WebViewManager.java:36)
       at com.onesignal.WebViewManager$5.run(WebViewManager.java:308)
       at com.onesignal.OSViewUtils$1$1.available(OSViewUtils.java:59)
       at com.onesignal.ActivityLifecycleHandler.setActivityAvailableListener(ActivityLifecycleHandler.java:77)
       at com.onesignal.OSViewUtils$1.run(OSViewUtils.java:54)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6644)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by yuji-yoshimura** [comment]
Completely solved.
Thank you.
