### ISSUE TITLE
NullPointerException on UserStatePushSynchronizer

### ISSUE THREAD

**Issue by sapardo10** [OneSignal/OneSignal-Android-SDK#904]
**Description:**

I have encountered a crash on the library. I cannot reproduce it since it happens to some of my users and I have only encountered the report on the crash reporting site. It appers to be something related to the state or characteristics of the user, because it happens with few users, but many times to each one of them.

**Environment**

1. I'm using the following version of the library: implementation 'com.onesignal:OneSignal:3.10.8'
2. It is not related to the android version since it happens at least from android 6 up to android 9.

**Steps to Reproduce Issue:**

I have not been able to reproduce it.

**Anything else:**
Crash stacktrace:

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
       at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:116)
       at org.json.JSONTokener.nextValue(JSONTokener.java:94)
       at org.json.JSONObject.<init>(JSONObject.java:159)
       at org.json.JSONObject.<init>(JSONObject.java:176)
       at com.onesignal.UserStatePushSynchronizer$1.onSuccess(UserStatePushSynchronizer.java:31)
       at com.onesignal.OneSignalRestClient$5.run(OneSignalRestClient.java:253)
       at java.lang.Thread.run(Thread.java:764)

**Comment by rgomezp** [comment]
Hello,
Thanks for bringing this up. Could you please provide more detailed info on the occurrence/frequency?

**Comment by sapardo10** [comment]
I do not have much additional information. But according to the reports, 95% of the cases happened while the application was on background. Also, after reviewing the data, it doesn't seem to occur on android 7 devices and below, it's almost 50/50 between android 8 and 9.

**Comment by rgomezp** [comment]
Thanks for the details. If you are able to reproduce the issue, we will be able to resolve the issue much more quickly 

Cheers

**Comment by JozeRi** [comment]
This issue happens for me too, a lot of my users are experiencing this on production :(

**Comment by ddabush** [comment]
We removed our android SDK.
There is any update with this issue? @rgomezp

**Comment by ddabush** [comment]
Stack trace:
java.lang.NullPointerException: 
  at com.kvisi.utils.OneSignalUtils$1.tagsAvailable (OneSignalUtils.java:35)
  at com.onesignal.OneSignal$15.run (OneSignal.java:1786)
  at java.lang.Thread.run (Thread.java:764)

**Comment by rgomezp** [comment]
@JozeRi @ddabush ,
Are you able to reproduce the issue?

**Comment by ddabush** [comment]
@rgomezp the code that I shared above it is from OneSignal Android SDK and it causes us many exceptions so we decided to remove it. waiting for you fix.

**Comment by ddabush** [comment]
The Exception code:
java.lang.NullPointerException: 
  at org.json.JSONTokener.nextCleanInternal (JSONTokener.java:116)
  at org.json.JSONTokener.nextValue (JSONTokener.java:94)
  at org.json.JSONObject.<init> (JSONObject.java:159)
  at org.json.JSONObject.<init> (JSONObject.java:176)
  at com.onesignal.UserStatePushSynchronizer$1.onSuccess (UserStatePushSynchronizer.java:31)
  at com.onesignal.OneSignalRestClient$5.run (OneSignalRestClient.java:263)
  at java.lang.Thread.run (Thread.java:784)

@rgomezp

**Comment by rgomezp** [comment]
@ddabush ,
Thanks for the details. We will look into this.
