### ISSUE TITLE
App crashing with push notifications.Initailly it was working.i manually tested push notification by creating a category and then removed it.Its crashing since then

### ISSUE THREAD

**Issue by aswin-r-aseuro** [OneSignal/OneSignal-Android-SDK#905]
E/AndroidRuntime: FATAL EXCEPTION: OS_REST_SUCCESS_CALLBACK
    Process: com.ibigroup.cholantaxi, PID: 4107
    java.lang.IllegalArgumentException
        at android.os.Parcel.createException(Parcel.java:1954)
        at android.os.Parcel.readException(Parcel.java:1918)
        at android.os.Parcel.readException(Parcel.java:1868)
        at android.app.INotificationManager$Stub$Proxy.createNotificationChannels(INotificationManager.java:1751)
        at android.app.NotificationManager.createNotificationChannels(NotificationManager.java:541)
        at android.app.NotificationManager.createNotificationChannel(NotificationManager.java:529)
        at com.onesignal.NotificationChannelManager.createChannel(NotificationChannelManager.java:177)
        at com.onesignal.NotificationChannelManager.processChannelList(NotificationChannelManager.java:218)
        at com.onesignal.OneSignal$5.complete(OneSignal.java:1011)
        at com.onesignal.OneSignalRemoteParams.processJson(OneSignalRemoteParams.java:139)
        at com.onesignal.OneSignalRemoteParams.access$100(OneSignalRemoteParams.java:11)
        at com.onesignal.OneSignalRemoteParams$1.onSuccess(OneSignalRemoteParams.java:79)
        at com.onesignal.OneSignalRestClient$5.run(OneSignalRestClient.java:263)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.internal.util.Preconditions.checkArgument(Preconditions.java:33)
        at com.android.server.notification.RankingHelper.createNotificationChannel(RankingHelper.java:613)
        at com.android.server.notification.NotificationManagerService$10.createNotificationChannelsImpl(NotificationManagerService.java:2332)
        at com.android.server.notification.NotificationManagerService$10.createNotificationChannels(NotificationManagerService.java:2347)
        at android.app.INotificationManager$Stub.onTransact(INotificationManager.java:256)

**Comment by aswin-r-aseuro** [comment]
Issue was resolved by deleting the category and removing the user credential from subscribed list
