### ISSUE TITLE
Default FirebaseApp is not initialized

### ISSUE THREAD

**Issue by cloudtenlabs** [OneSignal/OneSignal-Android-SDK#909]
I launched a new app recently and haven't had a problem until last night for one specific user who encountered the issue about 10 times yesterday and today.

As I don't use Firebase in my application, I think this might be the Firebase App created by OneSignal. However as it has only happened to one specific user, I think the issue might be with linked to his device.

Environment
One Signal SDK : 3.10.2
Play Services : 11.0.4
Android Support lib : 27.1.1

User Device : Teclast P10 (p10_m3f5_g in Google Play Console) on Android 7.1.2

Steps to Reproduce Issue:

I am guessing just launching the application but I have no information.

Anything else:

java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.jsl_prod.presse. Make sure to call FirebaseApp.initializeApp(Context) first.
at com.google.firebase.FirebaseApp.getInstance(Unknown Source)
at com.google.firebase.iid.FirebaseInstanceId.getInstance(Unknown Source)
at com.google.firebase.iid.FirebaseInstanceIdService.zza(Unknown Source)
at com.google.firebase.iid.FirebaseInstanceIdService.handleIntent(Unknown Source)
at com.google.firebase.iid.zzc.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:761)

**Comment by rahat14** [comment]
i am having the same issue .

**Comment by rgomezp** [comment]
Howdy,
Are you using the [OneSignal Gradle Plugin](https://github.com/OneSignal/OneSignal-Gradle-Plugin)?

**Comment by rgomezp** [comment]
Closing due to no response

**Comment by rahat14** [comment]
yes
