### ISSUE TITLE
Fatal Exception: java.lang.IllegalArgumentException No such service ComponentInfo{myapp/com.onesignal.SyncJobService}

### ISSUE THREAD

**Issue by amitgroch** [OneSignal/OneSignal-Android-SDK#961]
```Java
Fatal Exception: java.lang.IllegalArgumentException: No such service ComponentInfo{myapp/com.onesignal.SyncJobService}
       at android.os.Parcel.readException(Parcel.java:2017)
       at android.os.Parcel.readException(Parcel.java:1959)
       at android.app.job.IJobScheduler$Stub$Proxy.schedule(IJobScheduler.java:180)
       at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:44)
       at com.onesignal.bl.c(OneSignalSyncServiceUtils.java:148)
       at com.onesignal.bl.b(OneSignalSyncServiceUtils.java:116)
       at com.onesignal.bl.a(OneSignalSyncServiceUtils.java:63)
       at com.onesignal.az.f(OneSignal.java:1163)
       at com.onesignal.az.e(OneSignal.java:1141)
       at com.onesignal.a$b.run(ActivityLifecycleHandler.java:256)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.os.HandlerThread.run(HandlerThread.java:65)
```

Devices list effected 👎 
45% Z61
15% Z60S
10% Z91
22% Others
Lenovo K9 

I am using com.onesignal:OneSignal:3.11.4

**Comment by jkasten2** [comment]
@amitgroch We have gotten similar reports before of Lava devices reporting that JobServcies are missing. We suspect but haven't been able to confirm that Lava runs a modified version of Android that removes services in apps in some specific cases. I have tried to reach out to Lava before but wasn't able to get a response on this.
We haven't seen this with Lenovo devices, but if this a very low number it could be some rooted devices.

Please let us also know the following.
1. Are you able to reproduce this issue on your devices? If so please provide exact steps
2. How many of these crashes are you seeing? Number of affected users and instances.

**Comment by jkasten2** [comment]
Closing due to inactivity.
