### ISSUE TITLE
in-app messanging crashes

### ISSUE THREAD

**Issue by AKBIROCK3** [OneSignal/OneSignal-Android-SDK#997]
hi so guys could you help me i got this error when i tried to send in app massage 
normal massages work normally but in-app ones makes my app crash
my app has cardview as well but still get the error

`FATAL EXCEPTION: main
Process: com.magi.apk, PID: 17775
java.lang.NoClassDefFoundError: Failed resolution of: 
Landroid/support/v7/cardview/R$attr;
at android.support.v7.widget.CardView.<init>(CardView.java:117)
at android.support.v7.widget.CardView.<init>(CardView.java:113)
at com.onesignal.InAppMessageView.createCardView(InAppMessageView.java:346)
at 
com.onesignal.InAppMessageView.setUpDraggableLayout(InAppMessageView.java:325)
at com.onesignal.InAppMessageView.access$500(InAppMessageView.java:44)
at com.onesignal.InAppMessageView$2.run(InAppMessageView.java:235)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7356)
at java.lang.reflect.Method.invoke(Native Method)
at 
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
Caused by: java.lang.ClassNotFoundException: 
android.support.v7.cardview.R$attr
... 13 more
`

**Comment by rgomezp** [comment]
Howdy,
Can you remove your `build.gradle`, syncing and then adding it back?

**Comment by pedrofurtado** [comment]
Probably related: https://github.com/OneSignal/OneSignal-Android-SDK/issues/997

**Comment by jkasten2** [comment]
@AKBIROCK3 It seems one of your Android R files didn't get generated or it is being removed from your app from proguard or R8.

I recommend making sure you do a clean build in Android Studio by going to File > "Invalidate Caches / Restart ...". Then do a clean build after restarting.

If this does not help please disable proguard or R8 in your build to rule that out.

Lastly I also recommend updating the version of the Android Gradle Plugin and Gradle itself if they are not the latest.

**Comment by jkasten2** [comment]
@pedrofurtado This is issue #997, did you mean another issue?
